import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { TrendingDown, Microscope, TestTube, Globe2, Banknote, Moon, ArrowRight, Shield, Dna } from "lucide-react";
import { ThreeChannelSummary } from "@/components/ThreeChannelSummary";
import { SentinelCascadeCompact } from "@/components/SentinelCascadeCompact";
import { TheraBionicProof } from "@/components/TheraBionicProof";
import { BradfordHillCard } from "@/components/BradfordHillCard";
import { FinlandLagChart } from "@/components/FinlandLagChart";
import { ThreePhaseIndicator } from "@/components/ThreePhaseIndicator";
import { SixFactorSummary } from "@/components/SixFactorSummary";
import type { Locale } from "@/lib/i18n";
import { LOCKED_PREDICTIONS, countryLabel } from "@/lib/predictions";
import { LatestArticles } from "@/components/LatestArticles";
import { Sparkline } from "@/components/SparklineCard";
import { readFileSync } from "fs";
import { join } from "path";

const SPARKLINE_ICONS = [TrendingDown, Microscope, TestTube, Globe2, Banknote, Moon] as const;

function getReferenceCount(): number {
  const file = join(process.cwd(), "public/data/references_full.json");
  const data = JSON.parse(readFileSync(file, "utf-8")) as { references: unknown[] };
  return data.references.length;
}

function getFalsificationStats() {
  try {
    const raw = readFileSync(join(process.cwd(), "public/data/falsification_v19_1.json"), "utf-8");
    const data = JSON.parse(raw);
    const tests = data.tests || [];
    const total = tests.length;
    const ran = tests.filter((t: { status: string }) => t.status === "RAN").length;
    const falsified = tests.filter((t: { falsified?: boolean }) => t.falsified === true).length;
    const consistent = ran - falsified;
    const pending = total - ran;
    return { total, ran, consistent, falsified, pending };
  } catch {
    return { total: 7, ran: 3, consistent: 3, falsified: 0, pending: 4 };
  }
}

const SPARKLINE_DATA = [
  [5.0, 4.9, 4.5, 4.1, 3.7, 3.5, 3.2, 2.9, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2],
  [101, 96, 89, 83, 77, 70, 62, 55, 49, 42],
  [100, 97, 93, 90, 87, 83, 80],
  [0, 2, 5, 10, 18, 15, 20, 35, 49],
  [1.47, 1.08, 1.23, 1.24, 0.84, 0.72],
  [6.9, 6.8, 6.7, 6.5, 6.3, 6.1, 6.1, 6.1],
];

const COPY = {
  en: {
    heroTitle: "Something is happening to fertility",
    heroDeck: "Something is happening to human reproduction that pronatalist policies, economic incentives, and cultural interventions have failed to reverse.",
    heroContext: "Fertility rates are collapsing worldwide. Sperm counts have halved. Testosterone is declining in every industrialized population measured — even in men who haven't gained weight. Bee colonies, bird populations and amphibians are declining on the same timeline.",
    whatIsThis: "The Bio-Electromagnetic Reproductive Model (BERM) proposes an explanation: the electromagnetic fields generated by modern electrical infrastructure interact with voltage-gated calcium channels — proteins found in every cell — disrupting the biological systems that govern reproduction, metabolism, sleep, and neurological health.",
    heroEpistemic: "This website presents the model, its evidence, and its falsifiable predictions. Every claim is bounded by epistemic level. Every prediction is locked with a falsification criterion. If the model is wrong, it is designed to fail visibly.",

    s1Title: "THE CRISIS IN NUMBERS",
    s1Intro: "These trends are documented independently by thousands of studies. What remains unexplained is why they are all happening simultaneously, across all industrialized nations, and why no intervention has reversed them.",

    impactGrid: [
      { stat: "5.0 → 2.2", label: "Global TFR since 1960 — decline is accelerating", sub: "Below 2.1, populations shrink. Below 1.3, recovery has never been observed without immigration.", href: "/explore" },
      { stat: "−62%", label: "Sperm concentration (Levine 2023, 223 studies)", sub: "The decline shows no sign of leveling off. At current rates, median counts will reach subfertility thresholds within one generation.", href: "/model#causal-diagram" },
      { stat: "−1.2%/yr", label: "Testosterone decline, age-independent (Travison 2007)", sub: "This decline persists even in men who maintain their weight — ruling out obesity as the primary cause.", href: "/model#testosterone-threshold" },
      { stat: "49", label: "Countries below replacement TFR 1.4", sub: "Not just wealthy nations. Middle-income countries are following the same trajectory, 15–20 years delayed.", href: "/explore" },
      { stat: "$200B", label: "Korea pronatalism spending → TFR still dropped to 0.72", sub: "The most expensive pronatalist program in history has had no measurable effect on fertility.", href: "/model#testosterone-threshold" },
      { stat: "TFR 6.1 vs 1.66", label: "Amish vs US fertility — communities without smartphones", sub: "While other lifestyle factors differ, the magnitude of the fertility gap exceeds what diet or lifestyle studies have explained.", href: "/evidence/populations" },
    ],

    bridgeTitle: "WHY THESE NUMBERS BELONG TOGETHER",
    bridgeP1: "Conventional explanations treat each trend separately: fertility decline is attributed to economics and culture, sperm decline to chemicals and lifestyle, testosterone decline to obesity, and sleep disorders to screens.",
    bridgeP2: "But these explanations fail a basic test: they cannot explain why all of these trends are occurring simultaneously, in all industrialized countries, and why they correlate more strongly with electrical infrastructure than with any social or economic variable.",
    bridgeP3: "BERM proposes a single upstream mechanism: electromagnetic fields from electrical wiring, wireless devices, and cellular infrastructure interact with voltage-gated calcium channels (VGCCs) — the same proteins that regulate hormone secretion, sperm motility, neural signaling, and metabolic function. When calcium signaling is disrupted, the downstream effects appear as separate diseases. They are not. They are different symptoms of the same physiological perturbation.",
    bridgeCta1: "Explore the mechanism",
    bridgeCta2: "See the evidence",
    bridgeCta3: "Read the predictions",

    paradoxIntro: "If declining fertility were driven by information — access to contraception, changing values, economic calculation — then the information device (mobile phones) should be the strongest predictor. It isn't.",

    sentinelCta: "All sentinels",

    paradoxLabel: "CROSS-SECTIONAL DISCOVERY v17.1",
    paradoxTitle: "The mobile phone paradox",
    paradoxText: "Across 54 countries, residential electricity consumption is the strongest predictor of fertility decline (RMSE 0.533). Mobile phone subscriptions — the information device — are the weakest (RMSE 1.053). The infrastructure variable predicts best — consistent with a physical exposure mechanism.",
    paradoxStat1: "LOOCV RMSE",
    paradoxVal1: "0.522",
    paradoxStat2: "R²",
    paradoxVal2: "0.851",
    paradoxStat3: "Countries within 0.5",
    paradoxVal3: "74%",
    paradoxCta: "Cross-sectional formula",

    klimentidisLabel: "THE KLIMENTIDIS PARADOX",
    klimentidisTitle: "Even lab animals are getting fatter",
    klimentidisText: "Laboratory rats on controlled diets, wild rats, pet dogs and cats — all gaining weight across decades. 24 populations, 8 species, p = 1.2 × 10⁻⁷. BERM identifies EMF as the only environmental factor increasing across all these environments simultaneously.",
    klimentidisNote: "Klimentidis et al. (2010) did not study EMF. They suggested \"as-of-yet unidentified factors.\" The EMF interpretation is BERM's derivation.",
    klimentidisLink: "Read the metabolic cascade",

    why2012Label: "THE 2012 INFLECTION",
    why2012Title: "Why 2012? It was the device, not the content",
    why2012Text: "Social media existed since 2003 — with no mental health crisis. The crisis began in 2012, when smartphones crossed 50% adoption among teenagers. BERM's explanation: 2012 was not about content — it was about the device. The smartphone brought continuous body-contact EMF exposure (WiFi + 4G + Bluetooth, 24/7, including in bed at night).",
    why2012Detail: "Combined with existing power grid ELF priming and newly mandated LED lighting (EU incandescent ban 2009–2012), 2012 was the year when cumulative multi-frequency Ca²⁺ load exceeded the CaMKII autophosphorylation threshold at population level.",
    why2012Prediction: "Prediction: content restrictions (Australia, Norway) will NOT resolve the crisis because the mechanism is the hardware, not the content.",
    why2012Cta: "Technology exposure analysis",

    pharmaLabel: "THE PHARMACOLOGICAL TEST",
    pharmaTitle: "Calcium blockers reduce the diseases BERM predicts",
    pharmaText: "If BERM's calcium mechanism is correct, then drugs that block calcium channels should reduce disease rates across BERM's cascades — even when prescribed for other conditions.",
    pharmaEvidence: "Three registry studies (Finland, UK) involving 264,625 patients with severe mental illness found exactly this: calcium channel blockers prescribed for cardiovascular conditions reduced psychiatric hospitalizations (HR 0.79–0.83) and self-harm.",
    pharmaPenetrant: "Brain-penetrant calcium blockers (nifedipine) showed 12% better psychiatric outcomes than non-penetrant ones (amlodipine) — as predicted by the model.",
    pharmaTrial: "An ongoing clinical trial at ETH Zürich (NCT06998368) is directly testing whether the brain-penetrant calcium blocker nimodipine can block 5G's effects on sleep.",
    pharmaCta: "See pharmacological evidence",

    weightLabel: "THE WEIGHT-STABLE DECLINE",
    weightTitle: "Testosterone is declining even in men who haven't gained weight",
    weightIntro: "A common objection: \"Testosterone is declining because men are getting fatter.\" If true, men who maintain their weight should maintain their testosterone. They don't.",
    weightSanti: "In 2025, the largest meta-analysis ever conducted (Santi et al., 1,064,891 men) confirmed: testosterone and luteinizing hormone are both declining, independent of BMI. The problem is not just in the testes — it extends to the pituitary and hypothalamus.",
    weightMechanism: "BERM explains both findings: EMF disrupts testosterone production directly (via calcium channels in Leydig cells) and indirectly through the hypothalamic-pituitary axis (via melatonin and cortisol pathways).",

    mazurQuote: "We have not identified the reason for secular decline in testosterone, but we exclude increasing obesity as a sufficient or primary explanation, and we dispute the assumption that men who avoid excessive weight gain will maintain their youthful testosterone levels.",
    mazurSource: "Mazur et al. 2013, PLOS ONE",
    mazurContext: "991 US Air Force veterans, 20-year follow-up. Even weight-stable men lost 19% of their testosterone.",
    mazurLink: "Read the causal analysis",

    howTitle: "How the model works",
    causalLabel: "THREE-CHANNEL MECHANISM",
    causalTitle: "ELF · IF · RF — three frequency bands, three biological pathways",
    causalNote: "Mobile subscription density is a composite proxy for the overall electromagnetic environment. The model traces three independent channels — ELF (power grid, lighting), IF (switching electronics, LED flicker), RF (base stations, Wi-Fi, radar) — through cryptochrome disruption, calcium signaling and membrane voltage to paired reproductive capacity.",

    npLabel: "EVOLUTIONARY ORIGINS",
    npTitle: "The Northern Package",
    npText: "Why did Northern Europe fall below replacement fertility first? BERM proposes that the same co-selection that optimised cryptochrome sensitivity — blue eyes (OCA2), lactose tolerance (LCT), and cattle husbandry — created the population most coupled to electromagnetic fields. The nested χ model formalises this: each population carries a biological χ profile that modulates the EMF-fertility relationship at five scales, from molecular to demographic.",
    npCta: "Evidence: evolutionary origins",

    warningLabel: "PREDICTIVE POWER",
    warningTitle: "The 35-year warning",
    warningNarrative: "Finland's testosterone levels began declining in the 1970s. For 40 years, fertility remained stable. Then it collapsed: from 1.87 children per woman (2010) to 1.26 (2024) — a 33% drop in fifteen years. The testosterone data could have predicted this 15 years in advance. The same data now points to the United States reaching the same threshold around 2030.",
    warningCaveat: "Testosterone decline rates are age-independent secular trends documented in peer-reviewed longitudinal studies across five countries. TFR projections assume continuation of current rates. The threshold model is calibrated against Finland and South Korea; other country projections are extrapolations.",
    warningReadMore: "Read the full threshold model specification",

    teaserLabel: "LOCKED PREDICTIONS · TFR 2030",
    teaserNote: "Locked under BERM v17 and falsifiable: each will be compared against observed data in the stated year.",
    allPredictions: "All predictions",

    falsTitle: "FALSIFICATION STATUS",
    falsRan: "ran",
    falsConsistent: "consistent",
    falsFalsified: "falsified",
    falsPending: "pending",
    falsCta: "Test details",

    epistemicNote: (n: number) => `BERM v17 is a falsifiable research model, not a certainty. ${n} peer-reviewed references across 11 independent research domains. 24+ regulatory-validated non-thermal mechanisms. Cross-sectional formula: LOOCV RMSE 0.522, 74% of countries within 0.5 children of prediction. Residential electricity consumption outperforms GDP as a TFR predictor by 21%. Locked predictions with dates and confidence intervals. If the predictions fail, the model is wrong.`,
    epistemicStats: "Hindcast K₈ = 0.81 · K₁₀ = 0.71 · Cross-sectional RMSE = 0.522",
    epistemicAuthor: "Otto Juote · MSc Biomedicine, Bioscience and Society (LSE) · Independent research",

    ctaModel: "Model specification",
    ctaEvidence: "Evidence register",
    ctaData: "Explore data",
    ctaMath: "Mathematics",

    thesisBreak1Kicker: "FROM SYMPTOMS TO MECHANISM",
    thesisBreak1: "If all these declining indicators share one upstream cause, there should be a single biological pathway that explains each of them independently. There is.",
    thesisBreak2Kicker: "FROM EVIDENCE TO PREDICTION",
    thesisBreak2: "A model that only explains the past is a narrative. A model that predicts the future is falsifiable.",
  },
  fi: {
    heroTitle: "Jotain tapahtuu hedelmällisyydelle",
    heroDeck: "Ihmisen lisääntymiselle tapahtuu jotain, jota pronatalistiset politiikat, taloudelliset kannustimet ja kulttuuriset interventiot eivät ole onnistuneet kääntämään.",
    heroContext: "Syntyvyys romahtaa maailmanlaajuisesti. Siittiöiden määrä on puolittunut. Testosteroni laskee jokaisessa teollistuneessa populaatiossa — jopa miehillä, jotka eivät ole lihoneet. Mehiläisyhdyskunnat, lintupopulaatiot ja sammakkoeläimet vähenevät samalla aikajanalla.",
    whatIsThis: "Biosähkömagneettinen riskimalli (BERM) tarjoaa selityksen: modernin sähköinfrastruktuurin tuottamat sähkömagneettiset kentät vaikuttavat jänniteherkiin kalsiumkanaviin — proteiineihin, jotka löytyvät jokaisesta solusta — häiriten biologisia järjestelmiä, jotka säätelevät lisääntymistä, aineenvaihduntaa, unta ja neurologista terveyttä.",
    heroEpistemic: "Tämä sivusto esittää mallin, sen evidenssin ja falsifioitavat ennusteet. Jokainen väite on rajattu episteemisellä tasolla. Jokainen ennuste on lukittu kumoamiskriteerillä. Jos malli on väärässä, se on suunniteltu epäonnistumaan näkyvästi.",

    s1Title: "KRIISI LUVUISSA",
    s1Intro: "Nämä trendit on dokumentoitu itsenäisesti tuhansissa tutkimuksissa. Selittämättä jää, miksi ne kaikki tapahtuvat samanaikaisesti, kaikissa teollistuneissa maissa, ja miksi mikään interventio ei ole kääntänyt niitä.",

    impactGrid: [
      { stat: "5,0 → 2,2", label: "Globaali TFR vuodesta 1960 — lasku kiihtyy", sub: "Alle 2,1:n populaatiot supistuvat. Alle 1,3:n palautumista ei ole koskaan havaittu ilman maahanmuuttoa.", href: "/explore" },
      { stat: "−62 %", label: "Siittiökonsentraatio (Levine 2023, 223 tutkimusta)", sub: "Lasku ei osoita tasaantumisen merkkejä. Nykyisellä vauhdilla mediaaniluvut saavuttavat subfertiliteettikynnyksen yhden sukupolven sisällä.", href: "/model#causal-diagram" },
      { stat: "−1,2 %/v", label: "Testosteronilasku, ikäriippumaton (Travison 2007)", sub: "Tämä lasku jatkuu jopa miehillä, jotka pitävät painonsa — sulkien pois lihavuuden ensisijaisena syynä.", href: "/model#testosterone-threshold" },
      { stat: "49", label: "Maata alle korvaavuustason TFR 1,4", sub: "Ei vain vauraita maita. Keskituloiset maat seuraavat samaa kehityskulkua, 15–20 vuotta jäljessä.", href: "/explore" },
      { stat: "200 mrd $", label: "Korean pronatalismi → TFR silti 0,72", sub: "Historian kallein pronatalistinen ohjelma ei ole vaikuttanut hedelmällisyyteen mitattavasti.", href: "/model#testosterone-threshold" },
      { stat: "TFR 6,1 vs 1,66", label: "Amissit vs USA — yhteisöt ilman älypuhelimia", sub: "Vaikka muut elämäntapatekijät eroavat, hedelmällisyyseron suuruus ylittää sen, mitä ruokavalio- tai elämäntapatutkimukset ovat selittäneet.", href: "/evidence/populations" },
    ],

    bridgeTitle: "MIKSI NÄMÄ LUVUT KUULUVAT YHTEEN",
    bridgeP1: "Tavanomaiset selitykset käsittelevät jokaista trendiä erikseen: hedelmällisyyden lasku selitetään taloudella ja kulttuurilla, siittiölasku kemikaaleilla ja elämäntavoilla, testosteronilasku lihavuudella ja unihäiriöt ruuduilla.",
    bridgeP2: "Mutta nämä selitykset epäonnistuvat perustestissä: ne eivät pysty selittämään, miksi kaikki nämä trendit tapahtuvat samanaikaisesti, kaikissa teollistuneissa maissa, ja miksi ne korreloivat vahvemmin sähköinfrastruktuurin kuin minkään sosiaalisen tai taloudellisen muuttujan kanssa.",
    bridgeP3: "BERM ehdottaa yhtä ylävirran mekanismia: sähköjohdoista, langattomista laitteista ja tukiasemainfrastruktuurista tulevat sähkömagneettiset kentät vaikuttavat jänniteherkiin kalsiumkanaviin (VGCC) — samoihin proteiineihin, jotka säätelevät hormonien eritystä, siittiöiden liikkuvuutta, hermosignalointia ja aineenvaihduntatoimintaa. Kun kalsiumsignalointi häiriintyy, jälkivaikutukset ilmenevät erillisinä sairauksina. Ne eivät ole. Ne ovat saman fysiologisen häiriön eri oireita.",
    bridgeCta1: "Tutki mekanismia",
    bridgeCta2: "Katso evidenssi",
    bridgeCta3: "Lue ennusteet",

    paradoxIntro: "Jos hedelmällisyyden lasku johtuisi informaatiosta — pääsy ehkäisyyn, arvojen muutos, taloudellinen harkinta — niin tietolaitteen (matkapuhelin) pitäisi olla vahvin ennustaja. Ei ole.",

    sentinelCta: "Kaikki sentinellit",

    paradoxLabel: "POIKKILEIKKAUSLÖYDÖS v17.1",
    paradoxTitle: "Matkapuhelinparadoksi",
    paradoxText: "54 maan aineistossa asumisen sähkönkulutus on vahvin yksittäinen hedelmällisyyslaskun ennustaja (RMSE 0,533). Matkapuhelintilaukset — tietolaite — ovat heikoin (RMSE 1,053). Infrastruktuurimuuttuja ennustaa parhaiten — yhdenmukaista fyysisen altistusmekanismin kanssa.",
    paradoxStat1: "LOOCV RMSE",
    paradoxVal1: "0,522",
    paradoxStat2: "R²",
    paradoxVal2: "0,851",
    paradoxStat3: "Maat 0,5 sisällä",
    paradoxVal3: "74 %",
    paradoxCta: "Poikkileikkauskaava",

    klimentidisLabel: "KLIMENTIDISIN PARADOKSI",
    klimentidisTitle: "Jopa laboratoriorotat lihovat",
    klimentidisText: "Laboratoriorotat kontrolloidulla ruokavaliolla, villit rotat, lemmikit — koirat ja kissat — kaikki lihovat vuosikymmenestä toiseen. 24 populaatiota, 8 lajia, p = 1,2 × 10⁻⁷. BERM tunnistaa EMF:n ainoaksi ympäristötekijäksi, joka on lisääntynyt kaikissa näissä ympäristöissä samanaikaisesti.",
    klimentidisNote: "Klimentidis ym. (2010) eivät tutkineet EMF:ää. He ehdottivat \"toistaiseksi tunnistamattomia tekijöitä.\" EMF-tulkinta on BERM:n johtopäätös.",
    klimentidisLink: "Lue metabolinen kaskadi",

    why2012Label: "2012-INFLEKTIO",
    why2012Title: "Miksi 2012? Se oli laite, ei sisältö",
    why2012Text: "Sosiaalinen media on ollut olemassa vuodesta 2003 — ilman mielenterveyskriisiä. Kriisi alkoi 2012, kun älypuhelimet ylittivät 50 % adoption nuorten keskuudessa. BERM:n selitys: 2012 ei ollut sisällöstä — se oli laitteesta. Älypuhelin toi jatkuvan kehokontakti-EMF-altistuksen (WiFi + 4G + Bluetooth, 24/7, myös sängyssä yöllä).",
    why2012Detail: "Yhdistettynä olemassa olevaan sähköverkon ELF-primingiin ja juuri pakotettuun LED-valaistukseen (EU:n hehkulamppukielto 2009–2012), 2012 oli vuosi jolloin kumulatiivinen monitaajuinen Ca²⁺-kuorma ylitti CaMKII:n autofosforylaatiokynnyksen väestötasolla.",
    why2012Prediction: "Ennuste: sisältörajoitukset (Australia, Norja) EIVÄT ratkaise kriisiä koska mekanismi on laitteisto, ei sisältö.",
    why2012Cta: "Teknologia-altistusanalyysi",

    pharmaLabel: "FARMAKOLOGINEN TESTI",
    pharmaTitle: "Kalsiumsalpaajat vähentävät BERM:n ennustamia sairauksia",
    pharmaText: "Jos BERM:n kalsiummekanismi on oikea, kalsiumkanavia salpaavien lääkkeiden pitäisi vähentää sairauksien esiintyvyyttä BERM:n kaskadeissa — vaikka ne on määrätty muihin tarkoituksiin.",
    pharmaEvidence: "Kolme rekisteritutkimusta (Suomi, Iso-Britannia), joissa 264 625 vaikeasta mielenterveydenhäiriöstä kärsivää potilasta, löysi juuri tämän: sydänverisuonitautiin määrätyt kalsiumsalpaajat vähensivät psykiatrisia sairaalahoitoja (HR 0,79–0,83) ja itsetuhoisuutta.",
    pharmaPenetrant: "Aivoja läpäisevät kalsiumsalpaajat (nifedipiini) tuottivat 12 % paremmat psykiatriset tulokset kuin ei-läpäisevät (amlodipiini) — mallin ennusteen mukaisesti.",
    pharmaTrial: "ETH Zürichin meneillään oleva kliininen koe (NCT06998368) testaa suoraan voiko aivoja läpäisevä kalsiumsalpaaja nimodipiini estää 5G:n vaikutuksia uneen.",
    pharmaCta: "Katso farmakologinen evidenssi",

    weightLabel: "PAINOVAKAA LASKU",
    weightTitle: "Testosteroni laskee jopa miehillä, jotka eivät ole lihoneet",
    weightIntro: "Yleinen vastaväite: \"Testosteroni laskee koska miehet lihovat.\" Jos totta, painonsa säilyttävien miesten testosteronin pitäisi pysyä ennallaan. Ei pysy.",
    weightSanti: "Vuonna 2025 kaikkien aikojen suurin meta-analyysi (Santi ym., 1 064 891 miestä) vahvisti: sekä testosteroni että luteinisoiva hormoni laskevat, riippumatta painoindeksistä. Ongelma ei ole vain kiveksissä — se ulottuu aivolisäkkeeseen ja hypotalamukseen.",
    weightMechanism: "BERM selittää molemmat löydökset: EMF häiritsee testosteronituotantoa suoraan (kalsiumkanavien kautta Leydigin soluissa) ja epäsuorasti hypotalamus-aivolisäke-akselin kautta (melatoniini- ja kortisoolireittien kautta).",

    mazurQuote: "Emme ole tunnistaneet syytä testosteronin sekulaarilaskuun, mutta suljemme pois kasvavan lihavuuden riittävänä tai ensisijaisena selityksenä, ja kiistämme oletuksen, jonka mukaan miehet, jotka välttävät liiallista painonnousua, säilyttävät nuoruutensa testosteronitasot.",
    mazurSource: "Mazur ym. 2013, PLOS ONE",
    mazurContext: "991 US Air Force -veteraania, 20 vuoden seuranta. Painonsa säilyttäneet miehet menettivät 19 % testosteroninsa.",
    mazurLink: "Lue kausaalianalyysi",

    howTitle: "Miten malli toimii",
    causalLabel: "KOLMIKANAVAMEKANISMI",
    causalTitle: "ELF · IF · RF — kolme taajuuskaistaa, kolme biologista reittiä",
    causalNote: "Matkapuhelinliittymätiheys on yhdistelmäproksi koko sähkömagneettiselle ympäristölle. Malli jäljittää kolme itsenäistä kanavaa — ELF (sähköverkko, valaistus), IF (kytkentäelektroniikka, LED-välkyntä), RF (tukiasemat, Wi-Fi, tutka) — kryptokromihäiriön, kalsiumsignaloinnin ja kalvojännitteen kautta pariutumisen lisääntymiskapasiteettiin.",

    npLabel: "EVOLUUTION ALKUPERÄT",
    npTitle: "Pohjoinen paketti",
    npText: "Miksi Pohjois-Eurooppa laski ensimmäisenä korvaavuustason hedelmällisyyden alle? BERM ehdottaa, että sama koselektio joka optimoi kryptokromiherkkyyden — siniset silmät (OCA2), laktoosinsietokyky (LCT) ja karjankasvatus — loi populaation, joka on voimakkaimmin kytketty sähkömagneettisiin kenttiin. Sisäkkäinen χ-malli formalisoi tämän: jokaisella populaatiolla on biologinen χ-profiili, joka moduloi EMF-hedelmällisyyssuhdetta viidessä skaalassa, molekulaarisesta demografiseen.",
    npCta: "Evidenssi: evoluution alkuperät",

    warningLabel: "ENNUSTUSVOIMA",
    warningTitle: "35 vuoden varoitus",
    warningNarrative: "Suomen testosteronitasot alkoivat laskea 1970-luvulla. 40 vuoden ajan hedelmällisyys pysyi vakaana. Sitten se romahti: 1,87 lasta naista kohden (2010) → 1,26 (2024) — 33 %:n pudotus viidessätoista vuodessa. Testosteronidata olisi ennustanut tämän 15 vuotta etukäteen. Sama data ennustaa nyt Yhdysvalloille samaa noin vuodelle 2030.",
    warningCaveat: "Testosteronin laskuvauhdit ovat ikäriippumattomia sekulaaritrendejä, jotka on dokumentoitu vertaisarvioiduissa pitkittäistutkimuksissa viidessä maassa. TFR-ennusteet olettavat nykyisten vauhtien jatkumisen. Kynnysmalli on kalibroitu Suomen ja Etelä-Korean datalla; muiden maiden ennusteet ovat ekstrapolointeja.",
    warningReadMore: "Lue koko kynnysmallin määrittely",

    teaserLabel: "LUKITUT ENNUSTEET · TFR 2030",
    teaserNote: "Lukittu BERM v17:lla ja falsifioitavissa: jokainen verrataan havaittuun dataan ilmoitettuna vuonna.",
    allPredictions: "Kaikki ennusteet",

    falsTitle: "FALSIFIKAATIOTILANNE",
    falsRan: "ajettu",
    falsConsistent: "yhteensopiva",
    falsFalsified: "falsifioitu",
    falsPending: "odottaa",
    falsCta: "Testien yksityiskohdat",

    epistemicNote: (n: number) => `BERM v17 on falsifioitava tutkimusmalli, ei varma tieto. ${n} vertaisarvioitua viitettä 11 riippumattomalta tutkimusalalta. 24+ regulatiivisesti validoitua ei-termistä mekanismia. Poikkileikkauskaava: LOOCV RMSE 0,522, 74 % maista 0,5 lapsen sisällä ennusteesta. Asumisen sähkönkulutus ylittää BKT:n TFR-ennustajana 21 %. Lukitut ennusteet päivämäärineen ja luottamusväleineen. Jos ennusteet epäonnistuvat, malli on väärässä.`,
    epistemicStats: "Hindcast K₈ = 0,81 · K₁₀ = 0,71 · Poikkileikkaus-RMSE = 0,522",
    epistemicAuthor: "Otto Juote · MSc Biomedicine, Bioscience and Society (LSE) · Itsenäinen tutkimus",

    ctaModel: "Mallin määrittely",
    ctaEvidence: "Evidenssirekisteri",
    ctaData: "Tutki dataa",
    ctaMath: "Matematiikka",

    thesisBreak1Kicker: "OIREISTA MEKANISMIIN",
    thesisBreak1: "Jos kaikki nämä laskevat indikaattorit jakavat yhden yhteisen syyn, sen pitäisi selittyä yhdellä biologisella reitillä. Sellainen on.",
    thesisBreak2Kicker: "EVIDENSSISTÄ ENNUSTEESEEN",
    thesisBreak2: "Malli, joka selittää vain menneisyyden, on narratiivi. Malli, joka ennustaa tulevaisuuden, on falsifioitavissa.",
  },
} as const;

const TEASER_IDS = ["kr-2030-tfr", "fi-2030-tfr", "us-2030-tfr"] as const;
const TEASER_PREDICTIONS = TEASER_IDS.map(
  (id) => LOCKED_PREDICTIONS.find((p) => p.id === id)!
).filter(Boolean);

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  if (locale === "fi") {
    return {
      title: "Extinction Field – BERM-tutkimusmalli",
      description:
        "Falsifioitava tutkimusmalli sähkömagneettisten kenttätilojen ja lisääntymiskyvyn yhteyden testaamiseen.",
    };
  }
  return {
    title: "Extinction Field – BERM research model",
    description:
      "A falsifiable research model testing whether electromagnetic field states contribute to the global decline in reproductive indicators.",
  };
}

export default async function Home({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const activeLocale: Locale = locale === "fi" ? "fi" : "en";
  const d = COPY[activeLocale];
  const prefix = `/${activeLocale}`;
  const fals = getFalsificationStats();

  return (
    <div className="max-w-5xl mx-auto px-6">
      {/* ── 1. Hero — cinematic banner with overlay text ── */}
      <header className="relative -mx-6 overflow-hidden rounded-b-2xl sm:rounded-2xl sm:mx-0 mt-0 sm:mt-8 mb-14">
        <div className="relative min-h-[420px] sm:min-h-[480px] lg:min-h-[520px]">
          <Image
            src="/images/hero-fertilization.png"
            alt=""
            fill
            priority
            className="object-cover object-[65%_center]"
            sizes="(max-width: 1024px) 100vw, 1024px"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/40 to-black/5" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent" />
          <div className="relative z-10 flex flex-col justify-end h-full p-6 sm:p-10 lg:p-14 max-w-2xl">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-serif font-semibold tracking-[-0.02em] leading-[1.12] mb-4 text-white drop-shadow-lg">
              {d.heroTitle}
            </h1>
            <p className="text-base sm:text-lg leading-relaxed text-white/90 mb-3 drop-shadow">{d.heroDeck}</p>
            <p className="text-sm sm:text-base leading-relaxed text-white/70">{d.heroContext}</p>
          </div>
        </div>
      </header>

      <div className="max-w-3xl mb-14 space-y-4">
        <p className="text-[0.9375rem] leading-relaxed text-foreground-muted">{d.whatIsThis}</p>
        <p className="text-sm leading-relaxed text-foreground-muted border-l-2 border-accent/30 pl-4">{d.heroEpistemic}</p>
      </div>

      {/* ── 2. Crisis in Numbers — contextualized stat cards ── */}
      <section className="pb-20">
        <h2 className="editorial-kicker text-accent mb-3">{d.s1Title}</h2>
        <p className="text-sm text-foreground-muted leading-relaxed mb-6 max-w-3xl">{d.s1Intro}</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {d.impactGrid.map((item, i) => {
            const Icon = SPARKLINE_ICONS[i];
            return (
              <Link key={item.stat} href={`${prefix}${item.href}`} className="group">
                <article className="rounded-xl border border-card-border bg-card-bg p-5 flex flex-col h-full transition-colors group-hover:border-accent/50 group-hover:bg-accent/5">
                  <Icon size={22} className="text-accent/50 mb-3" strokeWidth={1.5} aria-hidden="true" />
                  <p className="font-mono-num text-2xl font-semibold text-accent leading-tight">{item.stat}</p>
                  <p className="text-[0.8125rem] text-foreground-muted mt-2 leading-snug">{item.label}</p>
                  <Sparkline data={SPARKLINE_DATA[i]} index={i} />
                  <p className="text-xs text-foreground-muted/70 mt-2 leading-snug border-t border-card-border pt-2">{item.sub}</p>
                </article>
              </Link>
            );
          })}
        </div>
      </section>

      {/* ── 3. Bridge — why these numbers belong together ── */}
      <section className="pb-20">
        <div className="max-w-3xl">
          <h2 className="text-xl sm:text-2xl font-semibold mb-6">{d.bridgeTitle}</h2>
          <p className="text-[0.9375rem] leading-relaxed text-foreground-muted mb-4">{d.bridgeP1}</p>
          <p className="text-[0.9375rem] leading-relaxed text-foreground-muted mb-4">{d.bridgeP2}</p>
          <p className="text-[0.9375rem] leading-relaxed text-foreground-muted mb-6">{d.bridgeP3}</p>
          <div className="flex flex-wrap gap-4">
            <Link
              href={`${prefix}/model`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
            >
              {d.bridgeCta1} <ArrowRight size={14} />
            </Link>
            <Link
              href={`${prefix}/evidence`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
            >
              {d.bridgeCta2} <ArrowRight size={14} />
            </Link>
            <Link
              href={`${prefix}/predictions`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
            >
              {d.bridgeCta3} <ArrowRight size={14} />
            </Link>
          </div>
        </div>
      </section>

      {/* ── 4. Mobile phone paradox — with contextualizing intro ── */}
      <section className="pb-20">
        <div className="rounded-xl border border-accent/20 bg-card-bg p-6 sm:p-8">
          <p className="editorial-kicker text-accent mb-2">{d.paradoxLabel}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-3">{d.paradoxTitle}</h2>
          <p className="text-[0.9375rem] text-foreground/90 leading-relaxed max-w-3xl mb-4">{d.paradoxIntro}</p>
          <p className="text-sm text-foreground-muted leading-relaxed max-w-3xl mb-5">{d.paradoxText}</p>
          <div className="grid grid-cols-3 gap-4 mb-5 max-w-md">
            <div>
              <p className="font-mono-num text-2xl font-semibold text-accent">{d.paradoxVal1}</p>
              <p className="text-xs text-foreground-muted mt-1">{d.paradoxStat1}</p>
            </div>
            <div>
              <p className="font-mono-num text-2xl font-semibold text-accent">{d.paradoxVal2}</p>
              <p className="text-xs text-foreground-muted mt-1">{d.paradoxStat2}</p>
            </div>
            <div>
              <p className="font-mono-num text-2xl font-semibold text-accent">{d.paradoxVal3}</p>
              <p className="text-xs text-foreground-muted mt-1">{d.paradoxStat3}</p>
            </div>
          </div>
          <Link
            href={`${prefix}/mathematics#cross-sectional`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.paradoxCta} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 5A. Klimentidis Paradox ── */}
      <section className="pb-20">
        <div className="max-w-4xl rounded-xl border border-status-partial/30 bg-status-partial/5 p-6 sm:p-8">
          <p className="text-xs uppercase tracking-wider text-status-partial font-semibold mb-2">{d.klimentidisLabel}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-3">{d.klimentidisTitle}</h2>
          <p className="text-3xl font-bold text-status-partial mb-4">
            24 {activeLocale === "fi" ? "populaatiota" : "populations"} · 8 {activeLocale === "fi" ? "lajia" : "species"} · p = 1.2 × 10⁻⁷
          </p>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.klimentidisText}</p>
          <p className="text-xs text-foreground-muted/70 italic mb-4">{d.klimentidisNote}</p>
          <Link
            href={`${prefix}/model#camkii-convergence`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.klimentidisLink} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 5A½. Why 2012? ── */}
      <section className="pb-20">
        <div className="max-w-4xl rounded-xl border border-amber-500/30 bg-amber-500/5 p-6 sm:p-8">
          <p className="text-xs uppercase tracking-wider text-amber-500 font-semibold mb-2">{d.why2012Label}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-3">{d.why2012Title}</h2>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.why2012Text}</p>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.why2012Detail}</p>
          <p className="text-sm font-medium text-amber-500 mb-4">{d.why2012Prediction}</p>
          <Link
            href={`${prefix}/evidence/technology`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.why2012Cta} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 5B. Pharmacological Test ── */}
      <section className="pb-20">
        <div className="max-w-4xl rounded-xl border border-accent/20 bg-accent/5 p-6 sm:p-8">
          <p className="text-xs uppercase tracking-wider text-accent font-semibold mb-2">{d.pharmaLabel}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-3">{d.pharmaTitle}</h2>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.pharmaText}</p>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.pharmaEvidence}</p>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3 max-w-3xl">{d.pharmaPenetrant}</p>
          <p className="text-xs text-foreground-muted/70 italic mb-4 max-w-3xl">{d.pharmaTrial}</p>
          <Link
            href={`${prefix}/evidence/pharmacology`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.pharmaCta} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 5C. Weight-Stable Decline (with Mazur quote) ── */}
      <section className="pb-20">
        <div className="max-w-3xl">
          <p className="editorial-kicker text-accent mb-2">{d.weightLabel}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-4">{d.weightTitle}</h2>
          <p className="text-[0.9375rem] text-foreground-muted leading-relaxed mb-6">{d.weightIntro}</p>
          <blockquote className="border-l-4 border-status-partial/50 pl-5 py-3 mb-5">
            <p className="text-base sm:text-lg text-foreground italic leading-relaxed mb-3">&ldquo;{d.mazurQuote}&rdquo;</p>
            <footer className="text-sm text-foreground-muted">
              <cite className="not-italic font-medium">{d.mazurSource}</cite>
              <span className="block text-xs mt-1">{d.mazurContext}</span>
            </footer>
          </blockquote>
          <p className="text-sm text-foreground-muted leading-relaxed mb-3">{d.weightSanti}</p>
          <p className="text-sm text-foreground-muted leading-relaxed mb-4">{d.weightMechanism}</p>
          <Link
            href={`${prefix}/model#causal-structure`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.mazurLink} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── Thesis break 1: symptoms → mechanism ── */}
      <section className="pb-20">
        <div className="thesis-break">
          <p className="editorial-kicker mb-3">{d.thesisBreak1Kicker}</p>
          <p className="text-lg sm:text-xl font-serif font-semibold leading-snug max-w-2xl">{d.thesisBreak1}</p>
        </div>
      </section>

      {/* ── 6. Sentinel cascade ── */}
      <section className="pb-20">
        <SentinelCascadeCompact locale={activeLocale} />
        <div className="mt-4 text-right">
          <Link
            href={`${prefix}/sentinel`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            {d.sentinelCta} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 7. How the model works ── */}
      <section className="pb-20">
        <h2 className="editorial-section-heading mb-8">{d.howTitle}</h2>
        <figure className="data-figure">
          <figcaption className="data-figure__caption">
            <p className="editorial-kicker text-accent">{d.causalLabel}</p>
            <p className="data-figure__title mt-1">{d.causalTitle}</p>
          </figcaption>
          <div className="overflow-x-auto p-1 md:p-3">
            <ThreeChannelSummary locale={activeLocale} />
          </div>
          <p className="data-figure__note">{d.causalNote}</p>
        </figure>
      </section>

      {/* ── 8. Northern Package ── */}
      <section className="pb-20">
        <div className="rounded-xl border border-card-border bg-card-bg p-6 sm:p-8">
          <div className="flex items-start gap-4">
            <Dna size={28} className="text-accent/60 shrink-0 mt-1" strokeWidth={1.5} aria-hidden="true" />
            <div>
              <h2 className="editorial-kicker text-accent mb-3">{d.npLabel}</h2>
              <p className="font-semibold mb-2">{d.npTitle}</p>
              <p className="text-sm sm:text-[0.9375rem] leading-relaxed text-foreground-muted">{d.npText}</p>
              <Link
                href={`${prefix}/evidence/evolution`}
                className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover mt-4"
              >
                {d.npCta} <ArrowRight size={14} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ── 9. TheraBionic clinical validation ── */}
      <TheraBionicProof locale={activeLocale} prefix={prefix} />

      {/* ── 10. Bradford Hill criteria ── */}
      <BradfordHillCard locale={activeLocale} prefix={prefix} />

      {/* ── Thesis break 2: evidence → prediction ── */}
      <section className="pb-20">
        <div className="thesis-break">
          <p className="editorial-kicker mb-3">{d.thesisBreak2Kicker}</p>
          <p className="text-lg sm:text-xl font-serif font-semibold leading-snug max-w-2xl">{d.thesisBreak2}</p>
        </div>
      </section>

      {/* ── 11. The 35-Year Warning ── */}
      <section className="pb-20">
        <div className="max-w-4xl">
          <p className="editorial-kicker text-accent mb-2">{d.warningLabel}</p>
          <h2 className="text-xl sm:text-2xl font-semibold mb-6">{d.warningTitle}</h2>
          <FinlandLagChart locale={activeLocale} />
          <p className="text-sm text-foreground-muted leading-relaxed mt-6 mb-6 max-w-3xl">{d.warningNarrative}</p>
          <ThreePhaseIndicator locale={activeLocale} />
          <SixFactorSummary locale={activeLocale} />
          <p className="text-xs text-foreground-muted mt-4 max-w-3xl leading-relaxed">{d.warningCaveat}</p>
          <Link
            href={`${prefix}/model#testosterone-threshold`}
            className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover mt-4"
          >
            {d.warningReadMore} <ArrowRight size={14} />
          </Link>
        </div>
      </section>

      {/* ── 12. Locked predictions ── */}
      <section className="pb-20">
        <div className="rounded-xl border border-card-border bg-card-bg p-6 sm:p-8">
          <div className="flex flex-wrap items-baseline justify-between gap-4 mb-6">
            <h2 className="editorial-kicker text-accent">{d.teaserLabel}</h2>
            <Link
              href={`${prefix}/predictions`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
            >
              {d.allPredictions} <ArrowRight size={14} />
            </Link>
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
            {TEASER_PREDICTIONS.map((p) => (
              <div key={p.id} className="border-t border-card-border pt-4">
                <p className="text-sm font-medium mb-2">
                  {countryLabel(p, activeLocale)} {p.year}
                </p>
                <p>
                  <span className="font-mono-num text-3xl font-semibold leading-none text-accent">
                    {p.central.toFixed(2)}
                  </span>
                  <span className="ml-2 font-mono-num text-sm text-foreground-muted">
                    [{p.ciLow.toFixed(2)} – {p.ciHigh.toFixed(2)}]
                  </span>
                </p>
              </div>
            ))}
          </div>
          <p className="mt-6 text-sm leading-relaxed text-foreground-muted">{d.teaserNote}</p>
        </div>
      </section>

      {/* ── 13. Featured articles ── */}
      <LatestArticles locale={activeLocale} />

      {/* ── 14. Falsification status ── */}
      <section className="pb-20">
        <div className="rounded-xl border border-card-border bg-card-bg p-5 sm:p-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <Shield size={20} className="text-accent/60 shrink-0" strokeWidth={1.5} aria-hidden="true" />
              <h2 className="editorial-kicker text-accent">{d.falsTitle}</h2>
            </div>
            <Link
              href={`${prefix}/mathematics#falsification`}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-accent transition-colors hover:text-accent-hover"
            >
              {d.falsCta} <ArrowRight size={14} />
            </Link>
          </div>
          <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm">
            <span><span className="font-mono-num font-semibold text-accent">{fals.total}</span> tests</span>
            <span><span className="font-mono-num font-semibold text-accent">{fals.ran}</span> {d.falsRan}</span>
            <span><span className="font-mono-num font-semibold text-status-confirmed">{fals.consistent}</span> {d.falsConsistent}</span>
            <span><span className="font-mono-num font-semibold text-status-refuted">{fals.falsified}</span> {d.falsFalsified}</span>
            <span><span className="font-mono-num font-semibold text-foreground-muted">{fals.pending}</span> {d.falsPending}</span>
          </div>
        </div>
      </section>

      {/* ── 15. Quick links ── */}
      <section className="pb-10">
        <div className="flex flex-wrap gap-3">
          {[
            { href: `${prefix}/model`, label: d.ctaModel },
            { href: `${prefix}/evidence`, label: d.ctaEvidence },
            { href: `${prefix}/explore`, label: d.ctaData },
            { href: `${prefix}/mathematics`, label: d.ctaMath },
          ].map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className="inline-flex items-center gap-2 rounded-lg border border-card-border bg-card-bg px-5 py-3 text-sm font-medium transition-colors hover:border-accent/40 hover:text-accent"
            >
              {link.label} <ArrowRight size={14} />
            </Link>
          ))}
        </div>
      </section>

      {/* ── 16. Epistemic footer ── */}
      <footer className="pb-16 border-t border-card-border pt-8">
        <p className="text-sm leading-relaxed text-foreground-muted max-w-3xl">{d.epistemicNote(getReferenceCount())}</p>
        <p className="font-mono-num text-xs text-foreground-muted/60 mt-3">{d.epistemicStats}</p>
        <p className="text-xs text-foreground-muted/40 mt-2">{d.epistemicAuthor}</p>
      </footer>
    </div>
  );
}
