/**
 * @deprecated Migration-audit artifact only.
 *
 * Inline citation link table.
 *
 * The website runtime no longer imports this translated-text lookup. All
 * visible citations resolve exclusively through a literal referenceId.
 * GENERATED by berm/export_citation_links.py — do not edit by hand.
 * Regenerate after changing references_full.json, legacyEvidence.json or any
 * inline `citation:` label.
 */

const CITATION_LINKS: Readonly<Record<string, string>> = {
  "aerts et al environment international|2019": "https://doi.org/10.1016/j.envint.2019.01.002",
  "aerts ym environment international|2019": "https://doi.org/10.1016/j.envint.2019.01.002",
  "ahmadi ss et al electronic physician 2016|2016": "https://doi.org/10.19082/2168",
  "alshammari 2022 pmc8777647": "https://doi.org/10.3390/nu14020339",
  "baldini gm et al toxics 2025|2025": "https://doi.org/10.3390/toxics13060510",
  "bartolke et al faseb j|2025": "https://doi.org/10.1096/fj.202402614R",
  "bartolke ym faseb j|2025": "https://doi.org/10.1096/fj.202402614R",
  "bektas et al bioelectromagnetics|2026": "https://doi.org/10.1002/bem.70043",
  "bektas ym bioelectromagnetics|2026": "https://doi.org/10.1002/bem.70043",
  "belmin et al nature sustainability|2022": "https://doi.org/10.1038/s41893-021-00830-3",
  "belmin ym nature sustainability|2022": "https://doi.org/10.1038/s41893-021-00830-3",
  "belpomme et al|2022": "https://doi.org/10.1016/j.envres.2022.113374",
  "belpomme ym|2022": "https://doi.org/10.1016/j.envres.2022.113374",
  "berm reproducibility analysis using un wpp 2024 asfr and world bank itu mobile subscriptions 2000 2023|2026": "https://population.un.org/wpp/",
  "berm v17 1 cross sectional analysis|2026": "https://population.un.org/wpp/",
  "berm v17 1 formula discovery|2026": "https://population.un.org/wpp/",
  "berm v17 1 kaavanloyto|2026": "https://population.un.org/wpp/",
  "berm v17 1 poikkileikkausanalyysi|2026": "https://population.un.org/wpp/",
  "bertagna et al ann ny acad sci|2025": "https://doi.org/10.1111/nyas.15386",
  "bertagna ym ann ny acad sci|2025": "https://doi.org/10.1111/nyas.15386",
  "blackman cf et al bioelectromagnetics 1985|1985": "https://doi.org/10.1002/bem.2250060402",
  "boyes et al science advances|2021": "https://doi.org/10.1126/sciadv.abi8322",
  "boyes ym science advances|2021": "https://doi.org/10.1126/sciadv.abi8322",
  "calis p et al fetal and pediatric pathology 2021|2021": "https://doi.org/10.1080/15513815.2019.1692112",
  "cao h et al international journal of environmental research and public health 2015|2015": "https://doi.org/10.3390/ijerph120202071",
  "chae et al plos one|2019": "https://doi.org/10.1371/journal.pone.0211826",
  "chae k s et al plos one 2019|2019": "https://doi.org/10.1371/journal.pone.0211826",
  "chae ym plos one|2019": "https://doi.org/10.1371/journal.pone.0211826",
  "chakraborty p et al reproductive toxicology 2020|2020": "https://doi.org/10.1016/j.reprotox.2020.06.012",
  "chen et al 2016 elife": "https://doi.org/10.1016/j.jid.2016.02.001",
  "chen ym 2016 elife": "https://doi.org/10.1016/j.jid.2016.02.001",
  "chinese lockdown cohort pubmed 41036143|2024": "https://pubmed.ncbi.nlm.nih.gov/41036143/",
  "clarke et al science|2013": "https://doi.org/10.1126/science.1230883",
  "clarke ym science|2013": "https://doi.org/10.1126/science.1230883",
  "colin et al journal of insect physiology 1992|1992": "https://doi.org/10.1016/0022-1910(92)90039-G",
  "cordelli e et al corrigendum environment international 2025|2025": "https://doi.org/10.1016/j.envint.2025.109449",
  "cordelli e et al environment international 2024|2024": "https://doi.org/10.1016/j.envint.2024.108509",
  "de iuliis gn et al plos one 2009|2009": "https://doi.org/10.1371/journal.pone.0006446",
  "delong et al plos one|2010": "https://doi.org/10.1371/journal.pone.0013206",
  "delong ym plos one|2010": "https://doi.org/10.1371/journal.pone.0013206",
  "deprez et al bioelectromagnetics|2025": "https://doi.org/10.1002/bem.70019",
  "deprez ym bioelectromagnetics|2025": "https://doi.org/10.1002/bem.70019",
  "dincmen hauser gursoy aatcc journal of research 2016|2016": "https://doi.org/10.14504/ajr.3.4.4",
  "dreher et al pnas|2016": "https://doi.org/10.1073/pnas.1608085113",
  "dreher ym pnas|2016": "https://doi.org/10.1073/pnas.1608085113",
  "eliyahu et al bioelectromagnetics|2006": "https://doi.org/10.1002/bem.20187",
  "eliyahu ym bioelectromagnetics|2006": "https://doi.org/10.1002/bem.20187",
  "engels et al nature|2014": "https://doi.org/10.1038/nature13290",
  "engels ym nature|2014": "https://doi.org/10.1038/nature13290",
  "england et al current biology|2023": "https://doi.org/10.1016/j.cub.2023.06.021",
  "england lihou robert current biology 2023|2023": "https://doi.org/10.1016/j.cub.2023.06.021",
  "england robert j r soc interface|2024": "https://doi.org/10.1098/rsif.2024.0156",
  "england robert pnas|2024": "https://doi.org/10.1098/rsif.2024.0156",
  "england ym current biology|2023": "https://doi.org/10.1016/j.cub.2023.06.021",
  "gao et al bioelectromagnetics|2024": "https://doi.org/10.1002/bem.22494",
  "gao ym bioelectromagnetics|2024": "https://doi.org/10.1002/bem.22494",
  "garcia robledo dierick manser pnas 2025|2025": "https://doi.org/10.1073/pnas.2419214122",
  "greggers et al proc r soc b|2013": "https://doi.org/10.1098/rspb.2013.0528",
  "greggers ym proc r soc b|2013": "https://doi.org/10.1098/rspb.2013.0528",
  "hallmann et al|2017": "https://doi.org/10.1371/journal.pone.0185809",
  "hallmann ym|2017": "https://doi.org/10.1371/journal.pone.0185809",
  "he c et al international journal of molecular sciences 2016|2016": "https://doi.org/10.3390/ijms17060939",
  "higuchi et al am j physiol|2007": "https://doi.org/10.1152/ajpregu.00355.2006",
  "higuchi et al|2007": "https://doi.org/10.1152/ajpregu.00355.2006",
  "higuchi ym am j physiol|2007": "https://doi.org/10.1152/ajpregu.00355.2006",
  "higuchi ym|2007": "https://doi.org/10.1152/ajpregu.00355.2006",
  "hore mouritsen annual review of biophysics|2016": "https://doi.org/10.1146/annurev-biophys-032116-094545",
  "huss et al environ health perspect|2007": "https://doi.org/10.1097/00001648-200611001-01176",
  "huss ym environ health perspect|2007": "https://doi.org/10.1097/00001648-200611001-01176",
  "iolchiev bs et al agricultural biology 2019|2019": "https://doi.org/10.15389/agrobiology.2019.6.1196eng",
  "kiinalainen lockdown kohortti pubmed 41036143|2024": "https://pubmed.ncbi.nlm.nih.gov/41036143/",
  "kim et al cell|2026": "https://doi.org/10.1016/j.cell.2026.03.029",
  "kim ym cell|2026": "https://doi.org/10.1016/j.cell.2026.03.029",
  "koivisto et al neuroreport|2000": "https://doi.org/10.1097/00001756-200002070-00038",
  "koivisto ym neuroreport|2000": "https://doi.org/10.1097/00001756-200002070-00038",
  "led power quality study pmc9920439|2023": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9920439/",
  "led sahkonlaatututkimus pmc9920439|2023": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9920439/",
  "liu y et al proceedings of the national academy of sciences 2014|2014": "https://doi.org/10.1073/pnas.1209249111",
  "lochhead jj et al journal of cerebral blood flow and metabolism 2010|2010": "https://doi.org/10.1038/jcbfm.2010.29",
  "luria et al bioelectromagnetics|2009": "https://doi.org/10.1002/bem.20454",
  "luria ym bioelectromagnetics|2009": "https://doi.org/10.1002/bem.20454",
  "ma et al|2026": "https://doi.org/10.1111/andr.70119",
  "ma ym|2026": "https://doi.org/10.1111/andr.70119",
  "majewska m et al acs chemical biology 2025|2025": "https://doi.org/10.1021/acschembio.4c00576",
  "mallinson et al iscience cell press|2025": "https://doi.org/10.1016/j.isci.2025.112550",
  "mallinson woodburn o reilly iscience 2025|2025": "https://doi.org/10.1016/j.isci.2025.112550",
  "mallinson ym iscience cell press|2025": "https://doi.org/10.1016/j.isci.2025.112550",
  "meena r et al electromagnetic biology and medicine 2014|2014": "https://doi.org/10.3109/15368378.2013.781035",
  "meyer et al bioelectromagnetics|2026": "https://doi.org/10.1002/bem.70046",
  "meyer ym bioelectromagnetics|2026": "https://doi.org/10.1002/bem.70046",
  "morley robert current biology 2018|2018": "https://doi.org/10.1016/j.cub.2018.05.057",
  "morley robert current biology|2018": "https://doi.org/10.1016/j.cub.2018.05.057",
  "naderi n et al reproductive toxicology 2026|2026": "https://doi.org/10.1016/j.reprotox.2026.109300",
  "nicholls racey plos one|2007": "https://doi.org/10.1371/journal.pone.0000297",
  "nicholls racey plos one|2009": "https://doi.org/10.1371/journal.pone.0006246",
  "niessner et al j exp biol|2014": "https://doi.org/10.1242/jeb.110965",
  "niessner ym j exp biol|2014": "https://doi.org/10.1242/jeb.110965",
  "pall j cell mol med|2013": "https://doi.org/10.1111/jcmm.12088",
  "panagopoulos et al frontiers in public health|2025": "https://doi.org/10.3389/fpubh.2025.1585441",
  "panagopoulos ym frontiers in public health|2025": "https://doi.org/10.3389/fpubh.2025.1585441",
  "pawson bader ecological applications|2014": "https://doi.org/10.1890/14-0468.1",
  "poutahidis erdman mit|2014": "https://doi.org/10.1371/journal.pone.0084877",
  "puts 2008|2008": "https://doi.org/10.1016/j.anbehav.2008.02.008",
  "reflex diem et al|2005": "https://doi.org/10.1016/j.mrgentox.2005.03.006",
  "reflex diem ym|2005": "https://doi.org/10.1016/j.mrgentox.2005.03.006",
  "ritz et al nature|2004": "https://doi.org/10.1038/nature02534",
  "ritz t et al nature 2004|2004": "https://doi.org/10.1038/nature02534",
  "ritz ym nature|2004": "https://doi.org/10.1038/nature02534",
  "robert current biology|2024": "https://doi.org/10.1016/j.cub.2024.06.028",
  "salford et al|2003": "https://doi.org/10.1289/ehp.6039",
  "salford ym|2003": "https://doi.org/10.1289/ehp.6039",
  "shafik a contraception 1992|1992": "https://doi.org/10.1016/0010-7824(92)90157-O",
  "shafik ibrahim el sayed andrologia 1992|1992": "https://doi.org/10.1111/j.1439-0272.1992.tb02628.x",
  "sherrard et al plos biology|2018": "https://doi.org/10.1371/journal.pbio.2006229",
  "sherrard rm et al plos biology 2018|2018": "https://doi.org/10.1371/journal.pbio.2006229",
  "sherrard rm et al plos biology|2018": "https://doi.org/10.1371/journal.pbio.2006229",
  "sherrard rm ym plos biology|2018": "https://doi.org/10.1371/journal.pbio.2006229",
  "sherrard ym plos biology|2018": "https://doi.org/10.1371/journal.pbio.2006229",
  "sofrankova et al pathogens 2023|2023": "https://doi.org/10.3390/pathogens12121398",
  "sousouri et al neuroimage eth zurich|2025": "https://doi.org/10.1016/j.neuroimage.2025.121340",
  "sousouri ym neuroimage eth zurich|2025": "https://doi.org/10.1016/j.neuroimage.2025.121340",
  "splawski et al 2004": "https://doi.org/10.1016/j.cell.2004.09.011",
  "splawski ym 2004": "https://doi.org/10.1016/j.cell.2004.09.011",
  "sutton et al pnas|2016": "https://doi.org/10.1073/pnas.1601624113",
  "sutton ym pnas|2016": "https://doi.org/10.1073/pnas.1601624113",
  "tbahriti et al sleep biol rhythms|2026": "https://doi.org/10.1007/s41105-026-00643-x",
  "tbahriti ym sleep biol rhythms|2026": "https://doi.org/10.1007/s41105-026-00643-x",
  "thielens et al|2018": "https://doi.org/10.1038/s41598-018-22271-3",
  "thielens ym|2018": "https://doi.org/10.1038/s41598-018-22271-3",
  "tuszynski et al ttfields pmc5129338|2016": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5129338/",
  "tuszynski ym ttfields pmc5129338|2016": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5129338/",
  "ulusoy et al int j basic med sci|2025": "https://doi.org/10.22038/ijbms.2025.86952.18784",
  "ulusoy ym int j basic med sci|2025": "https://doi.org/10.22038/ijbms.2025.86952.18784",
  "usselman rj et al scientific reports 2016|2016": "https://doi.org/10.1038/srep38543",
  "xiang et al|2025": "https://doi.org/10.1530/REP-24-0432",
  "xiang ym|2025": "https://doi.org/10.1530/REP-24-0432",
  "yakymenko et al|2016": "https://doi.org/10.3109/15368378.2015.1043557",
  "yakymenko ym|2016": "https://doi.org/10.3109/15368378.2015.1043557",
  "yang et al 2015": "https://doi.org/10.1016/j.celrep.2015.04.002",
  "yang ym 2015": "https://doi.org/10.1016/j.celrep.2015.04.002",
  "yap 2025": "https://doi.org/10.3390/cells14030231",
  "yap et al cells|2025": "https://doi.org/10.3390/cells14030231",
  "yap sherrard lab cells|2025": "https://doi.org/10.3390/cells14030231",
  "yap ym cells|2025": "https://doi.org/10.3390/cells14030231",
  "yoshii et al nature|2009": "https://doi.org/10.1038/nature07183",
  "yoshii ym nature|2009": "https://doi.org/10.1038/nature07183",
  "yousefi b et al reproductive sciences 2025|2025": "https://doi.org/10.1007/s43032-025-01880-0",
  "yu et al sci total environ|2019": "https://doi.org/10.1016/j.scitotenv.2019.133860",
  "yu g et al science of the total environment 2020|2020": "https://doi.org/10.1016/j.scitotenv.2019.133860",
  "yu ym sci total environ|2019": "https://doi.org/10.1016/j.scitotenv.2019.133860",
  "zandieh a et al scientific reports 2025|2025": "https://doi.org/10.1038/s41598-025-87235-w",
  "zeghoudi et al optics laser technology|2025": "https://doi.org/10.1016/j.optlastec.2025.112583",
  "zeghoudi ym optics laser technology|2025": "https://doi.org/10.1016/j.optlastec.2025.112583",
};

/** Normalizes a citation label to its lookup key; mirrors the generator. */
export function normalizeCitationKey(citation: string): string {
  return citation
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/**
 * Source URL for an inline citation, or null when none is known.
 *
 * Citations that carry a year are keyed by label and year; modulome pages cite
 * without a separate year field and are keyed by label alone.
 */
export function citationHref(citation: string, year?: number | string): string | null {
  const key = normalizeCitationKey(citation);
  if (year !== undefined && year !== null) {
    const dated = CITATION_LINKS[`${key}|${year}`];
    if (dated) return dated;
  }
  return CITATION_LINKS[key] ?? null;
}

export const CITATION_LINK_COUNT = 153;
