export type EpistemicLevel = "E" | "M|C" | "C" | "L*";

export interface ResponseModifierScale {
  id: string;
  label_en: string;
  label_fi: string;
  label_ja: string;
  label_fr: string;
  label_ko: string;
  background_en: string;
  background_fi: string;
  background_ja: string;
  background_fr: string;
  background_ko: string;
  perturbation_en: string;
  perturbation_fi: string;
  perturbation_ja: string;
  perturbation_fr: string;
  perturbation_ko: string;
  candidate_expression: string;
  at_zero_en: string;
  at_zero_fi: string;
  at_zero_ja: string;
  at_zero_fr: string;
  at_zero_ko: string;
  at_max_en: string;
  at_max_fi: string;
  at_max_ja: string;
  at_max_fr: string;
  at_max_ko: string;
  verification: string;
  referenceIds?: string[];
  level: EpistemicLevel;
}

export interface HistoricalPhase {
  id: string;
  period: string;
  title_en: string;
  title_fi: string;
  title_ja: string;
  title_fr: string;
  title_ko: string;
  description_en: string;
  description_fi: string;
  description_ja: string;
  description_fr: string;
  description_ko: string;
}

export interface PopulationProfile {
  id: string;
  label_en: string;
  label_fi: string;
  label_ja: string;
  label_fr: string;
  label_ko: string;
  candidate_env: string;
  candidate_optical: string;
  candidate_molecular: string;
  dominant_pathway: string;
  observed_tfr: string;
  status_en: string;
  status_fi: string;
  status_ja: string;
  status_fr: string;
  status_ko: string;
}

export interface NorthernTrait {
  id: string;
  trait_en: string;
  trait_fi: string;
  trait_ja: string;
  trait_fr: string;
  trait_ko: string;
  gene: string;
  mechanism_en: string;
  mechanism_fi: string;
  mechanism_ja: string;
  mechanism_fr: string;
  mechanism_ko: string;
  cry_link_en: string;
  cry_link_fi: string;
  cry_link_ja: string;
  cry_link_fr: string;
  cry_link_ko: string;
  level: EpistemicLevel;
}

export interface EvolutionPrediction {
  id: string;
  code: string;
  title_en: string;
  title_fi: string;
  title_ja: string;
  title_fr: string;
  title_ko: string;
  test_en: string;
  test_fi: string;
  test_ja: string;
  test_fr: string;
  test_ko: string;
  falsification_en?: string;
  falsification_fi?: string;
  falsification_ja?: string;
  falsification_fr?: string;
  falsification_ko?: string;
  level: EpistemicLevel;
  timeframe: string;
  pathway?: string[];
  tags?: string[];
}

export const RESPONSE_MODIFIER_SCALES: ResponseModifierScale[] = [
  {
    id: "molecular",
    label_en: "Molecular",
    label_fi: "Molekulaarinen",
    label_ja: "分子",
    label_fr: "Moléculaire",
    label_ko: "분자",
    background_en: "FAD chromophore in CRY",
    background_fi: "FAD-kromofori CRY:ssä",
    background_ja: "CRY内のFAD発色団",
    background_fr: "Chromophore FAD dans CRY",
    background_ko: "CRY 내 FAD 발색단",
    perturbation_en: "Magnetic field",
    perturbation_fi: "Magneettikenttä",
    perturbation_ja: "磁場",
    perturbation_fr: "Champ magnétique",
    perturbation_ko: "자기장",
    candidate_expression: "m_mol([FAD])",
    at_zero_en: "No FAD → no radical pairs → no sensitivity",
    at_zero_fi: "Ei FAD:tä → ei radikaaliparia → ei herkkyyttä",
    at_zero_ja: "FADなし → ラジカル対なし → 感受性なし",
    at_zero_fr: "Pas de FAD → pas de paires radicalaires → pas de sensibilité",
    at_zero_ko: "FAD 없음 → 라디칼 쌍 없음 → 감수성 없음",
    at_max_en: "FAD-replete → full magnetic sensitivity",
    at_max_fi: "FAD kyllästetty → täysi magneettinen herkkyys",
    at_max_ja: "FAD充足 → 完全な磁気感受性",
    at_max_fr: "FAD saturé → sensibilité magnétique maximale",
    at_max_ko: "FAD 충족 → 완전한 자기 감수성",
    verification: "Hirano 2017, Yap 2025",
    referenceIds: ["hirano2017", "yap2025"],
    level: "E",
  },
  {
    id: "optical",
    label_en: "Optical",
    label_fi: "Optinen",
    label_ja: "光学",
    label_fr: "Optique",
    label_ko: "광학",
    background_en: "Blue light at CRY1 (iris transmission)",
    background_fi: "Sininen valo CRY1:ssä (iiriksen transmissio)",
    background_ja: "CRY1における青色光（虹彩透過）",
    background_fr: "Lumière bleue sur CRY1 (transmission irienne)",
    background_ko: "CRY1에서의 청색광 (홍채 투과)",
    perturbation_en: "RF field",
    perturbation_fi: "RF-kenttä",
    perturbation_ja: "RF電磁場",
    perturbation_fr: "Champ RF",
    perturbation_ko: "RF 전자기장",
    candidate_expression: "m_opt(I_blue)",
    at_zero_en: "Dark / brown iris → CRY1 inactive → no coupling",
    at_zero_fi: "Tumma / ruskea iiris → CRY1 inaktiivinen → ei kytkentää",
    at_zero_ja: "暗色/茶色の虹彩 → CRY1不活性 → 結合なし",
    at_zero_fr: "Iris foncé / brun → CRY1 inactif → pas de couplage",
    at_zero_ko: "어두운/갈색 홍채 → CRY1 비활성 → 결합 없음",
    at_max_en: "Blue iris + blue light → CRY1 maximally active",
    at_max_fi: "Sininen iiris + sininen valo → CRY1 maksimaalisesti aktiivinen",
    at_max_ja: "青い虹彩 + 青色光 → CRY1が最大限に活性化",
    at_max_fr: "Iris bleu + lumière bleue → CRY1 maximalement actif",
    at_max_ko: "파란 홍채 + 청색광 → CRY1 최대 활성화",
    verification: "Higuchi 2007, Bartölke 2025",
    referenceIds: ["higuchi2007", "bartolke2025"],
    level: "M|C",
  },
  {
    id: "cellular",
    label_en: "Cellular membrane",
    label_fi: "Solukalvo",
    label_ja: "細胞膜",
    label_fr: "Membrane cellulaire",
    label_ko: "세포막",
    background_en: "Membrane potential V_mem ≈ −70 mV",
    background_fi: "Kalvopotentiaali V_mem ≈ −70 mV",
    background_ja: "膜電位 V_mem ≈ −70 mV",
    background_fr: "Potentiel membranaire V_mem ≈ −70 mV",
    background_ko: "막전위 V_mem ≈ −70 mV",
    perturbation_en: "External EMF",
    perturbation_fi: "Ulkoinen EMF",
    perturbation_ja: "外部EMF",
    perturbation_fr: "EMF externe",
    perturbation_ko: "외부 EMF",
    candidate_expression: "m_mem(V_mem)",
    at_zero_en: "Dead cell (V_mem = 0) → no VGCC response",
    at_zero_fi: "Kuollut solu (V_mem = 0) → ei VGCC-vastetta",
    at_zero_ja: "死細胞 (V_mem = 0) → VGCC応答なし",
    at_zero_fr: "Cellule morte (V_mem = 0) → pas de réponse VGCC",
    at_zero_ko: "사멸 세포 (V_mem = 0) → VGCC 반응 없음",
    at_max_en: "Living cell → candidate VGCC pathway available; response gain uncalibrated",
    at_max_fi: "Elävä solu → ehdokas-VGCC-reitti käytettävissä; vastevahvistus kalibroimatta",
    at_max_ja: "生細胞 → 候補VGCC経路は利用可能；応答利得は未校正",
    at_max_fr: "Cellule vivante → voie VGCC candidate disponible ; gain non calibré",
    at_max_ko: "생존 세포 → 후보 VGCC 경로 가능; 반응 이득 미보정",
    verification: "Pall 2013 (23 VGCC blocker studies)",
    referenceIds: ["pall2013_v2"],
    level: "E",
  },
  {
    id: "environmental",
    label_en: "Environmental",
    label_fi: "Ympäristö",
    label_ja: "環境",
    label_fr: "Environnemental",
    label_ko: "환경",
    background_en: "Ambient EMF (electrification, base stations)",
    background_fi: "Ympäristön EMF (sähköistys, tukiasemat)",
    background_ja: "環境EMF（電化、基地局）",
    background_fr: "EMF ambiant (électrification, stations de base)",
    background_ko: "환경 EMF (전화, 기지국)",
    perturbation_en: "Personal devices (phone, earbuds)",
    perturbation_fi: "Henkilökohtaiset laitteet (puhelin, nappikuulokkeet)",
    perturbation_ja: "個人用デバイス（携帯電話、イヤホン）",
    perturbation_fr: "Appareils personnels (téléphone, écouteurs)",
    perturbation_ko: "개인 기기 (휴대폰, 이어버드)",
    candidate_expression: "m_env(ambient proxy)",
    at_zero_en: "Unelectrified area → personal devices don't couple",
    at_zero_fi: "Sähköistämätön alue → henkilökohtaiset laitteet eivät kytkeydy",
    at_zero_ja: "非電化地域 → 個人用デバイスは結合しない",
    at_zero_fr: "Zone non électrifiée → les appareils personnels ne se couplent pas",
    at_zero_ko: "비전화 지역 → 개인 기기가 결합하지 않음",
    at_max_en: "Dense urban → personal devices fully coupled",
    at_max_fi: "Tiheä kaupunki → henkilökohtaiset laitteet täysin kytkeytyneitä",
    at_max_ja: "高密度都市 → 個人用デバイスが完全に結合",
    at_max_fr: "Urbain dense → appareils personnels entièrement couplés",
    at_max_ko: "고밀도 도시 → 개인 기기가 완전히 결합",
    verification: "BERM 54-country dataset, electrification boundary",
    level: "M|C",
  },
  {
    id: "population",
    label_en: "Population (COVID test)",
    label_fi: "Populaatio (COVID-testi)",
    label_ja: "集団（COVID検証）",
    label_fr: "Population (test COVID)",
    label_ko: "집단 (COVID 검증)",
    background_en: "Workplace ambient EMF",
    background_fi: "Työpaikan ympäristön EMF",
    background_ja: "職場の環境EMF",
    background_fr: "EMF ambiant au travail",
    background_ko: "직장 환경 EMF",
    perturbation_en: "Screen time",
    perturbation_fi: "Ruutuaika",
    perturbation_ja: "スクリーン時間",
    perturbation_fr: "Temps d'écran",
    perturbation_ko: "화면 시간",
    candidate_expression: "m_context(office, home)",
    at_zero_en: "WFH (low ambient) → screen time less coupled → baby bump",
    at_zero_fi: "Etätyö (matala ympäristö) → ruutuaika vähemmän kytkeytynyt → vauvapiikki",
    at_zero_ja: "在宅勤務（低環境） → スクリーン時間の結合が弱い → ベビーブーム",
    at_zero_fr: "Télétravail (faible ambiant) → temps d'écran moins couplé → baby bump",
    at_zero_ko: "재택근무 (낮은 환경) → 화면 시간 결합 약함 → 베이비붐",
    at_max_en: "Office (high ambient) → screen time fully coupled → TFR decline",
    at_max_fi: "Toimisto (korkea ympäristö) → ruutuaika täysin kytkeytynyt → TFR-lasku",
    at_max_ja: "オフィス（高環境） → スクリーン時間が完全に結合 → TFR低下",
    at_max_fr: "Bureau (ambiant élevé) → temps d'écran entièrement couplé → déclin du TFR",
    at_max_ko: "사무실 (높은 환경) → 화면 시간 완전 결합 → TFR 감소",
    verification: "PNAS 2023: +5.1% TFR for WFH women",
    level: "C",
  },
];

export const NORTHERN_TRAITS: NorthernTrait[] = [
  {
    id: "blue_eyes",
    trait_en: "Blue eyes (OCA2)",
    trait_fi: "Siniset silmät (OCA2)",
    trait_ja: "青い目 (OCA2)",
    trait_fr: "Yeux bleus (OCA2)",
    trait_ko: "파란 눈 (OCA2)",
    gene: "OCA2/HERC2",
    mechanism_en: "Reduced melanin → 100× iris transmission → maximizes CRY1 blue-light activation in retinal blue cones",
    mechanism_fi: "Vähentynyt melaniini → 100× iiriksen transmissio → maksimoi CRY1:n sinisenvalon aktivaation verkkokalvon sinisissä tapeissa",
    mechanism_ja: "メラニン減少 → 100倍の虹彩透過 → 網膜の青錐体におけるCRY1青色光活性化を最大化",
    mechanism_fr: "Mélanine réduite → 100× transmission irienne → maximise l'activation de CRY1 par la lumière bleue dans les cônes bleus rétiniens",
    mechanism_ko: "멜라닌 감소 → 100배 홍채 투과 → 망막 청추체에서 CRY1 청색광 활성화 극대화",
    cry_link_en: "Candidate optical moderator: iris transmission → CRY1 photon flux; EMF interaction uncalibrated",
    cry_link_fi: "Optinen moderaattoriehdokas: iiriksen transmissio → CRY1-fotonivuo; EMF-vuorovaikutus kalibroimatta",
    cry_link_ja: "光学候補修飾因子：虹彩透過→CRY1光子束；EMF相互作用は未校正",
    cry_link_fr: "Modérateur optique candidat : transmission irienne → flux CRY1 ; interaction EMF non calibrée",
    cry_link_ko: "광학 후보 조절인자: 홍채 투과 → CRY1 광자 플럭스; EMF 상호작용 미보정",
    level: "M|C",
  },
  {
    id: "lactose_tolerance",
    trait_en: "Lactose tolerance (LCT)",
    trait_fi: "Laktoosinsietokyky (LCT)",
    trait_ja: "乳糖耐性 (LCT)",
    trait_fr: "Tolérance au lactose (LCT)",
    trait_ko: "유당 내성 (LCT)",
    gene: "LCT −13910C>T",
    mechanism_en: "Adult milk digestion → year-round dairy → stable riboflavin (B2) supply → FAD for CRY chromophore",
    mechanism_fi: "Aikuisiän maidonsulatuskyky → ympärivuotinen maitotuote → vakaa riboflaviini (B2) -saanti → FAD CRY:n kromoforiksi",
    mechanism_ja: "成人の牛乳消化 → 通年の乳製品 → 安定したリボフラビン（B2）供給 → CRY発色団用FAD",
    mechanism_fr: "Digestion du lait à l'âge adulte → produits laitiers toute l'année → apport stable en riboflavine (B2) → FAD pour le chromophore CRY",
    mechanism_ko: "성인 우유 소화 → 연중 유제품 → 안정적 리보플라빈(B2) 공급 → CRY 발색단용 FAD",
    cry_link_en: "Candidate molecular moderator: riboflavin → FAD → CRY stability; EMF interaction uncalibrated",
    cry_link_fi: "Molekulaarinen moderaattoriehdokas: riboflaviini → FAD → CRY:n stabiilius; EMF-vuorovaikutus kalibroimatta",
    cry_link_ja: "分子候補修飾因子：リボフラビン→FAD→CRY安定性；EMF相互作用は未校正",
    cry_link_fr: "Modérateur moléculaire candidat : riboflavine → FAD → stabilité CRY ; interaction EMF non calibrée",
    cry_link_ko: "분자 후보 조절인자: 리보플라빈 → FAD → CRY 안정성; EMF 상호작용 미보정",
    level: "E",
  },
  {
    id: "cattle_husbandry",
    trait_en: "Cattle husbandry (cultural-genetic coevolution)",
    trait_fi: "Karjankasvatus (kulttuuris-geneettinen koevoluutio)",
    trait_ja: "牧畜（文化-遺伝的共進化）",
    trait_fr: "Élevage bovin (coévolution culturelle-génétique)",
    trait_ko: "목축 (문화-유전적 공진화)",
    gene: "Cultural + LCT selection",
    mechanism_en: "Pastoralism selected for LCT; dairy provided B2 through winter when solar synthesis and foraging failed",
    mechanism_fi: "Paimentolaisuus valitsi LCT:tä; maitotuotteet tarjosivat B2:ta talvella kun auringon synteesi ja keräily eivät riittäneet",
    mechanism_ja: "牧畜がLCTを選択; 太陽合成と採集が不可能な冬季に乳製品がB2を供給",
    mechanism_fr: "Le pastoralisme a sélectionné le LCT ; les produits laitiers ont fourni du B2 en hiver quand la synthèse solaire et la cueillette échouaient",
    mechanism_ko: "목축이 LCT를 선택; 태양 합성과 채집이 불가능한 겨울에 유제품이 B2를 공급",
    cry_link_en: "Environmental: winter B2 buffer sustaining CRY function in dark season",
    cry_link_fi: "Ympäristöllinen: talven B2-puskuri ylläpitäen CRY:n toimintaa pimeänä vuodenaikana",
    cry_link_ja: "環境的: 暗い季節にCRY機能を維持する冬季B2緩衝",
    cry_link_fr: "Environnemental : tampon hivernal de B2 maintenant la fonction CRY en saison sombre",
    cry_link_ko: "환경적: 어두운 계절에 CRY 기능을 유지하는 겨울철 B2 완충",
    level: "M|C",
  },
];

export const HISTORICAL_PHASES: HistoricalPhase[] = [
  {
    id: "phase1",
    period: "10,000–6,000 BP",
    title_en: "Biological Optimization",
    title_fi: "Biologinen optimointi",
    title_ja: "生物学的最適化",
    title_fr: "Optimisation biologique",
    title_ko: "생물학적 최적화",
    description_en: "Historical premise: OCA2/HERC2, lactase persistence and pastoralism changed in overlapping northern populations. BERM treats their CRY relevance as a candidate joint-moderator hypothesis; no EMF response or TFR coefficient is inferred for this period.",
    description_fi: "Historiallinen premissi: OCA2/HERC2, laktaasin pysyvyys ja paimentolaisuus muuttuivat osin samoissa pohjoisissa populaatioissa. BERM käsittelee niiden CRY-relevanssia yhteisen moderaattorihypoteesin ehdokkaana; kaudelle ei päätellä EMF-vastetta tai TFR-kerrointa.",
    description_ja: "歴史的前提：OCA2/HERC2、ラクターゼ持続、牧畜は重なる北方集団で変化した。BERMはCRY関連性を共同修飾仮説候補として扱い、この時期のEMF応答やTFR係数を推定しない。",
    description_fr: "Prémisse historique : OCA2/HERC2, persistance de la lactase et pastoralisme ont changé dans des populations nordiques en partie communes. BERM les traite comme hypothèse candidate de modération conjointe, sans inférer de réponse EMF ni coefficient TFR.",
    description_ko: "역사적 전제: OCA2/HERC2, 락타아제 지속성, 목축은 일부 겹치는 북부 집단에서 변화했다. BERM은 CRY 관련성을 공동 조절 가설 후보로 다루며 이 시기의 EMF 반응이나 TFR 계수를 추론하지 않는다.",
  },
  {
    id: "phase2",
    period: "1880–1960",
    title_en: "Electrification: timing scenario",
    title_fi: "Sähköistys: ajoitusskenaario",
    title_ja: "電化：タイミングシナリオ",
    title_fr: "Électrification : scénario temporel",
    title_ko: "전기화: 시점 시나리오",
    description_en: "Northern Europe electrified early and fertility later declined. BERM registers an exposure × moderator interaction as one candidate explanation, to be compared with urbanization, mortality, education, contraception and income using measured inputs.",
    description_fi: "Pohjois-Eurooppa sähköistyi varhain ja hedelmällisyys laski myöhemmin. BERM rekisteröi altistus × moderaattori -vuorovaikutuksen yhdeksi ehdokasselitykseksi, jota verrataan mitatuilla syötteillä kaupungistumiseen, kuolleisuuteen, koulutukseen, ehkäisyyn ja tuloihin.",
    description_ja: "北欧は早期に電化し、その後出生率が低下した。BERMは曝露×修飾因子を候補説明の一つとして登録し、都市化、死亡率、教育、避妊、所得と測定入力で比較する。",
    description_fr: "L'Europe du Nord s'est électrifiée tôt et la fertilité a ensuite diminué. BERM enregistre l'interaction exposition × modérateur comme explication candidate à comparer, avec mesures, à l'urbanisation, mortalité, éducation, contraception et revenu.",
    description_ko: "북유럽은 일찍 전기화되었고 이후 출산율이 감소했다. BERM은 노출 × 조절인자 상호작용을 후보 설명 중 하나로 등록하며 측정 입력으로 도시화, 사망률, 교육, 피임, 소득과 비교한다.",
  },
  {
    id: "phase3",
    period: "1990–2020",
    title_en: "Mobile Revolution: Differentiated Decline",
    title_fi: "Mobiilirevoluutio: eriytynyt lasku",
    title_ja: "モバイル革命：差別化された低下",
    title_fr: "Révolution mobile : déclin différencié",
    title_ko: "모바일 혁명: 차별화된 감소",
    description_en: "Mobile and infrastructure adoption expanded while fertility trajectories diverged. BERM proposes separately measured environmental, behavioural and biological moderators; the regional pathway labels below are scenarios, not calibrated causal assignments.",
    description_fi: "Mobiili- ja infrastruktuurikäyttö laajeni samalla kun hedelmällisyyskehitykset eriytyivät. BERM ehdottaa erikseen mitattavia ympäristö-, käyttäytymis- ja biologisia moderaattoreita; alueelliset polkumerkinnät ovat skenaarioita, eivät kalibroituja kausaaliluokituksia.",
    description_ja: "モバイルとインフラ導入が拡大する一方、出生軌跡は分岐した。BERMは環境・行動・生物修飾因子を別々に測定することを提案し、地域経路ラベルは未校正シナリオである。",
    description_fr: "L'adoption mobile et des infrastructures a augmenté tandis que les trajectoires de fertilité divergeaient. BERM propose des modérateurs environnementaux, comportementaux et biologiques mesurés séparément ; les voies régionales sont des scénarios non calibrés.",
    description_ko: "모바일·인프라 도입이 확대되는 동안 출산 궤적은 갈라졌다. BERM은 환경·행동·생물 조절인자를 별도로 측정하도록 제안하며 지역 경로 표지는 미보정 시나리오다.",
  },
  {
    id: "phase4",
    period: "2020+",
    title_en: "The Convergence",
    title_fi: "Yhdentyminen",
    title_ja: "収斂",
    title_fr: "La Convergence",
    title_ko: "수렴",
    description_en: "Prospective test: as electrification changes, compare within-region fertility and biomarkers using matched exposure, development controls and separately measured moderators. BERM does not assign a slower African decline from eye colour or lactase persistence alone.",
    description_fi: "Prospektiivinen testi: sähköistyksen muuttuessa verrataan alueen sisäistä hedelmällisyyttä ja biomarkkereita kohdistetulla altistuksella, kehityskontrolleilla ja erikseen mitatuilla moderaattoreilla. BERM ei päättele hitaampaa Afrikan laskua pelkän silmien värin tai laktaasin pysyvyyden perusteella.",
    description_ja: "前向きテスト：電化変化時に、対応する曝露・発展統制・別測定修飾因子で地域内出生とバイオマーカーを比較する。BERMは眼色やラクターゼ持続だけからアフリカの低下速度を割り当てない。",
    description_fr: "Test prospectif : lors des changements d'électrification, comparer fertilité et biomarqueurs intra-région avec exposition appariée, contrôles de développement et modérateurs séparés. BERM n'attribue pas un déclin africain plus lent à la seule couleur des yeux ou persistance de la lactase.",
    description_ko: "전향적 테스트: 전기화 변화 시 매칭 노출, 개발 통제, 별도 측정 조절인자로 지역 내 출산율과 바이오마커를 비교한다. BERM은 눈 색이나 락타아제 지속성만으로 아프리카 감소 속도를 지정하지 않는다.",
  },
];

export const POPULATION_PROFILES: PopulationProfile[] = [
  {
    id: "amish",
    label_en: "Old Order Amish",
    label_fi: "Vanhan järjestyksen amissit",
    label_ja: "Old Order Amish",
    label_fr: "Amish traditionnels",
    label_ko: "Old Order Amish",
    candidate_env: "~0.1 (scenario)",
    candidate_optical: "0.8–0.9 (scenario)",
    candidate_molecular: "0.9 (scenario)",
    dominant_pathway: "B (but uncoupled)",
    observed_tfr: "~6.5",
    status_en: "Candidate low-exposure comparison; not a randomized control and scenario modifiers are uncalibrated",
    status_fi: "Matalan altistuksen ehdokasvertailu; ei satunnaistettu kontrolli, moderaattorit kalibroimatta",
    status_ja: "低曝露の候補比較；無作為対照ではなく修飾因子は未校正",
    status_fr: "Comparaison candidate à faible exposition ; ni contrôle randomisé ni modérateurs calibrés",
    status_ko: "저노출 후보 비교; 무작위 대조가 아니며 조절인자 미보정",
  },
  {
    id: "mennonite",
    label_en: "Conservative Mennonites",
    label_fi: "Konservatiiviset mennoniitit",
    label_ja: "保守派メノナイト",
    label_fr: "Mennonites conservateurs",
    label_ko: "보수파 메노나이트",
    candidate_env: "~0.3–0.5 (scenario)",
    candidate_optical: "0.7–0.8 (scenario)",
    candidate_molecular: "0.8 (scenario)",
    dominant_pathway: "A+B (partial coupling)",
    observed_tfr: "~3.5–4.5",
    status_en: "Candidate intermediate-exposure comparison; cultural and demographic controls required",
    status_fi: "Kohtalaisen altistuksen ehdokasvertailu; kulttuuri- ja demografiakontrollit tarvitaan",
    status_ja: "中曝露の候補比較；文化・人口統制が必要",
    status_fr: "Comparaison candidate d'exposition intermédiaire ; contrôles culturels et démographiques requis",
    status_ko: "중간 노출 후보 비교; 문화·인구 통제 필요",
  },
  {
    id: "scandinavia",
    label_en: "Scandinavia",
    label_fi: "Skandinavia",
    label_ja: "スカンジナビア",
    label_fr: "Scandinavie",
    label_ko: "스칸디나비아",
    candidate_env: "0.8–0.9 (scenario)",
    candidate_optical: "0.7–0.9 (scenario)",
    candidate_molecular: "0.8–0.9 (scenario)",
    dominant_pathway: "A+B (fully coupled)",
    observed_tfr: "~1.5–1.7",
    status_en: "High-exposure northern scenario; exposure × modifier effect remains to be estimated",
    status_fi: "Pohjoinen korkean altistuksen skenaario; altistus × moderaattori -vaikutus on arvioimatta",
    status_ja: "北方高曝露シナリオ；曝露×修飾因子効果は未推定",
    status_fr: "Scénario nordique de forte exposition ; effet exposition × modérateur non estimé",
    status_ko: "북부 고노출 시나리오; 노출 × 조절인자 효과 미추정",
  },
  {
    id: "south_korea",
    label_en: "South Korea",
    label_fi: "Etelä-Korea",
    label_ja: "韓国",
    label_fr: "Corée du Sud",
    label_ko: "대한민국",
    candidate_env: "0.9–1.0 (scenario)",
    candidate_optical: "0.2–0.3 (scenario)",
    candidate_molecular: "0.5–0.6 (scenario)",
    dominant_pathway: "A (VGIC dominant)",
    observed_tfr: "~0.7",
    status_en: "High-density A-pathway scenario; observed TFR does not identify the proposed mechanism",
    status_fi: "Korkean tiheyden A-reittiskenaario; havaittu TFR ei tunnista ehdotettua mekanismia",
    status_ja: "高密度A経路シナリオ；観測TFRは提案機構を同定しない",
    status_fr: "Scénario de voie A à forte densité ; le TFR observé n'identifie pas le mécanisme",
    status_ko: "고밀도 A 경로 시나리오; 관측 TFR은 제안 메커니즘을 식별하지 않음",
  },
  {
    id: "china",
    label_en: "Urban China",
    label_fi: "Kaupunki-Kiina",
    label_ja: "都市部中国",
    label_fr: "Chine urbaine",
    label_ko: "도시 중국",
    candidate_env: "0.7–0.9 (scenario)",
    candidate_optical: "0.2–0.3 (scenario)",
    candidate_molecular: "0.4–0.5 (scenario)",
    dominant_pathway: "A (VGIC dominant)",
    observed_tfr: "~1.0",
    status_en: "Urban A-pathway comparison scenario; mechanism and dose remain unmeasured",
    status_fi: "Kaupunkien A-reittivertailuskenaario; mekanismia ja annosta ei ole mitattu",
    status_ja: "都市A経路比較シナリオ；機構と線量は未測定",
    status_fr: "Scénario urbain comparatif de voie A ; mécanisme et dose non mesurés",
    status_ko: "도시 A 경로 비교 시나리오; 메커니즘과 용량 미측정",
  },
  {
    id: "sub_saharan_africa",
    label_en: "Sub-Saharan Africa",
    label_fi: "Saharan eteläpuolinen Afrikka",
    label_ja: "サハラ以南アフリカ",
    label_fr: "Afrique subsaharienne",
    label_ko: "사하라 이남 아프리카",
    candidate_env: "0.2–0.4 (scenario)",
    candidate_optical: "0.05–0.1 (scenario)",
    candidate_molecular: "0.3–0.4 (scenario)",
    dominant_pathway: "A (weak coupling)",
    observed_tfr: "~4.5",
    status_en: "Prospective electrification comparison scenario; development confounding must be controlled",
    status_fi: "Prospektiivinen sähköistymisvertailuskenaario; kehityssekoittuminen on kontrolloitava",
    status_ja: "前向き電化比較シナリオ；発展交絡の統制が必要",
    status_fr: "Scénario prospectif de comparaison d'électrification ; confusion de développement à contrôler",
    status_ko: "전향적 전기화 비교 시나리오; 개발 교란 통제 필요",
  },
];

export const EVOLUTION_PREDICTIONS: EvolutionPrediction[] = [
  {
    id: "hist1",
    code: "HIST-1",
    title_en: "Biomarker ratios predict fertility differentials",
    title_fi: "Biomarkkeritasot ennustavat hedelmällisyyseroja",
    title_ja: "バイオマーカー比が出生率格差を予測",
    title_fr: "Les ratios de biomarqueurs prédisent les différentiels de fertilité",
    title_ko: "바이오마커 비율이 출산율 차이를 예측",
    test_en: "In populations with high lactose tolerance AND blue/green eye prevalence, CRY-associated biomarkers (urinary 6-sulphatoxymelatonin, FAD/FMN ratio) should correlate more strongly with fertility outcomes than in populations lacking these traits.",
    test_fi: "Populaatioissa joissa on korkea laktoosinsietokyky JA sinisten/vihreiden silmien esiintyvyys, CRY-liitteiset biomarkkerit (virtsan 6-sulfatoksimelatoniini, FAD/FMN-suhde) korreloivat voimakkaammin hedelmällisyystulosten kanssa kuin populaatioissa ilman näitä piirteitä.",
    test_ja: "乳糖耐性が高くかつ青/緑色の目の有病率が高い集団では、CRY関連バイオマーカー（尿中6-スルファトキシメラトニン、FAD/FMN比）が、これらの形質を持たない集団よりも出生率転帰とより強く相関するはずである。",
    test_fr: "Dans les populations à haute tolérance au lactose ET à prévalence élevée d'yeux bleus/verts, les biomarqueurs associés à CRY (6-sulphatoxymélatonine urinaire, ratio FAD/FMN) devraient corréler plus fortement avec les résultats de fertilité que dans les populations dépourvues de ces traits.",
    test_ko: "유당 내성이 높고 파란/녹색 눈 유병률이 높은 집단에서 CRY 관련 바이오마커(소변 6-설파톡시멜라토닌, FAD/FMN 비율)는 이러한 형질이 없는 집단보다 출산 결과와 더 강하게 상관해야 한다.",
    falsification_en: "If blue-eyed, lactose-tolerant populations show NO stronger biomarker-fertility correlation than brown-eyed, lactose-intolerant populations, the Northern Package hypothesis is falsified.",
    falsification_fi: "Jos sinisilmäisissä, laktoosinsietokyvyn omaavissa populaatioissa EI ole voimakkaampaa biomarkkeri-hedelmällisyyskorrelaatiota kuin ruskeasilmäisissä, laktoosi-intoleranteissa populaatioissa, Pohjoinen paketti -hypoteesi on falsifioitu.",
    falsification_ja: "青い目で乳糖耐性のある集団が、茶色い目で乳糖不耐性の集団と比較してバイオマーカー-出生率相関が強くない場合、Northern Package仮説は反証される。",
    falsification_fr: "Si les populations aux yeux bleus et tolérantes au lactose ne montrent PAS de corrélation biomarqueur-fertilité plus forte que les populations aux yeux bruns et intolérantes au lactose, l'hypothèse du Northern Package est falsifiée.",
    falsification_ko: "파란 눈의 유당 내성 집단이 갈색 눈의 유당 불내성 집단보다 바이오마커-출산율 상관관계가 강하지 않으면 Northern Package 가설은 반증된다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "hist2",
    code: "HIST-2",
    title_en: "Amish–Mennonite fertility gradient",
    title_fi: "Amissi–mennoniittigradientti hedelmällisyydessä",
    title_ja: "Amish-Mennonite出生率勾配",
    title_fr: "Gradient de fertilité Amish–Mennonite",
    title_ko: "Amish-Mennonite 출산율 기울기",
    test_en: "The TFR difference between Old Order Amish (~6.5) and Conservative Mennonites (~3.5–4.5) should correlate with measured EMF exposure differences, not with genetic, dietary, or cultural confounds alone.",
    test_fi: "TFR-ero vanhan järjestyksen amissien (~6,5) ja konservatiivisten mennoniittien (~3,5–4,5) välillä tulisi korreloida mitattujen EMF-altistuserojen kanssa, ei pelkästään geneettisten, ravitsemuksellisten tai kulttuuristen sekoittavien tekijöiden kanssa.",
    test_ja: "Old Order Amish（約6.5）とConservative Mennonite（約3.5〜4.5）のTFR差は、遺伝的・食事的・文化的交絡因子だけでなく、測定されたEMF曝露差と相関するはずである。",
    test_fr: "La différence de TFR entre les Amish traditionnels (~6,5) et les Mennonites conservateurs (~3,5–4,5) devrait corréler avec les différences d'exposition EMF mesurées, et non uniquement avec les facteurs confondants génétiques, alimentaires ou culturels.",
    test_ko: "Old Order Amish(약 6.5)와 Conservative Mennonite(약 3.5~4.5) 사이의 TFR 차이는 유전적, 식이적, 문화적 교란 요인만이 아닌 측정된 EMF 노출 차이와 상관해야 한다.",
    falsification_en: "If measured EMF exposure does not differ significantly between these groups, or if TFR differences are fully explained by other factors, the proposed environmental interaction is weakened.",
    falsification_fi: "Jos mitattu EMF-altistus ei eroa merkitsevästi ryhmien välillä tai muut tekijät selittävät TFR-erot, ehdotettu ympäristövuorovaikutus heikkenee.",
    falsification_ja: "群間の測定EMF曝露に差がない、または他要因がTFR差を説明するなら、提案環境相互作用は弱まる。",
    falsification_fr: "Si l'exposition EMF mesurée ne diffère pas ou si d'autres facteurs expliquent le TFR, l'interaction environnementale proposée est affaiblie.",
    falsification_ko: "집단 간 측정 EMF 노출 차이가 없거나 다른 요인이 TFR 차이를 설명하면 제안된 환경 상호작용이 약화된다.",
    level: "C",
    timeframe: "2–3 years",
  },
  {
    id: "hist3",
    code: "HIST-3",
    title_en: "COVID work-from-home baby bump mechanism",
    title_fi: "COVID-etätyön vauvapiikki-mekanismi",
    title_ja: "COVID在宅勤務ベビーブームメカニズム",
    title_fr: "Mécanisme du baby bump du télétravail COVID",
    title_ko: "COVID 재택근무 베이비붐 메커니즘",
    test_en: "Reanalyse the reported WFH association with prospectively measured home/office fields and candidate optical moderators, controlling age, partnership, income, policy and pandemic timing. Test the exposure × moderator term without assigning a direction in advance.",
    test_fi: "Analysoi raportoitu etätyöyhteys uudelleen prospektiivisesti mitatuilla koti-/toimistokentillä ja optisilla moderaattoriehdokkailla kontrolloiden ikä, parisuhde, tulot, politiikka ja pandemian ajoitus. Testaa altistus × moderaattori ilman ennalta määrättyä suuntaa.",
    test_ja: "前向きに測定した家庭・職場場と光学候補修飾因子で在宅勤務関連を再解析し、年齢・関係・所得・政策・パンデミック時期を統制する。方向を事前指定せず相互作用を検定する。",
    test_fr: "Réanalyser l'association télétravail avec champs domicile/bureau mesurés et modérateurs optiques candidats, en contrôlant âge, couple, revenu, politique et période pandémique. Tester l'interaction sans direction imposée.",
    test_ko: "전향적으로 측정한 가정·사무실 장과 광학 후보 조절인자로 재택근무 연관을 재분석하고 나이·관계·소득·정책·팬데믹 시점을 통제한다. 방향을 사전 지정하지 않고 상호작용을 검정한다.",
    falsification_en: "No reproducible exposure × moderator interaction weakens this candidate route.",
    falsification_fi: "Toistettavan altistus × moderaattori -vuorovaikutuksen puuttuminen heikentää ehdokasreittiä.",
    falsification_ja: "再現可能な曝露×修飾因子相互作用がなければ候補経路は弱まる。",
    falsification_fr: "L'absence d'interaction exposition × modérateur reproductible affaiblit cette voie candidate.",
    falsification_ko: "재현 가능한 노출 × 조절인자 상호작용이 없으면 후보 경로가 약화된다.",
    level: "C",
    timeframe: "1–3 years",
  },
  {
    id: "hist4",
    code: "HIST-4",
    title_en: "African TFR decline lag prediction",
    title_fi: "Afrikan TFR-laskun viive-ennuste",
    title_ja: "アフリカTFR低下ラグ予測",
    title_fr: "Prédiction du décalage de déclin du TFR africain",
    title_ko: "아프리카 TFR 감소 지연 예측",
    test_en: "Estimate within-region changes in measured exposure, biomarkers and fertility as electrification changes, with development covariates and prespecified candidate moderators. Compare the interaction coefficients across regions; no 0.3–0.5 factor is treated as calibrated.",
    test_fi: "Arvioi alueiden sisällä mitatun altistuksen, biomarkkereiden ja hedelmällisyyden muutoksia sähköistyksen muuttuessa kehityskovariaateilla ja ennaltamääritetyillä moderaattoriehdokkailla. Vertaa vuorovaikutuskertoimia; 0,3–0,5-kerrointa ei käsitellä kalibroituna.",
    test_ja: "電化変化時の測定曝露・バイオマーカー・出生を地域内で推定し、発展共変量と事前指定修飾因子を用いる。地域間の相互作用係数を比較し、0.3–0.5を校正値としない。",
    test_fr: "Estimer intra-région les changements d'exposition mesurée, biomarqueurs et fertilité avec covariables de développement et modérateurs préspecifiés. Comparer les interactions ; 0,3–0,5 n'est pas calibré.",
    test_ko: "전기화 변화 시 측정 노출·바이오마커·출산율 변화를 지역 내에서 개발 공변량과 사전 지정 조절인자로 추정한다. 지역 간 상호작용 계수를 비교하며 0.3~0.5는 보정값이 아니다.",
    falsification_en: "No reproducible interaction after development controls weakens the proposed moderator route.",
    falsification_fi: "Toistettavan vuorovaikutuksen puuttuminen kehityskontrollien jälkeen heikentää moderaattorireittiä.",
    falsification_ja: "発展統制後に再現可能な相互作用がなければ修飾経路は弱まる。",
    falsification_fr: "L'absence d'interaction reproductible après contrôles de développement affaiblit la voie.",
    falsification_ko: "개발 통제 후 재현 가능한 상호작용이 없으면 조절인자 경로가 약화된다.",
    level: "L*",
    timeframe: "10–20 years",
  },
  {
    id: "hist5",
    code: "HIST-5",
    title_en: "Lactose intolerance as EMF resistance factor",
    title_fi: "Laktoosi-intoleranssi EMF-resistenssitekijänä",
    title_ja: "乳糖不耐性がEMF抵抗因子として機能",
    title_fr: "L'intolérance au lactose comme facteur de résistance aux EMF",
    title_ko: "유당 불내성이 EMF 저항 인자로 작용",
    test_en: "Within the same EMF environment, lactose-intolerant individuals should show lower CRY-mediated biomarker responses (melatonin suppression, circadian disruption) than lactose-tolerant individuals with similar diets supplemented with B2.",
    test_fi: "Samassa EMF-ympäristössä laktoosi-intoleranttien yksilöiden tulisi osoittaa matalampia CRY-välitteisiä biomarkkerivasteita (melatoniinin suppressio, sirkadiaaninen häiriö) kuin laktoosinsietokykyisten yksilöiden vastaavilla B2-täydennetyillä ruokavalioilla.",
    test_ja: "同一EMF環境内で、乳糖不耐性の個人はB2を補充した類似の食事を持つ乳糖耐性の個人よりも低いCRY媒介バイオマーカー応答（メラトニン抑制、概日リズム障害）を示すはずである。",
    test_fr: "Dans le même environnement EMF, les individus intolérants au lactose devraient montrer des réponses biomarqueurs médiées par CRY plus faibles (suppression de la mélatonine, perturbation circadienne) que les individus tolérants au lactose avec des régimes similaires supplémentés en B2.",
    test_ko: "동일한 EMF 환경에서 유당 불내성 개인은 B2가 보충된 유사한 식단을 가진 유당 내성 개인보다 낮은 CRY 매개 바이오마커 반응(멜라토닌 억제, 일주기 리듬 장애)을 보여야 한다.",
    falsification_en: "If lactase-persistence status adds no information once measured B2 intake and FAD status are controlled, the proposed nutritional moderator is independent of lactase persistence.",
    falsification_fi: "Jos laktaasin pysyvyys ei lisää informaatiota mitatun B2-saannin ja FAD-tilan kontrolloinnin jälkeen, ravitsemusmoderaattori on siitä riippumaton.",
    falsification_ja: "測定B2摂取とFAD状態の統制後にラクターゼ持続が情報を加えないなら、栄養修飾因子はそれから独立である。",
    falsification_fr: "Si la persistance de la lactase n'ajoute rien après contrôle de B2 et FAD mesurés, le modérateur nutritionnel proposé en est indépendant.",
    falsification_ko: "측정 B2 섭취와 FAD 상태 통제 후 락타아제 지속성이 정보를 더하지 않으면 영양 조절인자는 독립적이다.",
    level: "L*",
    timeframe: "2–4 years",
  },
  {
    id: "ep2",
    code: "E-P2",
    title_en: "CatSper IF-resonance frequency window",
    title_fi: "CatSper IF-resonanssitaajuusikkuna",
    title_ja: "CatSper IF共鳴周波数帯",
    title_fr: "Fenêtre de fréquence de résonance IF du CatSper",
    title_ko: "CatSper IF 공명 주파수 대역",
    test_en: "CatSper channels should show maximum disruption at specific IF frequencies (1–100 kHz range) where the channel's voltage-sensing domain resonates. In-vitro patch-clamp studies at graded IF frequencies should reveal a non-monotonic dose-response with a peak disruption frequency predictable from the channel's gating charge displacement.",
    test_fi: "CatSper-kanavien tulisi osoittaa maksimaalinen häiriö tietyillä IF-taajuuksilla (1–100 kHz -alue), joilla kanavan jänniteanturidomeeni resonoi. In vitro -patch-clamp-tutkimusten porrastetulla IF-taajuudella tulisi paljastaa ei-monotoninen annosvasteen huippu, joka on ennustettavissa kanavan varausdynamiikasta.",
    test_ja: "CatSperチャネルは、チャネルの電圧感知ドメインが共鳴する特定のIF周波数（1〜100 kHz範囲）で最大の破壊を示すはずである。段階的IF周波数でのin vitroパッチクランプ研究で、チャネルのゲーティング電荷変位から予測可能なピーク破壊周波数を持つ非単調な用量反応が明らかになるはずである。",
    test_fr: "Les canaux CatSper devraient montrer une perturbation maximale à des fréquences IF spécifiques (gamme 1–100 kHz) où le domaine de détection de tension du canal entre en résonance. Des études de patch-clamp in vitro à des fréquences IF graduées devraient révéler une réponse dose non monotone avec une fréquence de perturbation maximale prédictible à partir du déplacement de charge du canal.",
    test_ko: "CatSper 채널은 채널의 전압 감지 도메인이 공명하는 특정 IF 주파수(1-100 kHz 범위)에서 최대 교란을 보여야 한다. 단계적 IF 주파수에서의 in vitro 패치 클램프 연구는 채널의 게이팅 전하 변위로부터 예측 가능한 피크 교란 주파수를 가진 비단조 용량 반응을 밝혀야 한다.",
    falsification_en: "If CatSper disruption scales monotonically with IF frequency (no resonance peak), the channel lacks a frequency-selective vulnerability and the IF-specific prediction fails.",
    falsification_fi: "Jos CatSper-häiriö skaalautuu monotonisesti IF-taajuuden kanssa (ei resonanssihuippua), kanavalla ei ole taajuustarkkaa haavoittuvuutta ja IF-tarkka ennuste epäonnistuu.",
    falsification_ja: "CatSperの破壊がIF周波数に対して単調にスケールする場合（共鳴ピークなし）、チャネルには周波数選択的脆弱性がなく、IF固有の予測は失敗する。",
    falsification_fr: "Si la perturbation de CatSper évolue de manière monotone avec la fréquence IF (pas de pic de résonance), le canal manque de vulnérabilité sélective en fréquence et la prédiction spécifique IF échoue.",
    falsification_ko: "CatSper 교란이 IF 주파수에 대해 단조롭게 스케일링되면(공명 피크 없음) 채널에는 주파수 선택적 취약성이 없으며 IF 특정 예측은 실패한다.",
    level: "L*",
    timeframe: "2–5 years",
  },
  {
    id: "ep5",
    code: "E-P5",
    title_en: "Phone-in-pocket sperm navigation deficit",
    title_fi: "Puhelin taskussa -siittiönavigoinnin vajaus",
    title_ja: "ポケット内携帯電話による精子ナビゲーション障害",
    title_fr: "Déficit de navigation des spermatozoïdes lié au téléphone en poche",
    title_ko: "주머니 속 휴대폰에 의한 정자 항행 결함",
    test_en: "Men who carry a phone in their front trouser pocket for >4 hours/day should show statistically significant deficits in CatSper-dependent sperm functions (rheotaxis, chemotaxis, hyperactivation) compared to matched controls, even when total sperm count and motility grade remain within WHO normal ranges. The deficit should be detectable by progesterone-induced Ca²⁺ response assay.",
    test_fi: "Miehillä, jotka kantavat puhelinta etutaskussaan >4 tuntia/päivä, tulisi olla tilastollisesti merkitseviä vajeita CatSper-riippuvaisissa siittiötoiminnoissa (reotaksis, kemotaksis, hyperaktivaatio) verrattuna kontrolliryhmään, vaikka kokonaissiittiömäärä ja motiliteettiluokka pysyisivät WHO:n normaaliarvioissa. Vaje tulisi olla havaittavissa progesterooni-indusoidulla Ca²⁺-vastekokeella.",
    test_ja: "前ズボンポケットに4時間/日以上携帯電話を持ち歩く男性は、総精子数と運動性グレードがWHO正常範囲内であっても、CatSper依存性精子機能（レオタキシス、走化性、過活性化）において統計的に有意な欠損を対照群と比較して示すはずである。この欠損はプロゲステロン誘導Ca²⁺応答アッセイで検出可能であるはず。",
    test_fr: "Les hommes portant un téléphone dans la poche avant du pantalon pendant >4 heures/jour devraient montrer des déficits statistiquement significatifs dans les fonctions spermatiques dépendantes de CatSper (rhéotaxie, chimiotaxie, hyperactivation) par rapport aux témoins appariés, même lorsque le nombre total et la motilité restent dans les normes OMS. Le déficit devrait être détectable par un test de réponse Ca²⁺ induit par la progestérone.",
    test_ko: "앞주머니에 하루 4시간 이상 휴대폰을 지참하는 남성은 총 정자 수와 운동성 등급이 WHO 정상 범위 내에 있더라도 대조군에 비해 CatSper 의존성 정자 기능(유변주성, 주화성, 과활성화)에서 통계적으로 유의한 결함을 보여야 한다. 이 결함은 프로게스테론 유도 Ca²⁺ 반응 분석으로 검출 가능해야 한다.",
    falsification_en: "If phone-carrying men show identical progesterone-induced Ca²⁺ responses and hyperactivation rates as non-carriers after controlling for confounders, pocket RF exposure does not affect CatSper function in vivo.",
    falsification_fi: "Jos puhelinta kantavien miesten progesterooni-indusoidut Ca²⁺-vasteet ja hyperaktivaatioasteet ovat identtiset ei-kantajien kanssa sekoittavien tekijöiden kontrolloinnin jälkeen, taskun RF-altistus ei vaikuta CatSper-toimintaan in vivo.",
    falsification_ja: "携帯電話所持男性が交絡因子を制御した後に非所持者と同一のプロゲステロン誘導Ca²⁺応答と過活性化率を示す場合、ポケットRF曝露はin vivoでCatSper機能に影響しない。",
    falsification_fr: "Si les hommes portant un téléphone montrent des réponses Ca²⁺ induites par la progestérone et des taux d'hyperactivation identiques aux non-porteurs après contrôle des facteurs confondants, l'exposition RF de poche n'affecte pas la fonction CatSper in vivo.",
    falsification_ko: "교란 요인을 통제한 후 휴대폰 소지 남성이 비소지자와 동일한 프로게스테론 유도 Ca²⁺ 반응과 과활성화율을 보이면 주머니 RF 노출은 in vivo에서 CatSper 기능에 영향을 미치지 않는다.",
    level: "C",
    timeframe: "1–3 years",
  },
  {
    id: "es1",
    code: "E-S1",
    title_en: "Whale stranding baseline rise tracks anthropogenic RF",
    title_fi: "Valaidenrantautumisen perustason nousu seuraa antropogeenista RF:ää",
    title_ja: "クジラ座礁のベースライン上昇は人為的RF追跡",
    title_fr: "L'augmentation du taux d'échouage des baleines suit les RF anthropiques",
    title_ko: "고래 좌초 기준선 상승이 인위적 RF를 추적",
    test_en: "Global cetacean mass stranding events per decade should show a statistically significant increase from the 1950s baseline correlating with cumulative coastal RF infrastructure (r > 0.7), independent of reporting bias (controlled by stranding network coverage expansion).",
    test_fi: "Maailmanlaajuisten valaiden joukkorantautumisten määrä vuosikymmenessä tulisi osoittaa tilastollisesti merkitsevä nousu 1950-luvun perustasolta, korreloiden kumulatiivisen rannikko-RF-infrastruktuurin kanssa (r > 0.7), raportointiharhan vaikutus kontrolloituna.",
    test_ja: "10年あたりの世界的な鯨類集団座礁事件は、累積沿岸RFインフラと相関する1950年代のベースラインからの統計的に有意な増加を示すべきである（r > 0.7）。報告バイアスは座礁ネットワークの拡大で制御。",
    test_fr: "Le nombre d'échouages massifs de cétacés par décennie devrait montrer une augmentation statistiquement significative par rapport au niveau de base des années 1950, corrélée avec l'infrastructure RF côtière cumulative (r > 0,7), indépendamment du biais de signalement.",
    test_ko: "10년당 세계 고래류 집단 좌초 사건은 누적 해안 RF 인프라와 상관관계를 보이며 1950년대 기준선에서 통계적으로 유의한 증가를 보여야 한다(r > 0.7). 보고 편향은 좌초 네트워크 확대로 통제.",
    falsification_en: "If stranding events show no increase above historical baseline after controlling for reporting expansion and climate variables, anthropogenic RF is not a driver of cetacean navigation failure.",
    falsification_fi: "Jos rantautumistapahtumat eivät osoita nousua historiallisen perustason yläpuolelle raportointilaajenemisen ja ilmastomuuttujien kontrolloinnin jälkeen, antropogeeninen RF ei aiheuta valaiden navigointivirheitä.",
    falsification_ja: "報告拡大と気候変数を制御した後、座礁事件が歴史的ベースラインを超える増加を示さない場合、人為的RFは鯨類のナビゲーション障害の原因ではない。",
    falsification_fr: "Si les échouages ne montrent aucune augmentation au-dessus du niveau historique après contrôle de l'expansion du réseau de signalement et des variables climatiques, les RF anthropiques ne sont pas responsables des défaillances de navigation des cétacés.",
    falsification_ko: "보고 확대와 기후 변수를 통제한 후 좌초 사건이 역사적 기준선 이상의 증가를 보이지 않으면 인위적 RF는 고래류 항행 장애의 원인이 아니다.",
    level: "M|C",
    timeframe: "3–5 years",
  },
  {
    id: "es2",
    code: "E-S2",
    title_en: "Granger causality: coastal RF density → cetacean stranding rate",
    title_fi: "Granger-kausaliteetti: rannikko-RF-tiheys → valaiden rantautumisaste",
    title_ja: "グランジャー因果性：沿岸RF密度→鯨類座礁率",
    title_fr: "Causalité de Granger : densité RF côtière → taux d'échouage des cétacés",
    title_ko: "그랜저 인과성: 해안 RF 밀도 → 고래류 좌초율",
    test_en: "Time-lagged Granger causality analysis should detect a statistically significant effect of regional coastal RF infrastructure density on cetacean stranding rates with a 1–3 year lag, consistent with cumulative magnetoreception disruption rather than acute exposure.",
    test_fi: "Aikaviivästetyn Granger-kausaliteettianalyysin tulisi havaita tilastollisesti merkitsevä alueellisen rannikko-RF-infrastruktuuritiheyden vaikutus valaiden rantautumisasteeseen 1–3 vuoden viiveellä, yhteensopiva kumulatiivisen magnetoreseptiohäiriön kanssa.",
    test_ja: "時間遅延グランジャー因果分析により、地域沿岸RFインフラ密度が鯨類座礁率に1〜3年の遅延で統計的に有意な影響を検出すべきである。急性曝露ではなく累積磁気受容障害と一致。",
    test_fr: "L'analyse de causalité de Granger avec décalage temporel devrait détecter un effet statistiquement significatif de la densité d'infrastructure RF côtière régionale sur les taux d'échouage des cétacés avec un décalage de 1 à 3 ans.",
    test_ko: "시간 지연 그랜저 인과 분석은 지역 해안 RF 인프라 밀도가 고래류 좌초율에 1-3년 지연으로 통계적으로 유의한 영향을 감지해야 한다. 급성 노출이 아닌 누적 자기수용 장애와 일치.",
    falsification_en: "If Granger analysis shows no directional causality from RF density to stranding rates in any ocean basin, the RF-magnetoreception link is not supported at the population level.",
    falsification_fi: "Jos Granger-analyysi ei osoita suuntakausaliteettia RF-tiheydestä rantautumisasteeseen millään valtamerialueella, RF-magnetoreseptioyhteyttä ei tueta populaatiotasolla.",
    falsification_ja: "いずれの海域でもRF密度から座礁率への方向性因果が検出されない場合、RF-磁気受容リンクは集団レベルで支持されない。",
    falsification_fr: "Si l'analyse de Granger ne montre aucune causalité directionnelle de la densité RF vers les taux d'échouage dans aucun bassin océanique, le lien RF-magnétoréception n'est pas soutenu au niveau populationnel.",
    falsification_ko: "어떤 해양 분지에서도 RF 밀도에서 좌초율로의 방향 인과가 감지되지 않으면 RF-자기수용 연결은 개체군 수준에서 지지되지 않는다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "es3",
    code: "E-S3",
    title_en: "Candidate response attenuates with measured source distance",
    title_fi: "Ehdokasvaste vaimenee mitatun lähde-etäisyyden mukana",
    title_ja: "候補応答は測定した線源距離で減衰",
    title_fr: "La réponse candidate s'atténue avec la distance mesurée",
    title_ko: "후보 반응이 측정 원거리와 함께 감쇠",
    test_en: "Test whether the registered E-S2 association attenuates with calibrated local field or dose—not distance alone—while controlling source placement, coastline use and reporting. The response curve belongs to BERM's open tissue/ecological mapping, not χ_geo.",
    test_fi: "Testaa vaimeneeko rekisteröity E-S2-yhteys kalibroidun paikallisen kentän tai annoksen, ei pelkän etäisyyden, mukana kontrolloiden lähdesijoittelu, rannikon käyttö ja raportointi. Vastekäyrä kuuluu BERM:n avoimeen kudos-/ekologiakuvaukseen, ei χ_geo:on.",
    test_ja: "線源配置・沿岸利用・報告を統制し、E-S2関連が距離だけでなく校正局所場または線量で減衰するか検定する。応答曲線はBERMの開いた組織・生態写像に属しχ_geoではない。",
    test_fr: "Tester si l'association E-S2 s'atténue avec le champ ou la dose locale calibrée, non la distance seule, en contrôlant placement, usage côtier et signalement. La courbe relève du mapping BERM ouvert, pas de χ_geo.",
    test_ko: "원 배치·해안 이용·보고를 통제하며 E-S2 연관이 거리만이 아니라 보정된 국소 장이나 용량과 함께 감쇠하는지 검정한다. 반응 곡선은 BERM의 열린 조직·생태 매핑에 속하며 χ_geo가 아니다.",
    falsification_en: "If Granger effect size is independent of distance to RF sources (no spatial gradient), the stranding correlation is coincidental rather than mechanistic.",
    falsification_fi: "Jos Granger-vaikutuskoko on riippumaton etäisyydestä RF-lähteisiin (ei spatiaalista gradienttia), rantautumiskorrelaatio on satunnaista eikä mekanistista.",
    falsification_ja: "グランジャー効果量がRF源からの距離に無関係（空間勾配なし）であれば、座礁相関は偶発的であり機構的ではない。",
    falsification_fr: "Si l'amplitude de l'effet Granger est indépendante de la distance aux sources RF (pas de gradient spatial), la corrélation d'échouage est fortuite et non mécanistique.",
    falsification_ko: "그랜저 효과 크기가 RF 원으로부터의 거리와 무관하면(공간 기울기 없음) 좌초 상관은 메커니즘적이 아니라 우연이다.",
    level: "L*",
    timeframe: "5–10 years",
  },
  {
    id: "es4",
    code: "E-S4",
    title_en: "Submarine cable ELF → aquatic CatSper reproductive decline",
    title_fi: "Merenalaiset kaapelit ELF → vesieliöiden CatSper-lisääntymishäiriö",
    title_ja: "海底ケーブルELF→水生CatSper生殖低下",
    title_fr: "ELF des câbles sous-marins → déclin reproductif aquatique via CatSper",
    title_ko: "해저 케이블 ELF → 수생 CatSper 생식 감소",
    test_en: "Marine species with CatSper-dependent fertilization (sea urchins, fish, marine mammals) near high-power submarine cable corridors should show measurable reproductive parameter declines compared to populations distant from cables. ELF field measurements at cable crossings should exceed the CatSper activation threshold identified in vitro.",
    test_fi: "CatSper-riippuvaisen hedelmöityksen omaavien merieliölajien (merisiilit, kalat, merieläimet) tulisi osoittaa mitattavia lisääntymisparametrien laskuja korkeateholisten merenalaisten kaapelikäytävien lähellä verrattuna kaapeleista etäällä oleviin populaatioihin.",
    test_ja: "高電力海底ケーブル回廊付近のCatSper依存受精を持つ海洋種（ウニ、魚類、海洋哺乳類）は、ケーブルから離れた集団と比較して測定可能な生殖パラメータ低下を示すべきである。",
    test_fr: "Les espèces marines à fécondation CatSper-dépendante (oursins, poissons, mammifères marins) près des corridors de câbles sous-marins à haute puissance devraient montrer des déclins mesurables des paramètres reproductifs par rapport aux populations éloignées des câbles.",
    test_ko: "고전력 해저 케이블 회랑 근처의 CatSper 의존 수정을 가진 해양 종(성게, 어류, 해양 포유류)은 케이블에서 먼 개체군에 비해 측정 가능한 생식 매개변수 감소를 보여야 한다.",
    falsification_en: "If marine populations near submarine cables show identical reproductive parameters to those in cable-free zones, ELF fields from cables do not disrupt aquatic CatSper function.",
    falsification_fi: "Jos merikaapelien läheiset merieliöpopulaatiot osoittavat identtiset lisääntymisparametrit kaapelittomien alueiden kanssa, kaapeleiden ELF-kentät eivät häiritse vesieliöiden CatSper-toimintaa.",
    falsification_ja: "海底ケーブル付近の海洋集団がケーブルのない地域と同一の生殖パラメータを示す場合、ケーブルからのELF場は水生CatSper機能を障害しない。",
    falsification_fr: "Si les populations marines près des câbles montrent des paramètres reproductifs identiques à celles des zones sans câble, les champs ELF des câbles ne perturbent pas la fonction CatSper aquatique.",
    falsification_ko: "해저 케이블 근처 해양 개체군이 케이블 없는 지역과 동일한 생식 매개변수를 보이면 케이블의 ELF 장은 수생 CatSper 기능을 방해하지 않는다.",
    level: "L*",
    timeframe: "5–10 years",
  },
  {
    id: "es5",
    code: "E-S5",
    title_en: "Farmed salmon CatSper weaker than wild salmon",
    title_fi: "Viljellyn lohen CatSper heikompi kuin villin lohen",
    title_ja: "養殖サーモンのCatSperは天然サーモンより弱い",
    title_fr: "CatSper du saumon d'élevage plus faible que celui du saumon sauvage",
    title_ko: "양식 연어 CatSper가 야생 연어보다 약함",
    test_en: "Atlantic salmon from high-EMF aquaculture environments (electrified feeding systems, underwater sensors, RF-emitting monitoring equipment) should show reduced CatSper-dependent sperm function compared to wild-caught or low-EMF farmed salmon. Specifically: progesterone-induced Ca²⁺ response amplitude, rheotaxis performance, and fertilization rate should be measurably lower.",
    test_fi: "Korkean EMF:n vesiviljelyympäristöistä (sähköistetyt ruokintajärjestelmät, vedenalaiset sensorit) peräisin olevan atlantinlohen tulisi osoittaa heikentynyttä CatSper-riippuvaista siittiötoimintaa verrattuna villiin tai matalan EMF:n viljeltyyn loheen.",
    test_ja: "高EMF養殖環境（電気化給餌システム、水中センサー）の大西洋サーモンは、天然捕獲または低EMF養殖サーモンと比較してCatSper依存性精子機能の低下を示すべきである。",
    test_fr: "Le saumon atlantique d'environnements d'aquaculture à forte EMF devrait montrer une fonction spermatique CatSper-dépendante réduite par rapport au saumon sauvage ou d'élevage à faible EMF.",
    test_ko: "고EMF 양식 환경(전기화 급이 시스템, 수중 센서)의 대서양 연어는 야생 또는 저EMF 양식 연어에 비해 CatSper 의존성 정자 기능 저하를 보여야 한다.",
    falsification_en: "If farmed and wild salmon show equivalent CatSper function and fertilization rates regardless of aquaculture EMF levels, chronic environmental EMF does not compromise salmon CatSper.",
    falsification_fi: "Jos viljelty ja villi lohi osoittavat vastaavan CatSper-toiminnan ja hedelmöitysasteet vesiviljelyympäristön EMF-tasoista riippumatta, krooninen ympäristön EMF ei heikennä lohen CatSper-toimintaa.",
    falsification_ja: "養殖と天然サーモンが養殖EMFレベルに関係なく同等のCatSper機能と受精率を示す場合、慢性環境EMFはサーモンのCatSperを損なわない。",
    falsification_fr: "Si le saumon d'élevage et sauvage montrent une fonction CatSper et des taux de fécondation équivalents quels que soient les niveaux EMF d'aquaculture, l'EMF environnementale chronique ne compromet pas le CatSper du saumon.",
    falsification_ko: "양식 및 야생 연어가 양식 EMF 수준에 관계없이 동등한 CatSper 기능과 수정율을 보이면 만성 환경 EMF는 연어 CatSper를 손상시키지 않는다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "solar-1-amish-periodicity",
    code: "SOLAR-1",
    title_en: "Amish birth rate shows ~11-year periodicity correlated with sunspot number",
    title_fi: "Amish-syntyvyys osoittaa ~11-vuoden jaksottomuutta korreloiden auringonpilkkuluvun kanssa",
    title_ja: "アーミッシュの出生率は太陽黒点数と相関する約11年の周期性を示す",
    title_fr: "Le taux de natalité amish montre une périodicité d'environ 11 ans corrélée avec le nombre de taches solaires",
    title_ko: "아미시 출생률은 태양흑점수와 상관하는 약 11년 주기성을 보인다",
    test_en: "Analyze Old Order Amish birth records for prespecified 11-year periodicity with solar/geomagnetic exposure series and seasonal, economic and demographic controls. This tests a separate spin-chemical candidate route, not χ_geo or the v17 proxy shape.",
    test_fi: "Analysoi amissien syntyvyystiedot ennalta määritetylle 11 vuoden jaksollisuudelle aurinko-/geomagneettisilla altistussarjoilla sekä kausi-, talous- ja demografiakontrolleilla. Testi koskee erillistä spin-kemiallista ehdokasreittiä, ei χ_geo:a tai v17-proxyn muotoa.",
    test_ja: "アーミッシュ出生記録の事前指定11年周期を太陽・地磁気曝露系列と季節・経済・人口統制で解析する。これは別のスピン化学候補経路を検定し、χ_geoやv17 proxy形状ではない。",
    test_fr: "Analyser la périodicité de 11 ans préspecifiée des naissances Amish avec séries solaires/géomagnétiques et contrôles saisonniers, économiques et démographiques. Cela teste une voie spin-chimique distincte, pas χ_geo ni le proxy v17.",
    test_ko: "아미시 출생 기록의 사전 지정 11년 주기를 태양·지자기 노출 계열과 계절·경제·인구 통제로 분석한다. 이는 별도 스핀화학 후보 경로를 검정하며 χ_geo나 v17 프록시 형태가 아니다.",
    falsification_en: "No significant periodicity in the 8-14 year band in Amish birth data (p > 0.05), or periodicity present but not correlated with SSN.",
    falsification_fi: "Ei merkittävää jaksottomuutta 8-14 vuoden kaistalla amish-syntyvyysdatassa (p > 0.05), tai jaksottomuus ei korreloi SSN:n kanssa.",
    falsification_ja: "アーミッシュの出生データに8-14年帯域で有意な周期性なし（p > 0.05）、または周期性がSSNと相関しない。",
    falsification_fr: "Pas de périodicité significative dans la bande 8-14 ans dans les données de naissance amish (p > 0,05), ou périodicité non corrélée avec le SSN.",
    falsification_ko: "아미시 출생 데이터에서 8-14년 대역의 유의한 주기성 없음(p > 0.05), 또는 주기성이 SSN과 상관하지 않음.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "solar-2-nordic-stronger",
    code: "SOLAR-2",
    title_en: "Nordic countries show stronger solar cycle-birth rate correlation than Southern Europe",
    title_fi: "Pohjoismaat osoittavat voimakkaamman aurinkosykli-syntyvyyskorrelaation kuin Etelä-Eurooppa",
    title_ja: "北欧諸国は南欧より強い太陽周期-出生率相関を示す",
    title_fr: "Les pays nordiques montrent une corrélation cycle solaire-natalité plus forte que l'Europe du Sud",
    title_ko: "북유럽 국가는 남유럽보다 강한 태양주기-출생률 상관을 보인다",
    test_en: "Compare prespecified 8–14-year SSN–CBR associations between Nordic and southern panels, then test exposure × measured optical/nutritional moderators. Do not assign populations higher susceptibility from ancestry proxies alone.",
    test_fi: "Vertaa ennalta määritettyä 8–14 vuoden SSN–CBR-yhteyttä pohjoisissa ja eteläisissä paneeleissa ja testaa sitten altistus × mitattu optinen/ravitsemusmoderaattori. Älä päättele korkeampaa herkkyyttä pelkistä syntyperäprokseista.",
    test_ja: "北欧・南欧パネルで事前指定8–14年SSN–CBR関連を比較し、曝露×測定光学・栄養修飾因子を検定する。祖先proxyだけで集団感受性を割り当てない。",
    test_fr: "Comparer les associations SSN–CBR de 8–14 ans préspecifiées, puis tester exposition × modérateurs optiques/nutritionnels mesurés. Ne pas attribuer une susceptibilité par seuls proxies d'ascendance.",
    test_ko: "북부·남부 패널의 사전 지정 8~14년 SSN–CBR 연관을 비교한 뒤 노출 × 측정 광학·영양 조절인자를 검정한다. 조상 프록시만으로 집단 감수성을 지정하지 않는다.",
    falsification_en: "r_Nordic ≤ r_Southern in bandpass analysis, or no significant difference between groups.",
    falsification_fi: "r_Pohjoismaat ≤ r_Etelä kaistanpäästöanalyysissä, tai ryhmien välillä ei merkittävää eroa.",
    falsification_ja: "バンドパス分析でr_北欧 ≤ r_南欧、または群間に有意差なし。",
    falsification_fr: "r_Nordique ≤ r_Sud dans l'analyse passe-bande, ou pas de différence significative entre les groupes.",
    falsification_ko: "밴드패스 분석에서 r_북유럽 ≤ r_남유럽, 또는 그룹 간 유의한 차이 없음.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "solar-3-eye-season-interaction",
    code: "SOLAR-3",
    title_en: "Blue-eyed individuals show stronger season-of-birth effect on puberty timing than brown-eyed",
    title_fi: "Sinisisilmäisillä voimakkaampi syntymäkauden vaikutus puberteetin ajoitukseen kuin ruskeasilmäisillä",
    title_ja: "青い目の人は茶色い目の人より強い出生季節-思春期タイミング効果を示す",
    title_fr: "Les individus aux yeux bleus montrent un effet plus fort de la saison de naissance sur le timing pubertaire",
    title_ko: "파란 눈의 사람은 갈색 눈보다 강한 출생계절-사춘기 시기 효과를 보인다",
    test_en: "UK Biobank reanalysis: test season-of-birth × measured iris transmission on puberty timing while controlling ancestry, latitude, socioeconomic status and multiple testing. Eye colour is a proxy, not a calibrated EMF-susceptibility coefficient.",
    test_fi: "UK Biobank -uudelleenanalyysi: testaa syntymäkausi × mitattu iiriksen transmissio puberteetin ajoitukseen kontrolloiden syntyperä, leveysaste, sosioekonomia ja monitestaus. Silmien väri on proxy, ei kalibroitu EMF-herkkyyskerroin.",
    test_ja: "UK Biobank再解析：祖先・緯度・社会経済・多重検定を統制し、出生季節×測定虹彩透過の思春期時期効果を検定する。眼色はproxyでありEMF感受性係数ではない。",
    test_fr: "Réanalyse UK Biobank : tester saison de naissance × transmission irienne mesurée sur le timing pubertaire, avec contrôles d'ascendance, latitude, statut socioéconomique et multiplicité. La couleur des yeux est un proxy, pas un coefficient EMF calibré.",
    test_ko: "UK Biobank 재분석: 조상·위도·사회경제·다중검정을 통제하며 출생 계절 × 측정 홍채 투과의 사춘기 시기 효과를 검정한다. 눈 색은 프록시이지 보정 EMF 감수성 계수가 아니다.",
    falsification_en: "No significant eye color × season interaction on puberty timing, or brown-eyed show equal or larger effect.",
    falsification_fi: "Ei merkittävää silmien väri × kausi -vuorovaikutusta puberteetin ajoituksessa, tai ruskeasilmäisillä yhtä suuri tai suurempi vaikutus.",
    falsification_ja: "思春期タイミングに目の色×季節の有意な交互作用なし、または茶色い目で同等以上の効果。",
    falsification_fr: "Pas d'interaction significative couleur des yeux × saison sur le timing pubertaire, ou les yeux bruns montrent un effet égal ou supérieur.",
    falsification_ko: "사춘기 시기에 눈 색깔×계절의 유의한 교호작용 없음, 또는 갈색 눈에서 동등 이상의 효과.",
    level: "L*",
    timeframe: "1-3 years",
  },
  {
    id: "solar-4-sama-fertility",
    code: "SOLAR-4",
    title_en: "SAMA region shows inverted or absent solar cycle modulation of fertility",
    title_fi: "SAMA-alue osoittaa kääntyneen tai puuttuvan aurinkosyklimodulaation hedelmällisyydessä",
    title_ja: "SAMA地域は逆転したまたは欠如した出生率の太陽周期変調を示す",
    title_fr: "La région SAMA montre une modulation inversée ou absente du cycle solaire sur la fertilité",
    title_ko: "SAMA 지역은 출산율의 역전된 또는 부재하는 태양주기 변조를 보인다",
    test_en: "Analyze Brazilian southern states (under SAMA: field ~24 μT) birth rate vs SSN correlation. BERM predicts inverted or null correlation compared to non-SAMA countries, consistent with altered geomagnetic geometry distorting CRY signal reading.",
    test_fi: "Analysoi Brasilian eteläisten osavaltioiden (SAMA:n alla: kenttä ~24 μT) syntyvyys vs SSN -korrelaatio. BERM ennustaa kääntyneen tai nollakorrelaation verrattuna ei-SAMA-maihin, johdonmukaisesti muuttuneen geomagneettisen geometrian vääristäessä CRY-signaalin lukemista.",
    test_ja: "ブラジル南部州（SAMA下：場約24μT）の出生率対SSN相関を分析。BERMは非SAMA国と比較して逆転またはゼロの相関を予測。これは変化した地磁気幾何学がCRY信号読み取りを歪めることと一致する。",
    test_fr: "Analyser la corrélation natalité vs SSN des états brésiliens du sud (sous SAMA : champ ~24 μT). BERM prédit une corrélation inversée ou nulle par rapport aux pays non-SAMA, cohérente avec la géométrie géomagnétique altérée déformant la lecture du signal CRY.",
    test_ko: "브라질 남부 주(SAMA 하: 장 약24μT)의 출생률 대 SSN 상관을 분석. BERM은 비SAMA 국가와 비교하여 역전 또는 영 상관을 예측. 이는 변화된 지자기 기하학이 CRY 신호 판독을 왜곡하는 것과 일치.",
    falsification_en: "SAMA region shows same-sign and comparable-magnitude solar cycle-fertility correlation as non-SAMA countries at similar latitudes.",
    falsification_fi: "SAMA-alue osoittaa samanmerkkisen ja vertailukelpoisen suuruusluokan aurinkosykli-hedelmällisyyskorrelaation kuin ei-SAMA-maat vastaavilla leveysasteilla.",
    falsification_ja: "SAMA地域が同緯度の非SAMA国と同符号・同程度の太陽周期-出生率相関を示す。",
    falsification_fr: "La région SAMA montre une corrélation cycle solaire-fertilité de même signe et magnitude comparable aux pays non-SAMA à des latitudes similaires.",
    falsification_ko: "SAMA 지역이 유사 위도의 비SAMA 국가와 같은 부호·비슷한 크기의 태양주기-출산율 상관을 보임.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "mast-solar-1",
    code: "MAST-SOLAR-1",
    title_en: "Masting–Solar Cycle Correlation",
    title_fi: "Masting–aurinkosyklkorrelaatio",
    title_ja: "マスティング-太陽周期相関",
    title_fr: "Corrélation masting-cycle solaire",
    title_ko: "마스팅-태양주기 상관",
    test_en: "European beech masting synchrony (Bogdziewicz 2024) should show ~11-year periodicity in Fourier analysis when controlled for temperature and photoperiod. The solar cycle modulates geomagnetic field which modulates CRY2 sensitivity threshold.",
    test_fi: "Eurooppalaisen pyökin masting-synkronian (Bogdziewicz 2024) tulisi näyttää ~11 vuoden periodisuutta Fourier-analyysissä, kun lämpötila ja valojakso vakioidaan. Aurinkosykli säätelee geomagneettista kenttää, joka säätelee CRY2:n herkkyyskynnystä.",
    test_ja: "ヨーロッパブナのマスティング同期は太陽周期と相関するはず",
    test_fr: "La synchronie du masting du hêtre devrait montrer une périodicité ~11 ans",
    test_ko: "유럽 너도밤나무 마스팅 동기화는 ~11년 주기성을 보여야 함",
    falsification_en: "If beech masting synchrony (Bogdziewicz 2024 series) shows no ~11-year spectral peak after temperature and photoperiod are partialled out, or if the peak disappears when geomagnetic activity (aa/Kp) is added as a covariate while temperature alone explains it, the solar–CRY2 coupling is falsified.",
    falsification_fi: "Jos pyökin siemensadon synkronia (Bogdziewicz 2024 -sarja) ei osoita ~11 vuoden spektripiikkiä lämpötilan ja valojakson osittamisen jälkeen, tai jos piikki katoaa kun geomagneettinen aktiivisuus (aa/Kp) lisätään kovariaatiksi ja lämpötila yksin selittää sen, aurinko–CRY2-kytkentä on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["masting", "solar_cycle", "beech", "CRY2", "periodicity"],
  },
  {
    id: "mast-rf-1",
    code: "MAST-RF-1",
    title_en: "RF Background Disrupts Masting Synchrony",
    title_fi: "RF-tausta häiritsee masting-synkroniaa",
    title_ja: "RF背景がマスティング同期を乱す",
    title_fr: "Le bruit de fond RF perturbe la synchronie du masting",
    title_ko: "RF 배경이 마스팅 동기화를 방해",
    test_en: "Bogdziewicz 2021 found weakening masting synchrony attributed to 'climate change.' BERM predicts: the weakening correlates better with RF background growth (mobile network rollout 1990s→2020s) than with temperature trends alone. CRY2-mediated photoperiod sensing is disrupted by RF, analogous to Ahmad 2020 in Arabidopsis.",
    test_fi: "Bogdziewicz 2021 havaitsi masting-synkronian heikkenemisen, joka attribuoitiin ilmastonmuutokselle. BERM ennustaa: heikkeneminen korreloi paremmin RF-taustan kasvun (matkapuhelinverkkojen leviäminen 1990-luku→2020-luku) kuin pelkän lämpötilatrendin kanssa. CRY2-välitteinen valojakson aistiminen häiriintyy RF:stä, analogisesti Ahmad 2020 Arabidopsis-tulosten kanssa.",
    test_ja: "マスティング同期の弱体化はRF背景の成長とよく相関するはず",
    test_fr: "L'affaiblissement de la synchronie du masting corrèle mieux avec la croissance du bruit RF",
    test_ko: "마스팅 동기화 약화는 RF 배경 성장과 더 잘 상관해야 함",
    falsification_en: "If the weakening of masting synchrony (Bogdziewicz 2021) is explained by temperature trends alone and adds no variance to RF-background growth (mobile-network rollout 1990s→2020s), or if sites with equal warming but different RF density show identical synchrony loss, the RF–CRY2 explanation is falsified.",
    falsification_fi: "Jos siemensadon synkronian heikkeneminen (Bogdziewicz 2021) selittyy pelkillä lämpötilatrendeillä eikä RF-taustan kasvu (mobiiliverkkojen rakentaminen 1990–2020-luvuilla) lisää selitysastetta, tai jos yhtä paljon lämmenneet mutta RF-tiheydeltään erilaiset alueet menettävät synkroniaa samalla tavalla, RF–CRY2-selitys on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["masting", "RF", "synchrony", "weakening", "CRY2", "mobile_network"],
  },
  {
    id: "plant-cry-rf-1",
    code: "PLANT-CRY-RF-1",
    title_en: "Plant CRY RF Response Is Universal",
    title_fi: "Kasvien CRY:n RF-vaste on universaali",
    title_ja: "植物CRYのRF応答は普遍的",
    title_fr: "La réponse RF du CRY végétal est universelle",
    title_ko: "식물 CRY RF 반응은 보편적",
    test_en: "Ahmad 2020 demonstrated RF effects on Arabidopsis CRY1. BERM predicts this extends to CRY2 and to crop species: wheat, rice, soybean CRY2-mediated flowering should show RF sensitivity in controlled experiments. The effect is 'relatively minor' (Ahmad 2020's own assessment) but DETECTABLE and species-universal because the RPM mechanism is conserved.",
    test_fi: "Ahmad 2020 osoitti RF-vaikutukset Arabidopsiksen CRY1:een. BERM ennustaa tämän ulottuvan CRY2:een ja viljelykasveihin: vehnän, riisin, soijan CRY2-välitteisen kukinnan tulisi näyttää RF-herkkyyttä kontrolloiduissa kokeissa. Vaikutus on 'suhteellisen pieni' (Ahmad 2020:n oma arvio) mutta HAVAITTAVISSA ja lajiuniversaali, koska RPM-mekanismi on konservoitunut.",
    test_ja: "植物CRYのRF感受性は作物種にも拡張されるはず",
    test_fr: "La sensibilité RF du CRY végétal devrait s'étendre aux espèces cultivées",
    test_ko: "식물 CRY RF 민감성은 작물 종으로도 확장되어야 함",
    falsification_en: "If controlled RF exposure (GSM/Wi-Fi bands at ambient intensities) produces no detectable change in CRY2-mediated flowering time or CRY2 signalling in wheat, rice or soybean while the Arabidopsis CRY1 effect (Ahmad 2020) replicates in the same setup, species-universality is falsified.",
    falsification_fi: "Jos kontrolloitu RF-altistus (GSM/Wi-Fi-taajuudet ympäristöintensiteeteillä) ei tuota havaittavaa muutosta CRY2-välitteiseen kukinta-aikaan tai CRY2-signalointiin vehnällä, riisillä tai soijalla, vaikka Arabidopsiksen CRY1-vaikutus (Ahmad 2020) toistuu samassa asetelmassa, lajiuniversaalisuus on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["plant", "CRY2", "RF", "crop_species", "universal", "RPM"],
  },
  {
    id: "mast-soil-b2-1",
    code: "MAST-SOIL-B2-1",
    title_en: "B2/FAD Links Plant Masting to Animal Fertility",
    title_fi: "B2/FAD yhdistää kasvien mastingin eläinten lisääntymiseen",
    title_ja: "B2/FADが植物マスティングと動物生殖を結ぶ",
    title_fr: "Le B2/FAD relie le masting végétal à la fertilité animale",
    title_ko: "B2/FAD가 식물 마스팅과 동물 생식력을 연결",
    test_en: "Plants synthesize their own B2 (riboflavin) for CRY function. Animals require dietary B2. In masting years, forest-floor B2 availability changes through seed/fruit abundance. BERM predicts: small mammal fertility in mast years correlates with BOTH food abundance AND B2 availability for CRY function. This is a trophic-CRY coupling prediction.",
    test_fi: "Kasvit syntetisoivat oman B2:nsa (riboflaviini) CRY-toimintaan. Eläimet tarvitsevat ravinto-B2:n. Masting-vuosina metsänpohjan B2-saatavuus muuttuu siemen/hedelmärunsauden kautta. BERM ennustaa: pienten nisäkkäiden lisääntymismenestys masting-vuosina korreloi SEKÄ ravinnon runsauden ETTÄ B2-saatavuuden kanssa CRY-toimintaa varten. Tämä on troofinen CRY-kytkentäennuste.",
    test_ja: "マスト年の小型哺乳類の繁殖力はB2利用可能性と相関するはず",
    test_fr: "La fertilité des petits mammifères en année de faine corrèle avec la disponibilité en B2",
    test_ko: "마스트 해의 소형 포유류 번식력은 B2 가용성과 상관해야 함",
    falsification_en: "If small-mammal fertility in mast years tracks caloric abundance only — no residual effect of dietary riboflavin/FAD status on litter size or conception timing after controlling for food mass — the trophic-CRY coupling is falsified.",
    falsification_fi: "Jos pienten nisäkkäiden hedelmällisyys siemensatovuosina seuraa vain kaloreiden runsautta — ilman ravinnon riboflaviini/FAD-tilan jäännösvaikutusta poikuekokoon tai hedelmöitymisen ajoitukseen, kun ravinnon määrä on kontrolloitu — troofinen CRY-kytkentä on falsifioitu.",
    level: "L*",
    timeframe: "5–10 years",
    pathway: ["B"],
    tags: ["masting", "B2", "FAD", "trophic", "CRY", "small_mammals", "diet"],
  },
];
