export type EpistemicLevel = "E" | "M|C" | "C" | "L*";

export interface ChiScale {
  id: string;
  label_en: string;
  label_fi: string;
  label_ja: string;
  label_fr: string;
  label_ko: string;
  background_en: string;
  background_fi: string;
  background_ja: string;
  background_fr: string;
  background_ko: string;
  perturbation_en: string;
  perturbation_fi: string;
  perturbation_ja: string;
  perturbation_fr: string;
  perturbation_ko: string;
  chi_expression: string;
  at_zero_en: string;
  at_zero_fi: string;
  at_zero_ja: string;
  at_zero_fr: string;
  at_zero_ko: string;
  at_max_en: string;
  at_max_fi: string;
  at_max_ja: string;
  at_max_fr: string;
  at_max_ko: string;
  verification: string;
  referenceIds?: string[];
  level: EpistemicLevel;
}

export interface HistoricalPhase {
  id: string;
  period: string;
  title_en: string;
  title_fi: string;
  title_ja: string;
  title_fr: string;
  title_ko: string;
  description_en: string;
  description_fi: string;
  description_ja: string;
  description_fr: string;
  description_ko: string;
}

export interface PopulationProfile {
  id: string;
  label_en: string;
  label_fi: string;
  label_ja: string;
  label_fr: string;
  label_ko: string;
  chi_env: string;
  chi_optical: string;
  chi_molecular: string;
  dominant_pathway: string;
  observed_tfr: string;
  status_en: string;
  status_fi: string;
  status_ja: string;
  status_fr: string;
  status_ko: string;
}

export interface NorthernTrait {
  id: string;
  trait_en: string;
  trait_fi: string;
  trait_ja: string;
  trait_fr: string;
  trait_ko: string;
  gene: string;
  mechanism_en: string;
  mechanism_fi: string;
  mechanism_ja: string;
  mechanism_fr: string;
  mechanism_ko: string;
  cry_link_en: string;
  cry_link_fi: string;
  cry_link_ja: string;
  cry_link_fr: string;
  cry_link_ko: string;
  level: EpistemicLevel;
}

export interface EvolutionPrediction {
  id: string;
  code: string;
  title_en: string;
  title_fi: string;
  title_ja: string;
  title_fr: string;
  title_ko: string;
  test_en: string;
  test_fi: string;
  test_ja: string;
  test_fr: string;
  test_ko: string;
  falsification_en?: string;
  falsification_fi?: string;
  falsification_ja?: string;
  falsification_fr?: string;
  falsification_ko?: string;
  level: EpistemicLevel;
  timeframe: string;
  pathway?: string[];
  tags?: string[];
}

export const CHI_SCALES: ChiScale[] = [
  {
    id: "molecular",
    label_en: "Molecular",
    label_fi: "Molekulaarinen",
    label_ja: "分子",
    label_fr: "Moléculaire",
    label_ko: "분자",
    background_en: "FAD chromophore in CRY",
    background_fi: "FAD-kromofori CRY:ssä",
    background_ja: "CRY内のFAD発色団",
    background_fr: "Chromophore FAD dans CRY",
    background_ko: "CRY 내 FAD 발색단",
    perturbation_en: "Magnetic field",
    perturbation_fi: "Magneettikenttä",
    perturbation_ja: "磁場",
    perturbation_fr: "Champ magnétique",
    perturbation_ko: "자기장",
    chi_expression: "χ([FAD])",
    at_zero_en: "No FAD → no radical pairs → no sensitivity",
    at_zero_fi: "Ei FAD:tä → ei radikaaliparia → ei herkkyyttä",
    at_zero_ja: "FADなし → ラジカル対なし → 感受性なし",
    at_zero_fr: "Pas de FAD → pas de paires radicalaires → pas de sensibilité",
    at_zero_ko: "FAD 없음 → 라디칼 쌍 없음 → 감수성 없음",
    at_max_en: "FAD-replete → full magnetic sensitivity",
    at_max_fi: "FAD kyllästetty → täysi magneettinen herkkyys",
    at_max_ja: "FAD充足 → 完全な磁気感受性",
    at_max_fr: "FAD saturé → sensibilité magnétique maximale",
    at_max_ko: "FAD 충족 → 완전한 자기 감수성",
    verification: "Hirano 2017, Yap 2025",
    referenceIds: ["hirano2017", "yap2025"],
    level: "E",
  },
  {
    id: "optical",
    label_en: "Optical",
    label_fi: "Optinen",
    label_ja: "光学",
    label_fr: "Optique",
    label_ko: "광학",
    background_en: "Blue light at CRY1 (iris transmission)",
    background_fi: "Sininen valo CRY1:ssä (iiriksen transmissio)",
    background_ja: "CRY1における青色光（虹彩透過）",
    background_fr: "Lumière bleue sur CRY1 (transmission irienne)",
    background_ko: "CRY1에서의 청색광 (홍채 투과)",
    perturbation_en: "RF field",
    perturbation_fi: "RF-kenttä",
    perturbation_ja: "RF電磁場",
    perturbation_fr: "Champ RF",
    perturbation_ko: "RF 전자기장",
    chi_expression: "χ(I_blue)",
    at_zero_en: "Dark / brown iris → CRY1 inactive → no coupling",
    at_zero_fi: "Tumma / ruskea iiris → CRY1 inaktiivinen → ei kytkentää",
    at_zero_ja: "暗色/茶色の虹彩 → CRY1不活性 → 結合なし",
    at_zero_fr: "Iris foncé / brun → CRY1 inactif → pas de couplage",
    at_zero_ko: "어두운/갈색 홍채 → CRY1 비활성 → 결합 없음",
    at_max_en: "Blue iris + blue light → CRY1 maximally active",
    at_max_fi: "Sininen iiris + sininen valo → CRY1 maksimaalisesti aktiivinen",
    at_max_ja: "青い虹彩 + 青色光 → CRY1が最大限に活性化",
    at_max_fr: "Iris bleu + lumière bleue → CRY1 maximalement actif",
    at_max_ko: "파란 홍채 + 청색광 → CRY1 최대 활성화",
    verification: "Higuchi 2007, Bartölke 2025",
    referenceIds: ["higuchi2007", "bartolke2025"],
    level: "M|C",
  },
  {
    id: "cellular",
    label_en: "Cellular membrane",
    label_fi: "Solukalvo",
    label_ja: "細胞膜",
    label_fr: "Membrane cellulaire",
    label_ko: "세포막",
    background_en: "Membrane potential V_mem ≈ −70 mV",
    background_fi: "Kalvopotentiaali V_mem ≈ −70 mV",
    background_ja: "膜電位 V_mem ≈ −70 mV",
    background_fr: "Potentiel membranaire V_mem ≈ −70 mV",
    background_ko: "막전위 V_mem ≈ −70 mV",
    perturbation_en: "External EMF",
    perturbation_fi: "Ulkoinen EMF",
    perturbation_ja: "外部EMF",
    perturbation_fr: "EMF externe",
    perturbation_ko: "외부 EMF",
    chi_expression: "χ(V_mem)",
    at_zero_en: "Dead cell (V_mem = 0) → no VGCC response",
    at_zero_fi: "Kuollut solu (V_mem = 0) → ei VGCC-vastetta",
    at_zero_ja: "死細胞 (V_mem = 0) → VGCC応答なし",
    at_zero_fr: "Cellule morte (V_mem = 0) → pas de réponse VGCC",
    at_zero_ko: "사멸 세포 (V_mem = 0) → VGCC 반응 없음",
    at_max_en: "Living cell → χ ≈ 1.0 → maximum sensitivity",
    at_max_fi: "Elävä solu → χ ≈ 1.0 → maksimaalinen herkkyys",
    at_max_ja: "生細胞 → χ ≈ 1.0 → 最大感受性",
    at_max_fr: "Cellule vivante → χ ≈ 1.0 → sensibilité maximale",
    at_max_ko: "생존 세포 → χ ≈ 1.0 → 최대 감수성",
    verification: "Pall 2013 (23 VGCC blocker studies)",
    referenceIds: ["pall2013_v2"],
    level: "E",
  },
  {
    id: "environmental",
    label_en: "Environmental",
    label_fi: "Ympäristö",
    label_ja: "環境",
    label_fr: "Environnemental",
    label_ko: "환경",
    background_en: "Ambient EMF (electrification, base stations)",
    background_fi: "Ympäristön EMF (sähköistys, tukiasemat)",
    background_ja: "環境EMF（電化、基地局）",
    background_fr: "EMF ambiant (électrification, stations de base)",
    background_ko: "환경 EMF (전화, 기지국)",
    perturbation_en: "Personal devices (phone, earbuds)",
    perturbation_fi: "Henkilökohtaiset laitteet (puhelin, nappikuulokkeet)",
    perturbation_ja: "個人用デバイス（携帯電話、イヤホン）",
    perturbation_fr: "Appareils personnels (téléphone, écouteurs)",
    perturbation_ko: "개인 기기 (휴대폰, 이어버드)",
    chi_expression: "χ(Ā_ambient)",
    at_zero_en: "Unelectrified area → personal devices don't couple",
    at_zero_fi: "Sähköistämätön alue → henkilökohtaiset laitteet eivät kytkeydy",
    at_zero_ja: "非電化地域 → 個人用デバイスは結合しない",
    at_zero_fr: "Zone non électrifiée → les appareils personnels ne se couplent pas",
    at_zero_ko: "비전화 지역 → 개인 기기가 결합하지 않음",
    at_max_en: "Dense urban → personal devices fully coupled",
    at_max_fi: "Tiheä kaupunki → henkilökohtaiset laitteet täysin kytkeytyneitä",
    at_max_ja: "高密度都市 → 個人用デバイスが完全に結合",
    at_max_fr: "Urbain dense → appareils personnels entièrement couplés",
    at_max_ko: "고밀도 도시 → 개인 기기가 완전히 결합",
    verification: "BERM 54-country dataset, electrification boundary",
    level: "M|C",
  },
  {
    id: "population",
    label_en: "Population (COVID test)",
    label_fi: "Populaatio (COVID-testi)",
    label_ja: "集団（COVID検証）",
    label_fr: "Population (test COVID)",
    label_ko: "집단 (COVID 검증)",
    background_en: "Workplace ambient EMF",
    background_fi: "Työpaikan ympäristön EMF",
    background_ja: "職場の環境EMF",
    background_fr: "EMF ambiant au travail",
    background_ko: "직장 환경 EMF",
    perturbation_en: "Screen time",
    perturbation_fi: "Ruutuaika",
    perturbation_ja: "スクリーン時間",
    perturbation_fr: "Temps d'écran",
    perturbation_ko: "화면 시간",
    chi_expression: "χ(Ā_office vs Ā_home)",
    at_zero_en: "WFH (low ambient) → screen time less coupled → baby bump",
    at_zero_fi: "Etätyö (matala ympäristö) → ruutuaika vähemmän kytkeytynyt → vauvapiikki",
    at_zero_ja: "在宅勤務（低環境） → スクリーン時間の結合が弱い → ベビーブーム",
    at_zero_fr: "Télétravail (faible ambiant) → temps d'écran moins couplé → baby bump",
    at_zero_ko: "재택근무 (낮은 환경) → 화면 시간 결합 약함 → 베이비붐",
    at_max_en: "Office (high ambient) → screen time fully coupled → TFR decline",
    at_max_fi: "Toimisto (korkea ympäristö) → ruutuaika täysin kytkeytynyt → TFR-lasku",
    at_max_ja: "オフィス（高環境） → スクリーン時間が完全に結合 → TFR低下",
    at_max_fr: "Bureau (ambiant élevé) → temps d'écran entièrement couplé → déclin du TFR",
    at_max_ko: "사무실 (높은 환경) → 화면 시간 완전 결합 → TFR 감소",
    verification: "PNAS 2023: +5.1% TFR for WFH women",
    level: "C",
  },
];

export const NORTHERN_TRAITS: NorthernTrait[] = [
  {
    id: "blue_eyes",
    trait_en: "Blue eyes (OCA2)",
    trait_fi: "Siniset silmät (OCA2)",
    trait_ja: "青い目 (OCA2)",
    trait_fr: "Yeux bleus (OCA2)",
    trait_ko: "파란 눈 (OCA2)",
    gene: "OCA2/HERC2",
    mechanism_en: "Reduced melanin → 100× iris transmission → maximizes CRY1 blue-light activation in retinal blue cones",
    mechanism_fi: "Vähentynyt melaniini → 100× iiriksen transmissio → maksimoi CRY1:n sinisenvalon aktivaation verkkokalvon sinisissä tapeissa",
    mechanism_ja: "メラニン減少 → 100倍の虹彩透過 → 網膜の青錐体におけるCRY1青色光活性化を最大化",
    mechanism_fr: "Mélanine réduite → 100× transmission irienne → maximise l'activation de CRY1 par la lumière bleue dans les cônes bleus rétiniens",
    mechanism_ko: "멜라닌 감소 → 100배 홍채 투과 → 망막 청추체에서 CRY1 청색광 활성화 극대화",
    cry_link_en: "Direct: iris transmission → CRY1 photon flux (optical χ scale)",
    cry_link_fi: "Suora: iiriksen transmissio → CRY1-fotonivuo (optinen χ-skaala)",
    cry_link_ja: "直接的: 虹彩透過 → CRY1光子束（光学χスケール）",
    cry_link_fr: "Direct : transmission irienne → flux de photons CRY1 (échelle χ optique)",
    cry_link_ko: "직접적: 홍채 투과 → CRY1 광자 플럭스 (광학 χ 척도)",
    level: "M|C",
  },
  {
    id: "lactose_tolerance",
    trait_en: "Lactose tolerance (LCT)",
    trait_fi: "Laktoosinsietokyky (LCT)",
    trait_ja: "乳糖耐性 (LCT)",
    trait_fr: "Tolérance au lactose (LCT)",
    trait_ko: "유당 내성 (LCT)",
    gene: "LCT −13910C>T",
    mechanism_en: "Adult milk digestion → year-round dairy → stable riboflavin (B2) supply → FAD for CRY chromophore",
    mechanism_fi: "Aikuisiän maidonsulatuskyky → ympärivuotinen maitotuote → vakaa riboflaviini (B2) -saanti → FAD CRY:n kromoforiksi",
    mechanism_ja: "成人の牛乳消化 → 通年の乳製品 → 安定したリボフラビン（B2）供給 → CRY発色団用FAD",
    mechanism_fr: "Digestion du lait à l'âge adulte → produits laitiers toute l'année → apport stable en riboflavine (B2) → FAD pour le chromophore CRY",
    mechanism_ko: "성인 우유 소화 → 연중 유제품 → 안정적 리보플라빈(B2) 공급 → CRY 발색단용 FAD",
    cry_link_en: "Nutritional: riboflavin → FAD → CRY stability and function (molecular χ scale)",
    cry_link_fi: "Ravitsemuksellinen: riboflaviini → FAD → CRY:n stabiilius ja toiminta (molekulaarinen χ-skaala)",
    cry_link_ja: "栄養的: リボフラビン → FAD → CRYの安定性と機能（分子χスケール）",
    cry_link_fr: "Nutritionnel : riboflavine → FAD → stabilité et fonction de CRY (échelle χ moléculaire)",
    cry_link_ko: "영양적: 리보플라빈 → FAD → CRY 안정성 및 기능 (분자 χ 척도)",
    level: "E",
  },
  {
    id: "cattle_husbandry",
    trait_en: "Cattle husbandry (cultural-genetic coevolution)",
    trait_fi: "Karjankasvatus (kulttuuris-geneettinen koevoluutio)",
    trait_ja: "牧畜（文化-遺伝的共進化）",
    trait_fr: "Élevage bovin (coévolution culturelle-génétique)",
    trait_ko: "목축 (문화-유전적 공진화)",
    gene: "Cultural + LCT selection",
    mechanism_en: "Pastoralism selected for LCT; dairy provided B2 through winter when solar synthesis and foraging failed",
    mechanism_fi: "Paimentolaisuus valitsi LCT:tä; maitotuotteet tarjosivat B2:ta talvella kun auringon synteesi ja keräily eivät riittäneet",
    mechanism_ja: "牧畜がLCTを選択; 太陽合成と採集が不可能な冬季に乳製品がB2を供給",
    mechanism_fr: "Le pastoralisme a sélectionné le LCT ; les produits laitiers ont fourni du B2 en hiver quand la synthèse solaire et la cueillette échouaient",
    mechanism_ko: "목축이 LCT를 선택; 태양 합성과 채집이 불가능한 겨울에 유제품이 B2를 공급",
    cry_link_en: "Environmental: winter B2 buffer sustaining CRY function in dark season",
    cry_link_fi: "Ympäristöllinen: talven B2-puskuri ylläpitäen CRY:n toimintaa pimeänä vuodenaikana",
    cry_link_ja: "環境的: 暗い季節にCRY機能を維持する冬季B2緩衝",
    cry_link_fr: "Environnemental : tampon hivernal de B2 maintenant la fonction CRY en saison sombre",
    cry_link_ko: "환경적: 어두운 계절에 CRY 기능을 유지하는 겨울철 B2 완충",
    level: "M|C",
  },
];

export const HISTORICAL_PHASES: HistoricalPhase[] = [
  {
    id: "phase1",
    period: "10,000–6,000 BP",
    title_en: "Biological Optimization",
    title_fi: "Biologinen optimointi",
    title_ja: "生物学的最適化",
    title_fr: "Optimisation biologique",
    title_ko: "생물학적 최적화",
    description_en: "Northern Europeans evolve the highest biological χ values through co-selection of blue eyes (optical χ), lactose tolerance (molecular χ via B2/FAD), and cattle husbandry (year-round B2 supply). χ_env ≈ 0 (no electrification). TFR follows natural biological maximum (~6–7).",
    description_fi: "Pohjoiseuroppalaiset kehittävät korkeimmat biologiset χ-arvot sinisilmäisyyden (optinen χ), laktoosinsietokyvyn (molekulaarinen χ B2/FAD kautta) ja karjankasvatuksen (ympärivuotinen B2-saanti) koselektiolla. χ_env ≈ 0 (ei sähköistystä). TFR seuraa luonnollista biologista maksimia (~6–7).",
    description_ja: "北欧人は青い目（光学χ）、乳糖耐性（B2/FADによる分子χ）、牧畜（通年B2供給）の共選択により最も高い生物学的χ値を進化させる。χ_env ≈ 0（電化なし）。TFRは自然な生物学的最大値（約6〜7）に従う。",
    description_fr: "Les Européens du Nord développent les valeurs biologiques de χ les plus élevées par co-sélection des yeux bleus (χ optique), de la tolérance au lactose (χ moléculaire via B2/FAD) et de l'élevage bovin (approvisionnement en B2 toute l'année). χ_env ≈ 0 (pas d'électrification). Le TFR suit le maximum biologique naturel (~6–7).",
    description_ko: "북유럽인은 파란 눈(광학 χ), 유당 내성(B2/FAD를 통한 분자 χ), 목축(연중 B2 공급)의 공동 선택을 통해 가장 높은 생물학적 χ 값을 진화시킨다. χ_env ≈ 0 (전화 없음). TFR은 자연적 생물학적 최대치(약 6~7)를 따른다.",
  },
  {
    id: "phase2",
    period: "1880–1960",
    title_en: "Electrification: χ_env Awakens",
    title_fi: "Sähköistys: χ_env herää",
    title_ja: "電化：χ_envの覚醒",
    title_fr: "Électrification : χ_env s'éveille",
    title_ko: "전화: χ_env의 각성",
    description_en: "Northern Europe electrifies first. The population with the HIGHEST biological χ values is FIRST to experience rising χ_env. The coupling function amplifies: high biological sensitivity × rising environmental EMF → first region below replacement TFR.",
    description_fi: "Pohjois-Eurooppa sähköistyy ensimmäisenä. Populaatio jolla on KORKEIMMAT biologiset χ-arvot kokee ENSIMMÄISENÄ nousevan χ_env:n. Kytkentäfunktio vahvistaa: korkea biologinen herkkyys × nouseva ympäristön EMF → ensimmäinen alue alle uusiutumistason TFR:n.",
    description_ja: "北欧が最初に電化する。最も高い生物学的χ値を持つ集団が最初にχ_envの上昇を経験する。結合関数が増幅：高い生物学的感受性 × 上昇する環境EMF → 人口置換水準以下のTFRとなる最初の地域。",
    description_fr: "L'Europe du Nord s'électrifie en premier. La population aux valeurs biologiques de χ les PLUS ÉLEVÉES est la PREMIÈRE à connaître un χ_env croissant. La fonction de couplage amplifie : haute sensibilité biologique × EMF environnemental croissant → première région sous le TFR de remplacement.",
    description_ko: "북유럽이 가장 먼저 전화된다. 가장 높은 생물학적 χ 값을 가진 집단이 가장 먼저 상승하는 χ_env를 경험한다. 결합 함수가 증폭: 높은 생물학적 감수성 × 상승하는 환경 EMF → 인구 대체 수준 이하 TFR의 첫 번째 지역.",
  },
  {
    id: "phase3",
    period: "1990–2020",
    title_en: "Mobile Revolution: Differentiated Decline",
    title_fi: "Mobiilirevoluutio: eriytynyt lasku",
    title_ja: "モバイル革命：差別化された低下",
    title_fr: "Révolution mobile : déclin différencié",
    title_ko: "모바일 혁명: 차별화된 감소",
    description_en: "EMF globalizes via mobile phones. Population-specific χ profiles produce different decline patterns: East Asia (A-pathway dominant, high screen time), Northern Europe (A+B balanced), Africa (minimal coupling due to low χ_optical and χ_molecular).",
    description_fi: "EMF globalisoituu matkapuhelimien kautta. Populaatiokohtaiset χ-profiilit tuottavat erilaisia laskukaavoja: Itä-Aasia (A-polku hallitseva, korkea ruutuaika), Pohjois-Eurooppa (A+B tasapainoinen), Afrikka (minimaalinen kytkentä matalan χ_optisen ja χ_molekulaarisen vuoksi).",
    description_ja: "EMFが携帯電話を通じてグローバル化する。集団固有のχプロファイルが異なる低下パターンを生む：東アジア（A経路優位、高スクリーン時間）、北欧（A+Bバランス型）、アフリカ（低χ_opticalと低χ_molecularによる最小結合）。",
    description_fr: "L'EMF se mondialise via les téléphones mobiles. Les profils χ spécifiques aux populations produisent des schémas de déclin différents : Asie de l'Est (voie A dominante, temps d'écran élevé), Europe du Nord (A+B équilibré), Afrique (couplage minimal dû à un faible χ_optique et χ_moléculaire).",
    description_ko: "EMF가 휴대폰을 통해 세계화된다. 집단별 χ 프로필이 서로 다른 감소 패턴을 만든다: 동아시아(A 경로 우위, 높은 화면 시간), 북유럽(A+B 균형), 아프리카(낮은 χ_optical과 χ_molecular로 인한 최소 결합).",
  },
  {
    id: "phase4",
    period: "2020+",
    title_en: "The Convergence",
    title_fi: "Yhdentyminen",
    title_ja: "収斂",
    title_fr: "La Convergence",
    title_ko: "수렴",
    description_en: "Africa electrifies rapidly. BERM predicts TFR decline follows but SLOWER than Northern Europe at equivalent χ_env, because biological χ values (optical and molecular) are lower. Sub-Saharan Africa's brown-eyed, lactose-intolerant population has less CRY coupling to amplify the environmental signal.",
    description_fi: "Afrikka sähköistyy nopeasti. BERM ennustaa TFR-laskun seuraavan mutta HITAAMMIN kuin Pohjois-Euroopassa vastaavalla χ_env:llä, koska biologiset χ-arvot (optinen ja molekulaarinen) ovat matalammat. Saharan eteläpuolisen Afrikan ruskesilmäinen, laktoosi-intolerantti populaatio kytkeytyy CRY:n kautta heikommin ympäristösignaaliin.",
    description_ja: "アフリカが急速に電化する。BERMはTFR低下が続くと予測するが、生物学的χ値（光学的および分子的）が低いため、同等のχ_envでは北欧よりも遅い。サハラ以南アフリカの茶色い目で乳糖不耐性の集団は、環境シグナルを増幅するCRY結合が弱い。",
    description_fr: "L'Afrique s'électrifie rapidement. BERM prédit que le déclin du TFR suit mais PLUS LENTEMENT qu'en Europe du Nord à χ_env équivalent, car les valeurs biologiques de χ (optique et moléculaire) sont plus basses. La population aux yeux bruns et intolérante au lactose d'Afrique subsaharienne a moins de couplage CRY pour amplifier le signal environnemental.",
    description_ko: "아프리카가 빠르게 전화된다. BERM은 TFR 감소가 뒤따르지만 생물학적 χ 값(광학적, 분자적)이 낮기 때문에 동등한 χ_env에서 북유럽보다 더 느릴 것으로 예측한다. 사하라 이남 아프리카의 갈색 눈, 유당 불내성 집단은 환경 신호를 증폭하는 CRY 결합이 적다.",
  },
];

export const POPULATION_PROFILES: PopulationProfile[] = [
  {
    id: "amish",
    label_en: "Old Order Amish",
    label_fi: "Vanhan järjestyksen amissit",
    label_ja: "Old Order Amish",
    label_fr: "Amish traditionnels",
    label_ko: "Old Order Amish",
    chi_env: "~0.1",
    chi_optical: "0.8–0.9",
    chi_molecular: "0.9",
    dominant_pathway: "B (but uncoupled)",
    observed_tfr: "~6.5",
    status_en: "Control: high biological χ, near-zero environmental χ → TFR at natural maximum",
    status_fi: "Kontrolli: korkea biologinen χ, lähes nolla ympäristön χ → TFR luonnollisessa maksimissa",
    status_ja: "対照群: 高い生物学的χ、ほぼゼロの環境χ → TFRは自然最大値",
    status_fr: "Contrôle : χ biologique élevé, χ environnemental quasi nul → TFR au maximum naturel",
    status_ko: "대조군: 높은 생물학적 χ, 거의 0인 환경 χ → TFR 자연 최대치",
  },
  {
    id: "mennonite",
    label_en: "Conservative Mennonites",
    label_fi: "Konservatiiviset mennoniitit",
    label_ja: "保守派メノナイト",
    label_fr: "Mennonites conservateurs",
    label_ko: "보수파 메노나이트",
    chi_env: "~0.3–0.5",
    chi_optical: "0.7–0.8",
    chi_molecular: "0.8",
    dominant_pathway: "A+B (partial coupling)",
    observed_tfr: "~3.5–4.5",
    status_en: "Intermediate: similar biology to Amish but moderate EMF exposure → moderate TFR reduction",
    status_fi: "Välitaso: samanlainen biologia kuin amisseilla mutta kohtalainen EMF-altistus → kohtalainen TFR-lasku",
    status_ja: "中間: Amishと類似の生物学だが中程度のEMF曝露 → 中程度のTFR減少",
    status_fr: "Intermédiaire : biologie similaire aux Amish mais exposition EMF modérée → réduction modérée du TFR",
    status_ko: "중간: Amish와 유사한 생물학이나 중간 정도의 EMF 노출 → 중간 정도의 TFR 감소",
  },
  {
    id: "scandinavia",
    label_en: "Scandinavia",
    label_fi: "Skandinavia",
    label_ja: "スカンジナビア",
    label_fr: "Scandinavie",
    label_ko: "스칸디나비아",
    chi_env: "0.8–0.9",
    chi_optical: "0.7–0.9",
    chi_molecular: "0.8–0.9",
    dominant_pathway: "A+B (fully coupled)",
    observed_tfr: "~1.5–1.7",
    status_en: "Maximum coupling: highest biological χ × highest environmental χ → deepest TFR decline",
    status_fi: "Maksimaalinen kytkentä: korkein biologinen χ × korkein ympäristön χ → syvin TFR-lasku",
    status_ja: "最大結合: 最高の生物学的χ × 最高の環境χ → 最も深いTFR低下",
    status_fr: "Couplage maximal : χ biologique le plus élevé × χ environnemental le plus élevé → déclin du TFR le plus profond",
    status_ko: "최대 결합: 가장 높은 생물학적 χ × 가장 높은 환경 χ → 가장 깊은 TFR 감소",
  },
  {
    id: "south_korea",
    label_en: "South Korea",
    label_fi: "Etelä-Korea",
    label_ja: "韓国",
    label_fr: "Corée du Sud",
    label_ko: "대한민국",
    chi_env: "0.9–1.0",
    chi_optical: "0.2–0.3",
    chi_molecular: "0.5–0.6",
    dominant_pathway: "A (VGIC dominant)",
    observed_tfr: "~0.7",
    status_en: "A-pathway extreme: low optical χ but extreme screen time and EMF density → TFR collapse via pathway A",
    status_fi: "A-polun ääriarvo: matala optinen χ mutta äärimmäinen ruutuaika ja EMF-tiheys → TFR-romahdus polun A kautta",
    status_ja: "A経路の極端: 低い光学χだが極端なスクリーン時間とEMF密度 → A経路によるTFR崩壊",
    status_fr: "Extrême voie A : faible χ optique mais temps d'écran et densité EMF extrêmes → effondrement du TFR via la voie A",
    status_ko: "A 경로 극단: 낮은 광학 χ이나 극단적 화면 시간과 EMF 밀도 → A 경로를 통한 TFR 붕괴",
  },
  {
    id: "china",
    label_en: "Urban China",
    label_fi: "Kaupunki-Kiina",
    label_ja: "都市部中国",
    label_fr: "Chine urbaine",
    label_ko: "도시 중국",
    chi_env: "0.7–0.9",
    chi_optical: "0.2–0.3",
    chi_molecular: "0.4–0.5",
    dominant_pathway: "A (VGIC dominant)",
    observed_tfr: "~1.0",
    status_en: "Similar to South Korea but lower density → less extreme A-pathway decline",
    status_fi: "Samankaltainen kuin Etelä-Korea mutta matalampi tiheys → vähemmän äärimmäinen A-polun lasku",
    status_ja: "韓国と類似だが密度が低い → A経路の低下がより穏やか",
    status_fr: "Similaire à la Corée du Sud mais densité plus faible → déclin moins extrême de la voie A",
    status_ko: "한국과 유사하나 밀도가 낮음 → 덜 극단적인 A 경로 감소",
  },
  {
    id: "sub_saharan_africa",
    label_en: "Sub-Saharan Africa",
    label_fi: "Saharan eteläpuolinen Afrikka",
    label_ja: "サハラ以南アフリカ",
    label_fr: "Afrique subsaharienne",
    label_ko: "사하라 이남 아프리카",
    chi_env: "0.2–0.4",
    chi_optical: "0.05–0.1",
    chi_molecular: "0.3–0.4",
    dominant_pathway: "A (weak coupling)",
    observed_tfr: "~4.5",
    status_en: "Minimal coupling: low biological χ × low-moderate environmental χ → TFR still high, declining slowly",
    status_fi: "Minimaalinen kytkentä: matala biologinen χ × matala-kohtalainen ympäristön χ → TFR edelleen korkea, laskee hitaasti",
    status_ja: "最小結合: 低い生物学的χ × 低〜中程度の環境χ → TFRは依然高く、緩やかに低下",
    status_fr: "Couplage minimal : faible χ biologique × χ environnemental faible à modéré → TFR encore élevé, déclinant lentement",
    status_ko: "최소 결합: 낮은 생물학적 χ × 낮은-중간 환경 χ → TFR 여전히 높음, 천천히 감소",
  },
];

export const EVOLUTION_PREDICTIONS: EvolutionPrediction[] = [
  {
    id: "hist1",
    code: "HIST-1",
    title_en: "Biomarker ratios predict fertility differentials",
    title_fi: "Biomarkkeritasot ennustavat hedelmällisyyseroja",
    title_ja: "バイオマーカー比が出生率格差を予測",
    title_fr: "Les ratios de biomarqueurs prédisent les différentiels de fertilité",
    title_ko: "바이오마커 비율이 출산율 차이를 예측",
    test_en: "In populations with high lactose tolerance AND blue/green eye prevalence, CRY-associated biomarkers (urinary 6-sulphatoxymelatonin, FAD/FMN ratio) should correlate more strongly with fertility outcomes than in populations lacking these traits.",
    test_fi: "Populaatioissa joissa on korkea laktoosinsietokyky JA sinisten/vihreiden silmien esiintyvyys, CRY-liitteiset biomarkkerit (virtsan 6-sulfatoksimelatoniini, FAD/FMN-suhde) korreloivat voimakkaammin hedelmällisyystulosten kanssa kuin populaatioissa ilman näitä piirteitä.",
    test_ja: "乳糖耐性が高くかつ青/緑色の目の有病率が高い集団では、CRY関連バイオマーカー（尿中6-スルファトキシメラトニン、FAD/FMN比）が、これらの形質を持たない集団よりも出生率転帰とより強く相関するはずである。",
    test_fr: "Dans les populations à haute tolérance au lactose ET à prévalence élevée d'yeux bleus/verts, les biomarqueurs associés à CRY (6-sulphatoxymélatonine urinaire, ratio FAD/FMN) devraient corréler plus fortement avec les résultats de fertilité que dans les populations dépourvues de ces traits.",
    test_ko: "유당 내성이 높고 파란/녹색 눈 유병률이 높은 집단에서 CRY 관련 바이오마커(소변 6-설파톡시멜라토닌, FAD/FMN 비율)는 이러한 형질이 없는 집단보다 출산 결과와 더 강하게 상관해야 한다.",
    falsification_en: "If blue-eyed, lactose-tolerant populations show NO stronger biomarker-fertility correlation than brown-eyed, lactose-intolerant populations, the Northern Package hypothesis is falsified.",
    falsification_fi: "Jos sinisilmäisissä, laktoosinsietokyvyn omaavissa populaatioissa EI ole voimakkaampaa biomarkkeri-hedelmällisyyskorrelaatiota kuin ruskeasilmäisissä, laktoosi-intoleranteissa populaatioissa, Pohjoinen paketti -hypoteesi on falsifioitu.",
    falsification_ja: "青い目で乳糖耐性のある集団が、茶色い目で乳糖不耐性の集団と比較してバイオマーカー-出生率相関が強くない場合、Northern Package仮説は反証される。",
    falsification_fr: "Si les populations aux yeux bleus et tolérantes au lactose ne montrent PAS de corrélation biomarqueur-fertilité plus forte que les populations aux yeux bruns et intolérantes au lactose, l'hypothèse du Northern Package est falsifiée.",
    falsification_ko: "파란 눈의 유당 내성 집단이 갈색 눈의 유당 불내성 집단보다 바이오마커-출산율 상관관계가 강하지 않으면 Northern Package 가설은 반증된다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "hist2",
    code: "HIST-2",
    title_en: "Amish–Mennonite fertility gradient",
    title_fi: "Amissi–mennoniittigradientti hedelmällisyydessä",
    title_ja: "Amish-Mennonite出生率勾配",
    title_fr: "Gradient de fertilité Amish–Mennonite",
    title_ko: "Amish-Mennonite 출산율 기울기",
    test_en: "The TFR difference between Old Order Amish (~6.5) and Conservative Mennonites (~3.5–4.5) should correlate with measured EMF exposure differences, not with genetic, dietary, or cultural confounds alone.",
    test_fi: "TFR-ero vanhan järjestyksen amissien (~6,5) ja konservatiivisten mennoniittien (~3,5–4,5) välillä tulisi korreloida mitattujen EMF-altistuserojen kanssa, ei pelkästään geneettisten, ravitsemuksellisten tai kulttuuristen sekoittavien tekijöiden kanssa.",
    test_ja: "Old Order Amish（約6.5）とConservative Mennonite（約3.5〜4.5）のTFR差は、遺伝的・食事的・文化的交絡因子だけでなく、測定されたEMF曝露差と相関するはずである。",
    test_fr: "La différence de TFR entre les Amish traditionnels (~6,5) et les Mennonites conservateurs (~3,5–4,5) devrait corréler avec les différences d'exposition EMF mesurées, et non uniquement avec les facteurs confondants génétiques, alimentaires ou culturels.",
    test_ko: "Old Order Amish(약 6.5)와 Conservative Mennonite(약 3.5~4.5) 사이의 TFR 차이는 유전적, 식이적, 문화적 교란 요인만이 아닌 측정된 EMF 노출 차이와 상관해야 한다.",
    falsification_en: "If measured EMF exposure does not differ significantly between these groups, or if TFR differences are fully explained by other factors, the environmental χ coupling hypothesis is weakened.",
    falsification_fi: "Jos mitattu EMF-altistus ei eroa merkitsevästi näiden ryhmien välillä, tai TFR-erot selittyvät täysin muilla tekijöillä, ympäristön χ-kytkentähypoteesi heikentyy.",
    falsification_ja: "これらのグループ間でEMF曝露が有意に異ならない場合、またはTFR差が他の要因で完全に説明される場合、環境χ結合仮説は弱体化する。",
    falsification_fr: "Si l'exposition EMF mesurée ne diffère pas significativement entre ces groupes, ou si les différences de TFR sont entièrement expliquées par d'autres facteurs, l'hypothèse de couplage χ environnemental est affaiblie.",
    falsification_ko: "이 그룹 간 측정된 EMF 노출이 유의하게 다르지 않거나 TFR 차이가 다른 요인으로 완전히 설명되면 환경 χ 결합 가설은 약화된다.",
    level: "C",
    timeframe: "2–3 years",
  },
  {
    id: "hist3",
    code: "HIST-3",
    title_en: "COVID work-from-home baby bump mechanism",
    title_fi: "COVID-etätyön vauvapiikki-mekanismi",
    title_ja: "COVID在宅勤務ベビーブームメカニズム",
    title_fr: "Mécanisme du baby bump du télétravail COVID",
    title_ko: "COVID 재택근무 베이비붐 메커니즘",
    test_en: "The PNAS 2023 finding (+5.1% TFR for WFH women) should replicate specifically in populations with high χ_optical AND high pre-COVID χ_env. Populations with low optical χ (e.g., East Asia) should show smaller WFH baby bumps.",
    test_fi: "PNAS 2023 -löydös (+5,1 % TFR etätyöntekijänaisille) tulisi replikoitua erityisesti populaatioissa joilla on korkea χ_optinen JA korkea χ_env ennen COVIDia. Matalan optisen χ:n populaatioissa (esim. Itä-Aasia) vauvapiikkien tulisi olla pienempiä.",
    test_ja: "PNAS 2023の知見（在宅勤務女性でTFR +5.1%）は、高いχ_opticalかつ高いCOVID前χ_envの集団で特に再現されるはずである。光学的χが低い集団（例：東アジア）では在宅勤務ベビーブームはより小さいはずである。",
    test_fr: "La découverte du PNAS 2023 (+5,1 % de TFR pour les femmes en télétravail) devrait se répliquer spécifiquement dans les populations à χ_optique élevé ET χ_env pré-COVID élevé. Les populations à faible χ optique (ex. Asie de l'Est) devraient montrer des baby bumps de télétravail plus faibles.",
    test_ko: "PNAS 2023 발견(재택근무 여성의 TFR +5.1%)은 높은 χ_optical 및 높은 COVID 이전 χ_env를 가진 집단에서 특히 재현되어야 한다. 광학 χ가 낮은 집단(예: 동아시아)은 재택근무 베이비붐이 더 작아야 한다.",
    falsification_en: "If WFH baby bump is equal across populations regardless of χ profile, the coupling mechanism is not χ-dependent.",
    falsification_fi: "Jos etätyön vauvapiikki on yhtä suuri kaikissa populaatioissa riippumatta χ-profiilista, kytkentämekanismi ei ole χ-riippuvainen.",
    falsification_ja: "χプロファイルに関係なく在宅勤務ベビーブームが全集団で同等の場合、結合メカニズムはχ依存ではない。",
    falsification_fr: "Si le baby bump du télétravail est égal dans toutes les populations indépendamment du profil χ, le mécanisme de couplage n'est pas χ-dépendant.",
    falsification_ko: "χ 프로필과 관계없이 재택근무 베이비붐이 모든 집단에서 동일하면 결합 메커니즘은 χ 의존적이지 않다.",
    level: "C",
    timeframe: "1–3 years",
  },
  {
    id: "hist4",
    code: "HIST-4",
    title_en: "African TFR decline lag prediction",
    title_fi: "Afrikan TFR-laskun viive-ennuste",
    title_ja: "アフリカTFR低下ラグ予測",
    title_fr: "Prédiction du décalage de déclin du TFR africain",
    title_ko: "아프리카 TFR 감소 지연 예측",
    test_en: "As Sub-Saharan Africa electrifies, TFR decline should follow but at a SLOWER rate per unit χ_env increase compared to Northern Europe's historical trajectory. The predicted lag factor is 0.3–0.5× (based on the ratio of biological χ values).",
    test_fi: "Saharan eteläpuolisen Afrikan sähköistyessä TFR-laskun tulisi seurata mutta HITAAMMIN χ_env-yksikköä kohden verrattuna Pohjois-Euroopan historialliseen kehityskulkuun. Ennustettu viivekerroin on 0,3–0,5× (biologisten χ-arvojen suhteella).",
    test_ja: "サハラ以南アフリカの電化に伴いTFR低下は続くが、北欧の歴史的軌跡と比較してχ_env増加単位当たりのペースはより遅いはずである。予測ラグ係数は0.3〜0.5×（生物学的χ値の比に基づく）。",
    test_fr: "À mesure que l'Afrique subsaharienne s'électrifie, le déclin du TFR devrait suivre mais à un rythme PLUS LENT par unité d'augmentation de χ_env comparé à la trajectoire historique de l'Europe du Nord. Le facteur de décalage prédit est de 0,3–0,5× (basé sur le ratio des valeurs biologiques de χ).",
    test_ko: "사하라 이남 아프리카가 전화됨에 따라 TFR 감소는 뒤따르되 북유럽의 역사적 궤적에 비해 χ_env 증가 단위당 더 느린 속도여야 한다. 예측 지연 계수는 0.3~0.5×(생물학적 χ 값의 비율 기준)이다.",
    falsification_en: "If Africa's TFR decline rate matches or exceeds Northern Europe's at equivalent electrification levels, the biological χ modulation hypothesis is falsified.",
    falsification_fi: "Jos Afrikan TFR-laskuvauhti vastaa tai ylittää Pohjois-Euroopan vastaavaa samoilla sähköistystasoilla, biologisen χ-modulaation hypoteesi on falsifioitu.",
    falsification_ja: "アフリカのTFR低下率が同等の電化レベルで北欧と同等以上の場合、生物学的χ調節仮説は反証される。",
    falsification_fr: "Si le taux de déclin du TFR de l'Afrique égale ou dépasse celui de l'Europe du Nord à des niveaux d'électrification équivalents, l'hypothèse de modulation biologique χ est falsifiée.",
    falsification_ko: "아프리카의 TFR 감소율이 동등한 전화 수준에서 북유럽과 같거나 초과하면 생물학적 χ 조절 가설은 반증된다.",
    level: "L*",
    timeframe: "10–20 years",
  },
  {
    id: "hist5",
    code: "HIST-5",
    title_en: "Lactose intolerance as EMF resistance factor",
    title_fi: "Laktoosi-intoleranssi EMF-resistenssitekijänä",
    title_ja: "乳糖不耐性がEMF抵抗因子として機能",
    title_fr: "L'intolérance au lactose comme facteur de résistance aux EMF",
    title_ko: "유당 불내성이 EMF 저항 인자로 작용",
    test_en: "Within the same EMF environment, lactose-intolerant individuals should show lower CRY-mediated biomarker responses (melatonin suppression, circadian disruption) than lactose-tolerant individuals with similar diets supplemented with B2.",
    test_fi: "Samassa EMF-ympäristössä laktoosi-intoleranttien yksilöiden tulisi osoittaa matalampia CRY-välitteisiä biomarkkerivasteita (melatoniinin suppressio, sirkadiaaninen häiriö) kuin laktoosinsietokykyisten yksilöiden vastaavilla B2-täydennetyillä ruokavalioilla.",
    test_ja: "同一EMF環境内で、乳糖不耐性の個人はB2を補充した類似の食事を持つ乳糖耐性の個人よりも低いCRY媒介バイオマーカー応答（メラトニン抑制、概日リズム障害）を示すはずである。",
    test_fr: "Dans le même environnement EMF, les individus intolérants au lactose devraient montrer des réponses biomarqueurs médiées par CRY plus faibles (suppression de la mélatonine, perturbation circadienne) que les individus tolérants au lactose avec des régimes similaires supplémentés en B2.",
    test_ko: "동일한 EMF 환경에서 유당 불내성 개인은 B2가 보충된 유사한 식단을 가진 유당 내성 개인보다 낮은 CRY 매개 바이오마커 반응(멜라토닌 억제, 일주기 리듬 장애)을 보여야 한다.",
    falsification_en: "If lactose tolerance status has no effect on CRY-mediated biomarkers when B2 intake is controlled, the nutritional χ pathway is independent of lactase persistence.",
    falsification_fi: "Jos laktoosinsietokykystatuksella ei ole vaikutusta CRY-välitteisiin biomarkkereihin kun B2-saanti on kontrolloitu, ravitsemuksellinen χ-polku on riippumaton laktaasin pysyvyydestä.",
    falsification_ja: "B2摂取量を制御した場合に乳糖耐性ステータスがCRY媒介バイオマーカーに影響しなければ、栄養χ経路はラクターゼ持続性から独立している。",
    falsification_fr: "Si le statut de tolérance au lactose n'a aucun effet sur les biomarqueurs médiés par CRY lorsque l'apport en B2 est contrôlé, la voie χ nutritionnelle est indépendante de la persistance de la lactase.",
    falsification_ko: "B2 섭취를 통제했을 때 유당 내성 상태가 CRY 매개 바이오마커에 영향이 없으면 영양 χ 경로는 유당분해효소 지속성과 독립적이다.",
    level: "L*",
    timeframe: "2–4 years",
  },
  {
    id: "ep2",
    code: "E-P2",
    title_en: "CatSper IF-resonance frequency window",
    title_fi: "CatSper IF-resonanssitaajuusikkuna",
    title_ja: "CatSper IF共鳴周波数帯",
    title_fr: "Fenêtre de fréquence de résonance IF du CatSper",
    title_ko: "CatSper IF 공명 주파수 대역",
    test_en: "CatSper channels should show maximum disruption at specific IF frequencies (1–100 kHz range) where the channel's voltage-sensing domain resonates. In-vitro patch-clamp studies at graded IF frequencies should reveal a non-monotonic dose-response with a peak disruption frequency predictable from the channel's gating charge displacement.",
    test_fi: "CatSper-kanavien tulisi osoittaa maksimaalinen häiriö tietyillä IF-taajuuksilla (1–100 kHz -alue), joilla kanavan jänniteanturidomeeni resonoi. In vitro -patch-clamp-tutkimusten porrastetulla IF-taajuudella tulisi paljastaa ei-monotoninen annosvasteen huippu, joka on ennustettavissa kanavan varausdynamiikasta.",
    test_ja: "CatSperチャネルは、チャネルの電圧感知ドメインが共鳴する特定のIF周波数（1〜100 kHz範囲）で最大の破壊を示すはずである。段階的IF周波数でのin vitroパッチクランプ研究で、チャネルのゲーティング電荷変位から予測可能なピーク破壊周波数を持つ非単調な用量反応が明らかになるはずである。",
    test_fr: "Les canaux CatSper devraient montrer une perturbation maximale à des fréquences IF spécifiques (gamme 1–100 kHz) où le domaine de détection de tension du canal entre en résonance. Des études de patch-clamp in vitro à des fréquences IF graduées devraient révéler une réponse dose non monotone avec une fréquence de perturbation maximale prédictible à partir du déplacement de charge du canal.",
    test_ko: "CatSper 채널은 채널의 전압 감지 도메인이 공명하는 특정 IF 주파수(1-100 kHz 범위)에서 최대 교란을 보여야 한다. 단계적 IF 주파수에서의 in vitro 패치 클램프 연구는 채널의 게이팅 전하 변위로부터 예측 가능한 피크 교란 주파수를 가진 비단조 용량 반응을 밝혀야 한다.",
    falsification_en: "If CatSper disruption scales monotonically with IF frequency (no resonance peak), the channel lacks a frequency-selective vulnerability and the IF-specific prediction fails.",
    falsification_fi: "Jos CatSper-häiriö skaalautuu monotonisesti IF-taajuuden kanssa (ei resonanssihuippua), kanavalla ei ole taajuustarkkaa haavoittuvuutta ja IF-tarkka ennuste epäonnistuu.",
    falsification_ja: "CatSperの破壊がIF周波数に対して単調にスケールする場合（共鳴ピークなし）、チャネルには周波数選択的脆弱性がなく、IF固有の予測は失敗する。",
    falsification_fr: "Si la perturbation de CatSper évolue de manière monotone avec la fréquence IF (pas de pic de résonance), le canal manque de vulnérabilité sélective en fréquence et la prédiction spécifique IF échoue.",
    falsification_ko: "CatSper 교란이 IF 주파수에 대해 단조롭게 스케일링되면(공명 피크 없음) 채널에는 주파수 선택적 취약성이 없으며 IF 특정 예측은 실패한다.",
    level: "L*",
    timeframe: "2–5 years",
  },
  {
    id: "ep5",
    code: "E-P5",
    title_en: "Phone-in-pocket sperm navigation deficit",
    title_fi: "Puhelin taskussa -siittiönavigoinnin vajaus",
    title_ja: "ポケット内携帯電話による精子ナビゲーション障害",
    title_fr: "Déficit de navigation des spermatozoïdes lié au téléphone en poche",
    title_ko: "주머니 속 휴대폰에 의한 정자 항행 결함",
    test_en: "Men who carry a phone in their front trouser pocket for >4 hours/day should show statistically significant deficits in CatSper-dependent sperm functions (rheotaxis, chemotaxis, hyperactivation) compared to matched controls, even when total sperm count and motility grade remain within WHO normal ranges. The deficit should be detectable by progesterone-induced Ca²⁺ response assay.",
    test_fi: "Miehillä, jotka kantavat puhelinta etutaskussaan >4 tuntia/päivä, tulisi olla tilastollisesti merkitseviä vajeita CatSper-riippuvaisissa siittiötoiminnoissa (reotaksis, kemotaksis, hyperaktivaatio) verrattuna kontrolliryhmään, vaikka kokonaissiittiömäärä ja motiliteettiluokka pysyisivät WHO:n normaaliarvioissa. Vaje tulisi olla havaittavissa progesterooni-indusoidulla Ca²⁺-vastekokeella.",
    test_ja: "前ズボンポケットに4時間/日以上携帯電話を持ち歩く男性は、総精子数と運動性グレードがWHO正常範囲内であっても、CatSper依存性精子機能（レオタキシス、走化性、過活性化）において統計的に有意な欠損を対照群と比較して示すはずである。この欠損はプロゲステロン誘導Ca²⁺応答アッセイで検出可能であるはず。",
    test_fr: "Les hommes portant un téléphone dans la poche avant du pantalon pendant >4 heures/jour devraient montrer des déficits statistiquement significatifs dans les fonctions spermatiques dépendantes de CatSper (rhéotaxie, chimiotaxie, hyperactivation) par rapport aux témoins appariés, même lorsque le nombre total et la motilité restent dans les normes OMS. Le déficit devrait être détectable par un test de réponse Ca²⁺ induit par la progestérone.",
    test_ko: "앞주머니에 하루 4시간 이상 휴대폰을 지참하는 남성은 총 정자 수와 운동성 등급이 WHO 정상 범위 내에 있더라도 대조군에 비해 CatSper 의존성 정자 기능(유변주성, 주화성, 과활성화)에서 통계적으로 유의한 결함을 보여야 한다. 이 결함은 프로게스테론 유도 Ca²⁺ 반응 분석으로 검출 가능해야 한다.",
    falsification_en: "If phone-carrying men show identical progesterone-induced Ca²⁺ responses and hyperactivation rates as non-carriers after controlling for confounders, pocket RF exposure does not affect CatSper function in vivo.",
    falsification_fi: "Jos puhelinta kantavien miesten progesterooni-indusoidut Ca²⁺-vasteet ja hyperaktivaatioasteet ovat identtiset ei-kantajien kanssa sekoittavien tekijöiden kontrolloinnin jälkeen, taskun RF-altistus ei vaikuta CatSper-toimintaan in vivo.",
    falsification_ja: "携帯電話所持男性が交絡因子を制御した後に非所持者と同一のプロゲステロン誘導Ca²⁺応答と過活性化率を示す場合、ポケットRF曝露はin vivoでCatSper機能に影響しない。",
    falsification_fr: "Si les hommes portant un téléphone montrent des réponses Ca²⁺ induites par la progestérone et des taux d'hyperactivation identiques aux non-porteurs après contrôle des facteurs confondants, l'exposition RF de poche n'affecte pas la fonction CatSper in vivo.",
    falsification_ko: "교란 요인을 통제한 후 휴대폰 소지 남성이 비소지자와 동일한 프로게스테론 유도 Ca²⁺ 반응과 과활성화율을 보이면 주머니 RF 노출은 in vivo에서 CatSper 기능에 영향을 미치지 않는다.",
    level: "C",
    timeframe: "1–3 years",
  },
  {
    id: "es1",
    code: "E-S1",
    title_en: "Whale stranding baseline rise tracks anthropogenic RF",
    title_fi: "Valaidenrantautumisen perustason nousu seuraa antropogeenista RF:ää",
    title_ja: "クジラ座礁のベースライン上昇は人為的RF追跡",
    title_fr: "L'augmentation du taux d'échouage des baleines suit les RF anthropiques",
    title_ko: "고래 좌초 기준선 상승이 인위적 RF를 추적",
    test_en: "Global cetacean mass stranding events per decade should show a statistically significant increase from the 1950s baseline correlating with cumulative coastal RF infrastructure (r > 0.7), independent of reporting bias (controlled by stranding network coverage expansion).",
    test_fi: "Maailmanlaajuisten valaiden joukkorantautumisten määrä vuosikymmenessä tulisi osoittaa tilastollisesti merkitsevä nousu 1950-luvun perustasolta, korreloiden kumulatiivisen rannikko-RF-infrastruktuurin kanssa (r > 0.7), raportointiharhan vaikutus kontrolloituna.",
    test_ja: "10年あたりの世界的な鯨類集団座礁事件は、累積沿岸RFインフラと相関する1950年代のベースラインからの統計的に有意な増加を示すべきである（r > 0.7）。報告バイアスは座礁ネットワークの拡大で制御。",
    test_fr: "Le nombre d'échouages massifs de cétacés par décennie devrait montrer une augmentation statistiquement significative par rapport au niveau de base des années 1950, corrélée avec l'infrastructure RF côtière cumulative (r > 0,7), indépendamment du biais de signalement.",
    test_ko: "10년당 세계 고래류 집단 좌초 사건은 누적 해안 RF 인프라와 상관관계를 보이며 1950년대 기준선에서 통계적으로 유의한 증가를 보여야 한다(r > 0.7). 보고 편향은 좌초 네트워크 확대로 통제.",
    falsification_en: "If stranding events show no increase above historical baseline after controlling for reporting expansion and climate variables, anthropogenic RF is not a driver of cetacean navigation failure.",
    falsification_fi: "Jos rantautumistapahtumat eivät osoita nousua historiallisen perustason yläpuolelle raportointilaajenemisen ja ilmastomuuttujien kontrolloinnin jälkeen, antropogeeninen RF ei aiheuta valaiden navigointivirheitä.",
    falsification_ja: "報告拡大と気候変数を制御した後、座礁事件が歴史的ベースラインを超える増加を示さない場合、人為的RFは鯨類のナビゲーション障害の原因ではない。",
    falsification_fr: "Si les échouages ne montrent aucune augmentation au-dessus du niveau historique après contrôle de l'expansion du réseau de signalement et des variables climatiques, les RF anthropiques ne sont pas responsables des défaillances de navigation des cétacés.",
    falsification_ko: "보고 확대와 기후 변수를 통제한 후 좌초 사건이 역사적 기준선 이상의 증가를 보이지 않으면 인위적 RF는 고래류 항행 장애의 원인이 아니다.",
    level: "M|C",
    timeframe: "3–5 years",
  },
  {
    id: "es2",
    code: "E-S2",
    title_en: "Granger causality: coastal RF density → cetacean stranding rate",
    title_fi: "Granger-kausaliteetti: rannikko-RF-tiheys → valaiden rantautumisaste",
    title_ja: "グランジャー因果性：沿岸RF密度→鯨類座礁率",
    title_fr: "Causalité de Granger : densité RF côtière → taux d'échouage des cétacés",
    title_ko: "그랜저 인과성: 해안 RF 밀도 → 고래류 좌초율",
    test_en: "Time-lagged Granger causality analysis should detect a statistically significant effect of regional coastal RF infrastructure density on cetacean stranding rates with a 1–3 year lag, consistent with cumulative magnetoreception disruption rather than acute exposure.",
    test_fi: "Aikaviivästetyn Granger-kausaliteettianalyysin tulisi havaita tilastollisesti merkitsevä alueellisen rannikko-RF-infrastruktuuritiheyden vaikutus valaiden rantautumisasteeseen 1–3 vuoden viiveellä, yhteensopiva kumulatiivisen magnetoreseptiohäiriön kanssa.",
    test_ja: "時間遅延グランジャー因果分析により、地域沿岸RFインフラ密度が鯨類座礁率に1〜3年の遅延で統計的に有意な影響を検出すべきである。急性曝露ではなく累積磁気受容障害と一致。",
    test_fr: "L'analyse de causalité de Granger avec décalage temporel devrait détecter un effet statistiquement significatif de la densité d'infrastructure RF côtière régionale sur les taux d'échouage des cétacés avec un décalage de 1 à 3 ans.",
    test_ko: "시간 지연 그랜저 인과 분석은 지역 해안 RF 인프라 밀도가 고래류 좌초율에 1-3년 지연으로 통계적으로 유의한 영향을 감지해야 한다. 급성 노출이 아닌 누적 자기수용 장애와 일치.",
    falsification_en: "If Granger analysis shows no directional causality from RF density to stranding rates in any ocean basin, the RF-magnetoreception link is not supported at the population level.",
    falsification_fi: "Jos Granger-analyysi ei osoita suuntakausaliteettia RF-tiheydestä rantautumisasteeseen millään valtamerialueella, RF-magnetoreseptioyhteyttä ei tueta populaatiotasolla.",
    falsification_ja: "いずれの海域でもRF密度から座礁率への方向性因果が検出されない場合、RF-磁気受容リンクは集団レベルで支持されない。",
    falsification_fr: "Si l'analyse de Granger ne montre aucune causalité directionnelle de la densité RF vers les taux d'échouage dans aucun bassin océanique, le lien RF-magnétoréception n'est pas soutenu au niveau populationnel.",
    falsification_ko: "어떤 해양 분지에서도 RF 밀도에서 좌초율로의 방향 인과가 감지되지 않으면 RF-자기수용 연결은 개체군 수준에서 지지되지 않는다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "es3",
    code: "E-S3",
    title_en: "Granger effect attenuates with χ(A) derivative distance",
    title_fi: "Granger-vaikutus vaimenee χ(A)-derivaattaetäisyyden myötä",
    title_ja: "グランジャー効果はχ(A)導関数距離で減衰",
    title_fr: "L'effet Granger s'atténue avec la distance dérivée χ(A)",
    title_ko: "그랜저 효과가 χ(A) 도함수 거리에 따라 감쇠",
    test_en: "The Granger effect size from E-S2 should attenuate monotonically with increasing distance from the nearest RF source, following the χ(A) coupling derivative (inverse-square or faster decay). Coastal strandings near major RF installations should show stronger temporal coupling than remote locations.",
    test_fi: "E-S2:n Granger-vaikutuskoon tulisi vaimentua monotonisesti etäisyyden kasvaessa lähimmästä RF-lähteestä, seuraten χ(A)-kytkentäderivaattaa. Rannikkorantautumiset suurten RF-laitosten lähellä osoittavat vahvempaa ajallista kytkentää kuin syrjäiset sijainnit.",
    test_ja: "E-S2のグランジャー効果量は最寄りRF源からの距離増大に伴いχ(A)結合導関数に従い単調に減衰すべきである。主要RF設備近くの沿岸座礁はより強い時間的結合を示すはず。",
    test_fr: "L'amplitude de l'effet Granger de E-S2 devrait s'atténuer de manière monotone avec la distance croissante de la source RF la plus proche, suivant la dérivée de couplage χ(A). Les échouages côtiers près des grandes installations RF devraient montrer un couplage temporel plus fort.",
    test_ko: "E-S2의 그랜저 효과 크기는 가장 가까운 RF 원으로부터의 거리 증가에 따라 χ(A) 결합 도함수를 따라 단조 감쇠해야 한다. 주요 RF 시설 근처 해안 좌초가 더 강한 시간적 결합을 보여야 한다.",
    falsification_en: "If Granger effect size is independent of distance to RF sources (no spatial gradient), the stranding correlation is coincidental rather than mechanistic.",
    falsification_fi: "Jos Granger-vaikutuskoko on riippumaton etäisyydestä RF-lähteisiin (ei spatiaalista gradienttia), rantautumiskorrelaatio on satunnaista eikä mekanistista.",
    falsification_ja: "グランジャー効果量がRF源からの距離に無関係（空間勾配なし）であれば、座礁相関は偶発的であり機構的ではない。",
    falsification_fr: "Si l'amplitude de l'effet Granger est indépendante de la distance aux sources RF (pas de gradient spatial), la corrélation d'échouage est fortuite et non mécanistique.",
    falsification_ko: "그랜저 효과 크기가 RF 원으로부터의 거리와 무관하면(공간 기울기 없음) 좌초 상관은 메커니즘적이 아니라 우연이다.",
    level: "L*",
    timeframe: "5–10 years",
  },
  {
    id: "es4",
    code: "E-S4",
    title_en: "Submarine cable ELF → aquatic CatSper reproductive decline",
    title_fi: "Merenalaiset kaapelit ELF → vesieliöiden CatSper-lisääntymishäiriö",
    title_ja: "海底ケーブルELF→水生CatSper生殖低下",
    title_fr: "ELF des câbles sous-marins → déclin reproductif aquatique via CatSper",
    title_ko: "해저 케이블 ELF → 수생 CatSper 생식 감소",
    test_en: "Marine species with CatSper-dependent fertilization (sea urchins, fish, marine mammals) near high-power submarine cable corridors should show measurable reproductive parameter declines compared to populations distant from cables. ELF field measurements at cable crossings should exceed the CatSper activation threshold identified in vitro.",
    test_fi: "CatSper-riippuvaisen hedelmöityksen omaavien merieliölajien (merisiilit, kalat, merieläimet) tulisi osoittaa mitattavia lisääntymisparametrien laskuja korkeateholisten merenalaisten kaapelikäytävien lähellä verrattuna kaapeleista etäällä oleviin populaatioihin.",
    test_ja: "高電力海底ケーブル回廊付近のCatSper依存受精を持つ海洋種（ウニ、魚類、海洋哺乳類）は、ケーブルから離れた集団と比較して測定可能な生殖パラメータ低下を示すべきである。",
    test_fr: "Les espèces marines à fécondation CatSper-dépendante (oursins, poissons, mammifères marins) près des corridors de câbles sous-marins à haute puissance devraient montrer des déclins mesurables des paramètres reproductifs par rapport aux populations éloignées des câbles.",
    test_ko: "고전력 해저 케이블 회랑 근처의 CatSper 의존 수정을 가진 해양 종(성게, 어류, 해양 포유류)은 케이블에서 먼 개체군에 비해 측정 가능한 생식 매개변수 감소를 보여야 한다.",
    falsification_en: "If marine populations near submarine cables show identical reproductive parameters to those in cable-free zones, ELF fields from cables do not disrupt aquatic CatSper function.",
    falsification_fi: "Jos merikaapelien läheiset merieliöpopulaatiot osoittavat identtiset lisääntymisparametrit kaapelittomien alueiden kanssa, kaapeleiden ELF-kentät eivät häiritse vesieliöiden CatSper-toimintaa.",
    falsification_ja: "海底ケーブル付近の海洋集団がケーブルのない地域と同一の生殖パラメータを示す場合、ケーブルからのELF場は水生CatSper機能を障害しない。",
    falsification_fr: "Si les populations marines près des câbles montrent des paramètres reproductifs identiques à celles des zones sans câble, les champs ELF des câbles ne perturbent pas la fonction CatSper aquatique.",
    falsification_ko: "해저 케이블 근처 해양 개체군이 케이블 없는 지역과 동일한 생식 매개변수를 보이면 케이블의 ELF 장은 수생 CatSper 기능을 방해하지 않는다.",
    level: "L*",
    timeframe: "5–10 years",
  },
  {
    id: "es5",
    code: "E-S5",
    title_en: "Farmed salmon CatSper weaker than wild salmon",
    title_fi: "Viljellyn lohen CatSper heikompi kuin villin lohen",
    title_ja: "養殖サーモンのCatSperは天然サーモンより弱い",
    title_fr: "CatSper du saumon d'élevage plus faible que celui du saumon sauvage",
    title_ko: "양식 연어 CatSper가 야생 연어보다 약함",
    test_en: "Atlantic salmon from high-EMF aquaculture environments (electrified feeding systems, underwater sensors, RF-emitting monitoring equipment) should show reduced CatSper-dependent sperm function compared to wild-caught or low-EMF farmed salmon. Specifically: progesterone-induced Ca²⁺ response amplitude, rheotaxis performance, and fertilization rate should be measurably lower.",
    test_fi: "Korkean EMF:n vesiviljelyympäristöistä (sähköistetyt ruokintajärjestelmät, vedenalaiset sensorit) peräisin olevan atlantinlohen tulisi osoittaa heikentynyttä CatSper-riippuvaista siittiötoimintaa verrattuna villiin tai matalan EMF:n viljeltyyn loheen.",
    test_ja: "高EMF養殖環境（電気化給餌システム、水中センサー）の大西洋サーモンは、天然捕獲または低EMF養殖サーモンと比較してCatSper依存性精子機能の低下を示すべきである。",
    test_fr: "Le saumon atlantique d'environnements d'aquaculture à forte EMF devrait montrer une fonction spermatique CatSper-dépendante réduite par rapport au saumon sauvage ou d'élevage à faible EMF.",
    test_ko: "고EMF 양식 환경(전기화 급이 시스템, 수중 센서)의 대서양 연어는 야생 또는 저EMF 양식 연어에 비해 CatSper 의존성 정자 기능 저하를 보여야 한다.",
    falsification_en: "If farmed and wild salmon show equivalent CatSper function and fertilization rates regardless of aquaculture EMF levels, chronic environmental EMF does not compromise salmon CatSper.",
    falsification_fi: "Jos viljelty ja villi lohi osoittavat vastaavan CatSper-toiminnan ja hedelmöitysasteet vesiviljelyympäristön EMF-tasoista riippumatta, krooninen ympäristön EMF ei heikennä lohen CatSper-toimintaa.",
    falsification_ja: "養殖と天然サーモンが養殖EMFレベルに関係なく同等のCatSper機能と受精率を示す場合、慢性環境EMFはサーモンのCatSperを損なわない。",
    falsification_fr: "Si le saumon d'élevage et sauvage montrent une fonction CatSper et des taux de fécondation équivalents quels que soient les niveaux EMF d'aquaculture, l'EMF environnementale chronique ne compromet pas le CatSper du saumon.",
    falsification_ko: "양식 및 야생 연어가 양식 EMF 수준에 관계없이 동등한 CatSper 기능과 수정율을 보이면 만성 환경 EMF는 연어 CatSper를 손상시키지 않는다.",
    level: "L*",
    timeframe: "3–5 years",
  },
  {
    id: "solar-1-amish-periodicity",
    code: "SOLAR-1",
    title_en: "Amish birth rate shows ~11-year periodicity correlated with sunspot number",
    title_fi: "Amish-syntyvyys osoittaa ~11-vuoden jaksottomuutta korreloiden auringonpilkkuluvun kanssa",
    title_ja: "アーミッシュの出生率は太陽黒点数と相関する約11年の周期性を示す",
    title_fr: "Le taux de natalité amish montre une périodicité d'environ 11 ans corrélée avec le nombre de taches solaires",
    title_ko: "아미시 출생률은 태양흑점수와 상관하는 약 11년 주기성을 보인다",
    test_en: "Analyze Old Order Amish birth records (Lancaster, Holmes counties) for 11-year periodicity using spectral analysis. Amish TFR is flat (no secular decline), so any solar cycle signal tests chi_B independently of chi(A-bar).",
    test_fi: "Analysoi vanhan järjestyksen amish-syntyvyystiedot (Lancaster, Holmes) spektrianalyysillä. Amish-TFR on tasainen (ei sekulaarista laskua), joten aurinkosyklisignaali testaa chi_B:tä riippumatta chi(Ā):sta.",
    test_ja: "ランカスター郡・ホームズ郡のオールドオーダー・アーミッシュの出生記録をスペクトル解析で分析。アーミッシュのTFRは横ばい（長期的低下なし）であるため、太陽周期信号はχ(Ā)とは独立にχ_Bを検証する。",
    test_fr: "Analyser les registres de naissance des Amish (comtés de Lancaster, Holmes) par analyse spectrale. Le TFR amish est stable (pas de déclin séculaire), donc tout signal du cycle solaire teste χ_B indépendamment de χ(Ā).",
    test_ko: "올드오더 아미시 출생 기록(랭커스터, 홈즈 카운티)을 스펙트럼 분석으로 분석. 아미시 TFR은 평탄하여(장기 감소 없음) 태양 주기 신호가 χ(Ā)와 독립적으로 χ_B를 검증한다.",
    falsification_en: "No significant periodicity in the 8-14 year band in Amish birth data (p > 0.05), or periodicity present but not correlated with SSN.",
    falsification_fi: "Ei merkittävää jaksottomuutta 8-14 vuoden kaistalla amish-syntyvyysdatassa (p > 0.05), tai jaksottomuus ei korreloi SSN:n kanssa.",
    falsification_ja: "アーミッシュの出生データに8-14年帯域で有意な周期性なし（p > 0.05）、または周期性がSSNと相関しない。",
    falsification_fr: "Pas de périodicité significative dans la bande 8-14 ans dans les données de naissance amish (p > 0,05), ou périodicité non corrélée avec le SSN.",
    falsification_ko: "아미시 출생 데이터에서 8-14년 대역의 유의한 주기성 없음(p > 0.05), 또는 주기성이 SSN과 상관하지 않음.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "solar-2-nordic-stronger",
    code: "SOLAR-2",
    title_en: "Nordic countries show stronger solar cycle-birth rate correlation than Southern Europe",
    title_fi: "Pohjoismaat osoittavat voimakkaamman aurinkosykli-syntyvyyskorrelaation kuin Etelä-Eurooppa",
    title_ja: "北欧諸国は南欧より強い太陽周期-出生率相関を示す",
    title_fr: "Les pays nordiques montrent une corrélation cycle solaire-natalité plus forte que l'Europe du Sud",
    title_ko: "북유럽 국가는 남유럽보다 강한 태양주기-출생률 상관을 보인다",
    test_en: "Compare bandpass-filtered (8-14yr) SSN-CBR correlation: r_Nordic (Finland, Sweden, Norway) vs r_Southern (Spain, Italy, Greece). Northern Package populations have higher chi_optical, chi_molecular, and chi_geomagnetic.",
    test_fi: "Vertaa kaistanpäästösuodatettua (8-14v) SSN-CBR-korrelaatiota: r_Pohjoismaat (Suomi, Ruotsi, Norja) vs r_Etelä (Espanja, Italia, Kreikka). Pohjoinen paketti -populaatioilla korkeampi chi_optinen, chi_molekulaarinen ja chi_geomagneettinen.",
    test_ja: "バンドパスフィルタ（8-14年）SSN-CBR相関を比較：r_北欧（フィンランド、スウェーデン、ノルウェー）対 r_南欧（スペイン、イタリア、ギリシャ）。北部パッケージ集団はχ_光学、χ_分子、χ_地磁気がより高い。",
    test_fr: "Comparer la corrélation SSN-CBR filtrée passe-bande (8-14 ans) : r_Nordique (Finlande, Suède, Norvège) vs r_Sud (Espagne, Italie, Grèce). Les populations du Package Nordique ont des χ_optique, χ_moléculaire et χ_géomagnétique plus élevés.",
    test_ko: "밴드패스 필터(8-14년) SSN-CBR 상관 비교: r_북유럽(핀란드, 스웨덴, 노르웨이) 대 r_남유럽(스페인, 이탈리아, 그리스). 북부 패키지 인구는 χ_광학, χ_분자, χ_지자기가 더 높다.",
    falsification_en: "r_Nordic ≤ r_Southern in bandpass analysis, or no significant difference between groups.",
    falsification_fi: "r_Pohjoismaat ≤ r_Etelä kaistanpäästöanalyysissä, tai ryhmien välillä ei merkittävää eroa.",
    falsification_ja: "バンドパス分析でr_北欧 ≤ r_南欧、または群間に有意差なし。",
    falsification_fr: "r_Nordique ≤ r_Sud dans l'analyse passe-bande, ou pas de différence significative entre les groupes.",
    falsification_ko: "밴드패스 분석에서 r_북유럽 ≤ r_남유럽, 또는 그룹 간 유의한 차이 없음.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "solar-3-eye-season-interaction",
    code: "SOLAR-3",
    title_en: "Blue-eyed individuals show stronger season-of-birth effect on puberty timing than brown-eyed",
    title_fi: "Sinisisilmäisillä voimakkaampi syntymäkauden vaikutus puberteetin ajoitukseen kuin ruskeasilmäisillä",
    title_ja: "青い目の人は茶色い目の人より強い出生季節-思春期タイミング効果を示す",
    title_fr: "Les individus aux yeux bleus montrent un effet plus fort de la saison de naissance sur le timing pubertaire",
    title_ko: "파란 눈의 사람은 갈색 눈보다 강한 출생계절-사춘기 시기 효과를 보인다",
    test_en: "UK Biobank reanalysis: stratify Perry 2015 season-of-birth → puberty timing effect by eye color. BERM predicts blue-eyed (high chi_optical) show larger seasonal amplitude because CRY responds more to photoperiod variation.",
    test_fi: "UK Biobank -uudelleenanalyysi: ositeta Perry 2015:n syntymäkausi → puberteetin ajoitus -vaikutus silmien värin mukaan. BERM ennustaa sinisisilmäisten (korkea chi_optinen) osoittavan suuremman kausittaisen amplitudin koska CRY reagoi enemmän valojakson vaihteluun.",
    test_ja: "UK Biobank再解析：Perry 2015の出生季節→思春期タイミング効果を目の色で層別化。BERMは青い目（高いχ_光学）がCRYの光周期変動への応答が大きいため、より大きな季節振幅を示すと予測。",
    test_fr: "Réanalyse UK Biobank : stratifier l'effet saison de naissance → timing pubertaire de Perry 2015 par couleur des yeux. BERM prédit que les yeux bleus (χ_optique élevé) montrent une plus grande amplitude saisonnière car CRY répond davantage à la variation photopériodique.",
    test_ko: "UK Biobank 재분석: Perry 2015의 출생계절→사춘기 시기 효과를 눈 색깔로 층화. BERM은 파란 눈(높은 χ_광학)이 CRY의 광주기 변동 반응이 크기 때문에 더 큰 계절 진폭을 보인다고 예측.",
    falsification_en: "No significant eye color × season interaction on puberty timing, or brown-eyed show equal or larger effect.",
    falsification_fi: "Ei merkittävää silmien väri × kausi -vuorovaikutusta puberteetin ajoituksessa, tai ruskeasilmäisillä yhtä suuri tai suurempi vaikutus.",
    falsification_ja: "思春期タイミングに目の色×季節の有意な交互作用なし、または茶色い目で同等以上の効果。",
    falsification_fr: "Pas d'interaction significative couleur des yeux × saison sur le timing pubertaire, ou les yeux bruns montrent un effet égal ou supérieur.",
    falsification_ko: "사춘기 시기에 눈 색깔×계절의 유의한 교호작용 없음, 또는 갈색 눈에서 동등 이상의 효과.",
    level: "L*",
    timeframe: "1-3 years",
  },
  {
    id: "solar-4-sama-fertility",
    code: "SOLAR-4",
    title_en: "SAMA region shows inverted or absent solar cycle modulation of fertility",
    title_fi: "SAMA-alue osoittaa kääntyneen tai puuttuvan aurinkosyklimodulaation hedelmällisyydessä",
    title_ja: "SAMA地域は逆転したまたは欠如した出生率の太陽周期変調を示す",
    title_fr: "La région SAMA montre une modulation inversée ou absente du cycle solaire sur la fertilité",
    title_ko: "SAMA 지역은 출산율의 역전된 또는 부재하는 태양주기 변조를 보인다",
    test_en: "Analyze Brazilian southern states (under SAMA: field ~24 μT) birth rate vs SSN correlation. BERM predicts inverted or null correlation compared to non-SAMA countries, consistent with altered geomagnetic geometry distorting CRY signal reading.",
    test_fi: "Analysoi Brasilian eteläisten osavaltioiden (SAMA:n alla: kenttä ~24 μT) syntyvyys vs SSN -korrelaatio. BERM ennustaa kääntyneen tai nollakorrelaation verrattuna ei-SAMA-maihin, johdonmukaisesti muuttuneen geomagneettisen geometrian vääristäessä CRY-signaalin lukemista.",
    test_ja: "ブラジル南部州（SAMA下：場約24μT）の出生率対SSN相関を分析。BERMは非SAMA国と比較して逆転またはゼロの相関を予測。これは変化した地磁気幾何学がCRY信号読み取りを歪めることと一致する。",
    test_fr: "Analyser la corrélation natalité vs SSN des états brésiliens du sud (sous SAMA : champ ~24 μT). BERM prédit une corrélation inversée ou nulle par rapport aux pays non-SAMA, cohérente avec la géométrie géomagnétique altérée déformant la lecture du signal CRY.",
    test_ko: "브라질 남부 주(SAMA 하: 장 약24μT)의 출생률 대 SSN 상관을 분석. BERM은 비SAMA 국가와 비교하여 역전 또는 영 상관을 예측. 이는 변화된 지자기 기하학이 CRY 신호 판독을 왜곡하는 것과 일치.",
    falsification_en: "SAMA region shows same-sign and comparable-magnitude solar cycle-fertility correlation as non-SAMA countries at similar latitudes.",
    falsification_fi: "SAMA-alue osoittaa samanmerkkisen ja vertailukelpoisen suuruusluokan aurinkosykli-hedelmällisyyskorrelaation kuin ei-SAMA-maat vastaavilla leveysasteilla.",
    falsification_ja: "SAMA地域が同緯度の非SAMA国と同符号・同程度の太陽周期-出生率相関を示す。",
    falsification_fr: "La région SAMA montre une corrélation cycle solaire-fertilité de même signe et magnitude comparable aux pays non-SAMA à des latitudes similaires.",
    falsification_ko: "SAMA 지역이 유사 위도의 비SAMA 국가와 같은 부호·비슷한 크기의 태양주기-출산율 상관을 보임.",
    level: "L*",
    timeframe: "3-5 years",
  },
  {
    id: "mast-solar-1",
    code: "MAST-SOLAR-1",
    title_en: "Masting–Solar Cycle Correlation",
    title_fi: "Masting–aurinkosyklkorrelaatio",
    title_ja: "マスティング-太陽周期相関",
    title_fr: "Corrélation masting-cycle solaire",
    title_ko: "마스팅-태양주기 상관",
    test_en: "European beech masting synchrony (Bogdziewicz 2024) should show ~11-year periodicity in Fourier analysis when controlled for temperature and photoperiod. The solar cycle modulates geomagnetic field which modulates CRY2 sensitivity threshold.",
    test_fi: "Eurooppalaisen pyökin masting-synkronian (Bogdziewicz 2024) tulisi näyttää ~11 vuoden periodisuutta Fourier-analyysissä, kun lämpötila ja valojakso vakioidaan. Aurinkosykli säätelee geomagneettista kenttää, joka säätelee CRY2:n herkkyyskynnystä.",
    test_ja: "ヨーロッパブナのマスティング同期は太陽周期と相関するはず",
    test_fr: "La synchronie du masting du hêtre devrait montrer une périodicité ~11 ans",
    test_ko: "유럽 너도밤나무 마스팅 동기화는 ~11년 주기성을 보여야 함",
    falsification_en: "If beech masting synchrony (Bogdziewicz 2024 series) shows no ~11-year spectral peak after temperature and photoperiod are partialled out, or if the peak disappears when geomagnetic activity (aa/Kp) is added as a covariate while temperature alone explains it, the solar–CRY2 coupling is falsified.",
    falsification_fi: "Jos pyökin siemensadon synkronia (Bogdziewicz 2024 -sarja) ei osoita ~11 vuoden spektripiikkiä lämpötilan ja valojakson osittamisen jälkeen, tai jos piikki katoaa kun geomagneettinen aktiivisuus (aa/Kp) lisätään kovariaatiksi ja lämpötila yksin selittää sen, aurinko–CRY2-kytkentä on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["masting", "solar_cycle", "beech", "CRY2", "periodicity"],
  },
  {
    id: "mast-rf-1",
    code: "MAST-RF-1",
    title_en: "RF Background Disrupts Masting Synchrony",
    title_fi: "RF-tausta häiritsee masting-synkroniaa",
    title_ja: "RF背景がマスティング同期を乱す",
    title_fr: "Le bruit de fond RF perturbe la synchronie du masting",
    title_ko: "RF 배경이 마스팅 동기화를 방해",
    test_en: "Bogdziewicz 2021 found weakening masting synchrony attributed to 'climate change.' BERM predicts: the weakening correlates better with RF background growth (mobile network rollout 1990s→2020s) than with temperature trends alone. CRY2-mediated photoperiod sensing is disrupted by RF, analogous to Ahmad 2020 in Arabidopsis.",
    test_fi: "Bogdziewicz 2021 havaitsi masting-synkronian heikkenemisen, joka attribuoitiin ilmastonmuutokselle. BERM ennustaa: heikkeneminen korreloi paremmin RF-taustan kasvun (matkapuhelinverkkojen leviäminen 1990-luku→2020-luku) kuin pelkän lämpötilatrendin kanssa. CRY2-välitteinen valojakson aistiminen häiriintyy RF:stä, analogisesti Ahmad 2020 Arabidopsis-tulosten kanssa.",
    test_ja: "マスティング同期の弱体化はRF背景の成長とよく相関するはず",
    test_fr: "L'affaiblissement de la synchronie du masting corrèle mieux avec la croissance du bruit RF",
    test_ko: "마스팅 동기화 약화는 RF 배경 성장과 더 잘 상관해야 함",
    falsification_en: "If the weakening of masting synchrony (Bogdziewicz 2021) is explained by temperature trends alone and adds no variance to RF-background growth (mobile-network rollout 1990s→2020s), or if sites with equal warming but different RF density show identical synchrony loss, the RF–CRY2 explanation is falsified.",
    falsification_fi: "Jos siemensadon synkronian heikkeneminen (Bogdziewicz 2021) selittyy pelkillä lämpötilatrendeillä eikä RF-taustan kasvu (mobiiliverkkojen rakentaminen 1990–2020-luvuilla) lisää selitysastetta, tai jos yhtä paljon lämmenneet mutta RF-tiheydeltään erilaiset alueet menettävät synkroniaa samalla tavalla, RF–CRY2-selitys on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["masting", "RF", "synchrony", "weakening", "CRY2", "mobile_network"],
  },
  {
    id: "plant-cry-rf-1",
    code: "PLANT-CRY-RF-1",
    title_en: "Plant CRY RF Response Is Universal",
    title_fi: "Kasvien CRY:n RF-vaste on universaali",
    title_ja: "植物CRYのRF応答は普遍的",
    title_fr: "La réponse RF du CRY végétal est universelle",
    title_ko: "식물 CRY RF 반응은 보편적",
    test_en: "Ahmad 2020 demonstrated RF effects on Arabidopsis CRY1. BERM predicts this extends to CRY2 and to crop species: wheat, rice, soybean CRY2-mediated flowering should show RF sensitivity in controlled experiments. The effect is 'relatively minor' (Ahmad 2020's own assessment) but DETECTABLE and species-universal because the RPM mechanism is conserved.",
    test_fi: "Ahmad 2020 osoitti RF-vaikutukset Arabidopsiksen CRY1:een. BERM ennustaa tämän ulottuvan CRY2:een ja viljelykasveihin: vehnän, riisin, soijan CRY2-välitteisen kukinnan tulisi näyttää RF-herkkyyttä kontrolloiduissa kokeissa. Vaikutus on 'suhteellisen pieni' (Ahmad 2020:n oma arvio) mutta HAVAITTAVISSA ja lajiuniversaali, koska RPM-mekanismi on konservoitunut.",
    test_ja: "植物CRYのRF感受性は作物種にも拡張されるはず",
    test_fr: "La sensibilité RF du CRY végétal devrait s'étendre aux espèces cultivées",
    test_ko: "식물 CRY RF 민감성은 작물 종으로도 확장되어야 함",
    falsification_en: "If controlled RF exposure (GSM/Wi-Fi bands at ambient intensities) produces no detectable change in CRY2-mediated flowering time or CRY2 signalling in wheat, rice or soybean while the Arabidopsis CRY1 effect (Ahmad 2020) replicates in the same setup, species-universality is falsified.",
    falsification_fi: "Jos kontrolloitu RF-altistus (GSM/Wi-Fi-taajuudet ympäristöintensiteeteillä) ei tuota havaittavaa muutosta CRY2-välitteiseen kukinta-aikaan tai CRY2-signalointiin vehnällä, riisillä tai soijalla, vaikka Arabidopsiksen CRY1-vaikutus (Ahmad 2020) toistuu samassa asetelmassa, lajiuniversaalisuus on falsifioitu.",
    level: "L*",
    timeframe: "3–5 years",
    pathway: ["B"],
    tags: ["plant", "CRY2", "RF", "crop_species", "universal", "RPM"],
  },
  {
    id: "mast-soil-b2-1",
    code: "MAST-SOIL-B2-1",
    title_en: "B2/FAD Links Plant Masting to Animal Fertility",
    title_fi: "B2/FAD yhdistää kasvien mastingin eläinten lisääntymiseen",
    title_ja: "B2/FADが植物マスティングと動物生殖を結ぶ",
    title_fr: "Le B2/FAD relie le masting végétal à la fertilité animale",
    title_ko: "B2/FAD가 식물 마스팅과 동물 생식력을 연결",
    test_en: "Plants synthesize their own B2 (riboflavin) for CRY function. Animals require dietary B2. In masting years, forest-floor B2 availability changes through seed/fruit abundance. BERM predicts: small mammal fertility in mast years correlates with BOTH food abundance AND B2 availability for CRY function. This is a trophic-CRY coupling prediction.",
    test_fi: "Kasvit syntetisoivat oman B2:nsa (riboflaviini) CRY-toimintaan. Eläimet tarvitsevat ravinto-B2:n. Masting-vuosina metsänpohjan B2-saatavuus muuttuu siemen/hedelmärunsauden kautta. BERM ennustaa: pienten nisäkkäiden lisääntymismenestys masting-vuosina korreloi SEKÄ ravinnon runsauden ETTÄ B2-saatavuuden kanssa CRY-toimintaa varten. Tämä on troofinen CRY-kytkentäennuste.",
    test_ja: "マスト年の小型哺乳類の繁殖力はB2利用可能性と相関するはず",
    test_fr: "La fertilité des petits mammifères en année de faine corrèle avec la disponibilité en B2",
    test_ko: "마스트 해의 소형 포유류 번식력은 B2 가용성과 상관해야 함",
    falsification_en: "If small-mammal fertility in mast years tracks caloric abundance only — no residual effect of dietary riboflavin/FAD status on litter size or conception timing after controlling for food mass — the trophic-CRY coupling is falsified.",
    falsification_fi: "Jos pienten nisäkkäiden hedelmällisyys siemensatovuosina seuraa vain kaloreiden runsautta — ilman ravinnon riboflaviini/FAD-tilan jäännösvaikutusta poikuekokoon tai hedelmöitymisen ajoitukseen, kun ravinnon määrä on kontrolloitu — troofinen CRY-kytkentä on falsifioitu.",
    level: "L*",
    timeframe: "5–10 years",
    pathway: ["B"],
    tags: ["masting", "B2", "FAD", "trophic", "CRY", "small_mammals", "diet"],
  },
];
