import type { Metadata } from "next";
import { Dna } from "lucide-react";
import { ClaimRef } from "@/components/ClaimRef";
import { ExplanationHub, ExplanationSection, ExplanationText, ResearchConnection } from "@/components/ExplanationHub";
import { MathBlock } from "@/components/MathBlock";
import { pickCopy } from "@/lib/i18n";

const COPY = {
  en: {
    title: "Biology: a changing receiving system",
    subtitle: "Receptors, clocks, hormone responsiveness and functional capacity form a connected state.",
    lead: "A living system responds through its current state. BERM carries the physical input through a named receiving operator into redox chemistry, electrical activity, clocks and hormone response. These systems regulate each other. Their shared state provides the route by which one upstream change can affect several organs, motivations and behaviors.",
    incoming: "The physical perturbation δg enters the conditional L2 response operator and produces receptor input z. BERM derives the formal operator under matter-coupling and response premises; gauge, scale, tissue kernels and endpoint calibration remain open. Biology develops the downstream consequences.",
    outgoing: "Changes in responsiveness, timing, recovery and functional capacity. In the brain and endocrine system, these also become changes in what feels rewarding, costly and worth doing.",
    contents: [{ id: "reception", title: "A state-dependent receiver" }, { id: "cry-hormones", title: "CRY, hormones and clocks" }, { id: "timing", title: "The timing of a signal" }, { id: "capacity", title: "Function and motivation" }, { id: "ecology", title: "Organisms and ecology" }],
    reception: "The receiving state includes molecular abundance and conformation, cofactors, membrane properties, redox balance and phase. A change can therefore alter both the immediate response and sensitivity to a later input. BERM represents reception, accumulated change, recovery and functional capacity as distinguishable quantities with their own timescales.",
    receptionStudies: "Sherrard used a defined pulsed magnetic protocol (10 Hz, approximately 1.8 mT peak in cell experiments) and CRY interventions to locate ROS and growth responses. Dufor combined low-intensity repetitive magnetic stimulation with Cry deletion and BDNF rescue in mouse neural repair. Fogle linked optical CRY activation through a redox-sensitive channel partner to fly-neuron activity. Each experiment locates a receiving or transmitting stage in its own field, species and tissue. [[ref:sherrard2018|Sherrard 2018]]; [[ref:dufor2019_cry_magnetic_repair|Dufor 2019]]; [[ref:fogle2015_cry_redox|Fogle 2015]].",
    receptionImplication: "The model carries the receiver’s state forward rather than assigning a fixed response to a source name. Magnetic pulses and optical activation are distinct inputs; the transferable piece is the measured biological interface and the variables on which it depends.",
    cryClaim: "Cryptochromes and steroid receptors form a reciprocal regulatory interface: CRY modifies hormone-receptor response, and steroid-receptor-driven clock resetting depends on CRY2 in the studied cell system.",
    cry: "This is a particularly economical connection. The clock is part of hormone reception; hormones also help set the clock. CRY additionally participates in G-protein/cAMP signaling, connecting the same molecular family to metabolic response.",
    cryStudies: "Lamia located CRY–glucocorticoid-receptor regulation; Rizzini identified a CRY–DET1–COP1 route regulating glucocorticoid transcription. Manella found CRY2-dependent steroid-receptor resetting of cultured-cell clocks, with a different response to the cAMP-activating agent forskolin. Zhang located CRY regulation of hepatic glucagon/cAMP signaling. [[ref:lamia2011_cry_glucocorticoid|Lamia 2011]]; [[ref:rizzini2019_cry_cop1|Rizzini 2019]]; [[ref:manella2026_cry2_steroid_clock|Manella 2025/2026]]; [[ref:zhang2010_cry_camp|Zhang 2010]].",
    cryImplication: "CRY, receptor sensitivity and clock phase can be treated as coupled state variables. Sherrard’s field-exposure gene response already includes corticosteroid-receptor and cyclic-nucleotide pathway enrichment, identifying a concrete interface for this synthesis. The next connection is a receptor-response measurement in the exposed system. Cell type, CRY isoform and molecular partners set the response direction; CRY abundance is not one universal gain control.",
    timingClaim: "The temporal structure of a hormone signal changes functional responses even when the administered daily dose remains the same.",
    timing: "Hormone availability and tissue responsiveness must overlap in time. A pulse has onset, duration, spacing and recovery. The same total amount can consequently produce a different sequence of receptor occupancy, gene activity and neural responses.",
    timingStudies: "In a crossover study of 15 healthy men, Kalafatakis varied the delivery pattern of the same daily hydrocortisone dose and observed differences in emotional and cognitive responses. The manipulation held administered dose constant; it did not make every blood-concentration property identical. Receptor-pulse experiments and human circadian-transcript studies locate additional stages of temporal decoding. [[ref:kalafatakis2018_cortisol_pulsatility|Kalafatakis 2018]]; [[ref:stavreva2009_hormone_pulses|Stavreva 2009]]; [[ref:archer2014_transcriptome|Archer 2014]].",
    timingImplication: "Hormone concentration, pulse structure, clock phase and tissue receptivity belong in the same explanation. A single blood sample can remain similar while the time-integrated functional signal changes. Biological coordination is therefore an outcome in its own right.",
    timingEquation: "For an illustrative rhythmic hormone H and receptivity R, their average product depends on relative phase Δφ even when their separate means remain fixed. This is a mathematical example of overlap, not an estimated physiological response law.",
    capacity: "A functional output requires the appropriate biological transitions. Routine abundance or concentration measures can miss a failure of timing, activation or response. In reproduction, sperm activation, ovulation, implantation and pregnancy maintenance have distinct requirements. Their conditional probabilities compose into success over time.",
    capacityStudies: "Human CatSper deficiency locates a sperm hyperactivation and fertilization gate that routine semen parameters can miss. A mouse steroidogenic-cell clock intervention locates another gate around implantation. Finkelstein’s hormone manipulation links testosterone and estradiol to sexual function; kisspeptin experiments connect the reproductive axis to sexual-stimulus processing. [[ref:catsper2024|Young 2024]]; [[ref:liu2014|Liu 2014]]; [[ref:finkelstein2013_gonadal_steroids|Finkelstein 2013]]; [[ref:mills2023_kisspeptin|Mills 2023]].",
    capacityImplication: "BERM carries two connected outputs into behavior: the ability to complete an action and the motivation to initiate it. Sexual desire, wanting a child, an intentional attempt and successful conception have their own transitions. A shared biological state can influence several of them without making them the same variable.",
    ecology: "The same sequence applies across living systems: reception → physiological state → behavior → successful encounters. In ecology the encounters include pollination, mating, predation and competition. Their rate and success change the growth and survival of the interacting populations.",
    ecologyStudies: "A pollinator-removal experiment altered the behavior of the remaining pollinators and reduced seed production. This locates a behavior-to-ecological-output transition. Reception studies in model organisms supply different upstream pieces, with each species’ receiver and field protocol retained. [[ref:brosi2013_pollination_network|Brosi & Briggs 2013]].",
    ecologyImplication: "Human civilization is one continuation of this biological structure. Ecological outcomes remain a parallel branch with species-specific interaction rates, reproduction and mortality. In both branches, successful interactions translate organism state into population change and feed back into the next material environment.",
    links: [
      { href: "/modulome", title: "Organs and the modulome", description: "Follow receptor and tissue mechanisms through the existing organ atlas." },
      { href: "/model/biological-coordination", title: "Biological coordination", description: "Receiving state, tissue timing, biological memory and functional gates." },
      { href: "/evidence/nutrition", title: "Nutrition and receptivity", description: "Cofactors, metabolic state and the existing CRY-related pathways." },
      { href: "/evidence/circadian", title: "Clocks and endocrine timing", description: "Circadian evidence and the physiological consequences of misalignment." },
      { href: "/evidence/reproductive-arc", title: "The reproductive arc", description: "The existing explanation from reproductive physiology to completed births." },
      { href: "/model/dual-kernel", title: "Biological memory", description: "Accumulation, recovery and effects with different time constants." },
      { href: "/ecology", title: "The ecological branch", description: "Organisms, interactions and population outcomes beyond the human branch." },
      { href: "/modulome/brain", title: "The brain", description: "The receiving and regulatory systems that continue into motivation and behavior." },
      { href: "/model/q-factor", title: "Neural response and Q-factor", description: "Damping, resonance and the modeled response spectrum of seven neural pathways." },
    ],
    next: { href: "/behavior", title: "From biology to desire and action", description: "How the same changing organism experiences value, effort, intention and reasons." },
  },
  fi: {
    title: "Biologia: muuttuva vastaanottava järjestelmä",
    subtitle: "Reseptorit, kellot, hormonien vaikuttavuus ja toimintakyky muodostavat toisiinsa kytkeytyvän tilan.",
    lead: "Elävä järjestelmä vastaa nykyisen tilansa kautta. BERM kuljettaa fysikaalisen syötteen nimetyn vastaanotto-operaattorin läpi redox-kemiaan, sähköiseen toimintaan, kelloihin ja hormonivasteeseen. Nämä järjestelmät säätelevät toisiaan. Yhteisen tilan kautta yksi alkupään muutos voi vaikuttaa useisiin elimiin, motivaatioihin ja tekoihin.",
    incoming: "Fysikaalinen muutos δg tulee ehdolliseen L2-vasteoperaattoriin ja tuottaa vastaanottimen syötteen z. BERM johtaa formaalin operaattorin materia-kytkennän ja vasteen premisseillä; gauge, mittakaava, kudosytimet ja päätepistekalibraatio ovat avoimia. Biologia kehittää myöhemmät seuraukset.",
    outgoing: "Vastaanottavuuden, ajoituksen, palautumisen ja toimintakyvyn muutokset. Aivoissa ja hormonijärjestelmässä ne muuttavat myös sitä, mikä tuntuu palkitsevalta, työläältä ja tavoittelemisen arvoiselta.",
    contents: [{ id: "reception", title: "Tilastaan riippuva vastaanotin" }, { id: "cry-hormones", title: "CRY, hormonit ja kellot" }, { id: "timing", title: "Signaalin ajoitus" }, { id: "capacity", title: "Toimintakyky ja motivaatio" }, { id: "ecology", title: "Eliöt ja ekologia" }],
    reception: "Vastaanottavaan tilaan kuuluvat molekyylien määrä ja rakenne, kofaktorit, kalvon ominaisuudet, redox-tasapaino ja vaihe. Muutos voi siksi vaikuttaa sekä välittömään vasteeseen että herkkyyteen myöhemmälle syötteelle. BERM erottaa vastaanoton, kertyneen muutoksen, palautumisen ja toimintakyvyn toisistaan ja kuvaa niiden omat aikaskaalat.",
    receptionStudies: "Sherrard käytti määriteltyä magneettipulssiprotokollaa (solukokeissa 10 Hz, noin 1,8 mT:n huippu) ja CRY-interventioita ROS- ja kasvuvasteiden paikantamiseen. Dufor yhdisti pienitehoisen toistuvan magneettistimulaation Cry-poistoon ja BDNF-palautukseen hiiren hermoston korjaantumisessa. Fogle liitti optisen CRY-aktivaation redox-herkän kanavakumppanin kautta kärpäsen hermosolutoimintaan. Jokainen koe paikantaa vastaanoton tai välityksen osan omassa kentässään, lajissaan ja kudoksessaan. [[ref:sherrard2018|Sherrard 2018]]; [[ref:dufor2019_cry_magnetic_repair|Dufor 2019]]; [[ref:fogle2015_cry_redox|Fogle 2015]].",
    receptionImplication: "Malli kuljettaa vastaanottimen tilaa eteenpäin sen sijaan, että lähteen nimi määräisi vakion vasteen. Magneettipulssi ja optinen aktivaatio ovat eri syötteitä; yhdistettävä osa on mitattu biologinen rajapinta ja muuttujat, joista se riippuu.",
    cryClaim: "Kryptokromit ja steroidireseptorit muodostavat vastavuoroisen säätelyrajapinnan: CRY muuttaa hormonireseptorin vastetta, ja steroidireseptorien välittämä kellon tahdistuminen riippuu CRY2:sta tutkitussa solujärjestelmässä.",
    cry: "Tämä on erityisen säästeliäs yhteys. Kello osallistuu hormonin vastaanottoon, ja hormonit puolestaan kellon asettamiseen. CRY osallistuu myös G-proteiini–cAMP-signalointiin, jolloin sama molekyyliperhe liittyy aineenvaihdunnan vasteeseen.",
    cryStudies: "Lamia paikansi CRY:n ja glukokortikoidireseptorin säätelyn; Rizzini tunnisti glukokortikoidien geenivastetta säätelevän CRY–DET1–COP1-reitin. Manella osoitti viljeltyjen solujen steroidireseptorivälitteisen kellon tahdistumisen CRY2-riippuvuuden sekä erilaisen vasteen cAMP:tä aktivoivalle forskoliinille. Zhang paikansi CRY:n maksan glukagoni–cAMP-signaloinnin säätelyyn. [[ref:lamia2011_cry_glucocorticoid|Lamia 2011]]; [[ref:rizzini2019_cry_cop1|Rizzini 2019]]; [[ref:manella2026_cry2_steroid_clock|Manella 2025/2026]]; [[ref:zhang2010_cry_camp|Zhang 2010]].",
    cryImplication: "CRY, reseptoriherkkyys ja kellovaihe voidaan kuvata kytkeytyvinä tilamuuttujina. Sherrardin kenttäaltistuksen geenivasteessa on jo kortikosteroidireseptoriin ja syklisiin nukleotideihin liittyviä rikastumia: synteesillä on näin nimetty rajapinta. Seuraava yhdistettävä suure on reseptorivaste altistetussa järjestelmässä. Solutyyppi, CRY:n alalaji ja molekyylikumppanit määräävät vasteen suunnan; CRY:n määrä ei ole yksi yleinen vahvistuskerroin.",
    timingClaim: "Hormonisignaalin aikarakenne muuttaa toiminnallisia vasteita myös annetun vuorokausiannoksen pysyessä samana.",
    timing: "Hormonin saatavuuden ja kudoksen vastaanottavuuden on kohdattava ajassa. Pulssilla on alku, kesto, väli ja palautuminen. Sama kokonaismäärä voi siksi tuottaa erilaisen reseptorimiehityksen, geenitoiminnan ja hermostovasteiden sarjan.",
    timingStudies: "Kalafatakis vaihteli 15 terveen miehen vaihtovuorokokeessa saman hydrokortisonin vuorokausiannoksen antotapaa ja havaitsi eroja tunne- ja kognitiivisissa vasteissa. Vakiona pysyi annettu annos; kaikki veren pitoisuuskäyrän ominaisuudet eivät olleet samoja. Reseptorien pulssikokeet ja ihmisen transkriptirytmien tutkimukset paikantavat ajallisen tulkinnan muita vaiheita. [[ref:kalafatakis2018_cortisol_pulsatility|Kalafatakis 2018]]; [[ref:stavreva2009_hormone_pulses|Stavreva 2009]]; [[ref:archer2014_transcriptome|Archer 2014]].",
    timingImplication: "Hormonipitoisuus, pulssirakenne, kellovaihe ja kudoksen vastaanottavuus kuuluvat samaan selitykseen. Yksi verinäyte voi säilyä samanlaisena ajassa kertyvän toiminnallisen signaalin muuttuessa. Biologinen koordinaatio on siksi itsessään selitettävä tulos.",
    timingEquation: "Havainnollistavan rytmisen hormonin H ja vastaanottavuuden R tulon keskiarvo riippuu vaihe-erosta Δφ, vaikka niiden omat keskiarvot säilyvät. Kyse on päällekkäisyyden matemaattisesta esimerkistä, ei estimoidusta fysiologisesta vastelaista.",
    capacity: "Toiminnallinen tulos tarvitsee asianmukaiset biologiset siirtymät. Tavanomainen määrä- tai pitoisuusmittaus voi ohittaa ajoituksen, aktivaation tai vasteen puutteen. Lisääntymisessä siittiön aktivaatio, ovulaatio, implantaatio ja raskauden ylläpito tarvitsevat omat edellytyksensä. Niiden ehdolliset todennäköisyydet yhdistyvät ajassa toteutuvaksi onnistumiseksi.",
    capacityStudies: "Ihmisen CatSper-puute paikantaa siittiön hyperaktivaation ja hedelmöityksen portin, jonka tavanomaiset siemennesteparametrit voivat ohittaa. Hiiren steroidogeenisten solujen kellointerventio paikantaa toisen portin implantaatioon. Finkelsteinin hormonimanipulaatio liittää testosteronin ja estradiolin seksuaaliseen toimintaan; kisspeptiinitutkimukset yhdistävät lisääntymisakselin seksuaalisten ärsykkeiden käsittelyyn. [[ref:catsper2024|Young 2024]]; [[ref:liu2014|Liu 2014]]; [[ref:finkelstein2013_gonadal_steroids|Finkelstein 2013]]; [[ref:mills2023_kisspeptin|Mills 2023]].",
    capacityImplication: "BERM vie käyttäytymiseen kaksi kytkeytyvää ulostuloa: kyvyn toteuttaa toiminto ja motivaation ryhtyä siihen. Seksuaalinen halu, lapsitoive, tarkoituksellinen yritys ja onnistunut hedelmöittyminen tarvitsevat omat siirtymänsä. Yhteinen biologinen tila voi vaikuttaa useaan niistä tekemättä niistä samaa muuttujaa.",
    ecology: "Sama ketju koskee eläviä järjestelmiä laajemmin: vastaanotto → fysiologinen tila → käyttäytyminen → onnistuvat kohtaamiset. Ekologiassa kohtaamisia ovat esimerkiksi pölytys, parittelu, saalistus ja kilpailu. Niiden määrä ja onnistuminen muuttavat vuorovaikutuksessa olevien populaatioiden kasvua ja säilymistä.",
    ecologyStudies: "Pölyttäjän poistokoe muutti jäljelle jäävien pölyttäjien käyttäytymistä ja vähensi siementuottoa. Se paikantaa siirtymän käyttäytymisestä ekologiseen tulokseen. Mallieliöiden vastaanottotutkimukset tarjoavat erillisiä alkupään osia siten, että kunkin lajin vastaanotin ja kenttäprotokolla säilyvät mukana. [[ref:brosi2013_pollination_network|Brosi ja Briggs 2013]].",
    ecologyImplication: "Ihmisen sivilisaatio on tämän biologisen rakenteen yksi jatko. Ekologinen tulos säilyy rinnakkaishaarana, jolla on lajikohtaiset vuorovaikutusnopeudet, lisääntyminen ja kuolleisuus. Molemmissa haaroissa onnistuvat vuorovaikutukset muuttavat eliöiden tilan populaatiomuutokseksi ja vaikuttavat seuraavaan materiaaliseen ympäristöön.",
    links: [
      { href: "/modulome", title: "Elimet ja modulomi", description: "Vastaanotinten ja kudosten mekanismit nykyisessä elinkartastossa." },
      { href: "/model/biological-coordination", title: "Biologinen koordinaatio", description: "Vastaanotintila, kudosten ajoitus, biologinen muisti ja toiminnalliset portit." },
      { href: "/evidence/nutrition", title: "Ravitsemus ja vastaanottavuus", description: "Kofaktorit, aineenvaihduntatila ja nykyiset CRY:hen liittyvät reitit." },
      { href: "/evidence/circadian", title: "Kellot ja hormonien ajoitus", description: "Vuorokausirytmien näyttö ja eritahtisuuden fysiologiset seuraukset." },
      { href: "/evidence/reproductive-arc", title: "Lisääntymiskaari", description: "Nykyinen selitys lisääntymisfysiologiasta toteutuneisiin syntymiin." },
      { href: "/model/dual-kernel", title: "Biologinen muisti", description: "Kertyminen, palautuminen ja eri aikavakioilla jatkuvat vaikutukset." },
      { href: "/ecology", title: "Ekologinen haara", description: "Eliöt, vuorovaikutukset ja populaatiotulokset ihmistä laajemmin." },
      { href: "/modulome/brain", title: "Aivot", description: "Vastaanottavat ja säätelevät järjestelmät, jotka jatkuvat motivaatioon ja toimintaan." },
      { href: "/model/q-factor", title: "Hermoston vaste ja Q-tekijä", description: "Vaimennus, resonanssi ja seitsemän hermoradan mallinnettu vastespektri." },
    ],
    next: { href: "/behavior", title: "Biologiasta haluun ja toimintaan", description: "Miten sama muuttuva eliö kokee arvon, vaivan, aikomuksen ja perustelut." },
  },
  ja: {}, fr: {}, ko: {},
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const d = pickCopy(COPY, locale) as typeof COPY.en;
  return { title: `${d.title} – Extinction Field`, description: d.subtitle };
}

export default async function BiologyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const d = pickCopy(COPY, locale) as typeof COPY.en;
  const p = (text: string) => <ExplanationText locale={locale}>{text}</ExplanationText>;
  return <ExplanationHub locale={locale} copy={COPY} {...d} icon={Dna} stage="biology">
    <ExplanationSection {...d.contents[0]}>{p(d.reception)}<ResearchConnection locale={locale} studies={d.receptionStudies} implication={d.receptionImplication} /></ExplanationSection>
    <ExplanationSection {...d.contents[1]}><p className="text-lg font-medium leading-8"><ClaimRef claimId="claim.coordination.cry-steroid-feedback">{d.cryClaim}</ClaimRef></p>{p(d.cry)}<ResearchConnection locale={locale} studies={d.cryStudies} implication={d.cryImplication} /></ExplanationSection>
    <ExplanationSection {...d.contents[2]}><p className="text-lg font-medium leading-8"><ClaimRef claimId="claim.coordination.hormone-waveform">{d.timingClaim}</ClaimRef></p>{p(d.timing)}<ResearchConnection locale={locale} studies={d.timingStudies} implication={d.timingImplication} /><MathBlock tex={String.raw`\langle H R\rangle=H_0R_0+\frac{hr}{2}\cos\Delta\phi`} />{p(d.timingEquation)}</ExplanationSection>
    <ExplanationSection {...d.contents[3]}>{p(d.capacity)}<ResearchConnection locale={locale} studies={d.capacityStudies} implication={d.capacityImplication} /></ExplanationSection>
    <ExplanationSection {...d.contents[4]}>{p(d.ecology)}<ResearchConnection locale={locale} studies={d.ecologyStudies} implication={d.ecologyImplication} /></ExplanationSection>
  </ExplanationHub>;
}
