import type { Locale } from "@/lib/i18n";

const COPY = {
  en: {
    refsTitle: "References",
    sections: [
      [
        "In 2025, Swiss biologist Daniel Favre and Swedish neuroscientist Olle Johansson published a study that should have made front-page news. They placed honeybee colonies inside Faraday cages — metal enclosures that block all electromagnetic fields. The bees, shielded from every radio signal, Wi-Fi transmission, and power line field in their environment, promptly collapsed. Queens stopped laying fertilized eggs. Workers became disoriented. Within weeks, the colonies were dead.",
        "But here’s the part that changes everything: when the researchers introduced a single frequency back into the shielded hive — the Schumann resonance, Earth’s natural electromagnetic “heartbeat” at 7.83 Hz — the colonies survived.",
        "The bees didn’t need silence. They needed the right signal.",
      ],
      [
        "To understand why this matters, you need to know about a mite.",
        "Varroa destructor is a parasitic mite roughly the size of a pinhead that attaches to honeybees, punctures their exoskeleton, and feeds on their fat body and hemolymph. It also injects viruses — most devastatingly, Deformed Wing Virus — that cripple the colony’s next generation. Since jumping from Asian honeybees to European honeybees in the 1950s, Varroa has become the single greatest threat to managed bee populations worldwide.",
        "Asian honeybees (Apis cerana) coexist with Varroa because they evolved together. They have two critical defenses: hygienic behavior (detecting and removing parasitized brood) and grooming (physically biting and removing mites from nestmates). European honeybees (Apis mellifera) have these behaviors too, but they’re weaker — the bees often fail to detect the mite, or fail to remove it effectively.",
        "Here’s the question nobody has asked: what if the bees’ defense systems are being externally suppressed?",
      ],
      [
        "In 2023, a team of researchers published a striking finding in Current Biology. They demonstrated that ticks — close relatives of Varroa — are passively attracted to their hosts by static electricity. The electrostatic charge that builds up on a moving animal’s body literally pulls the parasite through the air gap onto the host, even across distances of several millimeters. The researchers explicitly noted that this mechanism likely applies to Varroa as well.",
        "A separate study had already shown that Varroa mites become more active — more agitated, more mobile — in the presence of electric fields, even fields too weak to physically lift them. The mites don’t need to be launched onto their host. They just need to be activated — primed to grab on when a charged bee brushes past.",
        "Now consider this: honeybees carry a positive electrostatic charge that they accumulate during flight. The charge is essential — it helps pollen grains jump from flowers onto the bee’s body. Bees can even sense the electric fields of flowers and use them to determine whether a flower has recently been visited. Electricity is woven into the fabric of honeybee biology.",
        "But what happens when the electromagnetic environment changes?",
      ],
      [
        "In the natural environment where honeybees evolved over millions of years, there were exactly two electromagnetic signals: Earth’s steady geomagnetic field (~50 microtesla) and the Schumann resonances (~7.83 Hz) generated by lightning activity in the ionosphere. That was the entire electromagnetic landscape. No radio frequencies. No intermediate frequencies. Nothing above a few hundred hertz.",
        "Today, a typical beehive sits in an environment saturated with electromagnetic fields that did not exist a century ago: cellular base stations (700 MHz–6 GHz), Wi-Fi routers (2.4/5 GHz), power lines (50/60 Hz), LED street and agricultural lighting (20–200 kHz switch-mode harmonics), smart meters, and in some locations, weather radar.",
        "Research has documented what these fields do to bees. A 2023 study published in Science Advances showed that electromagnetic fields disrupt honeybees’ pollination behavior by altering the magnetic maps used during foraging flights and producing a magnetoreception disorder.",
        "A 2023 PLOS ONE study showed that 900 MHz exposure induced measurable changes in stress-related enzymes and gene expression in honeybees — the organism diverts resources from normal function to emergency stress response. A 2025 study documented that 50 Hz electric fields reduce self-grooming behavior in bees. And multiple studies show that EMF exposure reduces queen laying rates and brood viability.",
        "Each of these effects, individually, weakens the colony. But the critical insight is what they do in combination with Varroa.",
      ],
      [
        "Honeybees fight Varroa through two main behaviors: hygienic behavior (detecting infected brood by smell and removing it) and grooming (physically removing mites from nestmates). Both depend on the bee’s sensory capabilities — particularly olfaction — and on coordinated social behavior within the colony.",
        "EMF disrupts both.",
        "Grooming decreases under electromagnetic stress. Olfactory sensitivity decreases under electromagnetic stress. Navigation and foraging efficiency decrease, meaning the colony brings in less food, meaning fewer resources for immune function. Stress proteins activate, diverting metabolic energy from defense to damage repair. The queen lays fewer viable eggs, weakening the colony’s ability to replace lost workers.",
        "Meanwhile, Varroa is structurally protected.",
        "The adult Varroa mite wears what one researcher described as “military-grade arthropod armour” — a thick sclerotin protein coat that is nearly impervious to the bee’s grooming attempts. This same rigid exoskeleton likely attenuates electromagnetic fields far more effectively than the bee’s relatively thin, flexible cuticle. At 1.6 millimeters long, the mite is too small for resonant absorption at any environmental EMF frequency. Its parasitic strategy — injecting salivary chemicals to keep the feeding wound open and suppress host immune response — is biochemical, not electromagnetic.",
        "In short: EMF weakens the host and doesn’t touch the parasite.",
        "This creates a ratchet effect. Each increment of ambient EMF tilts the balance further in Varroa’s favor. The bee’s grooming becomes less effective. Its hygienic behavior becomes less sensitive. Its immune system becomes more burdened. But Varroa’s ability to find, attach to, and feed on its host remains intact — and may even be enhanced if changing electrostatic conditions improve its host-contact efficiency.",
        "The result is that a colony can appear healthy until it suddenly isn’t. The tipping point arrives when Varroa load exceeds the colony’s diminished capacity to resist. This is Colony Collapse Disorder: not a single cause, but a cascade in which EMF is the hidden amplifier that makes every other stressor worse.",
      ],
      [
        "There is a US patent — number 12,239,107 — for an EMF shield for beehives. The patent’s description states, with remarkable directness: “With EMF transmissions blocked, bees rest better, become more healthy, productive and can better defend the colony against mites and hive beetles.”",
        "And Favre and Johansson’s Faraday experiment demonstrates the underlying principle: bees need Earth’s natural electromagnetic environment (the Schumann resonance) but are harmed by the artificial electromagnetic environment that we have layered on top of it.",
      ],
      [
        "This isn’t just about bees.",
        "The same principle — that organisms are calibrated by evolution to their natural electromagnetic environment and are disrupted by artificial fields to which they have no evolutionary adaptation — applies across the biological world. The human eye can detect a single photon. Sharks can sense electric fields of half a microvolt per meter. Migratory birds’ magnetic compass is disrupted by radiofrequency noise at levels found in normal urban environments. In 2026, a study published in Science showed that even mammals — bats — suffer hours-long disorientation from brief RF exposure at urban levels.",
        "The ion channels that mediate these electromagnetic sensitivities are three billion years old. They are conserved from bacteria to humans. They evolved in a world where the only electromagnetic signals were Earth’s magnetic field and lightning. They have no filter for frequencies that nature never produced.",
        "When we examine the broader biological landscape through this lens, a pattern emerges that no single-cause theory can explain. Laboratory control animals are getting fatter despite controlled diets. Autoimmune diseases are epidemic in exactly the countries with the highest electromagnetic exposure. Cancer in people under 50 — particularly in rapidly dividing tissues like the gut and testes — has risen 79% since 1990. Depression responds better to electromagnetic treatment (TMS) than to chemical treatment (SSRIs), suggesting it may be primarily an electrical disturbance, not a chemical one. And global fertility is declining in ways that cannot be fully explained by cultural choice.",
        "The bees are the canary in the coal mine. But we are in the same mine.",
      ],
    ],
    references: [
      "Favre D, Johansson O (2025). Honeybees’ Behaviour in a Faraday-Shielded Hive: Mandatory Schumann Resonance for Colony Survival. Int J Research – GRANTHAALAYAH, 13(4), 25–38.",
      "England SJ et al. (2023). Static electricity passively attracts ticks onto hosts. Current Biology, 33(14), 3041–3047.",
      "Colin ME et al. (1992). Attraction of Varroa jacobsoni by electrical charges. J Apicultural Research.",
      "Shepherd S et al. (2023). Electromagnetic fields disrupt the pollination service by honeybees. Science Advances, 9(20), eadh1455.",
      "Wyszkowska J et al. (2023/2025). 900 MHz EMF induces stress protein expression in honeybees. PLOS ONE; Behavioral changes under 50 Hz E-field. Agriculture.",
      "Panagopoulos DJ et al. (2025). A comprehensive mechanism of biological and health effects of anthropogenic ELF and WC EMFs. Frontiers in Public Health, 13:1585441.",
      "Lindecke O et al. (2026). RF noise disrupts bat magnetic compass. Science, 388: 977+.",
      "US Patent 12,239,107: EMF shield for beehives.",
      "Tinsley JN et al. (2016). Direct detection of a single photon by humans. Nature Communications, 7, 12172.",
    ],
  },
  fi: {
    refsTitle: "Lähdeluettelo",
    sections: [
      [
        "Vuonna 2025 sveitsiläinen biologi Daniel Favre ja ruotsalainen neurotieteilijä Olle Johansson julkaisivat tutkimuksen, jonka olisi pitänyt olla etusivun uutinen. He asettivat mehiläisyhdyskuntia Faradayn häkkeihin — metallikotelointeihin, jotka estävät kaikki sähkömagneettiset kentät. Mehiläiset, suojattuina jokaiselta radiosignaalilta, Wi-Fi-lähetykseltä ja voimalinjakentältä ympäristössään, romahtivat nopeasti. Kuningattaret lopettivat hedelmöitettyjen munien munimisen. Työläiset desorientoituivat. Muutamassa viikossa yhdyskunnat olivat kuolleita.",
        "Mutta tässä on osa joka muuttaa kaiken: kun tutkijat toivat yhden taajuuden takaisin suojattuun pesään — Schumannin resonanssin, Maan luonnollisen sähkömagneettisen ”sydämenlyönnin” taajuudella 7,83 Hz — yhdyskunnat selväsivat.",
        "Mehiläiset eivät tarvinneet hiljaisuutta. Ne tarvitsivat oikean signaalin.",
      ],
      [
        "Ymmärtääksesi miksi tällä on merkitystä, sinun on tiedettävä eräästä punkista.",
        "Varroa destructor on loispunkki, joka on suunnilleen nuppineulan pään kokoinen. Se kiinnittyy mehiläisiin, lävistää niiden ulkokuoren ja imee niiden rasvakudosta ja hemolymfaa. Se myös injektoi viruksia — tuhoisimpana epämuodostuneen siiven virusta (DWV) — jotka rampauuttavat yhdyskunnan seuraavan sukupolven. Hypättyään aasialaisista mehiläisistä eurooppalaisiin mehiläisiin 1950-luvulla Varroa on muodostunut suurimmaksi yksittäiseksi uhaksi hoidetuille mehiläispopulaatioille maailmanlaajuisesti.",
        "Aasialaiset mehiläiset (Apis cerana) elävät rinnakkain Varroan kanssa, koska ne kehittyivät yhdessä. Niillä on kaksi kriittistä puolustusmekanismia: hygieeninen käyttäytyminen (loisitun sikiön havaitseminen ja poistaminen) ja sukiminen (punkkien fyysinen pureminen ja poistaminen pesätovereilta). Eurooppalaisilla mehiläisillä (Apis mellifera) on nämä käyttäytymiset myös, mutta ne ovat heikompia — mehiläiset usein epäonnistuvat punkin havaitsemisessa tai sen tehokkaassa poistamisessa.",
        "Tässä on kysymys jota kukaan ei ole esittänyt: entä jos mehiläisten puolustusjärjestelmiä tukahdutetaan ulkoisesti?",
      ],
      [
        "Vuonna 2023 tutkijaryhmä julkaisi hätkähdyttävän löydöksen Current Biology -lehdessä. He osoittivat, että punkit — Varroan lähisukulaiset — houkuttuvat passiivisesti isäntiinsä staattisen sähkön voimalla. Liikkuvan eläimen keholle kertyvä sähköstaattinen varaus vetää loisen kirjaimellisesti ilmaraon läpi isännälle, jopa useiden millimetrien etäisyyksiltä. Tutkijat totesivat nimenomaisesti, että tämä mekanismi todennäköisesti pätee myös Varroaan.",
        "Erillinen tutkimus oli jo osoittanut, että Varroa-punkit muuttuvat aktiivisemmiksi — levottomammiksi, liikkuvammiksi — sähkökenttien läsnä ollessa, jopa kentissä jotka ovat liian heikkoja nostaakseen niitä fyysisesti. Punkkien ei tarvitse singoutua isännälleen. Niiden tarvitsee vain aktivoitua — valmistautua tarttumaan, kun varattu mehiläinen ohittaa.",
        "Pohdi nyt tätä: mehiläiset kantavat positiivista sähköstaattista varausta, jonka ne keräävät lennon aikana. Varaus on välttämätön — se auttaa siitepölyhiukkasia hyppäämään kukista mehiläisen keholle. Mehiläiset voivat jopa aistia kukkien sähkökenttiä ja käyttää niitä määrittääkseen, onko kukassa vierailtu äskettäin. Sähkö on kudottu mehiläisbiologian peruskankaaseen.",
        "Mutta mitä tapahtuu kun sähkömagneettinen ympäristö muuttuu?",
      ],
      [
        "Luonnollisessa ympäristössä, jossa mehiläiset kehittyivät miljoonien vuosien ajan, oli tarkalleen kaksi sähkömagneettista signaalia: Maan vakaa geomagneettinen kenttä (~50 mikroteslaa) ja Schumannin resonanssit (~7,83 Hz), jotka syntyvät salamatoiminnasta ionosfäärissä. Se oli koko sähkömagneettinen maisema. Ei radiotaajuuksia. Ei välitaajuuksia. Ei mitään muutaman sadan hertsin yläpuolella.",
        "Nykyään tyypillinen mehiläispesä sijaitsee ympäristössä, joka on kyllästetty sähkömagneettisilla kentillä, joita ei ollut olemassa vuosisata sitten: matkapuhelintukiasemat (700 MHz–6 GHz), Wi-Fi-reitittmet (2,4/5 GHz), voimalinjat (50/60 Hz), LED-katu- ja maatalousvalaistus (20–200 kHz hakkuritehonmuokkaajaharmoniset), älykkäät mittarit ja joissain paikoissa säätutkia.",
        "Tutkimus on dokumentoinut mitä nämä kentät tekevät mehiläisille. Vuoden 2023 Science Advances -tutkimus osoitti, että sähkömagneettiset kentät häiritsevät mehiläisten pölytystoimintaa muuttamalla lentojen ja navigoinnin magneettikarttoja ja tuottamalla magnetoreseptiohäiriön.",
        "Vuoden 2023 PLOS ONE -tutkimus osoitti, että 900 MHz altistus aiheutti mitattavia muutoksia stressiin liittyvissä entsyymissä ja geeniekspressiossa mehiläisissä — organismi ohjaa resursseja normaalitoiminnasta hätästressivasteeseen. Vuoden 2025 tutkimus dokumentoi, että 50 Hz sähkökentät vähentävät itsesukimiskäyttäytymistä mehiläisillä. Ja useat tutkimukset osoittavat, että EMF-altistus vähentää kuningattaren munintaa ja sikiön elinkeloisuutta.",
        "Jokainen näistä vaikutuksista, yksittäin, heikentää yhdyskuntaa. Mutta ratkaiseva oivallus on mitä ne tekevät yhdessä Varroan kanssa.",
      ],
      [
        "Mehiläiset taistelevat Varroaa vastaan kahdella pääkäyttäytymisellä: hygieenisellä käyttäytymisellä (tartunnan saaneen sikiön havaitseminen hajun perusteella ja sen poistaminen) ja sukimisella (punkkien fyysinen poistaminen pesätovereilta). Molemmat riippuvat mehiläisen aistikyvyistä — erityisesti hajuaistista — ja koordinoidusta sosiaalisesta käyttäytymisestä yhdyskunnan sisällä.",
        "EMF häiritsee molempia.",
        "Sukiminen vähenee sähkömagneettisen stressin alla. Hajuherkkyys vähenee sähkömagneettisen stressin alla. Navigoinnin ja ravinnon hankinnan tehokkuus vähenee, mikä tarkoittaa että yhdyskunta kerää vähemmän ruokaa, mikä tarkoittaa vähemmän resursseja immuunitoimintaan. Stressiproteiiinit aktivoituvat ohjaten metabolista energiaa puolustuksesta vaurioiden korjaamiseen. Kuningatar munii vähemmän elinkelpoisia munia, heikentäen yhdyskunnan kykyä korvata menettyjä työläisiä.",
        "Samaan aikaan Varroa on rakenteellisesti suojattu.",
        "Aikuinen Varroa-punkki on pukeutunut siihen, mitä eräs tutkija kuvaili ”sotilasluokan niveljalkaishaarniskaksi” — paksuksi sklerotiiniproteiinikerrokseksi, joka on lähes läpäisemätön mehiläisen sukimisyrityksille. Tämä sama jäykkä ulkokuori todennäköisesti vaimentaa sähkömagneettisia kenttiä paljon tehokkaammin kuin mehiläisen suhteellisen ohut, joustava kutiikkeli. 1,6 millimetrin pituisena punkki on liian pieni resonantti-absorptiolle millään ympäristön EMF-taajuudella. Sen loisstrategia — sylkikemikaalien injektointi pitääkseen syöttöhaava auki ja tukahduttaakseen isännän immuunivasteen — on biokemiallinen, ei sähkömagneettinen.",
        "Lyhyesti: EMF heikentää isäntää eikä koske loiseen.",
        "Tämä luo räikkävaikutuksen. Jokainen lisäys ambient-EMF:ssä kallistaa tasapainoa edelleen Varroan eduksi. Mehiläisen sukiminen muuttuu vähemmän tehokkaaksi. Sen hygieeninen käyttäytyminen muuttuu vähemmän herkäksi. Sen immuunijärjestelmä kuormittuu enemmän. Mutta Varroan kyky löytää, kiinnittyä ja syöttää isännällään säilyy koskemattomana — ja voi jopa tehostua, jos muuttuvat sähköstaattiset olosuhteet parantavat sen isäntäkontaktitehokkuutta.",
        "Tulos on, että yhdyskunta voi vaikuttaa terveltä kunnes se yhtäkkiä ei ole. Käännepiste saapuu kun Varroa-kuorma ylittää yhdyskunnan heikentyneen kyvyn vastustaa. Tämä on Colony Collapse Disorder: ei yksittäinen syy, vaan kaskadi jossa EMF on piilotettu vahvistin, joka tekee jokaisesta muusta stressitekijästä pahemman.",
      ],
      [
        "On olemassa yhdysvaltalainen patentti — numero 12 239 107 — mehiläispesien EMF-suojalle. Patentin kuvaus toteaa merkittävällä suoruudella: ”Kun EMF-lähetykset estetään, mehiläiset lepäävät paremmin, tulevat terveemmiksi, tuottavammiksi ja pystyvät paremmin puolustamaan yhdyskuntaa punkkeja ja pesäkuoriaisia vastaan.”",
        "Ja Favren ja Johanssonin Faraday-koe osoittaa taustalla olevan periaatteen: mehiläiset tarvitsevat Maan luonnollista sähkömagneettista ympäristöä (Schumannin resonanssia), mutta niille on vahingollista keinotekoinen sähkömagneettinen ympäristö, jonka olemme kerrostaneet sen päälle.",
      ],
      [
        "Tässä ei ole kyse vain mehiläisistä.",
        "Sama periaate — että organismit on kalibroitu evoluution kautta luonnolliseen sähkömagneettiseen ympäristöönsä ja häiriintyvät keinotekoisista kentistä joihin niillä ei ole evolutiivista sopeutumista — pätee koko biologisessa maailmassa. Ihmissilmä voi havaita yksittäisen fotonin. Hait voivat aistia puolen mikrovoltin metriä kohden sähkökenttiä. Muuttolintujen magneettikompassi häiriintyy radiotaajuisesta kohinasta normaaleissa kaupunkiympäristöissä havaituilla tasoilla. Vuonna 2026 Sciencessä julkaistu tutkimus osoitti, että jopa nisäkkäät — lepakot — kärsivät tuntien desorientaatiosta lyhyestä RF-altistuksesta kaupunkitasoilla.",
        "Ionikanavat jotka välittävät näitä sähkömagneettisia herkkyksiä ovat kolme miljardia vuotta vanhoja. Ne ovat säilyneet bakteereista ihmisiin. Ne kehittyivät maailmassa, jossa ainoat sähkömagneettiset signaalit olivat Maan magneettikenttä ja salamat. Niillä ei ole suodatinta taajuuksille joita luonto ei koskaan tuottanut.",
        "Kun tarkastelemme laajempaa biologista maisemaa tämän linssin läpi, esiin nousee kuvio jota yksikään yksisyyteoria ei voi selitää. Laboratorion kontrollieläimet lihovat kontrolloiduista ruokavalioista huolimatta. Autoimmuunisairaudet ovat epidemioita täsmälleen niissä maissa joissa sähkömagneettinen altistus on suurin. Syöpä alle 50-vuotiailla — erityisesti nopeasti jakautuvissa kudoksissa kuten suolistossa ja kiveksissä — on noussut 79 % vuodesta 1990. Masennus vastaa paremmin sähkömagneettiseen hoitoon (TMS) kuin kemialliseen hoitoon (SSRI), mikä viittaa siihen että se voi olla ensisijaisesti sähköinen häiriö, ei kemiallinen. Ja globaali hedelmällisyys laskee tavoilla joita ei voida täysin selitää kulttuurisella valinnalla.",
        "Mehiläiset ovat kaivoksen kanarialintuja. Mutta me olemme samassa kaivoksessa.",
      ],
    ],
    references: [
      "Favre D, Johansson O (2025). Honeybees’ Behaviour in a Faraday-Shielded Hive: Mandatory Schumann Resonance for Colony Survival. Int J Research – GRANTHAALAYAH, 13(4), 25–38.",
      "England SJ ym. (2023). Static electricity passively attracts ticks onto hosts. Current Biology, 33(14), 3041–3047.",
      "Colin ME ym. (1992). Attraction of Varroa jacobsoni by electrical charges. J Apicultural Research.",
      "Shepherd S ym. (2023). Electromagnetic fields disrupt the pollination service by honeybees. Science Advances, 9(20), eadh1455.",
      "Wyszkowska J ym. (2023/2025). 900 MHz EMF ja stressiproteiinien ilmentyminen mehiläisissä. PLOS ONE; Käyttäytymismuutokset 50 Hz E-kentässä. Agriculture.",
      "Panagopoulos DJ ym. (2025). Kattava mekanismi ihmisen tekemien ELF- ja WC-EMF-kenttien biologisista ja terveysvaikutuksista. Frontiers in Public Health, 13:1585441.",
      "Lindecke O ym. (2026). RF-kohina häiritsee lepakkojen magneettikompassia. Science, 388: 977+.",
      "US Patent 12 239 107: EMF-suoja mehiläispesille.",
      "Tinsley JN ym. (2016). Yksittäisen fotonin suora havaitseminen ihmisillä. Nature Communications, 7, 12172.",
    ],
  },
} as const;

export function BeeArticleContent({ locale }: { locale: Locale }) {
  const d = COPY[locale];

  return (
    <div className="article-body">
      {d.sections.map((section, si) => (
        <section key={si} className="mb-10">
          {si > 0 && (
            <div className="mb-10 flex justify-center">
              <span className="text-foreground-muted/30 text-lg tracking-[0.5em]">***</span>
            </div>
          )}
          {section.map((paragraph, pi) => (
            <p
              key={pi}
              className="text-[1.0625rem] sm:text-lg leading-[1.8] text-foreground/90 mb-6 last:mb-0"
            >
              {paragraph}
            </p>
          ))}
        </section>
      ))}

      {/* References */}
      <section className="mt-16 pt-8 border-t border-card-border">
        <h2 className="font-serif text-xl font-semibold mb-6">{d.refsTitle}</h2>
        <ol className="space-y-3 text-sm text-foreground-muted leading-relaxed">
          {d.references.map((ref, i) => (
            <li key={i} className="flex gap-3">
              <span className="font-mono-num text-foreground-muted/50 shrink-0">{i + 1}.</span>
              <span>{ref}</span>
            </li>
          ))}
        </ol>
      </section>
    </div>
  );
}
