"""BERM civilization-level model.

Extends the micro-level EMF-fertility model to macro-historical scales:
solar reconstruction, latitude-dependent susceptibility (chi), biological
carrying capacity (BioCap), migration gradients, and empire lifespan
analysis against the Suess cycle.
"""

from berm.civilization.solar_reconstruction import (
    GRAND_MINIMA,
    GrandMinimum,
    SCHWABE_PERIOD,
    GLEISSBERG_PERIOD,
    SUESS_PERIOD,
    is_grand_minimum,
    solar_activity,
    solar_activity_series,
)
from berm.civilization.chi_map import (
    ELECTRIFICATION_CHI_PEAK,
    ELECTRIFICATION_YEARS,
    chi_electrification,
    chi_latitude,
    chi_total,
)
from berm.civilization.biocap import (
    ALPHA,
    biocap,
    biocap_series,
    electrification_proxy,
    sigma,
    urbanization_proxy,
)
from berm.civilization.migration_gradient import (
    REGIONS,
    Region,
    biocap_gradient,
    gradient_matrix,
    migration_pressure,
)
from berm.civilization.historical_test import (
    EMPIRES,
    RENAISSANCES,
    Empire,
    Renaissance,
    empire_solar_overlap,
    renaissance_solar_correlation,
)
from berm.civilization.empire_lifespan import (
    EXTENDED_EMPIRES,
    empire_lifespan_distribution,
    empire_lifespans,
    lifespan_histogram_bins,
    suess_cycle_match,
)
from berm.civilization.cultural_energy import (
    BIOMARKER_WEIGHTS,
    compute_biocap,
    compute_cultural_energy,
)
from berm.civilization.biomarker_trajectories import (
    BiomarkerTrajectory,
    TRAJECTORIES,
    TREND_DATA,
    biomarker_values_at,
    get_trajectory,
)
from berm.civilization.unwin_validation import (
    PHASE_THRESHOLDS,
    Phase,
    classify_phase,
    detect_transitions,
)
from berm.civilization.sensitivity import (
    sensitivity_all,
    sensitivity_single,
)
from berm.civilization.phase_transitions import (
    identify_transitions,
    predict_next_transition,
)
from berm.civilization.political_biology import (
    BINDING_FOUNDATIONS,
    DIMENSION_FUNCTIONS,
    ENVIRONMENTS,
    FOUNDATION_VULNERABILITY,
    IDEOLOGY_PROFILES,
    INDIVIDUALIZING_FOUNDATIONS,
    MORAL_FOUNDATION_FUNCTIONS,
    RK_TRAIT_FUNCTIONS,
    RK_TRAIT_LABELS,
    RK_TRAIT_SUBSTRATES,
    EMFEnvironment,
    POLICY_DOMAINS,
    classify_ideology,
    collective_action_capacity,
    environment_biomarkers,
    environment_comparison,
    environment_profile,
    foundation_collapse_order,
    ideology_trajectory,
    loyalty_collapse_analysis,
    loyalty_collapse_gradient,
    moral_breadth,
    moral_distress_index,
    moral_foundations_profile,
    orientation_profile,
    pathological_universalism_index,
    policy_vulnerability_profile,
    rk_competition,
    rk_environment_gradient,
    rk_group_loyalty,
    rk_mating_strategy,
    rk_parental_investment,
    rk_sexual_timing,
    rk_strategy_index,
    rk_strategy_profile,
    urban_rural_gradient,
    IQ_SHREDDER_LABELS,
    dopaminergic_capture_index,
    genetic_burn_rate,
    iq_shredder_gradient,
    iq_shredder_profile,
    reproductive_suppression_index,
    shredder_efficiency,
    time_preference_biological,
    anomic_distress_index,
    cognitive_fragility_index,
    external_locus_index,
    moral_compensation_index,
    pathopolites_gradient,
    pathopolites_profile,
    safety_seeking_index,
    victimhood_identity_index,
    BEHAVIORAL_SINK_FUNCTIONS,
    COUNTRY_PROFILES,
    SIGNAL_DEGRADATION_FUNCTIONS,
    CountryEMFProfile,
    behavioral_sink_gradient,
    behavioral_sink_index,
    behavioral_sink_profile,
    country_berm_analysis,
    country_emf_index,
    country_predicted_tfr,
    cross_country_comparison,
    cryptic_signal_index,
    dynamic_signal_index,
    institutional_capture_index,
    morphological_signal_index,
    normative_predation_index,
    obesity_amplification_index,
    pair_signal_compound,
    signal_degradation_gradient,
    signal_degradation_profile,
    signal_perception_capacity,
    sterilization_contagion_index,
    CALHOUN_PHASE_FUNCTIONS,
    BIOLENINIST_FUNCTIONS,
    REPRODUCTIVE_SPECTRUM_FUNCTIONS,
    PARASITIC_TRANSMISSION_FUNCTIONS,
    CIVILIZATIONAL_SINK_FUNCTIONS,
    calhoun_phase_indicators,
    calhoun_phase,
    calhoun_recovery_potential,
    bioleninist_loyalty_value,
    institutional_competence_decay,
    bioleninist_ratchet_index,
    reproductive_behavior_spectrum,
    effective_fertility_index,
    prenatal_disruption_index,
    endocrine_sexual_disruption_index,
    wolbachia_sterilization_index,
    sacculina_hijacking_index,
    baculovirus_institutional_index,
    disoperator_destruction_index,
    cooperative_group_integrity,
    civilizational_sink_index,
    civilizational_sink_profile,
    civilizational_sink_gradient,
    BEHAVIORAL_IMMUNE_FUNCTIONS,
    SOCIAL_TRANSMISSION_FUNCTIONS,
    behavioral_immune_index,
    destigmatization_index,
    stigma_inversion_index,
    net_behavioral_immunity,
    transmission_resistance,
    recovery_sabotage_index,
    dependency_transmission_index,
    social_contagion_index,
    empathy_weaponization_index,
    active_infection_seeking_index,
    civilizational_transmission_composite,
    civilizational_transmission_profile,
    civilizational_transmission_gradient,
)
