"use client";
import { useEffect, useId, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { scaleLinear, line, area } from "d3";
import Link from "next/link";
import { fieldReconstruction, getReconstructionTracks, getReconstructionOperatingWindows, type ReconstructionCountryId } from "@/lib/field-reconstruction";
import { parseBermScenarioParameters, runBermAtlasScenarioDetailed, applyBermScenarioToAsfr, evaluateScenarioSource, type ScenarioSource, type BermAtlasScenarioParameters } from "@/lib/berm-atlas-scenario";
import { buildTechnologyScenarioSources, getTechnologyInputChoices, technologyInputCoverage, type TechnologyScenarioInput } from "@/lib/berm-technology-inputs";
import { atlasText as t, atlasNumber as num, downloadAtlasBlob } from "@/lib/change-atlas-display";
import { getChangeAtlasSeries, getChangeAtlasSource } from "@/lib/change-atlas-data";
import { atlasCsvCell } from "@/lib/change-atlas-state";
import { MathBlock } from "./MathBlock";
import { ChangeAtlasCharts } from "./ChangeAtlasCharts";
import styles from "./ChangeAtlas.module.css";

/** Input windows are an explicit scenario mapping, not reconstructed amplitude observations. */
export function atlasScenarioSources(countryId: string, params: Pick<URLSearchParams,"get">): ScenarioSource[] {
  if(params.get("s_input")!=="history")return buildTechnologyScenarioSources(countryId,params);
  const off=(params.get("s_off")??"").split(",");
  return getReconstructionTracks(countryId).flatMap(track=>{
    const windows=getReconstructionOperatingWindows(countryId,track.familyId).map(w=>({...w,endYear:Math.min(2023,w.endYear)})).filter(w=>w.startYear<=w.endYear);
    if(!windows.length)return [];
    const number=(key:string,fallback:number,max:number)=>{const raw=params.get(key);return raw!==null&&raw.trim()!==""&&Number.isFinite(Number(raw))&&Number(raw)>=0&&Number(raw)<=max?Number(raw):fallback;};
    return [{id:track.familyId,startYear:windows[0].startYear,endYear:windows[windows.length-1].endYear,windows,amplitude:number(`s_amp_${track.familyId}`,.25,2),angleDegrees:number(`s_angle_${track.familyId}`,0,180),enabled:!off.includes(track.familyId)}];
  });
}

export function BermAtlasScenario({countryId,locale,from,to,year,onYearChange}:{countryId:ReconstructionCountryId;locale:string;from:number;to:number;year:number;onYearChange:(year:number)=>void}) {
  const fi=locale==="fi";
  const params=useSearchParams();
  const p=parseBermScenarioParameters(params);
  const dataMode=params.get("s_input")!=="history";
  const timing=["early","late"].includes(params.get("s_timing")??"")?params.get("s_timing")!:"linear";
  const sources=atlasScenarioSources(countryId,params);
  const allChoices=getTechnologyInputChoices(countryId);
  const choices=params.get("s_shared")==="1"?allChoices.filter(s=>s.familyId==="cellular-total"||s.id.endsWith("_electricity_per_capita")):allChoices;
  const calculate=(s:ScenarioSource[])=>{try{return {...runBermAtlasScenarioDetailed(s,p,from,to,from),error:""};}catch(error){return {points:[],coverage:null,error:error instanceof Error?error.message:"Unknown calculation error"};}};
  const comparisonSources=sources.map(s=>({...s,enabled:!dataMode||!(s as TechnologyScenarioInput).singleObservation||(s as TechnologyScenarioInput).singleObservationOptIn}));
  const current=calculate(sources),complete=calculate(comparisonSources);
  const points=current.points;
  const reference=complete.points;
  const at=points.find(p=>p.year===year)!;
  const country=fieldReconstruction.countries.find(c=>c.id===countryId)!;
  const allCountries=fieldReconstruction.countries.map(c=>({country:c,sources:atlasScenarioSources(c.id,params),...calculate(atlasScenarioSources(c.id,params))}));
  const timingCases=dataMode?(["linear","early","late"] as const).map(timing=>({timing,...calculate(buildTechnologyScenarioSources(countryId,params,timing))})):[];
  const timingBand=points.map((point,i)=>{const values=timingCases.filter(c=>!c.error).map(c=>c.points[i].relativeChangePercent);return {year:point.year,lower:Math.min(point.relativeChangePercent,...values),upper:Math.max(point.relativeChangePercent,...values)};});
  const ageClosure=applyBermScenarioToAsfr(getChangeAtlasSeries(countryId,"asfr").map(s=>({ageGroup:s.ageGroup!,points:s.points})),points,from);
  const inputCoverage=dataMode?technologyInputCoverage(countryId,sources as TechnologyScenarioInput[],year):[];
  const update=(patch:Record<string,string|null>|((current:URLSearchParams)=>Record<string,string|null>))=>{
    const next=new URLSearchParams(window.location.search);
    const values=typeof patch==="function"?patch(next):patch;
    for(const[key,value]of Object.entries(values)){if(value===null)next.delete(key);else next.set(key,value);}
    window.history.replaceState(null,"",`${window.location.pathname}?${next}${window.location.hash}`);
  };
  const setSourceEnabled=(sourceId:string,enabled:boolean)=>update(current=>{
    const off=new Set((current.get("s_off")??"").split(",").filter(Boolean));
    if(enabled)off.delete(sourceId);else off.add(sourceId);
    const selected=current.get("s_input")==="history"?undefined:buildTechnologyScenarioSources(current.get("country")??countryId,current).find(s=>s.id===sourceId);
    return {s_off:[...off].join(","),...(selected?.singleObservation?{[`s_single_${sourceId}`]:enabled?"1":null}:{})};
  });
  const name=(id:string)=>id==="cellular-total"?(fi?"Mobiili, kaikki sukupolvet":"Mobile, all generations"):t(fieldReconstruction.families.find(f=>f.id===id)!.label,locale);
  const dataSources=[...new Set(allCountries.flatMap(c=>(c.sources as Partial<TechnologyScenarioInput>[]).flatMap(s=>s.sourceIds??[])))].flatMap(id=>{const source=getChangeAtlasSource(id);return source?[source]:[];});
  const metadata={kind:"conditional_uncalibrated_BERM_sensitivity",status:current.error?"unavailable":"calculated",error:current.error,inputMode:dataMode?"source_quantity_profiles":"legacy_history_ramps",formulation:"2025-weyl-gme",normalization:"kappa=1; e=(0,1,0,0); A0=(0,B,0,0)",sourceWindowRule:dataMode?"Source observations are normalized using the named reference. One indicator per family, mobile total and generation-specific series are alternatives. Intermediate years use the selected linear/early/late timing hypothesis. Endpoint holding, if selected, is an explicit assumption inside historical scope; unknown history is not a physical zero. No measured potential amplitude is asserted.":"Legacy comparison: generic ramp within declared historical operating windows.",parameters:{...p,mapping:params.get("s_mapping")==="linear"?"linear":"sqrt",timing,singleObservationPolicy:"explicit-opt-in",countryDataBasis:params.get("s_shared")==="1"?"shared-indicators":"broader-histories",edges:params.get("s_edges")==="unknown"?"unknown":"hold"},sources,dataSources,coverage:current.coverage,inputCoverage,timingCases,ageClosure,baselineYear:from,points,comparison:{...complete,sources:comparisonSources},countries:allCountries.map(c=>({countryId:c.country.id,sources:c.sources,points:c.points,coverage:c.coverage,status:c.error?"unavailable":"calculated",error:c.error})),edition:fieldReconstruction.updatedAt};
  const parameters: {key:keyof BermAtlasScenarioParameters;label:string;min:number;max:number;step:number}[]=[
    {key:"beta",label:fi?"Biologinen herkkyys β":"Biological sensitivity β",min:-1,max:1,step:.05},
    {key:"lagYears",label:fi?"Vasteviive (vuotta)":"Response delay (years)",min:0,max:30,step:1},
    {key:"memoryYears",label:fi?"Muisti-ikkunan lisäpituus (vuotta)":"Extra memory span (years)",min:0,max:30,step:1},
    {key:"coherence",label:fi?"Tehollisten moodien korrelaatio c":"Effective-mode correlation c",min:0,max:1,step:.05},
    {key:"meanFraction",label:fi?"Keskiarvon osuus r":"Mean fraction r",min:-1,max:1,step:.05},
    {key:"background",label:fi?"Normalisoitu tausta B":"Normalized background B",min:0,max:3,step:.1},
    {key:"rampYears",label:fi?"Oletettu nousuaika (vuotta)":"Assumed ramp (years)",min:0,max:30,step:1},
  ];
  const reset=()=>update(current=>{const values:Record<string,null>={};for(const key of current.keys())if(key.startsWith("s_"))values[key]=null;return values;});
  const inputControls=<div className={styles.controls}>
    <label>{fi?"Laskennan teknologiatieto":"Technology input"}<select value={dataMode?"data":"history"} onChange={e=>update({s_input:e.target.value})}><option value="data">{fi?"Tilastoista muuttuvat lähteet":"Sources changing with statistics"}</option><option value="history">{fi?"Aiempi ajoitusskenaario":"Earlier timing scenario"}</option></select></label>
    {dataMode&&<><label>{fi?"Välivuosien ajoitus":"Intermediate-year timing"}<select value={timing} onChange={e=>update({s_timing:e.target.value})}><option value="linear">{fi?"Tasainen muutos havaintojen välillä":"Linear between observations"}</option><option value="early">{fi?"Muutos aikaisin":"Change early"}</option><option value="late">{fi?"Muutos myöhään":"Change late"}</option></select></label>
    <label>{fi?"Tilastosta moodin amplitudiksi":"Quantity to mode amplitude"}<select value={params.get("s_mapping")==="linear"?"linear":"sqrt"} onChange={e=>update({s_mapping:e.target.value})}><option value="sqrt">{fi?"Neliöjuuri · oletus":"Square root · assumption"}</option><option value="linear">{fi?"Lineaarinen · oletus":"Linear · assumption"}</option></select></label>
    <label>{fi?"Aikasarjan ulkopuoliset vuodet":"Years beyond source data"}<select value={params.get("s_edges")==="unknown"?"unknown":"hold"} onChange={e=>update({s_edges:e.target.value})}><option value="hold">{fi?"Pidä lähin arvo · oletus":"Hold nearest value · assumption"}</option><option value="unknown">{fi?"Jätä avoimeksi · vaadi täysi kattavuus":"Leave unknown · require coverage"}</option></select></label>
    <label>{fi?"Maiden aineistopohja":"Country data basis"}<select value={params.get("s_shared")==="1"?"1":"0"} onChange={e=>update({s_shared:e.target.value})}><option value="0">{fi?"Maakohtainen laaja historia":"Broader country histories"}</option><option value="1">{fi?"Samat mittarit kaikille maille":"Same indicators in every country"}</option></select></label>
    {choices.some(c=>/^mobile-/.test(c.familyId))&&<label>{fi?"Mobiilin erottelu":"Mobile representation"}<select value={params.get("s_mobile")==="generations"?"generations":"total"} onChange={e=>update({s_mobile:e.target.value})}><option value="total">{fi?"Kaikkien sukupolvien kokonaismäärä":"Total across generations"}</option><option value="generations">{fi?"Saatavilla olevat sukupolvitiedot":"Available generation records"}</option></select></label>}</>}
  </div>;
  const controlPanel=<div className={styles.scenarioControls}>{parameters.filter(input=>!dataMode||input.key!=="rampYears").map(input=><label key={input.key}>{input.label}<output>{num(p[input.key],locale)}</output><input aria-label={input.label} type="range" min={input.min} max={input.max} step={input.step} value={p[input.key]} onChange={e=>update({[`s_${input.key}`]:e.target.value})}/></label>)}</div>;
  const sourceControls=(<details className={styles.details}><summary>{fi?"Valitse lähteet, amplitudit ja suunnat":"Choose sources, amplitudes and directions"}</summary>
      <p className={styles.note}>{fi?"Amplitudi b on yksikötön potentiaalimoodin skenaarioparametri. Kulma on sen suunta valittuun vastaanotinprojektioon nähden. Sama arvo siirtyy maavertailuun; teknologian nimi ei määrää voimakkuutta tai herkkyyttä.":"Amplitude b is a dimensionless potential-mode scenario parameter. Angle describes its direction relative to the chosen receiver projection. Values carry across countries; a technology name does not determine magnitude or sensitivity."}</p>
      <div className={styles.scenarioSources}>{sources.map(s=><div key={s.id} className={styles.scenarioSource}><label><input type="checkbox" checked={s.enabled} onChange={e=>setSourceEnabled(s.id,e.target.checked)}/>{name(s.id)}</label>{dataMode&&<label>{fi?"Lähdesarja":"Source series"}<select aria-label={`${name(s.id)} ${fi?"lähdesarja":"source series"}`} value={(s as TechnologyScenarioInput).driverSeriesId} onChange={e=>update({[`s_driver_${s.id}`]:e.target.value})}>{choices.filter(c=>c.familyId===s.id).map(c=><option key={c.id} value={c.id}>{t(c.title,locale)}</option>)}</select></label>}<label aria-label={`${name(s.id)} b`}><span>{fi?"Kenttäkytkentä b · oletus":"Field coupling b · assumption"}</span><input aria-label={`${name(s.id)} ${fi?"amplitudi":"amplitude"}`} type="range" min={0} max={2} step={.05} value={s.amplitude} onChange={e=>update({[`s_amp_${s.id}`]:e.target.value})}/><output>{num(s.amplitude,locale)}</output></label><label aria-label={`${name(s.id)} ${fi?"kulma":"angle"}`}><input aria-label={`${name(s.id)} ${fi?"kulma":"angle"}`} type="range" min={0} max={180} step={15} value={s.angleDegrees} onChange={e=>update({[`s_angle_${s.id}`]:e.target.value})}/><output>{s.angleDegrees}°</output></label></div>)}</div>
      <p className={styles.note}>{fi?"Käyttöjaksot (vuosiresoluutio)":"Operating intervals (annual resolution)"}: {sources.map(s=>`${name(s.id)} ${s.windows?.map(w=>`${w.startYear}–${w.endYear}`).join(", ")}`).join("; ")}.</p>
      <p className={styles.note}>{fi?"Laskelma kattaa valittujen lähteiden ilmoitetut ajalliset rajaukset. Rajaus voi perustua historiaan tai pelkkään tilaston havaintojaksoon. Sen alku tai loppu ei silloin osoita todellista käyttöönottoa tai sulkemista. Ulkopuolelle jäävä komponentti on tämän osalaskelman puute; muistiydin voi jatkaa mukana olleen komponentin vastetta.":"The calculation covers the selected components’ declared time scopes, based on historical records or only a statistical observation period. Such a boundary need not indicate actual adoption or shutdown. An excluded component is a gap in this subset calculation; memory can continue the response to an included component."}</p>
    </details>);
  if(current.error)return <section data-berm-scenario={JSON.stringify(metadata)}><h2 className={styles.panelTitle}>{fi?"Skenaarion laskentaraja":"Scenario calculation limit"}</h2><p role="alert" className={styles.note}>{current.error.startsWith("Missing source profile")?(fi?"Valittu ajanjakso ja muistiydin sisältävät vuosia, joille lähdetieto puuttuu. Valitse näkyvä reuna-arvon pitämisoletus tai rajaa ajanjakso. Avoimista vuosista ei lasketa nollakenttää.":"The selected interval and memory kernel include years without source data. Select the explicit endpoint-holding assumption or narrow the interval. Unknown years are not calculated as zero fields."):(fi?"Valittu yhdistelmä ylittää numeerisen laskennan alueen. Pienennä amplitudia tai biologista herkkyyttä.":"The chosen combination exceeds the numerical range. Reduce amplitude or biological sensitivity.")}</p>{inputControls}{controlPanel}{sourceControls}<button className={styles.textButton} onClick={reset}>{fi?"Palauta alkuarvot":"Restore defaults"}</button></section>;
  const downloadScenario=()=>{
    const rows:unknown[][]=[["kind","input_mode","country","year","projected_geometry","self","cross","background_term","response_from_baseline","relative_TFR_multiplier","relative_change_percent","conditional_tfr_15_49","baseline_year","parameters_json","sources_json","coverage_json","age_specific_rates_json","edition","calculation_status","calculation_error"]];
    for(const c of allCountries){
      if(c.error){rows.push([metadata.kind,metadata.inputMode,c.country.id,...Array(9).fill(null),from,JSON.stringify(metadata.parameters),JSON.stringify(c.sources),JSON.stringify(c.coverage),null,metadata.edition,"unavailable",c.error]);continue;}
      const closure=applyBermScenarioToAsfr(getChangeAtlasSeries(c.country.id,"asfr").map(s=>({ageGroup:s.ageGroup!,points:s.points})),c.points,from);
      for(const d of c.points){const age=closure.points.find(p=>p.year===d.year);rows.push([metadata.kind,metadata.inputMode,c.country.id,d.year,d.geometry,d.self,d.cross,d.backgroundTerm,d.response,d.multiplier,d.relativeChangePercent,age?.tfr,from,JSON.stringify(metadata.parameters),JSON.stringify(c.sources),JSON.stringify(c.coverage),JSON.stringify(age?.asfr),metadata.edition,"calculated",""]);}
    }
    downloadAtlasBlob(new Blob(["\uFEFF"+rows.map(r=>r.map(atlasCsvCell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),"berm-conditional-scenario-5-countries.csv");
  };
  return <section data-berm-scenario={JSON.stringify(metadata)}>
    <p className={styles.scenarioBadge}>{fi?"Ehdollinen herkkyyslaskelma · käyttäjän oletukset":"Conditional sensitivity calculation · user assumptions"}</p>
    <h2 className={styles.panelTitle}>{fi?"Miten päällekkäisyys voisi välittyä syntyvyyteen?":"How could overlapping sources propagate to fertility?"}</h2>
    <p className={styles.note}>{dataMode?(fi?"Teknologioiden leviäminen ja käyttö muuttavat nyt lähdekohtaisia syötteitä tilastojen mukana. Laskelma etenee lähdetilastosta valittuun kenttämoodiin, BERM-vasteeseen ja ikäkohtaiseen syntyvyyteen. Tilaston ja paikallisen kentän välinen muunnos sekä biologinen herkkyys ovat näkyviä oletuksia.":"Technology adoption and use now change source inputs with the statistics. The calculation moves from source quantity to a chosen field mode, the BERM response and age-specific fertility. Mapping the statistic to a local field and biological sensitivity remain explicit assumptions."):(fi?"Aiempi vertailulaskelma käyttää historiallisia käyttöjaksoja ja samaa nousuaikaa eri lähteille.":"The earlier comparison uses historical operating intervals and a common ramp across sources.")}</p>
    {inputControls}
    {controlPanel}
    <p className={styles.note}>{fi?"Alkuarvot ovat havainnollistavia. Kun r = 0 ja c = 0, riippumattomien nollakeskiarvoisten moodien keskimääräiset ristiter­mit häviävät. Päällekkäiset lähteet säilyttävät omat neliöterminsä. Korrelaation muuttaminen kokeilee erillistä oletusta yhteisestä tehollisesta moodista.":"Initial values are illustrative. With r = 0 and c = 0, independent zero-mean modes have no average cross terms, while each source retains its self term. Changing correlation tests a separate assumption about a shared effective mode."}</p>
    {dataMode&&<p className={styles.note}>{fi?`Laskentaan kytketty ${sources.filter(s=>s.enabled).length} lähdeperhettä. ${inputCoverage.filter(c=>c.basis==="history-only"||c.basis==="unresolved").length} rekonstruktion perhettä odottaa vielä määrällistä syötettä; mobiilin kokonaismäärä käsitellään erillisenä eikä monisteta sukupolville.`:`${sources.filter(s=>s.enabled).length} source families enter this calculation. ${inputCoverage.filter(c=>c.basis==="history-only"||c.basis==="unresolved").length} reconstruction families still await quantitative inputs; total mobile subscriptions form one separate component and are not duplicated across generations.`}</p>}
    {dataMode&&<p className={styles.note}>{params.get("s_shared")==="1"?(fi?"Yhteinen mittaristo sisältää sähkönkulutuksen asukasta kohti ja mobiililiittymät. Se tekee mittarimääritelmistä vertailukelpoiset ja samalla supistaa mukana olevia teknologioita.":"Shared indicators include electricity use per person and mobile subscriptions. This aligns metric definitions while narrowing technology coverage."):(fi?"Laaja historia käyttää kunkin maan saatavilla olevia lähteitä. Esimerkiksi maan kokonaiskulutus ja kotitaloussektorin kulutus ovat eri suureita. Maavertailu havainnollistaa näillä syötteillä laskettua skenaariota; maiden järjestys ei ole mitattujen altistusten järjestys.":"Broader histories use each country’s available records. National total and household-sector electricity use are different quantities. Country comparisons show scenarios under these inputs; their ranking is not a ranking of measured exposure.")}</p>}
    {sourceControls}
    {dataMode&&sources.some(s=>(s as TechnologyScenarioInput).singleObservation)&&<p className={styles.note}>{fi?"Yhteen havaintovuoteen perustuva lähde on oletuksena pois laskennasta: piste ei yksin kuvaa leviämisen kehitystä. Sen voi kytkeä erikseen mukaan reuna-arvon pitämiseen perustuvana oletuksena.":"A source with only one observed year is excluded by default: a snapshot does not establish an adoption trajectory. It can be enabled explicitly as an endpoint-holding assumption."}</p>}
    {dataMode&&<details className={styles.details}><summary>{fi?"Mitä laskelma tietää valitun vuoden lähteistä?":"What is known about sources in the selected year?"}</summary>
      {(sources as TechnologyScenarioInput[]).map(s=>{const value=evaluateScenarioSource(s,year,0);const original=choices.find(c=>c.id===s.driverSeriesId);return <section key={s.id} className={styles.source}><h3>{name(s.id)} · {t(s.title,locale)}</h3><p>{t(s.scope,locale)}</p><p>{fi?"Havaintovuodet":"Source years"}: {s.dataYears.join("–")} · {fi?"Vertailusuure":"Reference"}: {t(s.reference,locale)}</p><p>{t(s.interpretation,locale)}</p><p>{fi?"Vuoden syöte":"Selected-year input"}: {value.value===null?(fi?"avoin":"unknown"):num(value.value,locale,3)} · {value.basis==="assumed-hold"?(fi?"Havaintojakson ulkopuolelle pidetty reuna-arvo (oletus)":"Endpoint held beyond observation period (assumption)"):value.basis==="profile-point"?(fi?"Lähdehavainto, valittu normalisointi ja kenttämuunnos":"Source observation with chosen normalization and field mapping"):value.basis==="disabled"?(fi?"Poistettu tästä skenaariosta":"Excluded from this scenario"):value.basis==="outside-operation-window"?(fi?"Valitun historiallisesti rajatun komponentin ulkopuolella":"Outside the selected historical component"):fi?"Välivuoden rekonstruktio (oletus)":"Intermediate-year reconstruction (assumption)"}</p>{original?.sourceIds.map(id=>{const source=getChangeAtlasSource(id);return source?<p key={id}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></p>:null;})}</section>;})}
      <p className={styles.note}>{fi?"Määrällistä syötettä odottavat perheet":"Families awaiting quantitative inputs"}: {inputCoverage.filter(c=>!c.inputId).map(c=>t(c.label,locale)).join("; ")}. {fi?"Ne jäävät tämän laskelman ulkopuolelle; todellista kenttää ei aseteta nollaksi.":"They remain outside this calculation; their physical fields are not declared zero."}</p>
    </details>}
    <h3 className={styles.panelTitle}>{t(country.name,locale)} · {year}</h3>
    <p className={styles.insight}>{fi?"Skenaarion suhteellinen TFR-muutos":"Scenario relative TFR change"}: <strong>{at.relativeChangePercent>0?"+":""}{num(at.relativeChangePercent,locale,1)} %</strong> ({from} = 0 %). {fi?"Muutos on valituilla oletuksilla laskettu herkkyys, ei aineistosta tunnistettu EMF:n osuus.":"This is the sensitivity calculated under the selected assumptions, not an EMF-attributable share identified from the data."}</p>
    <ScenarioPlot title={fi?"Ehdollinen muutos syntyvyyden tasossa":"Conditional change in fertility level"} unit={fi?`Muutos suhteessa vuoteen ${from} (%)`:`Change from ${from} (%)`} from={from} to={to} year={year} locale={locale} onYearChange={onYearChange} band={dataMode?timingBand:undefined} series={[
      {name:fi?"Valitut lähteet":"Selected sources",color:"var(--chart-series-4)",points:points.map(p=>({year:p.year,value:p.relativeChangePercent}))},
      ...(!complete.error?[{name:fi?"Kaikki saatavilla olevat lähteet":"All available sources",color:"var(--foreground-muted)",dashed:true,points:reference.map(p=>({year:p.year,value:p.relativeChangePercent}))}]:[]),
    ]}/>
    {(complete.error||allCountries.some(c=>c.error))&&<p className={styles.note}>{fi?"Osasta vertailuja puuttuu laskennan vaatima ajallinen kattavuus. Näytetään valitun maan toimiva laskelma; puuttuvat vertailut eivät ole nollatuloksia.":"Some comparisons lack the required temporal coverage. The valid selected-country result remains visible; unavailable comparisons are not zero effects."} {allCountries.filter(c=>c.error).map(c=>t(c.country.name,locale)).join(", ")}</p>}
    {dataMode&&<p className={styles.note}>{fi?"Varjostus näyttää kolmen välivuosioletuksen vaihtelun: muutos aikaisin, tasaisesti tai myöhään. Se ei ole tilastollinen luottamusväli eikä kata puuttuvia teknologioita, kenttäkytkentää tai biologisen herkkyyden epävarmuutta. Havaintojakson ulkopuolisten arvojen pitäminen on erillinen, yllä näkyvä oletus.":"Shading spans three intermediate-year timing assumptions: early, linear and late. It is not a confidence interval and does not cover missing technologies, field coupling or biological sensitivity. Endpoint holding outside observations is a separate assumption shown above."}</p>}
    {dataMode&&<details className={styles.details}><summary>{fi?"Miten kunkin lähteen poistaminen muuttaa tulosta?":"How does removing each source change the result?"}</summary><p className={styles.note}>{fi?"Poistaminen koskee koko laskentahistoriaa, myös vertailuvuotta. Erot eivät summaudu kokonaisvaikutukseksi, koska lähteillä voi olla ristitermejä.":"Removal applies to the full calculation history, including baseline. Differences do not add to a total effect because sources may have cross terms."}</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{fi?"Lähde":"Source"}</th><th>{fi?"TFR-muutos ilman lähdettä":"TFR change without source"}</th><th>{fi?"Ero valittuun laskelmaan":"Difference from selected result"}</th></tr></thead><tbody>{sources.filter(s=>s.enabled).map(s=>{const result=calculate(sources.map(other=>other.id===s.id?{...other,enabled:false}:other));const without=result.points.find(point=>point.year===year)?.relativeChangePercent;return <tr key={s.id}><th scope="row">{name(s.id)}</th><td>{without===undefined?"—":`${num(without,locale,2)} %`}</td><td>{without===undefined?"—":`${num(at.relativeChangePercent-without,locale,2)} ${fi?"prosenttiyksikköä":"percentage points"}`}</td></tr>;})}</tbody></table></div></details>}
    <details className={styles.details}><summary>{fi?"Johda syntyvyys ikäryhmien kautta":"Derive fertility through age groups"}</summary><p className={styles.note}>{fi?`Vuoden ${from} lähde-ASFR:t pidetään lähtötasona ja jokaisen ikäryhmän luku kerrotaan BERM-skenaarion suhteellisella vasteella. Muut tilatekijät ja lisääntymisen ajoitus pysyvät tässä sulussa vakioina. Summa kattaa 15–49-vuotiaat; erillinen WPP-TFR säilyy omana havaintosarjanaan.`:`Source ASFRs in ${from} form the baseline and each age-group rate is multiplied by the BERM scenario response. Other state and reproductive timing remain fixed in this closure. The sum covers ages 15–49; the separately published WPP TFR remains its own observation series.`}</p>{ageClosure.baselineTfr===null?<p>{fi?"Valitulta alkuvuodelta puuttuu täysi ikäryhmäaineisto. Valitse lähtövuosi 1950–2023.":"The selected baseline lacks complete age-group data. Choose a baseline in 1950–2023."}</p>:<><ScenarioPlot title={fi?"Ikäryhmistä summattu ehdollinen TFR":"Conditional TFR summed from age groups"} unit={fi?"Lasta / nainen · 15–49-vuotiaat":"Children / woman · ages 15–49"} from={from} to={to} year={year} locale={locale} onYearChange={onYearChange} series={[{name:fi?"Ehdollinen ASFR-summa":"Conditional ASFR sum",color:"var(--chart-series-4)",points:ageClosure.points.map(p=>({year:p.year,value:p.tfr!}))},{name:fi?"Vertailuvuoden taso":"Baseline level",color:"var(--foreground-muted)",dashed:true,points:points.map(p=>({year:p.year,value:ageClosure.baselineTfr!}))}]}/><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{fi?"Ikä":"Age"}</th><th>{from}</th><th>{year} · {fi?"skenaario":"scenario"}</th></tr></thead><tbody>{ageClosure.points.find(p=>p.year===year)?.asfr.map(a=><tr key={a.ageGroup}><th scope="row">{a.ageGroup}</th><td>{a.baseline===null?"—":num(a.baseline,locale)}</td><td>{a.value===null?"—":num(a.value,locale)}</td></tr>)}</tbody></table></div><p className={styles.note}>{fi?"Ikäryhmien luvut: syntymää / 1 000 naista.":"Age-group rates: births / 1,000 women."}</p></>}</details>
    <ChangeAtlasCharts series={getChangeAtlasSeries(countryId,"tfr")} locale={locale} yearDomain={[from,to]} selectedYear={year} onSelectYear={onYearChange}/>
    <ScenarioPlot title={fi?"Sama sulkuoletus viidessä maassa":"The same closure across five countries"} unit={fi?`Skenaarion muutos, ${from} = 0 %`:`Scenario change, ${from} = 0%`} from={from} to={to} year={year} locale={locale} onYearChange={onYearChange} series={allCountries.filter(c=>!c.error).map((c,i)=>({name:t(c.country.name,locale),color:`var(--chart-series-${i+1})`,points:c.points.map(p=>({year:p.year,value:p.relativeChangePercent}))}))}/>
    <p className={styles.note}>{fi?"Maiden viivat ovat samalla asteikolla ja käyttävät samoja vaste- ja muunnosoletuksia. Erot syntyvät lähteiden kehityksestä, valituista mittareista ja aineistokattavuudesta. Tarkista lähdesarjojen alueet ja normalisointi: maan tai alueen tilasto ei yksin määritä väestön paikallisia kenttiä.":"Country curves use one scale and common response and mapping assumptions. Differences reflect source trajectories, selected indicators and data coverage. Check each series’ geographic scope and normalization: country or regional statistics alone do not identify local population fields."}</p>
    <details className={styles.details}><summary>{fi?"Avaa johdettu geometria ja käytetyt sulkuoletukset":"Open derived geometry and the chosen closure assumptions"}</summary>
      <h3 className={styles.panelTitle}>{fi?"Lindgrenistä johdettu geometria":"Lindgren-derived geometry"}</h3>
      <MathBlock tex={String.raw`g_{μν}=η_{μν}+κ A_μ A_ν,\quad A=A_0+\sum_j a_j`} />
      <MathBlock tex={String.raw`\Delta g_{μν}=κ\left(A_{0μ}\sum_j a_{jν}+\sum_j a_{jμ}A_{0ν}+\sum_{j,k}a_{jμ}a_{kν}\right)`}/>
      <p className={styles.note}>{fi?"Tämä ulkotulon avaus seuraa vuoden 2025 premissistä. Seuraavat momentit, projektio ja biologinen sulku ovat erikseen valittuja oletuksia.":"This outer-product expansion follows from the 2025 premise. The following moments, projection and biological closure are separately chosen assumptions."}</p>
      <MathBlock tex={String.raw`u_i(t)=\int_0^\infty K_i^{μν}(\tau;S_i(t-\tau))\,\Delta g_{μν}(t-\tau)\,d\tau`}/>
      <h3 className={styles.panelTitle}>{fi?"Laskelmassa valittu normalisoitu moodi":"Normalized mode chosen for this calculation"}</h3>
      <MathBlock tex={String.raw`\kappa=1,\ e=(0,1,0,0),\ A_0=(0,B,0,0),\ p_j(t)=b_jq_j(t)\cos\theta_j`}/>
      <MathBlock tex={String.raw`Q(t)=\mathbb E[e^μ e^ν\Delta g_{μν}]=2Br\sum_j p_j+\sum_jp_j^2+\left[r^2+(1-r^2)c\right]\sum_{j\ne k}p_jp_k`}/>
      <p className={styles.note}>{dataMode?(fi?"q muodostetaan lähteen omasta määrästä ja ilmoitetusta vertailusuureesta. Lineaarisessa vaihtoehdossa q = x / x_ref; neliöjuurivaihtoehdossa q = √(x / x_ref). Jälkimmäinen olettaa, että moodin oma neliötermi skaalautuu lähdesuureen mukana. Kumpikaan muunnos ei yksin mittaa paikallista potentiaalia. b määrittää erikseen oletetun kytkennän. Väestöpeittoa ei tulkita automaattisesti jokaisen yksilön amplitudiksi.":"q is constructed from source quantity and its named reference. Linear mapping uses q = x / x_ref; square-root mapping uses q = √(x / x_ref). The latter assumes that the mode’s self term scales with source quantity. Neither mapping measures a local potential by itself. b separately specifies the assumed coupling. Population coverage is not automatically an individual amplitude."):(fi?"Aiemmassa ajoitusskenaariossa q on käyttöikkunasta alkava yhteisen nousuajan ramppi.":"In the earlier timing scenario q is a common-duration ramp starting at the operating window.")}</p>
      <p className={styles.note}>{fi?"Momenttioletus on E[a_j] = r b_j q_j n_j sekä positiivisesti semidefiniitti kovarianssi (1−r²)b_jq_j b_kq_k[(1−c)δ_jk+c] n_j⊗n_k. c kuvaa tehollisten moodien oletettua korrelaatiota. Päällekkäisyys, vaihe ja vastaanotingeometria tarvitsevat oman fysikaalisen rekonstruktionsa.":"The moment assumption is E[a_j] = r b_j q_j n_j with positive-semidefinite covariance (1−r²)b_jq_j b_kq_k[(1−c)δ_jk+c] n_j⊗n_k. c is an assumed correlation of effective modes. Overlap, phase and receiver geometry require their own physical reconstruction."}</p>
      <ScenarioPlot title={fi?"Geometrisen projektion osat":"Components of the geometric projection"} unit={fi?"Normalisoidut skenaariomomentit":"Normalized scenario moments"} from={from} to={to} year={year} locale={locale} onYearChange={onYearChange} series={[{name:fi?"Omat termit":"Self terms",color:"var(--chart-series-1)",points:points.map(p=>({year:p.year,value:p.self}))},{name:fi?"Lähteiden ristiter­mit":"Source cross terms",color:"var(--chart-series-2)",points:points.map(p=>({year:p.year,value:p.cross}))},{name:fi?"Taustan ristiter­mi":"Background cross term",color:"var(--chart-series-3)",points:points.map(p=>({year:p.year,value:p.backgroundTerm}))}]}/>
      <h3 className={styles.panelTitle}>{fi?"BERM:n ehdollinen biologinen jatko":"BERM’s conditional biological continuation"}</h3>
      <MathBlock tex={String.raw`R(t)=\frac{1}{m+1}\sum_{\tau=\ell}^{\ell+m}Q(t-\tau),\quad \Delta R(t)=R(t)-R(t_0)`}/>
      <MathBlock tex={String.raw`\mathrm{ASFR}_a^{\mathrm{scen}}(t)=\mathrm{ASFR}_a(t_0)e^{-\beta\Delta R(t)}\ \Longrightarrow\ \frac{\mathrm{TFR}^{\mathrm{scen}}(t)}{\mathrm{TFR}(t_0)}=e^{-\beta\Delta R(t)}`}/>
      <p className={styles.note}>{fi?"Tässä eksplisiittisessä sulussa kaikilla lisääntymisi’illä on sama vastekerroin ja muut tilan osat pidetään vakioina. Siksi kerroin voidaan viedä saman ikärajaston ASFR-summan ulkopuolelle. Se kokoaa vastaanotin-, elin-, pari- ja käyttäytymistason herkkyyden yhdeksi kokeiltavaksi parametriksi; hormonimuutosta tai väliporrasta ei väitetä mitatuksi. Täydessä BERM-ketjussa nämä siirtymät saavat omat tilansa, aineistonsa ja kalibrointinsa.":"This explicit closure uses the same response multiplier at every reproductive age, holding other state components fixed. The factor can therefore be taken outside the ASFR sum over the same age support. It compresses receiver, organ, partnership and behavioural sensitivity into one exploratory parameter; it does not claim a measured hormone change or intermediate response. In the full BERM chain those transitions have their own states, data and calibration."}</p>
      <h3 className={styles.panelTitle}>{fi?"Empiirinen biologia ja avoin kalibrointi":"Empirical biology and open calibration"}</h3>
      <p className={styles.note}>{fi?"Vastaanotintilaa, reseptoreita, vuorokausikelloa ja lisääntymistoimintaa koskeva osanäyttö rajaa ketjun omia osia. Tämän laskelman β, viive ja muistiydin ovat käyttäjän oletuksia. Gauge, fysikaalinen mittakaava, kudoskohtaiset ytimet ja ihmisen päätepistekalibrointi ovat avoimia. FieldState voi tuoda fysikaalisen syötteen; biologinen operaattori ja skenaario kuuluvat BERM:iin.":"Component evidence on receiver state, receptors, circadian clocks and reproduction constrains its own links. This calculation’s β, delay and memory kernel are user assumptions. Gauge, physical scale, tissue kernels and human endpoint calibration remain open. FieldState may supply physical input; the biological operator and scenario belong to BERM."}</p>
      <p className={styles.note}><Link href={`/${locale}/evidence/converging-patterns`}>{fi?"Avaa ketjun osanäyttö":"Open the component evidence"} →</Link> · <Link href={`/${locale}/evidence/response-conditions`}>{fi?"Vaste-ehdot ja nollatulosten tulkinta":"Response conditions and interpretation of null results"} →</Link></p>
    </details>
    <div className={styles.actions}><button onClick={downloadScenario}>{fi?"Lataa viiden maan skenaariolaskelma ja parametrit (CSV)":"Download five-country scenario and parameters (CSV)"}</button><button onClick={reset}>{fi?"Palauta havainnollistavat alkuarvot":"Restore illustrative defaults"}</button></div>
  </section>;
}

interface PlotSeries {name:string;color:string;dashed?:boolean;points:{year:number;value:number}[]}
interface TimingBandPoint {year:number;lower:number;upper:number}
function ScenarioPlot({title,unit,from,to,year,locale,series,onYearChange,band}:{title:string;unit:string;from:number;to:number;year:number;locale:string;series:PlotSeries[];onYearChange:(year:number)=>void;band?:TimingBandPoint[]}) {
  const ref=useRef<HTMLDivElement>(null),id=useId();const[width,setWidth]=useState(700);
  useEffect(()=>{if(!ref.current||typeof ResizeObserver==="undefined")return;const ro=new ResizeObserver(entries=>{const w=entries[0]?.contentRect.width;if(w>0)setWidth(w);});ro.observe(ref.current);return()=>ro.disconnect();},[]);
  const vals=[...series.flatMap(s=>s.points.map(p=>p.value)),...(band??[]).flatMap(p=>[p.lower,p.upper])];const low=Math.min(0,...vals),high=Math.max(0,...vals),pad=Math.max((high-low)*.12,.01);
  const x=scaleLinear().domain([from,to]).range([60,width-16]),y=scaleLinear().domain([low-pad,high+pad]).nice().range([155,15]);
  const path=line<{year:number;value:number}>().x(p=>x(p.year)).y(p=>y(p.value));
  const c=locale==="fi"?"Ehdollinen skenaario":"Conditional scenario";
  const columns=width>=850?3:width>=620?2:1;
  const height=215+Math.ceil(series.length/columns)*22+(band?22:0);
  return <figure className={styles.details} aria-labelledby={`${id}-title`}><figcaption id={`${id}-title`} style={{fontWeight:600,fontSize:".9rem"}}>{title}</figcaption><p className={styles.note}>{unit} · {c}</p><div ref={ref}>
    <svg data-atlas-export="scenario" viewBox={`0 0 ${width} ${height}`} width={width} height={height} style={{width:"100%",height:"auto"}} role="img" aria-label={`${title} ${from}–${to}`}><title>{`${title} · ${c} · ${from}–${to}`}</title><desc>{`${unit}. ${series.map(s=>s.name).join("; ")}.`}</desc>
      {y.ticks(4).map(v=><g key={v}><line x1={60} x2={width-16} y1={y(v)} y2={y(v)} stroke="var(--chart-grid)"/><text x={51} y={y(v)+4} textAnchor="end" fontSize={11} fill="var(--foreground-muted)">{num(v,locale,1)}</text></g>)}
      {x.ticks(width<500?4:8).filter(Number.isInteger).map(v=><text key={v} x={x(v)} y={180} textAnchor="middle" fontSize={11} fill="var(--foreground-muted)">{v}</text>)}
      {band&&<path data-timing-envelope="true" d={area<TimingBandPoint>().x(p=>x(p.year)).y0(p=>y(p.lower)).y1(p=>y(p.upper))(band)??""} fill="var(--chart-series-4)" fillOpacity={0.18}/>}
      {series.map((s,i)=><path key={s.name} d={path(s.points)??""} fill="none" stroke={s.color} strokeWidth={i===0?2.5:1.8} strokeDasharray={s.dashed?"5 4":undefined}/>)}
      <line x1={x(year)} x2={x(year)} y1={12} y2={158} stroke="var(--foreground-muted)" strokeDasharray="3 3"/>
      {series.map((s,i)=>{const left=60+(i%columns)*(width-76)/columns,top=209+Math.floor(i/columns)*22;return <g key={s.name}><line x1={left} x2={left+14} y1={top-4} y2={top-4} stroke={s.color} strokeWidth={2} strokeDasharray={s.dashed?"4 3":undefined}/><text x={left+20} y={top} fontSize={11} fill="var(--foreground)">{`${s.name}: ${num(s.points.find(p=>p.year===year)?.value??0,locale,2)}`}</text></g>;})}
      {band&&<text x={60} y={209+Math.ceil(series.length/columns)*22} fontSize={11} fill="var(--foreground-muted)">{locale==="fi"?"Varjostus: välivuosien ajoitusvaihtoehdot":"Shading: intermediate-year timing cases"}</text>}
    </svg>
    <button type="button" className={styles.textButton} onClick={()=>onYearChange(from)}>{locale==="fi"?"Valitse vertailuvuosi":"Select baseline year"} {from}</button>
  </div></figure>;
}
