"use client";

import { AlertTriangle } from "lucide-react";
import { SolarMiniTimeline } from "./SolarMiniTimeline";
import { BiocapSparkline } from "./BiocapSparkline";

const ESSAY_COPY = {
  en: {
    epistemicBanner:
      "This page presents a theoretical framework connecting biological mechanisms to civilizational dynamics. The biological evidence (molecular, hormonal, cross-species) is empirically supported. The civilizational interpretation is a hypothesis — consistent with historical data but not proven by it. Correlation between solar cycles and civilizational transitions does not establish causation.",

    // Section 1
    s1title: "The Pattern Everyone Sees But No One Can Explain",
    s1p1: "Throughout recorded history, civilizations have followed a remarkably consistent pattern. They emerge with explosive energy, expand across vast territories, flourish for a time, and then — without exception — decline. The pattern is so regular that for three hundred years, serious thinkers have tried to understand it. Giambattista Vico described it in 1725 as a recurring cycle of three ages. Oswald Spengler saw it as the organic lifecycle of a living organism. Arnold Toynbee documented it across twenty-one civilizations. John Bagot Glubb, having led the Arab Legion across the Middle East and studied thirteen empires, found that each lasted approximately 250 years and passed through the same six stages in the same order. Peter Turchin translated the pattern into differential equations and found secular cycles of roughly 80–100 years nested within it.",
    s1p2: "These thinkers disagreed about almost everything — method, ideology, and scope. Most were unaware of each other’s work. Yet they independently converged on the same observation: civilizations do not progress linearly. They rise and fall in cycles, and the late stages are marked by a strikingly consistent set of symptoms — declining birth rates, increasing hedonism, loss of collective will, pessimism, a reliance on foreign labour, and what Glubb called “an extraordinary increase in frivolity.”",
    s1p3: "The question none of them could answer is: why?",
    s1p4: "Conventional explanations attribute civilizational decline to cultural, economic, or institutional factors. Societies become complacent. Elites overproduce. Complexity exceeds its returns. These explanations describe what happens but not why it happens with such mechanical regularity, across cultures that share no common language, religion, or political structure. If decline were purely cultural, it should be preventable by cultural means. Yet South Korea — a nation with strong family values, extraordinary work ethic, and over $200 billion invested in pronatalist policies since 2006 — has the lowest fertility rate in recorded human history, at 0.72 children per woman. The policies did not slow the decline. They did not even stop it from accelerating.",
    s1p5: "Something more fundamental is at work.",

    // Section 2
    s2title: "The Biological Substrate of Civilizational Capacity",
    s2p1: "BERM — the Bioelectromagnetic Reproductive Model — proposes that underneath the cultural, economic, and political dynamics of civilizations lies a biological substrate: the collective physiological state of the population. This substrate can be measured. Male testosterone has declined by approximately 1.2% per year since the 1980s, independent of age, obesity, and lifestyle. Sperm concentration has fallen by more than half since 1973, and the rate of decline is accelerating. Melatonin — the hormone that governs sleep, circadian rhythm, and immune function — is chronically suppressed by the modern electromagnetic and light environment. Vitamin D deficiency affects nearly half the world’s population. These are not cultural choices. They are biological measurements.",
    s2p2: "BERM identifies the mechanism: the electromagnetic fields generated by electrical infrastructure — power grids, wireless networks, LED lighting, personal devices — activate voltage-gated calcium channels in cell membranes, disrupting the calcium signalling cascades that govern virtually every physiological process: hormone production, neurotransmitter release, immune function, DNA repair, and reproduction. The effect is cumulative, chronic, and largely imperceptible. It does not produce acute symptoms. It produces a gradual, population-wide erosion of biological capacity.",
    s2p3: "This is not a metaphor. It is a measurable, testable, falsifiable biological process. A single genetic mutation in one calcium channel gene — CACNA1C, the cause of Timothy syndrome — produces every pathology that BERM predicts: cardiac arrhythmia, immune dysfunction, metabolic disorder, autism spectrum features, and facial dysmorphism. BERM proposes that chronic environmental electromagnetic exposure produces the same spectrum of effects, qualitatively but at lower magnitude, across entire populations over decades.",

    // Section 3
    s3title: "What This Explains That Nothing Else Can",
    s3sub1: "The simultaneous decline of fertility across all species.",
    s3sub1p:
      "Human sperm quality, dog sperm quality, horse fertility, bee colony health, insect biomass, and bird populations are all declining simultaneously, across different continents. Dogs do not attend university. Horses do not use contraception. Bees do not delay family formation for career reasons. The seven-species electromagnetic gradient — correlating the degree of electromagnetic exposure with the rate of reproductive decline — produces r = 0.909 (p = 0.005). No social or economic variable achieves comparable cross-species explanatory power.",
    s3sub2: "The systematic failure of pronatalist policy.",
    s3sub2p:
      "Every developed country that has attempted to reverse fertility decline through financial incentives has failed. Hungary achieved a modest increase from 1.23 to approximately 1.5 — still far below replacement. South Korea, Japan, and Singapore saw no effect whatsoever. If the decline were a rational response to economic incentives, sufficiently large counter-incentives should reverse it. They do not. BERM explains this: the decline is partly biological. The quadruple suppression of testosterone, oxytocin, dopamine, and cortisol dysregulation reduces both the desire for and the biological capacity for reproduction. Financial incentives address conscious decision-making. They cannot address unconscious biological erosion.",
    s3sub3: "The technology gradient in fertility.",
    s3sub3p:
      "The clearest natural experiments are communities that restrict technology. The Old Order Amish maintain a total fertility rate of approximately 6–7 children per woman — in the United States, where the national average is 1.62. They share the same healthcare system, the same legal framework, and the same economic environment as their neighbours. What they do not share is the electromagnetic environment: no grid electricity, no mobile phones, no WiFi, no LED lighting. Ultra-Orthodox Jewish communities in Israel, which use restricted “kosher phones” and observe technology-free Sabbaths, maintain a fertility rate above 6. Modern Mennonites who adopted technology saw their fertility converge toward the mainstream within one generation. The gradient is consistent across religions, cultures, and continents. Only communities that actually restrict electromagnetic technology maintain pre-modern fertility.",
    s3sub4: "The absence of a fertility floor.",
    s3sub4p:
      "Every demographic model implicitly assumes that fertility will stabilize at some natural minimum. No such floor has been found. South Korea passed through 1.3, then 1.0, then 0.8, and is now at 0.72. BERM explains this: if the decline has a biological component driven by cumulative electromagnetic exposure, and if that exposure continues to increase, there is no reason for the decline to stop. The “floor” does not exist because the mechanism is progressive.",
    s3sub5: "The convergence of late-civilizational symptoms.",
    s3sub5p:
      "The markers of civilizational decline identified by Glubb, Sorokin, and Spengler — declining fertility, hedonism, pessimism, loss of social cohesion, reliance on immigration, weakening of institutional religion, “an influx of foreigners” — are each independently predicted by BERM’s hormonal cascade. Testosterone decline reduces assertiveness and risk tolerance. Oxytocin decline reduces social trust and group bonding — precisely what Ibn Khaldun called asabiya and Turchin modelled as collective solidarity. Cortisol elevation shifts the population from proactive to reactive behaviour. BDNF decline impairs long-term strategic thinking. These are not cultural pathologies. They are the behavioural expression of a neuroendocrine cascade.",

    // Section 4
    s4title: "Before and After Electrification",
    s4p1: "The most striking implication of BERM’s framework concerns the difference between pre-electric and post-electric civilizational dynamics.",
    s4p2: "Before electrification — for the five thousand years of recorded civilizational history — the only significant electromagnetic influence on biology came from the sun. Solar activity oscillates in nested cycles: the 11-year Schwabe cycle, the 88-year Gleissberg cycle, and the approximately 200-year Suess/de Vries cycle. During grand solar minima — extended periods of low solar activity lasting 50 to 80 years — the electromagnetic burden on biology decreases, and biological recovery occurs. During grand solar maxima, the burden increases.",
    s4p3: "This produces a prediction: cultural renaissances should cluster around grand solar minima, and civilizational peaks should cluster around grand solar maxima. When tested against historical data, this prediction finds support. Eight of ten major European renaissances occurred during or immediately following grand solar minima: the Italian Renaissance during the Spörer Minimum, the Scientific Revolution and Dutch Golden Age during the Maunder Minimum, German Romanticism and the American founding during the Dalton Minimum. The British Empire’s two defining moments — the Glorious Revolution (1688) and Waterloo (1815) — fall precisely at the nadirs of the Maunder and Dalton Minima, when the model predicts maximum biological recovery.",
    s4p4: "The Suess cycle of approximately 200 years — the interval between successive grand minima — corresponds remarkably closely to Glubb’s empirically observed empire lifespan of 250 years. The difference is consistent with biological inertia: the recovery from a grand minimum takes a generation to translate into civilizational energy, adding roughly 50 years to the astronomical cycle.",
    s4p5: "This framework explains a persistent paradox in historical scholarship: why do periods of harsh climate (the Little Ice Age) coincide with periods of extraordinary intellectual achievement? The conventional assumption is that cold climate should suppress civilizational capacity. BERM’s answer is that the climate effect (cold) and the biological effect (recovery) are driven by different mechanisms. Solar minima reduce both solar irradiance (producing cold) and electromagnetic perturbation of biology (producing recovery). The population shivers — but thinks more clearly, bonds more strongly, and reproduces more vigorously.",
    s4p6: "After electrification, this cyclical dynamic breaks. The electromagnetic burden is no longer dominated by the sun. It is dominated by infrastructure: power grids, transmitters, lighting, and devices. This infrastructure does not oscillate with the solar cycle. It grows monotonically. The recovery windows that grand solar minima previously provided are now masked by an anthropogenic electromagnetic background that exceeds the solar signal by orders of magnitude.",
    s4p7: "A grand solar minimum is predicted for the period 2020–2053. If BERM’s framework is correct, this minimum will not produce a cultural renaissance comparable to those of previous centuries — because the electromagnetic infrastructure prevents the biological recovery that was previously the mechanism. If, contrary to prediction, a marked cultural flowering does occur in high-latitude nations during this period, the masking hypothesis is falsified.",

    // Section 5
    s5title: "The Gradient and the Open Question",
    s5p1: "Throughout history, civilizational decline was always followed by renewal — because there was always a population with higher biological capacity ready to replace the declining one. The Germanic tribes that replaced Rome had not spent centuries in lead-piped cities. The Arab armies that swept through Byzantium had not accumulated generations of urban electromagnetic exposure. The Mongol cavalry that conquered Song China came from an environment with virtually no artificial infrastructure.",
    s5p2: "The same gradient exists today. Sub-Saharan Africa — with the shortest cumulative electromagnetic exposure of any major population — has the highest fertility rates, the youngest age structure, and, if BERM is correct, the highest biological capacity. The migration flows from Africa and the Middle East into Europe follow the gradient of biological contrast just as Germanic migration followed the contrast with Rome. Europe’s institutional difficulty in managing these flows is, in BERM’s framework, itself a symptom of the hormonal cascade: reduced collective will (testosterone, oxytocin) and elevated anxiety-driven paralysis (cortisol).",
    s5p3: "What happens next is genuinely open. Joseph Tainter’s analysis of diminishing returns on complexity suggests that the infrastructure sustaining modern electromagnetic environments may itself be fragile. The global supply chains that manufacture and maintain mobile networks, power grids, and semiconductor production depend on a level of civilizational complexity that cannot be taken for granted. If the biological erosion that BERM describes degrades the human capacity to maintain that complexity — as the declining cognitive, motivational, and cooperative indicators suggest it might — then the infrastructure could contract, and with it, the electromagnetic burden.",
    s5p4: "In that scenario, the historical pattern reasserts itself: decline opens a recovery window, a less-burdened population fills the vacuum, and a new cycle begins. The “barbarian at the gates” is not the last of his kind — he is the perennial figure of civilizational renewal, appearing whenever the gradient between biologically depleted and biologically intact populations grows large enough to drive movement.",
    s5p5: "But there is an alternative scenario in which electrification outpaces decline — in which Africa and South Asia acquire the full electromagnetic infrastructure before the existing order contracts. In that case, the gradient would close not through renewal but through convergence: every population arriving at the same depleted state, with no biological reserve remaining anywhere.",

    // Section 6
    s6title: "The Deepest Difficulty",
    s6p1: "We do not know which scenario will prevail. But intellectual honesty requires acknowledging what the data does and does not support.",
    s6p2: "The rate of biological erosion is not slowing. It is accelerating. Sperm decline doubled its pace after the year 2000. Testosterone decline shows no sign of inflection. No fertility floor has been found anywhere in the world. Every pronatalist policy ever attempted has failed to reverse the trend, and most have failed to even slow it. The electromagnetic environment is not stabilising; it is growing exponentially with each generation of wireless technology. There is no significant political movement anywhere in the world to reduce electromagnetic exposure, no regulatory body that recognises the non-thermal biological mechanisms described here, and no economic incentive structure that would favour such reduction. The telecommunications industry generates approximately $1.8 trillion in annual revenue.",
    s6p3: "The political and institutional capacity to confront a challenge of this scale is itself subject to the biological erosion the challenge produces — testosterone decline reduces institutional assertiveness, BDNF decline impairs long-term strategic cognition, oxytocin decline erodes the collective solidarity required for coordinated action. This is the deepest difficulty: the mechanism that would need to be recognised impairs the very cognitive and social capacities required to recognise it.",
    s6p4: "The “deliberate management” scenario — in which humanity identifies the mechanism and redesigns its electromagnetic environment before irreversible damage accumulates — remains physically possible. Nothing in physics prevents it. But nothing in the current trajectory of technology deployment, regulatory policy, or political will suggests it is probable.",
    s6p5: "The cycle that the Prophets of Doom observed may continue through collapse — infrastructure fails, the electromagnetic burden lifts, biology recovers over generations, and a new civilisation emerges from the populations least damaged. This is the pattern of the past five thousand years. It is brutal, slow, and enormously costly in human suffering, but it is self-correcting.",
    s6p6: "Or the cycle may end — not because humanity transcends it, but because the global reach of electromagnetic infrastructure closes the last recovery windows before collapse can open them. In that case, the convergence is downward, permanent, and without historical precedent.",
    s6p7: "The data does not tell us which outcome is more likely. It tells us that the process is underway, that it is accelerating, and that the window for deliberate intervention — if it exists at all — is not wide.",

    // Falsification card
    falsCardTitle: "Testable prediction: 2020–2053 Grand Solar Minimum",
    falsCardText:
      "A grand solar minimum is underway (2020–2053). If high-latitude nations experience a marked cultural renaissance during this period, the electromagnetic masking hypothesis is incorrect. If they do not, it gains support.",
    falsCardSupport: "If no renaissance → hypothesis supported",
    falsCardFalsify: "If renaissance occurs → hypothesis falsified",
  },

  fi: {
    epistemicBanner:
      "Tämä sivu esittelee teoreettisen viitekehyksen, joka yhdistää biologiset mekanismit sivilisaatiodynamiikkaan. Biologinen todistusaineisto (molekulaarinen, hormonaalinen, lajien välinen) on empiirisesti tuettu. Sivilisaatiotulkinta on hypoteesi — yhdenmukainen historiallisen datan kanssa, mutta ei sen todistama. Korrelaatio auringon syklien ja sivilisaatiomuutosten välillä ei osoita syy-yhteyttä.",

    // Section 1
    s1title: "Kaava, jonka kaikki näkevät mutta kukaan ei osaa selittää",
    s1p1: "Läpi kirjoitetun historian sivilisaatiot ovat noudattaneet hämmästyttävän johdonmukaista kaavaa. Ne syntyvät räjähtävällä energialla, laajenevat valtavien alueiden yli, kukoistavat aikansa ja sitten — poikkeuksetta — taantuvat. Kaava on niin säännöllinen, että kolmensadan vuoden ajan vakavasti otettavat ajattelijat ovat yrittäneet ymmärtää sitä. Giambattista Vico kuvasi sen vuonna 1725 kolmen aikakauden toistuvana kiertänä. Oswald Spengler näki sen elävän organismin orgaanisena elinkaarena. Arnold Toynbee dokumentoi sen kahdenkymmenenyhden sivilisaation poikkileikkauksena. John Bagot Glubb, joka oli johtanut Arabilegioonaa Lähi-idässä ja tutkinut kolmetoista imperiumia, havaitsi että kukin kesti noin 250 vuotta ja kulki samat kuusi vaihetta samassa järjestyksessä. Peter Turchin käänsi kaavan differentiaaliyhtälöiksi ja löysi noin 80–100 vuoden sekuläärisyklit sen sisältä.",
    s1p2: "Nämä ajattelijat olivat erimielisiä lähes kaikesta — menetelmistä, ideologiasta ja laajuudesta. Useimmat eivät tunteneet toistensa töitä. Silti he päätyivät itsenäisesti samaan havaintoon: sivilisaatiot eivät etene lineaarisesti. Ne nousevat ja laskevat sykleinä, ja myöhäisvaiheita leimaavat hämmästyttävän johdonmukaiset oireet — laskevat syntyvyysluvut, lisääntyvä hedonismi, kollektiivisen tahdon menetys, pessimismi, riippuvuus ulkomaisesta työvoimasta ja se, mitä Glubb kutsui ”poikkeukselliseksi kevytmielisyyden lisääntymiseksi.”",
    s1p3: "Kysymys, johon kukaan heistä ei pystynyt vastaamaan: miksi?",
    s1p4: "Tavanomaiset selitykset liittävät sivilisaation taantumisen kulttuurisiin, taloudellisiin tai institutionaalisiin tekijöihin. Yhteiskunnat muuttuvat itsetyötyväisiksi. Eliittejä ylituotetaan. Monimutkaisuus ylittää tuottavuutensa. Nämä selitykset kuvaavat mitä tapahtuu, mutta eivät sitä miksi se tapahtuu niin mekaanisen säännöllisesti, sivilisaatioissa joilla ei ole yhteistä kieltä, uskontoa tai poliittista rakennetta. Jos taantuminen olisi puhtaasti kulttuurista, sen pitäisi olla estettävissä kulttuurisin keinoin. Silti Etelä-Korea — maa jolla on vahvat perhearvot, poikkeuksellinen työmoraali ja yli 200 miljardia dollaria syntyvyyspolitiikkaan sijoitettuna vuodesta 2006 — omaa kirjoitetun historian alhaisimman hedelmällisyysluvun, 0,72 lasta naista kohden. Politiikkatoimet eivät hidastaneet laskua. Ne eivät edes estäneet sen kiihtymistä.",
    s1p5: "Jotain perustavanlaatuisempaa on käynnissä.",

    // Section 2
    s2title: "Sivilisaatiokyvykkyyden biologinen substraatti",
    s2p1: "BERM — bioeläktromagneettinen lisääntymismalli — esittää, että sivilisaatioiden kulttuuristen, taloudellisten ja poliittisten dynamiikkojen alla on biologinen substraatti: väestön kollektiivinen fysiologinen tila. Tämä substraatti on mitattavissa. Miesten testosteroni on laskenut noin 1,2 % vuodessa 1980-luvulta lähtien, riippumatta iästä, lihavuudesta ja elämäntavasta. Siittiöiden pitoisuus on pudonnut yli puoleen vuodesta 1973, ja laskuvauhti kiihtyy. Melatoniini — hormoni joka säätelee unta, vuorokausirytmiä ja immuunitoimintaa — on kroonisesti vaimentunut modernissa sähkömagneettisessa ja valoympäristössä. D-vitamiinin puutos koskee lähes puolta maailman väestöstä. Nämä eivät ole kulttuurisia valintoja. Ne ovat biologisia mittauksia.",
    s2p2: "BERM tunnistaa mekanismin: sähköisen infrastruktuurin tuottamat sähkömagnäettiset kentät — sähköverkot, langattomat verkot, LED-valaistus, henkilökohtaiset laitteet — aktivoivat jänniteohjattuja kalsiumkanavia solukalvoissa, häiriten kalsiumsignaalikaskadeja jotka ohjaavat käytännössä jokaista fysiologista prosessia: hormonituotantoa, välittäjäaineiden vapautumista, immuunitoimintaa, DNA:n korjausta ja lisääntymistä. Vaikutus on kumulatiivinen, krooninen ja suurelta osin huomaamaton. Se ei tuota akuutteja oireita. Se tuottaa asteittaisen, koko väestön laajuisen biologisen kapasiteetin rapautumisen.",
    s2p3: "Tämä ei ole metafora. Se on mitattava, testattava, falsifioitava biologinen prosessi. Yksi ainoa geenimutaatio yhdessä kalsiumkanavageenissä — CACNA1C, Timothyn oireyhtymän aiheuttaja — tuottaa jokaisen taudinkuvan jonka BERM ennustaa: sydämen rytmihäiriöt, immuunihäiriöt, aineenvaihduntahäiriöt, autismikirjon piirteet ja kasvojen dysmorfismin. BERM esittää, että krooninen ympäristön sähkömagneettinen altistus tuottaa saman kirjon vaikutuksia, laadullisesti mutta pienemmallä voimakkuudella, kokonaisissa väestöissä vuosikymmenten kuluessa.",

    // Section 3
    s3title: "Mitä tämä selittää, mitä mikään muu ei voi",
    s3sub1: "Hedelmällisyyden samanaikainen lasku kaikilla lajeilla.",
    s3sub1p:
      "Ihmisten siittiöiden laatu, koirien siittiöiden laatu, hevosten hedelmällisyys, mehiläisyhdyskuntien terveys, hyönteisbiomassa ja lintupopulaatiot laskevat kaikki samanaikaisesti, eri mantereilla. Koirat eivät käy yliopistoa. Hevoset eivät käytä ehkäisyä. Mehiläiset eivät lykätä perheenperustamista urasyistä. Seitsemän lajin sähkömagneettinen gradientti — joka korreloi sähkömagneettisen altistuksen asteen ja lisääntymisen laskuvauhdin — tuottaa r = 0,909 (p = 0,005). Mikään sosiaalinen tai taloudellinen muuttuja ei saavuta vertailukelpoista lajien välistä selitysvoimaa.",
    s3sub2: "Syntyvyyspolitiikan järjestelmällinen epäonnistuminen.",
    s3sub2p:
      "Jokainen kehittynyt maa, joka on yrittänyt kääntää hedelmällisyyden laskun taloudellisilla kannustimilla, on epäonnistunut. Unkari saavutti vaatimattoman nousun 1,23:sta noin 1,5:een — edelleen kaukana korvautumistasosta. Etelä-Korea, Japani ja Singapore eivät nähneet minkäänlaista vaikutusta. Jos lasku olisi rationaalinen vastaus taloudellisiin kannustimiin, riittävän suurten vastakannustimien pitäisi kääntää se. Ne eivät tee sitä. BERM selittää tämän: lasku on osittain biologista. Testosteronin, oksitosiinin, dopamiinin nelinkertainen tukahduttaminen sekä kortisolin säätelhäiriö vähentävät sekä halua että biologista kykyä lisääntyä. Taloudelliset kannustimet kohdistuvat tietoiseen päätöksentekoon. Ne eivät voi kohdistua tiedostamattomaan biologiseen rapautumiseen.",
    s3sub3: "Teknologiagradientti hedelmällisyydessä.",
    s3sub3p:
      "Selkeimpänä luonnollisena kokeena toimivat yhteisöt, jotka rajoittavat teknologiaa. Vanhan järjestyksen amishit ylläpitävät kokonaishedelmällisyyslukua noin 6–7 lasta naista kohden — Yhdysvalloissa, jossa kansallinen keskiarvo on 1,62. He jakavat saman terveydenhuoltojärjestelmän, saman oikeudellisen kehyksen ja saman taloudellisen ympäristön naapureidensa kanssa. Mitä he eivät jaa, on sähkömagneettinen ympäristö: ei verkkovirtaa, ei matkapuhelimia, ei WiFiä, ei LED-valaistusta. Ultraortodoksiset juutalaisyhteisöt Israelissa, jotka käyttävät rajoitettuja ”kosher-puhelimia” ja viettävät teknologiavapaata sapattia, ylläpitävät hedelmällisyyslukua yli 6. Modernit mennoniitat, jotka omaksuivat teknologian, näkivät hedelmällisyytensä lähestyneen valtavirtaa yhden sukupolven kuluessa. Gradientti on johdonmukainen uskontojen, kulttuurien ja mantereiden välillä. Vain yhteisöt, jotka todella rajoittavat sähkömagneettista teknologiaa, ylläpitävät esimodernia hedelmällisyyttä.",
    s3sub4: "Hedelmällisyyden lattian puuttuminen.",
    s3sub4p:
      "Jokainen demografinen malli olettaa implisiittisesti, että hedelmällisyys vakiintuu jollekin luonnolliselle minimitasolle. Tällaista lattiaa ei ole löytynyt. Etelä-Korea läpäisi 1,3:n, sitten 1,0:n, sitten 0,8:n ja on nyt 0,72:ssa. BERM selittää tämän: jos laskulla on biologinen komponentti, jota ohjaa kumulatiivinen sähkömagneettinen altistus, ja jos altistus jatkaa kasvuaan, laskun päättymiselle ei ole syytä. ”Lattiaa” ei ole olemassa, koska mekanismi on etenevä.",
    s3sub5: "Myöhäissivilisaation oireiden yhdentyminen.",
    s3sub5p:
      "Sivilisaation taantumisen merkit, jotka Glubb, Sorokin ja Spengler tunnistivat — laskeva hedelmällisyys, hedonismi, pessimismi, sosiaalisen koheesion menetys, riippuvuus maahanmuutosta, institutionaalisen uskonnon heikentyminen, ”ulkomaalaisten tulva” — ovat kukin itsenäisesti ennustettavissa BERM:n hormonikaskadin kautta. Testosteronin lasku vähentää päättäväisyyttä ja riskinsietokykyä. Oksitosiinin lasku vähentää sosiaalista luottamusta ja ryhmäsidonnaisuutta — juuri sitä mitä Ibn Khaldun kutsui nimellä asabiya ja Turchin mallisti kollektiivisena solidaarisuutena. Kortisolin kohoaminen siirtää väestön proaktiivisesta reaktiiviseen käyttäytymiseen. BDNF:n lasku heikentää pitkän aikavälin strategista ajattelua. Nämä eivät ole kulttuurisia patologioita. Ne ovat neuroendokriinisen kaskadin käyttäytymisellinen ilmaus.",

    // Section 4
    s4title: "Ennen ja jälkeen sähköistämisen",
    s4p1: "BERM:n viitekehyksen hämmästyttävin seuraus koskee erosähköisten ja jälkisähköisten sivilisaatiodynamiikkojen välistä.",
    s4p2: "Ennen sähköistämistä — viiden tuhannen vuoden kirjoitetun sivilisaatiohistorian ajan — ainoa merkittävä biologiaan kohdistuva sähkömagneettinen vaikutus tuli auringosta. Auringon aktiivisuus värähtelee sisäkkäisissä sykleissä: 11 vuoden Schwabe-sykli, 88 vuoden Gleissberg-sykli ja noin 200 vuoden Suess/de Vries -sykli. Suurminimien aikana — pitkäkestoiset matalan aurinkoaktiivisuuden jaksot, 50–80 vuotta — biologiaan kohdistuva sähkömagneettinen kuormitus vähenee ja biologinen palautuminen tapahtuu. Suurmaksimien aikana kuormitus kasvaa.",
    s4p3: "Tämä tuottaa ennusteen: kulttuuristen renessanssien pitäisi kasaantua suurminimien ympärille, ja sivilisaatioiden huippujen suurmaksimien ympärille. Historiallista dataa vasten testattuna ennuste saa tukea. Kahdeksan kymmenestä merkittävästä eurooppalaisesta renessanssista tapahtui suurminimien aikana tai välittömästi niiden jälkeen: Italian renessanssi Spörer-minimin aikana, tieteellinen vallankumous ja Hollannin kultakausi Maunder-minimin aikana, saksalainen romantiikka ja Amerikan perustaminen Dalton-minimin aikana. Brittiläisen imperiumin kaksi määrittävää hetkeä — kunniallinen vallankumous (1688) ja Waterloo (1815) — osuvat täsmälleen Maunder- ja Dalton-minimien pohjiin, jolloin malli ennustaa biologisen palautumisen maksimin.",
    s4p4: "Noin 200 vuoden Suess-sykli — peräkkäisten suurminimien väli — vastaa hämmästyttävän läheisesti Glubbin empiirisesti havaitsemaa imperiumin eliniänodotetta, 250 vuotta. Ero on yhdenmukainen biologisen inertian kanssa: suurminimin palautuminen vaatii yhden sukupolven muuntuakseen sivilisaatioenergiaksi, mikä lisää noin 50 vuotta astronomiseen sykliin.",
    s4p5: "Tämä viitekehys selittää historiantutkimuksen sitkeän paradoksin: miksi ankaran ilmaston kaudet (pieni jääkausi) osuvat yhteen poikkeuksellisen älyllisen saavutuksen kausien kanssa? Tavanomainen oletus on, että kylmän ilmaston pitäisi tukahduttaa sivilisaatiokyky. BERM:n vastaus on, että ilmastovaikutus (kylmä) ja biologinen vaikutus (palautuminen) johtuvat eri mekanismeista. Auringon minimit vähentävät sekä auringon säteilyvoimakkuutta (tuottaen kylmyyttä) että biologian sähkömagneettista häiriötä (tuottaen palautumista). Väestö palelee — mutta ajattelee selkeämmin, sitoutuu vahvemmin ja lisääntyy voimakkaammin.",
    s4p6: "Sähköistämisen jälkeen tämä syklinen dynamiikka murtuu. Sähkömagneettista kuormitusta ei enää hallitse aurinko. Sitä hallitsee infrastruktuuri: sähköverkot, lähettimet, valaistus ja laitteet. Tämä infrastruktuuri ei värähtele auringon syklin mukaan. Se kasvaa monotonisesti. Palautumisikkunat, jotka suurminimit aiemmin tarjosivat, ovat nyt peittyneet ihmisen tuottaman sähkömagneettisen taustan alle, joka ylittää auringon signaalin kertaluokilla.",
    s4p7: "Suurminimi on ennustettu kaudelle 2020–2053. Jos BERM:n viitekehys on oikeassa, tämä minimi ei tuota aiempien vuosisatojen kaltaista kulttuurista renessanssia — koska sähkömagneettinen infrastruktuuri estää biologisen palautumisen, joka aiemmin oli mekanismina. Jos ennusteen vastaisesti merkittävä kulttuurinen kukoistus tapahtuu korkean leveysasteen maissa tänä aikana, peittymishypoteesi on falsifioitu.",

    // Section 5
    s5title: "Gradientti ja avoin kysymys",
    s5p1: "Läpi historian sivilisaation taantumista seurasi aina uudistuminen — koska aina oli olemassa väestö, jolla oli korkeampi biologinen kapasiteetti korvaamaan taanätuvan. Germaaniheimot, jotka korvasivat Rooman, eivät olleet viettäneet vuosisatoja lyijyputkitetuissa kaupungeissa. Arabiarmeijat, jotka pyälsivät Bysantin läpi, eivät olleet keränneet sukupolvien kaupunkien sähkömagneettista altistusta. Mongolien ratsuväki, joka valloitti Song-Kiinan, tuli ympäristöstä jossa ei ollut käytännössä lainkaan keinotekoista infrastruktuuria.",
    s5p2: "Sama gradientti on olemassa tänään. Saharan eteläpuolisella Afrikalla — jolla on suurten väestöjen lyhyin kumulatiivinen sähkömagneettinen altistus — on korkeimmat hedelmällisyysluvut, nuorin ikärakenne ja, jos BERM on oikeassa, korkein biologinen kapasiteetti. Muuttovirrat Afrikasta ja Lähi-idästä Eurooppaan noudattavat biologisen kontrastin gradienttia aivan kuten germaaninen muuttoliike noudatti kontrastia Rooman kanssa. Euroopan institutionaalinen vaikeus hallita näitä virtoja on BERM:n viitekehyksessä itsessään hormonikaskadin oire: vähentynyt kollektiivinen tahto (testosteroni, oksitosiini) ja kohonnut ahdistusperäinen halvaantuminen (kortisoli).",
    s5p3: "Se mitä tapahtuu seuraavaksi, on aidosti avoin. Joseph Tainterin analyysi monimutkaisuuden vähenevistä tuotoista viittaa siihen, että moderneja sähkömagneettisia ympäristöjä ylläpitävä infrastruktuuri voi olla itsessään hauras. Globaalit toimitusketjut, jotka valmistavat ja ylläpitävät mobiiliverkkoja, sähköverkkoja ja puolijohdetu otantoa, ovat riippuvaisia sivilisaation monimutkaisuuden tasosta, jota ei voi pitää itsestäänselvyytenä. Jos biologinen rapautuminen, jota BERM kuvaa, heikentää ihmisten kykyä ylläpitää tätä monimutkaisuutta — kuten laskevat kognitiiviset, motivationaaliset ja yhteistyöindikaattorit viittaavat — infrastruktuuri voi supistua ja sen myötä sähkömagneettinen kuormitus.",
    s5p4: "Siinä skenaariossa historiallinen kaava vahvistuu uudelleen: taantuminen avaa palautumisikkunan, vähemmän kuormittunut väestö täyttää tyhjiön ja uusi sykli alkaa. ”Porttien barbaari” ei ole lajinsa viimeinen — hän on sivilisaation uudistumisen ikuinen hahmo, joka ilmestyy aina kun biologisesti ehtyneiden ja biologisesti koskemattomien väestöjen välinen gradientti kasvaa riittävän suureksi liikuttaakseen väkimassoja.",
    s5p5: "Mutta on olemassa vaihtoehtoinen skenaario, jossa sähköistäminen ohittaa taantumisen — jossa Afrikka ja Etelä-Aasia hankkivat täyden sähkömagneettisen infrastruktuurin ennen kuin nykyinen järjestys supistuu. Siinä tapauksessa gradientti sulkeutuisi ei uudistumisen kautta vaan yhdentymisen: jokainen väestö päätyisi samaan ehtyneeseen tilaan, ilman biologista reserviä missään.",

    // Section 6
    s6title: "Syvin vaikeus",
    s6p1: "Emme tiedä kumpi skenaario toteutuu. Mutta älyllinen rehellisyys edellyttää sen tunnustamista, mitä data tukee ja mitä ei.",
    s6p2: "Biologisen rapautumisen vauhti ei ole hidastumassa. Se kiihtyy. Siittiöiden lasku kaksinkertaisti vauhtinsa vuoden 2000 jälkeen. Testosteronin lasku ei osoita merkkejä taittumisesta. Hedelmällisyyden lattiaa ei ole löytynyt mistään maailmasta. Jokainen koskaan kokeiltu syntyvyyspolitiikka on epäonnistunut trendin kääntämisessä, ja useimmat eivät ole onnistuneet edes hidastamaan sitä. Sähkömagneettinen ympäristö ei vakiinnu; se kasvaa eksponentiaalisesti jokaisen langattoman teknologian sukupolven myötä. Missään maailmassa ei ole merkittävää poliittista liikettä sähkömagneettisen altistuksen vähentämiseksi, yhtään sääntelyelintä joka tunnustaisi tässä kuvatut ei-termiset biologiset mekanismit, eikä taloudellista kannustinrakennetta joka suosisi sellaista vähennystä. Tietoliikenneala tuottaa noin 1,8 biljoonan dollarin vuosittaisen liikevaihdon.",
    s6p3: "Poliittinen ja institutionaalinen kyky kohdata tämän mittakaavan haaste on itsessään alttiina biologiselle rapautumiselle, jota haaste tuottaa — testosteronin lasku vähentää institutionaalista päättäväisyyttä, BDNF:n lasku heikentää pitkän aikavälin strategista kognitiota, oksitosiinin lasku rappeuttaa koordinoituun toimintaan tarvittavaa kollektiivista solidaarisuutta. Tämä on syvin vaikeus: mekanismi, joka pitäisi tunnistaa, heikentää juuri niitä kognitiivisia ja sosiaalisia kykejä, joita sen tunnistaminen edellyttää.",
    s6p4: "”Tietoisen hallinnan” skenaario — jossa ihmiskunta tunnistaa mekanismin ja uudelleensuunnittelee sähkömagneettisen ympäristönsä ennen kuin peruuttamaton vahinko kertyy — on fysikaalisesti mahdollinen. Mikään fysiikassa ei estä sitä. Mutta mikään teknologian käyttöönoton, sääntelypolitiikan tai poliittisen tahdon nykyisessä kehityskulussa ei viittaa siihen, että se olisi todennäköistä.",
    s6p5: "Sykli, jonka Tuhon profeetat havaitsivat, voi jatkua romahduksen kautta — infrastruktuuri pettää, sähkömagneettinen kuormitus kevenee, biologia palautuu sukupolvien kuluessa ja uusi sivilisaatio nousee vähiten vahingoittuneista väestöistä. Tämä on viiden tuhannen vuoden kaava. Se on raaka, hidas ja ihmiskärsimyksessään valtavan kallis, mutta itsekorjautuva.",
    s6p6: "Tai sykli voi päättyä — ei siksi että ihmiskunta ylittäisi sen, vaan siksi että sähkömagneettisen infrastruktuurin maailmanlaajuinen ulottuvuus sulkee viimeiset palautumisikkunat ennen kuin romahdus voi avata niitä. Siinä tapauksessa yhdentyminen on aleneva, pysyvä ja vailla historiallista ennakkotapausta.",
    s6p7: "Data ei kerro meille kumpi lopputulos on todennäköisempi. Se kertoo, että prosessi on käynnissä, että se kiihtyy ja että tietoisen väliintulon ikkuna — jos sellaista ylipäätään on — ei ole leveä.",

    // Falsification card
    falsCardTitle: "Testattava ennuste: 2020–2053 suurminimi",
    falsCardText:
      "Suurminimi on käynnissä (2020–2053). Jos korkean leveysasteen maat kokevat merkittävän kulttuurisen renessanssin tänä aikana, sähkömagneettinen peittymishypoteesi on virheellinen. Jos eivät, hypoteesi saa tukea.",
    falsCardSupport: "Jos ei renessanssia → hypoteesi tuettu",
    falsCardFalsify: "Jos renessanssi tapahtuu → hypoteesi falsifioitu",
  },
};

function pickEssayCopy(locale: string) {
  if (locale === "fi") return ESSAY_COPY.fi;
  return ESSAY_COPY.en;
}

export function CivilizationEssay({ locale }: { locale: string }) {
  const d = pickEssayCopy(locale);

  return (
    <div className="max-w-3xl mx-auto">
      {/* Epistemic Banner */}
      <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-5 mb-10 flex gap-3 items-start">
        <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
        <p className="text-sm text-foreground-muted leading-relaxed">
          {d.epistemicBanner}
        </p>
      </div>

      {/* Section 1: The Pattern Everyone Sees But No One Can Explain */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s1title}</h2>
      <p className="text-base leading-relaxed text-foreground-muted mb-4 first-letter:text-3xl first-letter:font-bold first-letter:mr-1">
        {d.s1p1}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s1p2}
      </p>
      <p className="text-xl font-bold text-center my-8 italic">{d.s1p3}</p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s1p4}
      </p>
      <p className="text-lg font-semibold text-center my-8">{d.s1p5}</p>

      {/* Section 2: The Biological Substrate of Civilizational Capacity */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s2title}</h2>
      <p className="text-base leading-relaxed text-foreground-muted mb-4 first-letter:text-3xl first-letter:font-bold first-letter:mr-1">
        {d.s2p1}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s2p2}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s2p3}
      </p>

      {/* Section 3: What This Explains That Nothing Else Can */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s3title}</h2>

      <h3 className="text-lg font-semibold mb-2 mt-8">{d.s3sub1}</h3>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s3sub1p}
      </p>

      <h3 className="text-lg font-semibold mb-2 mt-8">{d.s3sub2}</h3>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s3sub2p}
      </p>

      <h3 className="text-lg font-semibold mb-2 mt-8">{d.s3sub3}</h3>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s3sub3p}
      </p>

      <h3 className="text-lg font-semibold mb-2 mt-8">{d.s3sub4}</h3>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s3sub4p}
      </p>

      <h3 className="text-lg font-semibold mb-2 mt-8">{d.s3sub5}</h3>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s3sub5p}
      </p>

      {/* Section 4: Before and After Electrification */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s4title}</h2>
      <p className="text-base leading-relaxed text-foreground-muted mb-4 first-letter:text-3xl first-letter:font-bold first-letter:mr-1">
        {d.s4p1}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p2}
      </p>

      <div className="rounded-xl border border-card-border p-4 bg-card-bg my-6">
        <SolarMiniTimeline />
      </div>

      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p3}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p4}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p5}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p6}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s4p7}
      </p>

      {/* Section 5: The Gradient and the Open Question */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s5title}</h2>
      <p className="text-base leading-relaxed text-foreground-muted mb-4 first-letter:text-3xl first-letter:font-bold first-letter:mr-1">
        {d.s5p1}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s5p2}
      </p>

      <div className="rounded-xl border border-card-border p-4 bg-card-bg my-6">
        <BiocapSparkline />
      </div>

      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s5p3}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s5p4}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s5p5}
      </p>

      {/* Section 6: The Deepest Difficulty */}
      <h2 className="text-2xl font-bold mb-4 mt-12">{d.s6title}</h2>
      <p className="text-base leading-relaxed text-foreground-muted mb-4 first-letter:text-3xl first-letter:font-bold first-letter:mr-1">
        {d.s6p1}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p2}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p3}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p4}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p5}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p6}
      </p>
      <p className="text-sm leading-relaxed text-foreground-muted mb-4">
        {d.s6p7}
      </p>

      {/* Falsification Card */}
      <div className="border-l-4 border-emerald-500 bg-card-bg rounded-r-lg p-5 my-10">
        <h3 className="text-lg font-bold mb-2">{d.falsCardTitle}</h3>
        <p className="text-sm text-foreground-muted mb-3">
          {d.falsCardText}
        </p>
        <div className="flex gap-4 text-xs">
          <span className="text-emerald-400">{d.falsCardSupport}</span>
          <span className="text-red-400">{d.falsCardFalsify}</span>
        </div>
      </div>
    </div>
  );
}
