import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { StudyCitation } from "@/components/StudyCitation";
import { TranslationNotice } from "@/components/TranslationNotice";
import { pickCopy } from "@/lib/i18n";

export type ReproductiveRegulationContext = "model" | "pathopege" | "pathopolites" | "patopolis" | "patokinesis" | "epistapege" | "civilization" | "behavior" | "coordination" | "convergence" | "proxy";

const COPY = {
  en: {
    label: "Reproductive regulation · behaviour · feedback", link: "Follow the three branches and their evidence",
    model: { title: "One biological state, three reproductive routes", text: "Reproductive regulation branches into motivation and realised encounters, physiological capacity, and caregiving. A selective biological brake can alter one output while another remains available. BERM connects these measured dependencies to its receiving state: opportunity and realised action join reproductive capacity before outcomes are aggregated over couples and time." },
    pathopege: { title: "A selective reproductive brake has experimental anchors", text: "RFRP-3 administration in naked mole-rats reduced sexually directed investigation and prevented a progesterone rise while several other social and motor responses remained intact. Marmoset social transitions changed LH and ovulation. These experiments locate reversible reproductive regulation more precisely than a general stress score; the field-triggered entry into those circuits is BERM’s conditional synthesis." },
    pathopolites: { title: "Caregiving and own reproduction can diverge", text: "Prolactin-sensitive circuits can support contact with offspring while a different prolactin pathway restrains reproductive-axis activation. Human fatherhood research also separates hormonal change, caregiving and sexual activity. A behavioural profile therefore records the amount and target of care alongside desire, approaches and physiological capacity." },
    patopolis: { title: "A changed response alters another person’s opportunities", text: "A father’s oxytocin intervention changed the father–infant interaction and parallel infant responses. Sleep loss changed both social distance and others’ willingness to approach. BERM uses these interpersonal transitions to connect individual state with realised contact, care and cooperation; external resources and constraints retain their own measured contribution." },
    patokinesis: { title: "Social transmission has a measurable time course", text: "Friendship and workplace studies link a peer’s birth with the timing of later reproductive transitions. They identify networks and lags, while hormonal interventions identify different upstream transitions. BERM joins these levels through actual encounters: an individual’s output changes the input encountered by others and by later cohorts." },
    epistapege: { title: "Keep the state, action and reported reason in temporal order", text: "The same person can report desire, make a choice, encounter a partner and describe the reason at different times. Published multivariable studies already connect several of these outputs. BERM retains a stated reason as an observation within that sequence, then follows its reuse in shared explanations and institutions." },
    civilization: { title: "Contact, caregiving and institutions carry different memories", text: "Biological regulation changes whom people approach, which encounters occur and how care is allocated. Births and relationships then change the next stream of social cues. Repeated actions and their explanations also shape practices and institutions. BERM connects these feedbacks across timescales; recovery of a population need not follow the recovery time of one hormone." },
    behavior: { title: "From felt motivation to realised reproduction", text: "Animal interventions show selective changes in reproductive interest; human hormone interventions locate sexual responses and target-specific endocrine gates. BERM follows desire into approach, the other person’s response and an actual encounter. The biological success of that encounter remains a separate branch, alongside caregiving and its feedback." },
    coordination: { title: "Prolactin reveals why one signal can have different outputs", text: "Prolactin–kisspeptin experiments locate a reproductive-axis brake; a distinct prolactin-sensitive MPOA–VTA pathway supports offspring contact. In women with hyperprolactinaemia, kisspeptin increased LH pulses without a significant overall fall in prolactin. BERM connects the studies through the shared hormone and the receiving circuit, retaining each experiment’s own endpoint and time course." },
    convergence: { title: "Connect studies at the variable they actually share", text: "Hormonal challenge, social removal and return, neural-circuit intervention and longitudinal follow-up identify different parts of reproductive regulation. The useful convergence is a named transition—such as LH responsiveness, partner-directed approach or caregiving contact. A shared cohort stays one data family when its hormone, sexual-activity and fatherhood findings are brought together." },
    proxy: { title: "Eight axes become a joint measurement problem", text: "Care allocation, contact, stress, courtship, signalling, social regulation, hormone dynamics and effort occupy different positions in the causal sequence. Existing studies already combine some of them within the same people. Connecting these measurements recovers information lost when each outcome is assigned a separate social explanation." },
  },
  fi: {
    label: "Lisääntymisen säätely · käyttäytyminen · palaute", link: "Seuraa kolmea haaraa ja niiden näyttöä",
    model: { title: "Yksi biologinen tila, kolme lisääntymiseen jatkuvaa reittiä", text: "Lisääntymisen säätely haarautuu motivaatioon ja toteutuneisiin kohtaamisiin, fysiologiseen kapasiteettiin sekä hoivaan. Valikoiva biologinen jarru voi muuttaa yhtä ulostuloa toisen säilyessä. BERM yhdistää mitatut riippuvuudet vastaanottavaan tilaan: mahdollisuus ja toteutunut toiminta liittyvät lisääntymiskykyyn ennen tulosten kokoamista parien ja ajan yli." },
    pathopege: { title: "Valikoivalla lisääntymisjarrulla on kokeelliset ankkurit", text: "RFRP-3:n anto paljaskoirarotille vähensi seksuaalisesti kohdennettua tutkimista ja esti progesteronin nousun useiden muiden sosiaalisten ja motoristen vasteiden säilyessä. Marmosettien sosiaaliset tilasiirtymät muuttivat LH:ta ja ovulaatiota. Kokeet paikantavat palautuvan lisääntymissäätelyn yleistä stressimittaria tarkemmin; kentästä näihin piireihin johtava alkuvaihe on BERM:n ehdollinen synteesi." },
    pathopolites: { title: "Hoiva ja oma lisääntyminen voivat eriytyä", text: "Prolaktiinille herkät piirit voivat tukea poikaskontaktia samalla kun toinen prolaktiinireitti jarruttaa lisääntymisakselin aktivoitumista. Ihmisen isyystutkimus erottaa myös hormonimuutoksen, hoivan ja seksuaalisen toiminnan. Käyttäytymisprofiilissa mitataan siksi hoivan määrä ja kohde halun, lähestymisen ja fysiologisen kapasiteetin rinnalla." },
    patopolis: { title: "Muuttunut vaste muuttaa myös toisen mahdollisuuksia", text: "Isän oksitosiini-interventio muutti isän ja vauvan vuorovaikutusta sekä vauvan rinnakkaisia vasteita. Univaje muutti sosiaalista etäisyyttä ja muiden halukkuutta lähestyä. BERM yhdistää näiden henkilöiden välisten siirtymien kautta yksilön tilan toteutuneeseen kontaktiin, hoivaan ja yhteistyöhön; ulkoiset resurssit ja rajoitteet säilyttävät oman mitatun osuutensa." },
    patokinesis: { title: "Sosiaalisella välityksellä on mitattava aikakulku", text: "Ystävyys- ja työpaikkatutkimukset yhdistävät vertaisen lapsen syntymän myöhempien lisääntymissiirtymien ajoitukseen. Ne paikantavat verkostoja ja viiveitä, kun taas hormonikokeet paikantavat erillisiä alkupään siirtymiä. BERM yhdistää tasot toteutuvien kohtaamisten kautta: yksilön ulostulo muuttaa muiden ja myöhempien kohorttien saamaa syötettä." },
    epistapege: { title: "Säilytä tilan, teon ja kerrotun syyn aikajärjestys", text: "Sama ihminen voi kertoa halustaan, tehdä valinnan, kohdata kumppanin ja kuvata syyn eri ajankohtina. Julkaistut monimuuttujatutkimukset yhdistävät jo osan näistä ulostuloista. BERM säilyttää kerrotun syyn havaintona tässä järjestyksessä ja seuraa sen uudelleenkäyttöä yhteisissä selityksissä ja instituutioissa." },
    civilization: { title: "Kontakteilla, hoivalla ja instituutioilla on eri muistit", text: "Biologinen säätely muuttaa lähestymistä, toteutuvia kohtaamisia ja hoivan kohdentumista. Syntymät ja suhteet muuttavat seuraavaksi sosiaalisten vihjeiden virtaa. Toistuvat teot ja niiden selitykset muokkaavat myös käytäntöjä ja instituutioita. BERM yhdistää nämä palautteet eri aikaskaaloilla; väestön palautuminen ei välttämättä seuraa yhden hormonin palautumisaikaa." },
    behavior: { title: "Koetusta motivaatiosta toteutuvaan lisääntymiseen", text: "Eläininterventiot osoittavat lisääntymiskiinnostuksen valikoivia muutoksia; ihmisen hormonikokeet paikantavat seksuaalisia vasteita ja kohdereittien endokriinisia portteja. BERM seuraa halua lähestymiseen, toisen vasteeseen ja toteutuneeseen kohtaamiseen. Kohtaamisen biologinen onnistuminen säilyy erillisenä haarana hoivan ja sen palautteen rinnalla." },
    coordination: { title: "Prolaktiini näyttää, miksi yksi signaali voi tuottaa eri ulostuloja", text: "Prolaktiini–kisspeptiinikokeet paikantavat lisääntymisakselin jarrua; erillinen prolaktiinille herkkä MPOA–VTA-reitti tukee poikaskontaktia. Hyperprolaktinemiasta kärsivillä naisilla kisspeptiini lisäsi LH-pulsseja ilman prolaktiinin merkitsevää laskua koko aineistossa. BERM yhdistää tutkimukset yhteisen hormonin ja vastaanottavan piirin kautta säilyttäen kunkin kokeen oman päätepisteen ja aikakulun." },
    convergence: { title: "Yhdistä tutkimukset niiden todella jakaman muuttujan kohdalta", text: "Hormonialtistus, sosiaalinen irrotus ja paluu, hermopiiri-interventio ja pitkittäisseuranta paikantavat lisääntymissäätelyn eri osia. Hyödyllinen konvergenssi on nimetty siirtymä, kuten LH-vaste, kumppaniin kohdistuva lähestyminen tai hoivakontakti. Yhteinen kohortti säilyy yhtenä aineistoperheenä, kun sen hormoni-, seksuaalitoiminta- ja isyyslöydökset yhdistetään." },
    proxy: { title: "Kahdeksasta akselista tulee yhteismittauksen kysymys", text: "Hoivan kohdentuminen, kontakti, stressi, seurustelu, signalointi, sosiaalinen säätely, hormonidynamiikka ja vaivannäkö sijaitsevat kausaaliketjun eri kohdissa. Olemassa olevat tutkimukset yhdistävät jo osan niistä samoissa ihmisissä. Mittausten yhdistäminen palauttaa tietoa, joka katoaa kunkin ulostulon saadessa erillisen sosiaalisen selityksen." },
  }, ja: {}, fr: {}, ko: {},
} as const;

const DETAILS: Record<ReproductiveRegulationContext, { anchor: string; refs: string[] }> = {
  model: { anchor: "three-branches", refs: ["peragine2017_rfrp_suppression", "hoskova2022_hyperprolactin_kisspeptin"] },
  pathopege: { anchor: "selective-regulation", refs: ["peragine2017_rfrp_suppression", "abbott1988_social_lh"] },
  pathopolites: { anchor: "caregiving", refs: ["clarkson2026_prolactin_parental", "gettler2013_fatherhood_sex"] },
  patopolis: { anchor: "feedback", refs: ["weisman2012_oxytocin_dyad", "bensimon2018_sleep_social"] },
  patokinesis: { anchor: "feedback", refs: ["balbo2014_fertility_friends", "pink2014_fertility_coworkers"] },
  epistapege: { anchor: "shared-measures", refs: ["johansson2005_choice_blindness", "lei_south2021_sexual_activity"] },
  civilization: { anchor: "feedback", refs: ["gettler2013_fatherhood_sex", "balbo2014_fertility_friends"] },
  behavior: { anchor: "three-branches", refs: ["peragine2017_rfrp_suppression", "mills2023_kisspeptin"] },
  coordination: { anchor: "caregiving", refs: ["sonigo2012_prolactin_kisspeptin", "hoskova2022_hyperprolactin_kisspeptin", "clarkson2026_prolactin_parental"] },
  convergence: { anchor: "evidence-matrix", refs: ["peragine2017_rfrp_suppression", "gettler2013_fatherhood_sex"] },
  proxy: { anchor: "eight-axes", refs: ["herbenick2021_sexual_repertoire", "lei_south2021_sexual_activity"] },
};

export function ReproductiveRegulationIntegration({ locale, context = "model" }: { locale: string; context?: ReproductiveRegulationContext }) {
  const c = pickCopy(COPY, locale) as typeof COPY.en;
  const d = c[context];
  const detail = DETAILS[context];
  return <section id={`reproductive-regulation-${context}`} className="my-8 min-w-0 scroll-mt-28 rounded-xl border border-accent/25 bg-accent/5 p-5 sm:p-7">
    <TranslationNotice copy={COPY} locale={locale} />
    <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-accent">{c.label}</p>
    <h3 className="mb-4 font-serif text-xl leading-snug sm:text-2xl">{d.title}</h3>
    <p className="text-base leading-7">{d.text}</p>
    <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs">{detail.refs.map(referenceId => <StudyCitation key={referenceId} referenceId={referenceId} locale={locale} />)}</div>
    <Link className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-accent hover:underline" href={`/${locale}/behavior/reproductive-regulation#${detail.anchor}`}>{c.link}<ArrowRight size={15} aria-hidden="true" /></Link>
  </section>;
}
