import { InlineReferenceText } from "@/components/InlineReferenceText";
import { TranslationNotice } from "@/components/TranslationNotice";
import { pickCopy } from "@/lib/i18n";

const COPY = {
  en: {
    title: "Eight axes, measured at different points in the sequence",
    intro: "The existing comparison axes become more informative when their measurements are joined within the same study or cohort. The table locates each axis as an input, receiving state, action or later outcome.",
    axis: "Comparison axis", measure: "Joint measurement", evidence: "What existing evidence connects",
    rows: [
      { axis: "Care allocation", measure: "Caregiving target and time × reproductive state × contact response", evidence: "Prolactin-sensitive offspring contact and father–infant interaction locate different caregiving transitions. [[ref:clarkson2026_prolactin_parental|Clarkson 2026]]; [[ref:weisman2012_oxytocin_dyad|Weisman 2012]]." },
      { axis: "Dispersal and social proximity", measure: "Contact seeking × others’ response × realised contact × household transition", evidence: "Sleep loss altered social distance and observer responses. PSID analyses connect sexual activity with relationships and living conditions in the same young adults. [[ref:bensimon2018_sleep_social|Ben Simon 2018]]; [[ref:lei_south2021_sexual_activity|Lei & South 2021]]." },
      { axis: "Stress and reproductive responsiveness", measure: "HPA dynamics alongside GnRH/LH response and ovulation", evidence: "Marmoset status transitions locate LH and ovulation changes. Reproductive-axis responsiveness supplies a more specific measurement than inferring the same cortisol direction for every suppression pathway. [[ref:abbott1988_social_lh|Abbott 1988]]." },
      { axis: "Courtship and sexual motivation", measure: "Desire × partner-directed approach × sexual response × realised encounter", evidence: "RFRP-3 changed sexually directed investigation selectively. Kisspeptin changed measured human sexual responses. These are distinct components of initiation and realisation. [[ref:peragine2017_rfrp_suppression|Peragine 2017]]; [[ref:mills2023_kisspeptin|Mills 2023]]." },
      { axis: "Signal production and reception", measure: "Specified sensory cue × receiver state × measured response", evidence: "Queen odour supplies a defined chemical input in naked mole-rats; human infant-odour experiments measure reward-related responses. The shared level is the cue–receiver–response relationship. [[ref:khallaf2026_queen_odour|Khallaf 2026]]; [[ref:lundstrom2013_newborn_odor|Lundström 2013]]." },
      { axis: "Social regulation", measure: "Sanction or support × contact availability × later action", evidence: "Human network studies identify timed reproductive transitions after peer births. Together with interpersonal interventions, they constrain how others’ actions become a new opportunity structure. [[ref:balbo2014_fertility_friends|Balbo & Barban 2014]]; [[ref:pink2014_fertility_coworkers|Pink 2014]]." },
      { axis: "Hormonal and genomic change", measure: "Hormone and pulse timing × receptor response × fatherhood × sexual activity", evidence: "The Cebu fatherhood and sexual-activity analyses share a cohort. Kisspeptin challenge under hyperprolactinaemia identifies a separate human pulse-response transition. [[ref:gettler2011_fatherhood_testosterone|Gettler 2011]]; [[ref:gettler2013_fatherhood_sex|Gettler 2013]]; [[ref:hoskova2022_hyperprolactin_kisspeptin|Hoskova 2022]]." },
      { axis: "Risk, exploration and effort", measure: "Reward and effort choices × developmental stage × resources × later action", evidence: "Dopamine and sleep interventions identify effort-related choices; PSID adds realised activities and life-course conditions. The observed task and the later demographic transition remain separately measured. [[ref:westbrook2020_dopamine_effort|Westbrook 2020]]; [[ref:jurgelis2022_sleep_effort|Jurgelis 2022]]; [[ref:lei_south2021_sexual_activity|Lei & South 2021]]." },
    ],
    conclusion: "The strongest shared profile comes from several outcomes measured in the same individuals, followed through time. A household category, a caregiving target or a reported preference alone does not identify the receiving state. The eight axes organise these observations into a common causal question.",
  },
  fi: {
    title: "Kahdeksan akselia ketjun eri kohdissa mitattuina",
    intro: "Nykyiset vertailuakselit tarkentuvat, kun niiden mittaukset yhdistetään samassa kokeessa tai kohortissa. Taulukko paikantaa kunkin akselin syötteeksi, vastaanottavaksi tilaksi, teoksi tai myöhemmäksi tulokseksi.",
    axis: "Vertailuakseli", measure: "Yhteismittaus", evidence: "Mitä nykyinen näyttö yhdistää",
    rows: [
      { axis: "Hoivan kohdentuminen", measure: "Hoivan kohde ja aika × lisääntymistila × kontaktivaste", evidence: "Prolaktiinille herkkä poikaskontakti ja isän ja vauvan vuorovaikutus paikantavat hoivan eri siirtymiä. [[ref:clarkson2026_prolactin_parental|Clarkson 2026]]; [[ref:weisman2012_oxytocin_dyad|Weisman 2012]]." },
      { axis: "Dispersaali ja sosiaalinen läheisyys", measure: "Kontaktin hakeminen × toisten vaste × toteutunut kontakti × asumissiirtymä", evidence: "Univaje muutti sosiaalista etäisyyttä ja ulkopuolisten arvioijien vasteita. PSID-analyysit yhdistävät samoissa nuorissa aikuisissa seksuaalisen toiminnan suhteisiin ja elinoloihin. [[ref:bensimon2018_sleep_social|Ben Simon 2018]]; [[ref:lei_south2021_sexual_activity|Lei ja South 2021]]." },
      { axis: "Stressi ja lisääntymisakselin vastaanottavuus", measure: "HPA-dynamiikka rinnakkain GnRH/LH-vasteen ja ovulaation kanssa", evidence: "Marmosettien statussiirtymät paikantavat LH:n ja ovulaation muutoksia. Lisääntymisakselin vaste on tarkempi mittaus kuin saman kortisolisuunnan olettaminen jokaiselle suppressioreitille. [[ref:abbott1988_social_lh|Abbott 1988]]." },
      { axis: "Seurustelu ja seksuaalinen motivaatio", measure: "Halu × kumppaniin kohdistuva lähestyminen × seksuaalinen vaste × toteutunut kohtaaminen", evidence: "RFRP-3 muutti seksuaalisesti kohdennettua tutkimista valikoivasti. Kisspeptiini muutti ihmisen mitattuja seksuaalisia vasteita. Nämä ovat aloittamisen ja toteutumisen erillisiä komponentteja. [[ref:peragine2017_rfrp_suppression|Peragine 2017]]; [[ref:mills2023_kisspeptin|Mills 2023]]." },
      { axis: "Signaalin tuotanto ja vastaanotto", measure: "Nimetty aistivihje × vastaanottajan tila × mitattu vaste", evidence: "Kuningattaren haju on määritelty kemiallinen syöte paljaskoirarotalla; ihmisen vauvanhajukokeet mittaavat palkkioihin liittyviä vasteita. Yhteinen taso on vihjeen, vastaanottajan ja vasteen suhde. [[ref:khallaf2026_queen_odour|Khallaf 2026]]; [[ref:lundstrom2013_newborn_odor|Lundström 2013]]." },
      { axis: "Sosiaalinen säätely", measure: "Sanktio tai tuki × kontaktimahdollisuus × myöhempi toiminta", evidence: "Ihmisten verkostotutkimukset paikantavat lisääntymissiirtymien ajoitusta vertaisen lapsen syntymän jälkeen. Yhdessä vuorovaikutusinterventioiden kanssa ne rajaavat muiden tekojen muuttumista uudeksi mahdollisuusrakenteeksi. [[ref:balbo2014_fertility_friends|Balbo ja Barban 2014]]; [[ref:pink2014_fertility_coworkers|Pink 2014]]." },
      { axis: "Hormonaalinen ja genominen muutos", measure: "Hormoni ja pulssitus × reseptorivaste × isyys × seksuaalinen toiminta", evidence: "Cebun isyys- ja seksuaalitoiminta-analyysit jakavat kohortin. Kisspeptiinihaaste hyperprolaktinemiassa paikantaa erillisen ihmisen pulssivastesiirtymän. [[ref:gettler2011_fatherhood_testosterone|Gettler 2011]]; [[ref:gettler2013_fatherhood_sex|Gettler 2013]]; [[ref:hoskova2022_hyperprolactin_kisspeptin|Hoskova 2022]]." },
      { axis: "Riskinotto, tutkiminen ja vaivannäkö", measure: "Palkkio- ja vaivavalinnat × kehitysvaihe × resurssit × myöhempi toiminta", evidence: "Dopamiini- ja uni-interventiot paikantavat vaivavalintoja; PSID lisää toteutuneet toiminnot ja elämänkulun olosuhteet. Mitattu tehtävä ja myöhempi väestöllinen siirtymä säilyvät erillisinä havaintoina. [[ref:westbrook2020_dopamine_effort|Westbrook 2020]]; [[ref:jurgelis2022_sleep_effort|Jurgelis 2022]]; [[ref:lei_south2021_sexual_activity|Lei ja South 2021]]." },
    ],
    conclusion: "Vahvin yhteisprofiili muodostuu samoissa yksilöissä mitatuista ulostuloista ja niiden ajallisesta seurannasta. Asumisluokka, hoivan kohde tai kerrottu mieltymys yksin ei tunnista vastaanottavaa tilaa. Kahdeksan akselia kokoaa havainnot yhteiseksi kausaaliseksi kysymykseksi.",
  }, ja: {}, fr: {}, ko: {},
} as const;

export function ReproductiveRegulationAxes({ locale, id = "eight-axes" }: { locale: string; id?: string }) {
  const c = pickCopy(COPY, locale) as typeof COPY.en;
  return <section id={id} className="min-w-0 scroll-mt-28 space-y-5">
    <h2 className="editorial-section-heading">{c.title}</h2><p className="max-w-4xl text-base leading-7 text-foreground-muted">{c.intro}</p><TranslationNotice copy={COPY} locale={locale} />
    <div className="overflow-x-auto rounded-xl border border-card-border"><table className="w-full min-w-[42rem] border-collapse text-left text-sm"><thead><tr className="border-b border-card-border bg-[var(--figure-bg)]">{[c.axis, c.measure, c.evidence].map(title => <th key={title} scope="col" className="p-4 font-semibold">{title}</th>)}</tr></thead><tbody>{c.rows.map(row => <tr key={row.axis} className="border-b border-card-border last:border-b-0"><th scope="row" className="w-[20%] p-4 align-top font-semibold leading-6">{row.axis}</th><td className="w-[30%] p-4 align-top leading-6">{row.measure}</td><td className="p-4 align-top leading-6 text-foreground-muted"><InlineReferenceText text={row.evidence} locale={locale} /></td></tr>)}</tbody></table></div>
    <p className="max-w-4xl text-sm leading-7 text-foreground-muted">{c.conclusion}</p>
  </section>;
}
