import Link from "next/link";
import { ClaimRef } from "@/components/ClaimRef";
import { MathBlock } from "@/components/MathBlock";
import { pickCopy } from "@/lib/i18n";

const COPY = {
  en: { title: "Integrate structure, then direction, then magnitude", structure: "Structure: record calcium compartment and timing, absolute glutathione pools, mitochondrial state, cholesterol supply and measured steroid output with their experimental context.", direction: "Direction: a sign belongs to a specific intervention and state. Physiological calcium and redox signalling support production; either insufficient stimulation or excessive load can impair it. Basal and stimulated output can move in opposite directions.", magnitude: "Magnitude: pool identities introduce no fitted constants. Synthesis, reduction, oxidation and export fluxes have no universal coefficients here. Quantitative transfer to hormone response, fecundability and TFR remains a separate calibration step; shared bottlenecks enter the existing production branch once.", pool: "Use the same compartment and molar basis. Oxidation of two GSH into one GSSG preserves this equivalent pool. The GSH/GSSG ratio alone cannot identify pool size or production capacity.", data: "The current research task uses existing experiments and data: align measured variables, stimulus, timing, cell system and research family, then evaluate which directional relations transfer. No new exposure experiment is required for this integration.", link: "Inspect the evidence and integration stages" },
  fi: { title: "Ensin rakenne, sitten suunta ja lopuksi suuruus", structure: "Rakenne: kirjataan kalsiumin osasto ja ajoitus, absoluuttiset glutationipoolit, mitokondriotila, kolesterolihuolto ja mitattu steroidituotanto koeolosuhteineen.", direction: "Suunta: vaikutuksen etumerkki kuuluu tiettyyn interventioon ja lähtötilaan. Fysiologinen kalsium- ja redox-signalointi tukee tuotantoa; sekä liian vähäinen stimulaatio että liian suuri kuorma voivat heikentää sitä. Basaalinen ja stimuloitu tuotanto voivat muuttua eri suuntiin.", magnitude: "Suuruus: poolin määritelmä ei lisää sovitettavia vakioita. Synteesin, pelkistyksen, hapetuksen ja viennin virroille ei tässä aseteta universaaleja kertoimia. Numeerinen siirto hormonivasteeseen, hedelmöittyvyyteen ja TFR:ään on erillinen kalibrointivaihe; yhteinen pullonkaula kirjautuu nykyiseen tuotantohaaraan kerran.", pool: "Käytetään samaa solun osastoa ja molaarista perustaa. Kahden GSH:n hapettuminen yhdeksi GSSG:ksi säilyttää tämän ekvivalenttipoolin. Pelkkä GSH/GSSG-suhde ei määritä poolin kokoa eikä tuotantokapasiteettia.", data: "Nykyvaiheen tutkimustyö käyttää olemassa olevia kokeita ja dataa: yhteensovitetaan mitattu suure, stimulaatio, ajankohta, solujärjestelmä ja tutkimusperhe ja arvioidaan vaikutussuuntien siirrettävyyttä. Integraatio ei edellytä uutta altistuskoetta.", link: "Tutki näyttö ja integraation vaiheet" },
  ja: { title: "構造、方向、最後に大きさを統合する", structure: "構造：カルシウム区画と時間、グルタチオン絶対量、ミトコンドリア状態、コレステロール供給、ステロイド産生を実験条件とともに記録します。", direction: "方向：効果の符号は特定の介入と状態に属します。生理的信号は産生を支えますが、刺激不足と過剰負荷はともに機能を損ない得ます。基礎産生と刺激産生は逆方向に動く場合があります。", magnitude: "大きさ：プールの定義に適合係数は不要です。合成、還元、酸化、排出に普遍的係数を設定しません。ホルモン応答、受胎能、TFRへの数値的変換は別途校正し、共通の律速段階を二重に数えません。", pool: "同じ区画とモル基準を使います。2個のGSHから1個のGSSGへの酸化はこの等価プールを保存します。比だけではプール量や産生能力を決められません。", data: "現段階では既存の実験とデータを用い、測定量、刺激、時間、細胞系、研究群を照合して方向の移植可能性を調べます。新規曝露実験は必要ありません。", link: "証拠と統合段階を見る" },
  fr: { title: "Intégrer la structure, puis le sens, puis l’amplitude", structure: "Structure : enregistrer compartiment et temporalité du calcium, pools absolus de glutathion, état mitochondrial, cholestérol et production de stéroïdes avec le contexte expérimental.", direction: "Sens : le signe appartient à une intervention et un état précis. La signalisation physiologique soutient la production ; stimulation insuffisante et surcharge peuvent toutes deux l’altérer. Productions basale et stimulée peuvent évoluer en sens opposés.", magnitude: "Amplitude : l’identité du pool ne crée aucun coefficient ajusté. Aucun coefficient universel de synthèse, réduction, oxydation ou export n’est fixé. Le transfert quantitatif vers réponse hormonale, fécondabilité et TFR nécessite une calibration distincte ; un goulot commun n’est compté qu’une fois.", pool: "Employer le même compartiment et la même base molaire. L’oxydation de deux GSH en un GSSG conserve ce pool équivalent. Le rapport seul ne détermine ni sa taille ni la capacité de production.", data: "Cette étape utilise les expériences et données existantes : aligner mesures, stimulation, temporalité, système cellulaire et famille de recherche pour examiner le transfert des relations directionnelles. Elle ne nécessite pas de nouvelle exposition expérimentale.", link: "Examiner les preuves et les étapes d’intégration" },
  ko: { title: "구조, 방향, 마지막으로 크기를 통합", structure: "구조: 칼슘 구획과 시점, 절대 글루타티온 풀, 미토콘드리아 상태, 콜레스테롤 공급 및 스테로이드 생산을 실험 맥락과 함께 기록합니다.", direction: "방향: 효과의 부호는 특정 개입과 상태에 속합니다. 생리적 신호는 생산을 돕지만 자극 부족과 과부하 모두 기능을 저해할 수 있습니다. 기저 생산과 자극 생산은 반대 방향으로 변할 수 있습니다.", magnitude: "크기: 풀 정의는 적합 상수를 추가하지 않습니다. 합성, 환원, 산화 및 배출에 보편 계수를 설정하지 않습니다. 호르몬 반응, 수태능, TFR로의 수치 변환은 별도 보정 단계이며 공통 병목을 중복 계산하지 않습니다.", pool: "같은 구획과 몰 기준을 사용합니다. 두 GSH가 한 GSSG로 산화되어도 등가 풀은 보존됩니다. 비율만으로 풀 크기나 생산 능력을 결정할 수 없습니다.", data: "현재 단계는 기존 실험과 데이터로 측정량, 자극, 시점, 세포계 및 연구 계열을 맞추고 방향 관계의 이전 가능성을 평가합니다. 새 노출 실험은 필요하지 않습니다.", link: "증거와 통합 단계 보기" },
};

export function SteroidogenesisCalibrationNote({ locale }: { locale: string }) {
  const c = pickCopy(COPY, locale);
  return <section id="steroidogenesis-calibration" className="my-9 scroll-mt-28 space-y-4 rounded-xl border border-card-border p-5 sm:p-7">
    <h2 className="font-serif text-2xl">{c.title}</h2>
    <ol className="list-decimal space-y-3 pl-5 text-sm leading-7"><li>{c.structure}</li><li>{c.direction}</li><li><ClaimRef claimId="claim.steroidogenesis.staged-integration">{c.magnitude}</ClaimRef></li></ol>
    <MathBlock tex={String.raw`G_T=[\mathrm{GSH}]+2[\mathrm{GSSG}]`} />
    <p className="text-sm leading-7 text-foreground-muted">{c.pool}</p>
    <p className="text-sm leading-7">{c.data}</p>
    <Link href={`/${locale}/biology/calcium-redox-steroidogenesis`} className="inline-block text-sm font-semibold text-accent hover:underline">{c.link} →</Link>
  </section>;
}
