"use client";

const copy = {
  en: {
    eyebrow: "LEGACY_TIMING_PROXY",
    title: "Archived temporal-backtest viewer",
    lead: "The line-by-line v17 BERM-versus-M0 viewer has been withdrawn from the primary research surface. Its apparent predictions were generated by a legacy scalar proxy with conditional later covariates, rather than by measured FieldState inputs and a calibrated ASFR endpoint.",
    keep: "What remains useful",
    keepText: "Observed demographic series and the date of technology adoption can still be inspected descriptively. The site treats mobile subscriptions only as a timing proxy; it does not convert them into RF exposure or biological dose.",
    replace: "What must replace it",
    replaceText: "A prospective v2 viewer will require a measured FieldState record, documented transfer to the relevant organ state, a preregistered biological endpoint, and age-specific fertility data. It will show uncertainty and competing demographic pathways separately.",
  },
  fi: {
    eyebrow: "LEGACY_TIMING_PROXY",
    title: "Arkistoitu ajallisen backtestin katselin",
    lead: "Rivi-riviltä esittävä v17 BERM–M0-katselin on poistettu ensisijaisesta tutkimusnäkymästä. Sen näennäiset ennusteet tuotettiin vanhalla skalaariproxylla ja ehdollisilla myöhemmillä kovariaateilla, ei mitatuilla FieldState-syötteillä ja kalibroidulla ASFR-päätepisteellä.",
    keep: "Mikä säilyy hyödyllisenä",
    keepText: "Havaittuja demografisia aikasarjoja ja teknologiakäyttöönoton ajankohtaa voi edelleen tarkastella kuvailevasti. Sivusto käsittelee mobiililiittymiä vain ajoitusproxyna; niitä ei muuneta RF-altistukseksi tai biologiseksi annokseksi.",
    replace: "Mitä tarvitaan tilalle",
    replaceText: "Prospektiivinen v2-katselin vaatii mitatun FieldState-tietueen, dokumentoidun siirron kyseiseen elintilaan, esirekisteröidyn biologisen päätepisteen ja ikäryhmäkohtaisen hedelmällisyysdatan. Se näyttää epävarmuuden ja kilpailevat demografiset polut erillään.",
  },
} as const;

export function TemporalBacktestExplorer({ locale }: { locale: string }) {
  const d = locale === "fi" ? copy.fi : copy.en;
  return (
    <section className="mt-12 rounded-xl border border-status-partial/30 bg-status-partial/5 p-5 sm:p-6">
      <p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-status-partial">{d.eyebrow}</p>
      <h2 className="text-xl font-semibold tracking-tight">{d.title}</h2>
      <p className="mt-2 max-w-3xl text-sm leading-relaxed text-foreground-muted">{d.lead}</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">
        <div className="rounded-lg border border-card-border bg-background p-4">
          <h3 className="mb-2 text-sm font-semibold">{d.keep}</h3>
          <p className="text-xs leading-relaxed text-foreground-muted">{d.keepText}</p>
        </div>
        <div className="rounded-lg border border-card-border bg-background p-4">
          <h3 className="mb-2 text-sm font-semibold">{d.replace}</h3>
          <p className="text-xs leading-relaxed text-foreground-muted">{d.replaceText}</p>
        </div>
      </div>
    </section>
  );
}
