export interface ModulomeLayer {
  id: string;
  number: number;
  nameEn: string;
  nameFi: string;
  nameJa: string;
  nameFr: string;
  nameKo: string;
  chiModulatorEn: string;
  chiModulatorFi: string;
  chiModulatorJa: string;
  chiModulatorFr: string;
  chiModulatorKo: string;
  keyComponentsEn: string;
  keyComponentsFi: string;
  keyComponentsJa: string;
  keyComponentsFr: string;
  keyComponentsKo: string;
  newInSession: boolean;
  integrationEn: string;
  integrationFi: string;
  integrationJa: string;
  integrationFr: string;
  integrationKo: string;
}

export const MODULOME_LAYERS: ModulomeLayer[] = [
  {
    id: "molecular",
    number: 1,
    nameEn: "Molecular (Spin & Chromophore)",
    nameFi: "Molekulaarinen (spin ja kromofori)",
    nameJa: "分子 (スピンと発色団)",
    nameFr: "Moléculaire (spin et chromophore)",
    nameKo: "분자 (스핀과 발색단)",
    chiModulatorEn: "Flavin redox state, binding occupancy and the ordered light history",
    chiModulatorFi: "Flaviinin hapetus-pelkistystila, sitoutumisaste ja järjestetty valohistoria",
    chiModulatorJa: "フラビンの酸化還元状態、結合占有率、順序づけられた光履歴",
    chiModulatorFr: "État redox du flavine, taux d'occupation et historique lumineux ordonné",
    chiModulatorKo: "플라빈 산화환원 상태, 결합 점유율, 순서가 있는 광 이력",
    keyComponentsEn: "CRY1, CRY2, FAD, FADH•, tryptophan chain, sequential two-photon step, RFK",
    keyComponentsFi: "CRY1, CRY2, FAD, FADH•, tryptofaaniketju, peräkkäinen kahden fotonin askel, RFK",
    keyComponentsJa: "CRY1, CRY2, FAD, FADH•, トリプトファン鎖, 逐次二光子ステップ, RFK",
    keyComponentsFr: "CRY1, CRY2, FAD, FADH•, chaîne tryptophane, étape séquentielle à deux photons, RFK",
    keyComponentsKo: "CRY1, CRY2, FAD, FADH•, 트립토판 사슬, 순차적 이광자 단계, RFK",
    newInSession: false,
    integrationEn: "The input is the flavin state, not the amount of FAD. Human CRY1 changes conformation as the flavin moves from the neutral radical to the fully reduced state, and the transition involves the sequential absorption of two photons, so the same total light dose can leave a different molecular state when the order of wavelengths and the delay between them change. The photochemical change is observed; its magnetic modulation is the next separate test. Parameters are registered per cryptochrome: one shared CRY coefficient is not used.",
    integrationFi: "Syöte on flaviinin tila, ei FAD:n määrä. Ihmisen CRY1 muuttaa rakennettaan flaviinin siirtyessä neutraalista radikaalitilasta täysin pelkistyneeseen, ja siirtymä sisältää kahden fotonin peräkkäisen absorption. Sama kokonaisvaloannos voi siksi jättää eri molekyylitilan, kun aallonpituuksien järjestys ja niiden välinen viive muuttuvat. Fotokemiallinen muutos on havaittu; sen magneettinen modulaatio on seuraava erillinen testikohde. Parametrit rekisteröidään kryptokromikohtaisesti: yhtä yhteistä CRY-kerrointa ei käytetä.",
    integrationJa: "入力はFADの量ではなくフラビンの状態である。ヒトCRY1は中性ラジカルから完全還元状態への遷移に伴い構造変化し、その過程は二光子の逐次吸収を含む。したがって総光量が同じでも、波長の順序と間隔が変われば異なる分子状態が残る。光化学的変化は観測済みで、その磁気変調は次の独立した検証対象である。パラメータはクリプトクロムごとに登録し、共通のCRY係数は用いない。",
    integrationFr: "L'entrée est l'état du flavine, non la quantité de FAD. La CRY1 humaine change de conformation lorsque le flavine passe du radical neutre à l'état complètement réduit, et la transition implique l'absorption séquentielle de deux photons : une même dose lumineuse totale peut donc laisser un état moléculaire différent si l'ordre des longueurs d'onde et le délai changent. Le changement photochimique est observé ; sa modulation magnétique est le test suivant, distinct. Les paramètres sont enregistrés par cryptochrome ; aucun coefficient CRY commun n'est utilisé.",
    integrationKo: "입력은 FAD의 양이 아니라 플라빈의 상태다. 인간 CRY1은 플라빈이 중성 라디칼에서 완전 환원 상태로 이동할 때 구조가 변하며, 이 전이는 두 광자의 순차적 흡수를 포함한다. 따라서 총 광량이 같아도 파장의 순서와 지연이 달라지면 다른 분자 상태가 남는다. 광화학적 변화는 관측되었고, 그 자기 조절은 다음의 별도 검증 과제다. 파라미터는 크립토크롬별로 등록하며 공통 CRY 계수는 쓰지 않는다.",
  },
  {
    id: "ion_channel",
    number: 2,
    nameEn: "Ion Channel (Gating Dynamics)",
    nameFi: "Ionikanava (porttidynamiikka)",
    nameJa: "イオンチャネル (ゲーティング動態)",
    nameFr: "Canal ionique (dynamique de gating)",
    nameKo: "이온 채널 (게이팅 역학)",
    chiModulatorEn: "Vm vs channel threshold; store load and resting potential at fixed channel expression",
    chiModulatorFi: "Vm vs kanavakynnys; varastokuorma ja lepojännite kanavien ilmentymisen pysyessä samana",
    chiModulatorJa: "Vm対チャネル閾値；チャネル発現一定下での貯蔵負荷と静止電位",
    chiModulatorFr: "Vm vs seuil du canal ; charge du stock et potentiel de repos à expression constante",
    chiModulatorKo: "Vm 대 채널 역치; 채널 발현이 같을 때의 저장 부하와 안정 전위",
    keyComponentsEn: "Cav1 (L-type), Cav3 (T-type), TRPC1, CatSper, K_ATP, KCNJ15/Kir4.2",
    keyComponentsFi: "Cav1 (L-tyyppi), Cav3 (T-tyyppi), TRPC1, CatSper, K_ATP, KCNJ15/Kir4.2",
    keyComponentsJa: "Cav1 (L型), Cav3 (T型), TRPC1, CatSper, K_ATP, KCNJ15/Kir4.2",
    keyComponentsFr: "Cav1 (type L), Cav3 (type T), TRPC1, CatSper, K_ATP, KCNJ15/Kir4.2",
    keyComponentsKo: "Cav1 (L형), Cav3 (T형), TRPC1, CatSper, K_ATP, KCNJ15/Kir4.2",
    newInSession: false,
    integrationEn: "T-type window current = pathway-A transduction step at low intensities. L-type at high intensities. B (CRY/RPM) is the primary pathway. A change in membrane current is not necessarily a direct action on the channel: interfering with release from the ER store or with reuptake into it prevented the reported current changes, so the same channel expression level produces a different response in a different cell state.",
    integrationFi: "T-tyypin ikkunavirta = reitti-A:n transduktioaskel matalilla intensiteeteillä. L-tyyppi korkeilla. B (CRY/RPM) on ensisijainen reitti. Kalvovirran muutos ei ole väistämättä suora vaikutus kanavaan: ER-varaston vapautumiseen tai takaisinottoon puuttuminen esti raportoidut virtamuutokset, joten sama kanavien ilmentymistaso tuottaa eri vasteen eri solutilassa.",
    integrationJa: "T型ウィンドウ電流＝低強度での経路Aの伝達ステップ。高強度ではL型。B（CRY/RPM）が主要経路。膜電流の変化は必ずしもチャネルへの直接作用ではない：ER貯蔵からの放出または再取り込みへの介入が報告された電流変化を阻止したため、同じチャネル発現量でも細胞状態が異なれば応答は異なる。",
    integrationFr: "Courant de fenêtre de type T = étape de transduction de la voie A à faibles intensités. Type L à hautes intensités. B (CRY/RPM) est la voie primaire. Un changement de courant membranaire n'est pas nécessairement une action directe sur le canal : bloquer la libération depuis le stock du RE ou sa recapture a empêché les changements rapportés, donc une même expression de canaux donne une réponse différente selon l'état cellulaire.",
    integrationKo: "T형 창 전류 = 저강도에서 경로 A의 변환 단계. 고강도에서는 L형. B (CRY/RPM)가 주요 경로. 막 전류의 변화가 반드시 채널에 대한 직접 작용은 아니다: ER 저장고의 방출이나 재흡수를 차단하면 보고된 전류 변화가 나타나지 않았으므로, 같은 채널 발현량이라도 세포 상태가 다르면 반응이 다르다.",
  },
  {
    id: "mitochondrial",
    number: 3,
    nameEn: "Mitochondrial (ΔΨm Ca²⁺→ROS Converter)",
    nameFi: "Mitokondriaalinen (ΔΨm Ca²⁺→ROS-muunnin)",
    nameJa: "ミトコンドリア (ΔΨm Ca²⁺→ROS変換器)",
    nameFr: "Mitochondrial (convertisseur ΔΨm Ca²⁺→ROS)",
    nameKo: "미토콘드리아 (ΔΨm Ca²⁺→ROS 변환기)",
    chiModulatorEn: "ΔΨm ≈ −180 mV (>2× plasma membrane), read as a functional state with respiratory reserve, ATP output and mitochondrial number",
    chiModulatorFi: "ΔΨm ≈ −180 mV (>2× solukalvo), luettuna toimintatilana yhdessä hengitysreservin, ATP-tuotannon ja mitokondrioiden määrän kanssa",
    chiModulatorJa: "ΔΨm ≈ −180 mV（細胞膜の2倍以上）。呼吸予備能、ATP産生、ミトコンドリア数とともに機能状態として読む",
    chiModulatorFr: "ΔΨm ≈ −180 mV (>2× membrane plasmique), lu comme état fonctionnel avec réserve respiratoire, production d'ATP et nombre de mitochondries",
    chiModulatorKo: "ΔΨm ≈ −180 mV (세포막의 2배 이상), 호흡 예비능·ATP 생산·미토콘드리아 수와 함께 기능 상태로 읽음",
    keyComponentsEn: "VDAC (outer), MCU (inner, Ca²⁺ uniporter), ETC complexes I–IV, respiratory reserve, ATP output, mitochondrial number",
    keyComponentsFi: "VDAC (ulompi), MCU (sisä, Ca²⁺-uniportteri), ETC-kompleksit I–IV, hengitysreservi, ATP-tuotanto, mitokondrioiden määrä",
    keyComponentsJa: "VDAC（外膜）, MCU（内膜, Ca²⁺ユニポーター）, ETC複合体I–IV, 呼吸予備能, ATP産生, ミトコンドリア数",
    keyComponentsFr: "VDAC (externe), MCU (interne, uniporteur Ca²⁺), complexes ETC I–IV, réserve respiratoire, production d'ATP, nombre de mitochondries",
    keyComponentsKo: "VDAC (외막), MCU (내막, Ca²⁺ 유니포터), ETC 복합체 I–IV, 호흡 예비능, ATP 생산, 미토콘드리아 수",
    newInSession: true,
    integrationEn: "The MISSING LINK in ‘Ca²⁺ → ROS’. Cytoplasmic Ca²⁺ from VGCC enters mitochondria via MCU → disrupts the electron transport chain → ROS production. ΔΨm is the highest sustained voltage in the cell and is recorded as a functional state, not as an age: the quantities that decide the ROS yield per unit of Ca²⁺ are respiratory reserve, ATP output and mitochondrial number, each measured in its own right.",
    integrationFi: "PUUTTUVA LINKKI ‘Ca²⁺ → ROS’ -ketjussa. Sytoplasman Ca²⁺ VGCC:ltä pääsee mitokondrioihin MCU:n kautta → häiritsee elektroninsiirtoketjua → ROS-tuotanto. ΔΨm on solun korkein pysyvä jännite ja kirjataan toimintatilaksi, ei iäksi: ROS-saannon Ca²⁺-yksikköä kohden ratkaisevat hengitysreservi, ATP-tuotanto ja mitokondrioiden määrä, kukin omana mittauksenaan.",
    integrationJa: "「Ca²⁺ → ROS」の欠けていたリンク。VGCCからの細胞質Ca²⁺がMCU経由でミトコンドリアに流入し電子伝達鎖を撹乱してROSを産生する。ΔΨmは細胞内で最も高い持続電圧であり、年齢ではなく機能状態として記録する。Ca²⁺単位あたりのROS産生量を決めるのは呼吸予備能、ATP産生、ミトコンドリア数であり、それぞれ独立に測定する。",
    integrationFr: "Le CHAÎNON MANQUANT dans « Ca²⁺ → ROS ». Le Ca²⁺ cytoplasmique issu des VGCC entre dans les mitochondries via MCU → perturbe la chaîne de transport d'électrons → production de ROS. ΔΨm est la tension soutenue la plus élevée de la cellule et se consigne comme état fonctionnel, non comme un âge : ce qui décide du rendement en ROS par unité de Ca²⁺ est la réserve respiratoire, la production d'ATP et le nombre de mitochondries, chacun mesuré séparément.",
    integrationKo: "'Ca²⁺ → ROS'의 빠진 고리. VGCC로부터의 세포질 Ca²⁺가 MCU를 통해 미토콘드리아로 들어가 전자전달계를 교란하고 ROS를 생성한다. ΔΨm은 세포 내 가장 높은 지속 전압이며 연령이 아니라 기능 상태로 기록한다. Ca²⁺ 단위당 ROS 생성량을 정하는 것은 호흡 예비능, ATP 생산, 미토콘드리아 수이며 각각 독립적으로 측정한다.",
  },
  {
    id: "membrane_barrier",
    number: 4,
    nameEn: "Membrane & Biological Barriers",
    nameFi: "Kalvo ja biologiset esteet",
    nameJa: "膜と生物学的障壁",
    nameFr: "Membrane et barrières biologiques",
    nameKo: "막과 생물학적 장벽",
    chiModulatorEn: "Membrane composition, protein complexes and their localisation, plus TJ integrity",
    chiModulatorFi: "Kalvon koostumus, proteiinikompleksit ja niiden sijainti sekä TJ-eheys",
    chiModulatorJa: "膜組成、タンパク質複合体とその局在、およびTJの完全性",
    chiModulatorFr: "Composition membranaire, complexes protéiques et leur localisation, plus intégrité des TJ",
    chiModulatorKo: "막 조성, 단백질 복합체와 그 위치, 그리고 TJ 완전성",
    keyComponentsEn: "Occludin, claudin, ZO-1; ω-3/7 lipids; BBB, BTB, BRB, placenta; TRPC1 complexes, cell-derived vesicles",
    keyComponentsFi: "Okkludiini, klaudiini, ZO-1; ω-3/7-lipidit; BBB, BTB, BRB, istukka; TRPC1-kompleksit, soluperäiset vesikkelit",
    keyComponentsJa: "オクルディン, クローディン, ZO-1; ω-3/7脂質; BBB, BTB, BRB, 胎盤; TRPC1複合体, 細胞由来小胞",
    keyComponentsFr: "Occludine, claudine, ZO-1 ; lipides ω-3/7 ; BHE, BTB, BRB, placenta ; complexes TRPC1, vésicules d'origine cellulaire",
    keyComponentsKo: "오클루딘, 클라우딘, ZO-1; ω-3/7 지질; BBB, BTB, BRB, 태반; TRPC1 복합체, 세포 유래 소포",
    newInSession: false,
    integrationEn: "Barrier integrity is a candidate tissue-kernel moderator. A proposed feedback is EMF → barrier opening → greater target exposure → further damage; its direction and gain require endpoint calibration. Imported L3 candidate χ_barrier represents barrier state. Its proposed feedback is biological and does not derive from χ_geo. The receptor coordinate of this layer is the membrane itself rather than a channel count: vesicles prepared from normal cells responded to a pulsed field and partly restored field-associated respiratory and growth responses in channel-silenced recipients, so receptor function is partly transferable with the membrane structure. That was a prepared-vesicle design; natural transfer inside tissue is a separate hypothesis.",
    integrationFi: "Esteen eheys on kudosytimen ehdokasmoderaattori. Ehdotettu takaisinkytkentä on EMF → esteen avautuminen → suurempi kohdekudosaltistus → lisävaurio; suunta ja vahvistus vaativat päätepistekalibroinnin. Tuotu L3-ehdokas χ_barrier kuvaa estetilaa. Ehdotettu takaisinkytkentä on biologinen eikä seuraa χ_geosta. Tämän kerroksen vastaanotinkoordinaatti on kalvo itse, ei kanavien lukumäärä: normaaleista soluista valmistetut vesikkelit vastasivat pulssikenttään ja palauttivat osittain kenttään liittyvät hengitys- ja kasvuvasteet kanavavaimennetuissa vastaanottajissa, joten vastaanottimen toiminta on osittain siirrettävissä kalvorakenteen mukana. Kyse oli valmistetuista vesikkeleistä; luonnollinen siirtyminen kudoksessa on erillinen hypoteesi.",
    integrationJa: "障壁完全性は組織カーネルの候補修飾因子です。EMF→障壁開口→標的曝露増加→追加損傷というフィードバックが提案されますが、方向と利得にはエンドポイント校正が必要です。 導入L3候補χ_barrierは障壁状態を表す。提案フィードバックは生物学的で、χ_geoから導出されない。この層の受容体座標はチャネル数ではなく膜そのものである：正常細胞から調製した小胞はパルス磁場に応答し、チャネルを抑制した受容細胞の呼吸・増殖応答を部分的に回復させた。受容体機能は膜構造とともに部分的に移送可能である。これは調製小胞の設計であり、組織内での自然な移行は別の仮説である。",
    integrationFr: "L'intégrité de la barrière est un modérateur candidat du noyau tissulaire. La rétroaction proposée est CEM → ouverture de la barrière → exposition accrue de la cible → dommages supplémentaires ; direction et gain exigent une calibration d'endpoint. Le candidat L3 importé χ_barrier représente l'état des barrières. Sa rétroaction proposée est biologique et ne dérive pas de χ_geo. La coordonnée réceptrice de cette couche est la membrane elle-même, non un décompte de canaux : des vésicules issues de cellules normales ont répondu à un champ pulsé et ont partiellement restauré les réponses respiratoires et de croissance de cellules réceptrices dont le canal était éteint. La fonction réceptrice est donc partiellement transférable avec la structure membranaire. Il s'agissait de vésicules préparées ; un transfert naturel dans le tissu est une hypothèse distincte.",
    integrationKo: "장벽 완전성은 조직 커널의 후보 조절인자입니다. 제안된 피드백은 EMF → 장벽 개방 → 표적 노출 증가 → 추가 손상이며 방향과 이득은 종점 보정이 필요합니다. 도입 L3 후보 χ_barrier는 장벽 상태를 나타낸다. 제안된 피드백은 생물학적이며 χ_geo에서 도출되지 않는다. 이 층의 수용체 좌표는 채널 수가 아니라 막 자체다: 정상 세포에서 만든 소포는 펄스장에 반응했고, 채널이 침묵된 수용 세포의 호흡·성장 반응을 부분적으로 회복시켰다. 수용체 기능은 막 구조와 함께 부분적으로 이전 가능하다. 이는 제작된 소포 설계이며, 조직 내 자연적 이전은 별개의 가설이다.",
  },
  {
    id: "redox_defense",
    number: 5,
    nameEn: "Redox Defense (Buffer Capacity)",
    nameFi: "Redox-puolustus (puskurikapasiteetti)",
    nameJa: "レドックス防御 (緩衝能力)",
    nameFr: "Défense redox (capacité tampon)",
    nameKo: "산화환원 방어 (완충 용량)",
    chiModulatorEn: "Repair capacity measured separately from damage load: glutathione reserve, SOD, catalase, autophagic flux",
    chiModulatorFi: "Korjauskapasiteetti mitattuna erillään vauriokuormasta: glutationivarasto, SOD, katalaasi, autofagiavirtaus",
    chiModulatorJa: "損傷負荷と分けて測る修復能：グルタチオン予備量, SOD, カタラーゼ, オートファジー流量",
    chiModulatorFr: "Capacité de réparation mesurée séparément de la charge de dommage : réserve de glutathion, SOD, catalase, flux autophagique",
    chiModulatorKo: "손상 부하와 분리해 측정하는 복구 능력: 글루타치온 예비량, SOD, 카탈라아제, 자가포식 흐름",
    keyComponentsEn: "GSH/GSSG ratio, glutathione reductase (GR, requires FAD), SOD1/2, catalase, Nrf2 pathway, autophagic flux, ATG5/ATG7, challenge tolerance",
    keyComponentsFi: "GSH/GSSG-suhde, glutationireduktaasi (GR, vaatii FAD:n), SOD1/2, katalaasi, Nrf2-reitti, autofagiavirtaus, ATG5/ATG7, haastetoleranssi",
    keyComponentsJa: "GSH/GSSG比, グルタチオン還元酵素（GR、FAD必須）, SOD1/2, カタラーゼ, Nrf2経路, オートファジー流量, ATG5/ATG7, 負荷耐性",
    keyComponentsFr: "Ratio GSH/GSSG, glutathion réductase (GR, nécessite FAD), SOD1/2, catalase, voie Nrf2, flux autophagique, ATG5/ATG7, tolérance au challenge",
    keyComponentsKo: "GSH/GSSG 비율, 글루타치온 환원효소 (GR, FAD 필요), SOD1/2, 카탈라아제, Nrf2 경로, 자가포식 흐름, ATG5/ATG7, 부하 내성",
    newInSession: true,
    integrationEn: "The THRESHOLD LAYER, and the layer that holds the repair memory. Below redox capacity, Ca²⁺→ROS is buffered; above it, damage rises steeply. B2/FAD links this to layer 1: FAD is required for BOTH CRY stability AND glutathione reductase. Repair capacity is a state of its own: blocking autophagy, or removing ATG5 or ATG7 function, abolished the protection produced by a pre-exposure, and that protection was still present about 20 hours after the pre-exposure ended. A small increment can therefore mean strengthened repair rather than a weakened receptor.",
    integrationFi: "KYNNYSKERROS ja korjauksen muistin sijaintipaikka. Redox-kapasiteetin alla Ca²⁺→ROS puskuroidaan; sen yläpuolella vaurio kasvaa jyrkästi. B2/FAD linkittää tämän kerrokseen 1: FAD tarvitaan SEKÄ CRY:n vakauteen ETTÄ glutationireduktaasiin. Korjauskapasiteetti on oma tilansa: autofagian esto tai ATG5- tai ATG7-toiminnan poisto kumosi esikäsittelyn tuottaman suojan, ja suoja oli yhä havaittavissa noin 20 tuntia esikäsittelyn päättymisen jälkeen. Vähäinen lisävaste voi siksi tarkoittaa vahvistunutta korjausta eikä heikentynyttä vastaanotinta.",
    integrationJa: "閾値層であり、修復の記憶が置かれる層。レドックス容量以下ではCa²⁺→ROSは緩衝され、それを超えると損傷は急峻に増える。B2/FADはこれを第1層に結びつける：FADはCRYの安定性とグルタチオン還元酵素の双方に必要である。修復能は独立した状態である：オートファジーの阻害やATG5・ATG7機能の除去は前曝露による保護を消失させ、その保護は前曝露終了後およそ20時間なお残っていた。増分が小さいことは、受容体の弱化ではなく修復の強化を意味しうる。",
    integrationFr: "La COUCHE SEUIL, et celle qui porte la mémoire de réparation. Sous la capacité redox, Ca²⁺→ROS est tamponné ; au-dessus, les dommages montent fortement. B2/FAD relie ceci à la couche 1 : le FAD est requis pour la stabilité de CRY ET pour la glutathion réductase. La capacité de réparation est un état à part entière : bloquer l'autophagie ou supprimer ATG5 ou ATG7 a aboli la protection produite par une pré-exposition, et cette protection subsistait environ 20 heures après la fin de la pré-exposition. Un faible incrément peut donc signifier une réparation renforcée plutôt qu'un récepteur affaibli.",
    integrationKo: "역치 층이자 복구 기억이 자리하는 층. 산화환원 용량 이하에서는 Ca²⁺→ROS가 완충되고, 그 이상에서는 손상이 가파르게 증가한다. B2/FAD가 이것을 제1층과 연결한다: FAD는 CRY 안정성과 글루타치온 환원효소 모두에 필요하다. 복구 능력은 그 자체로 하나의 상태다: 자가포식을 차단하거나 ATG5 또는 ATG7 기능을 제거하면 사전 노출이 만든 보호가 사라졌고, 그 보호는 사전 노출 종료 후 약 20시간까지 남아 있었다. 증분이 작다는 것은 수용체 약화가 아니라 복구 강화를 뜻할 수 있다.",
  },
  {
    id: "cell_type",
    number: 6,
    nameEn: "Cell Type (χ_tissue Expression Profile)",
    nameFi: "Solutyyppi (χ_tissue-ekspressioprofiili)",
    nameJa: "細胞型 (χ_tissue)",
    nameFr: "Type cellulaire (χ_tissue)",
    nameKo: "세포 유형 (χ_tissue)",
    chiModulatorEn: "Cell-specific channel expression, plus polarity and the spatial PIP₃ distribution",
    chiModulatorFi: "Solutarkka kanavien ilmentyminen sekä polariteetti ja PIP₃:n alueellinen jakautuminen",
    chiModulatorJa: "細胞特異的なチャネル発現に加え、極性とPIP₃の空間分布",
    chiModulatorFr: "Expression des canaux propre à la cellule, plus la polarité et la distribution spatiale du PIP₃",
    chiModulatorKo: "세포 특이적 채널 발현과 극성 및 PIP₃의 공간 분포",
    keyComponentsEn: "Leydig (Cav3), gonadotroph (Cav3), β-cell (Cav1+3), cardiomyocyte (Cav1.2), KCNJ15 + polyamines, PI3Kγ, PTEN",
    keyComponentsFi: "Leydig (Cav3), gonadotrooppi (Cav3), β-solu (Cav1+3), kardiomyosyytti (Cav1.2), KCNJ15 + polyamiinit, PI3Kγ, PTEN",
    keyComponentsJa: "ライディッヒ細胞 (Cav3), 性腺刺激ホルモン分泌細胞 (Cav3), β細胞 (Cav1+3), 心筋細胞 (Cav1.2), KCNJ15＋ポリアミン, PI3Kγ, PTEN",
    keyComponentsFr: "Cellule de Leydig (Cav3), gonadotrope (Cav3), cellule β (Cav1+3), cardiomyocyte (Cav1.2), KCNJ15 + polyamines, PI3Kγ, PTEN",
    keyComponentsKo: "라이디히 세포 (Cav3), 생식선자극호르몬 분비세포 (Cav3), β세포 (Cav1+3), 심근세포 (Cav1.2), KCNJ15 + 폴리아민, PI3Kγ, PTEN",
    newInSession: false,
    integrationEn: "Imported L3 candidate χ_tissue varies with channel expression; it is not χ_geo and requires endpoint calibration. This layer also carries direction as its own endpoint: silencing KCNJ15 removed field-directed orientation while basic motility was retained, and interfering with polyamines, PI3Kγ or PTEN changed electrically guided movement. A cell can stay alive and motile while processing directional information incorrectly, which no damage measure reaches.",
    integrationFi: "Tuotu L3-ehdokas χ_tissue vaihtelee kanavailmentymisen mukaan; se ei ole χ_geo ja vaatii päätepistekalibroinnin. Tämä kerros kantaa myös suunnan omana päätepisteenään: KCNJ15:n vaimentaminen poisti kenttään suuntautumisen perusliikkuvuuden säilyessä, ja polyamiineihin, PI3Kγ:hyn tai PTEN:iin puuttuminen muutti sähköisesti ohjautuvaa liikettä. Solu voi säilyä elävänä ja liikkuvana mutta käsitellä suunnan informaatiota väärin, mihin vauriomittari ei yllä.",
    integrationJa: "導入L3候補χ_tissueはチャネル発現で変化する。χ_geoではなく、エンドポイント較正が必要である。この層は方向も独自のエンドポイントとして担う：KCNJ15の抑制は基本的な運動性を保ったまま場への配向を消失させ、ポリアミン、PI3Kγ、PTENへの介入は電気的に誘導される移動を変えた。細胞は生存し運動しながら方向情報を誤って処理しうる。損傷指標ではここに届かない。",
    integrationFr: "Le candidat L3 importé χ_tissue varie avec l'expression des canaux ; il n'est pas χ_geo et exige un calibrage d'endpoint. Cette couche porte aussi la direction comme endpoint propre : éteindre KCNJ15 a supprimé l'orientation dans le champ tout en conservant la motilité de base, et intervenir sur les polyamines, PI3Kγ ou PTEN a modifié le déplacement guidé électriquement. Une cellule peut rester vivante et mobile tout en traitant mal l'information directionnelle, ce qu'aucune mesure de dommage n'atteint.",
    integrationKo: "도입 L3 후보 χ_tissue는 채널 발현에 따라 달라진다. χ_geo가 아니며 종점 보정이 필요하다. 이 층은 방향도 고유한 종점으로 담는다: KCNJ15를 침묵시키면 기본 운동성은 유지된 채 장 방향 배향이 사라졌고, 폴리아민·PI3Kγ·PTEN에 개입하면 전기 유도 이동이 변했다. 세포는 살아 움직이면서도 방향 정보를 잘못 처리할 수 있으며, 손상 지표로는 이 종점에 닿지 못한다.",
  },
  {
    id: "organ",
    number: 7,
    nameEn: "Organ (Composite χ_organ Profile)",
    nameFi: "Elin (χ_organ-yhdistelmäprofiili)",
    nameJa: "臓器系（複合χ_organ）",
    nameFr: "Système organique (χ_organ composite)",
    nameKo: "장기 계통(복합 χ_organ)",
    chiModulatorEn: "Combined cell types + vascularization + barrier status + dielectric properties + the local tissue environment",
    chiModulatorFi: "Yhdistetyt solutyypit + vaskularisaatio + estetilanne + dielektriset ominaisuudet + paikallinen kudosympäristö",
    chiModulatorJa: "複合細胞型 + 血管化 + 障壁状態 + 誘電特性 + 局所組織環境",
    chiModulatorFr: "Types cellulaires combinés + vascularisation + état des barrières + propriétés diélectriques + environnement tissulaire local",
    chiModulatorKo: "복합 세포 유형 + 혈관화 + 장벽 상태 + 유전 특성 + 국소 조직 환경",
    keyComponentsEn: "Eye, testes, pituitary, adrenal, pancreas, hippocampus, heart, thyroid; cell density, secreted mediators, recipient-cell state, immune cells",
    keyComponentsFi: "Silmä, kivekset, aivolisäke, lisämunuainen, haima, hippokampus, sydän, kilpirauhanen; solutiheys, eritetyt välittäjät, vastaanottajasolujen tila, immuunisolut",
    keyComponentsJa: "眼, 精巣, 下垂体, 副腎, 膵臓, 海馬, 心臓, 甲状腺; 細胞密度, 分泌メディエーター, 受容細胞の状態, 免疫細胞",
    keyComponentsFr: "Œil, testicules, hypophyse, surrénale, pancréas, hippocampe, cœur, thyroïde ; densité cellulaire, médiateurs sécrétés, état des cellules réceptrices, cellules immunitaires",
    keyComponentsKo: "눈, 고환, 뇌하수체, 부신, 췌장, 해마, 심장, 갑상선; 세포 밀도, 분비 매개체, 수용 세포 상태, 면역 세포",
    newInSession: false,
    integrationEn: "12 target organs verified from existing research. Pituitary is the EMF hub: outside BBB, T-type in all hormone cell types. The organ is also where the environment enters: medium from exposed cells carried a protective effect to unexposed recipients, and a brief pulsed exposure changed macrophage function through a TRPC1–STING–NF-κB route with phagocytosis of co-cultured target cells as the endpoint. This is why an isolated cell and the same cell type in tissue can respond differently, and why a rise in an inflammatory or calcium signal is always reported with the function it changes.",
    integrationFi: "12 kohde-elintä todennettu olemassa olevasta tutkimuksesta. Aivolisäke on EMF-solmukohta: BBB:n ulkopuolella, T-tyyppi kaikissa hormonisolutyypeissä. Elin on myös se kohta, jossa ympäristö tulee mukaan: altistettujen solujen kasvatusneste välitti suojaavan vaikutuksen altistamattomille vastaanottajille, ja lyhyt pulssialtistus muutti makrofagien toimintaa TRPC1–STING–NF-κB-reitin kautta päätepisteenä yhteisviljeltyjen kohdesolujen fagosytoosi. Siksi eristetty solu ja sama solutyyppi kudoksessa voivat vastata eri tavoin, ja siksi tulehdus- tai kalsiumsignaalin nousu raportoidaan aina sen toiminnan kanssa, jota se muuttaa.",
    integrationJa: "既存の研究から12の標的臓器を検証。下垂体がEMFのハブ：BBBの外側、すべてのホルモン細胞型にT型。臓器は環境が入り込む地点でもある：曝露細胞の培地は非曝露の受容細胞に保護効果を運び、短時間のパルス曝露はTRPC1–STING–NF-κB経路を介してマクロファージ機能を変え、共培養標的細胞の貪食がエンドポイントとなった。だからこそ単離細胞と組織内の同一細胞型は異なる応答を示し、炎症やカルシウム信号の上昇は常にそれが変える機能とともに報告される。",
    integrationFr: "12 organes cibles vérifiés à partir de la recherche existante. L'hypophyse est le hub EMF : hors BHE, type T dans tous les types de cellules hormonales. L'organe est aussi le point d'entrée de l'environnement : le milieu de cellules exposées a porté un effet protecteur à des receveuses non exposées, et une brève exposition pulsée a modifié la fonction macrophagique via une voie TRPC1–STING–NF-κB, avec la phagocytose de cellules cibles co-cultivées comme endpoint. C'est pourquoi une cellule isolée et le même type cellulaire en tissu peuvent répondre différemment, et pourquoi une hausse de signal inflammatoire ou calcique est toujours rapportée avec la fonction qu'elle modifie.",
    integrationKo: "기존 연구에서 12개 표적 장기 검증. 뇌하수체가 EMF 허브: BBB 외부, 모든 호르몬 세포 유형에 T형. 장기는 환경이 들어오는 지점이기도 하다: 노출된 세포의 배지가 노출되지 않은 수용 세포에 보호 효과를 전달했고, 짧은 펄스 노출은 TRPC1–STING–NF-κB 경로를 통해 대식세포 기능을 바꾸었으며 공배양 표적 세포의 식균작용이 종점이었다. 그래서 분리된 세포와 조직 속 같은 세포 유형의 반응이 다를 수 있고, 염증이나 칼슘 신호의 상승은 언제나 그것이 바꾸는 기능과 함께 보고된다.",
  },
  {
    id: "autonomic",
    number: 8,
    nameEn: "Autonomic Nervous System (System-Wide Modulator)",
    nameFi: "Autonominen hermosto (koko kehon modulaattori)",
    nameJa: "自律神経 (迷走神経ブレーキ)",
    nameFr: "Autonome (frein vagal)",
    nameKo: "자율신경 (미주신경 브레이크)",
    chiModulatorEn: "HRV, vagal tone, sympathetic/parasympathetic balance",
    chiModulatorFi: "HRV, vagaalinen tonus, sympaattinen/parasympaattinen tasapaino",
    chiModulatorJa: "HRV, 迷走神経緊張, 交感神経/副交感神経バランス",
    chiModulatorFr: "VFC, tonus vagal, équilibre sympathique/parasympathique",
    chiModulatorKo: "HRV, 미주신경 긴장도, 교감/부교감 신경 균형",
    keyComponentsEn: "SA node (Cav3 pacemaking), vagus nerve, cholinergic anti-inflammatory pathway, baroreflexes",
    keyComponentsFi: "SA-solmu (Cav3-tahdistus), vagushermo, kolinerginen anti-inflammatorinen reitti, barorefleksit",
    keyComponentsJa: "洞房結節（Cav3ペースメーキング）, 迷走神経, コリン作動性抗炎症経路, 圧受容器反射",
    keyComponentsFr: "Nœud SA (pacemaking Cav3), nerf vague, voie anti-inflammatoire cholinergique, baroréflexes",
    keyComponentsKo: "동방결절 (Cav3 박동 조율), 미주신경, 콜린성 항염증 경로, 압력반사",
    newInSession: true,
    integrationEn: "The INTEGRATION LAYER. Autonomic balance modulates ALL lower layers simultaneously: sympathetic activation → cortisol → HPA→HPG suppression. HRV reduction → chronic inflammation → barrier weakening. SA node T-type channels are direct EMF targets → HRV reduction is a measurable early biomarker. FOURTH independent EMF→TFR route.",
    integrationFi: "INTEGRAATIOKERROS. Autonominen tasapaino säätelee KAIKKIA alempia kerroksia samanaikaisesti: sympaattinen aktivaatio → kortisoli → HPA→HPG-suppressio. HRV:n lasku → krooninen tulehdus → esteiden heikkeneminen. SA-solmun T-tyypin kanavat ovat suoria EMF-kohteita → HRV:n lasku on mitattava varhainen biomarkeri. NELJÄS itsenäinen EMF→TFR-reitti.",
    integrationJa: "統合層。自律神経バランスがすべての下位層を同時に調節：交感神経活性化 → コルチゾール → HPA→HPG抑制。HRV低下 → 慢性炎症 → 障壁弱体化。洞房結節のT型チャネルは直接的なEMF標的 → HRV低下は測定可能な早期バイオマーカー。第4の独立したEMF→TFR経路。",
    integrationFr: "La COUCHE D'INTÉGRATION. L'équilibre autonome module TOUTES les couches inférieures simultanément : activation sympathique → cortisol → suppression HPA→HPG. Réduction de la VFC → inflammation chronique → affaiblissement des barrières. Les canaux de type T du nœud SA sont des cibles EMF directes → la réduction de la VFC est un biomarqueur précoce mesurable. QUATRIÈME voie indépendante EMF→TFR.",
    integrationKo: "통합 층. 자율신경 균형이 모든 하위 층을 동시에 조절: 교감신경 활성화 → 코르티솔 → HPA→HPG 억제. HRV 감소 → 만성 염증 → 장벽 약화. 동방결절 T형 채널은 직접적인 EMF 표적 → HRV 감소는 측정 가능한 조기 바이오마커. 제4의 독립적 EMF→TFR 경로.",
  },
  {
    id: "endocrine",
    number: 9,
    nameEn: "Endocrine Axes (HPG, HPA, HPT)",
    nameFi: "Endokriiniset akselit (HPG, HPA, HPT)",
    nameJa: "内分泌 (HPG軸)",
    nameFr: "Endocrinien (axe HPG)",
    nameKo: "내분비 (HPG 축)",
    chiModulatorEn: "Pituitary T-type channels → all hormone secretion",
    chiModulatorFi: "Aivolisäkkeen T-tyypin kanavat → kaikki hormonisekretio",
    chiModulatorJa: "下垂体T型チャネル → すべてのホルモン分泌",
    chiModulatorFr: "Canaux de type T hypophysaires → toute sécrétion hormonale",
    chiModulatorKo: "뇌하수체 T형 채널 → 모든 호르몬 분비",
    keyComponentsEn: "HPG (FSH/LH), HPA (ACTH/cortisol), HPT (TSH/T3/T4), prolactin",
    keyComponentsFi: "HPG (FSH/LH), HPA (ACTH/kortisoli), HPT (TSH/T3/T4), prolaktiini",
    keyComponentsJa: "HPG (FSH/LH), HPA (ACTH/コルチゾール), HPT (TSH/T3/T4), プロラクチン",
    keyComponentsFr: "HPG (FSH/LH), HPA (ACTH/cortisol), HPT (TSH/T3/T4), prolactine",
    keyComponentsKo: "HPG (FSH/LH), HPA (ACTH/코르티솔), HPT (TSH/T3/T4), 프로락틴",
    newInSession: false,
    integrationEn: "Pituitary as EMF hub: Cav3 in gonadotroph, corticotroph, thyrotroph, lactotroph. Outside BBB.",
    integrationFi: "Aivolisäke EMF-solmukohtana: Cav3 gonadotroopissa, kortikotroopissa, tyreotroopissa, laktotroopissa. BBB:n ulkopuolella.",
    integrationJa: "下垂体がEMFハブ：性腺刺激ホルモン分泌細胞、副腎皮質刺激ホルモン分泌細胞、甲状腺刺激ホルモン分泌細胞、乳腺刺激ホルモン分泌細胞にCav3。BBBの外側。",
    integrationFr: "L'hypophyse comme hub EMF : Cav3 dans les gonadotropes, corticotropes, thyréotropes, lactotropes. En dehors de la BHE.",
    integrationKo: "뇌하수체가 EMF 허브: 생식선자극호르몬 분비세포, 부신피질자극호르몬 분비세포, 갑상선자극호르몬 분비세포, 유즙분비호르몬 분비세포에 Cav3. BBB 외부.",
  },
  {
    id: "circadian",
    number: 10,
    nameEn: "Circadian Timing",
    nameFi: "Sirkadiaaninen ajoitus",
    nameJa: "概日リズム (CRY時計)",
    nameFr: "Circadien (horloge CRY)",
    nameKo: "일주기 (CRY 시계)",
    chiModulatorEn: "Light spectrum, CRY photocycle, melatonin",
    chiModulatorFi: "Valospektri, CRY-fotosykli, melatoniini",
    chiModulatorJa: "光スペクトル, CRY光サイクル, メラトニン",
    chiModulatorFr: "Spectre lumineux, photocycle CRY, mélatonine",
    chiModulatorKo: "광 스펙트럼, CRY 광주기, 멜라토닌",
    keyComponentsEn: "SCN, pineal, CRY1/2, peripheral clocks",
    keyComponentsFi: "SCN, käpyli, CRY1/2, periferiset kellot",
    keyComponentsJa: "SCN, 松果体, CRY1/2, 末梢時計",
    keyComponentsFr: "NSC, pinéale, CRY1/2, horloges périphériques",
    keyComponentsKo: "SCN, 송과체, CRY1/2, 말초 시계",
    newInSession: false,
    integrationEn: "Eye as primary target. CRY dual system. Melatonin-fertility bridge.",
    integrationFi: "Silmä primaarisena kohteena. CRY-kaksoissysteemi. Melatoniini-fertiliteetti-silta.",
    integrationJa: "眼が主要標的。CRY二重システム。メラトニン-生殖能力の橋渡し。",
    integrationFr: "L'œil comme cible primaire. Système dual CRY. Pont mélatonine-fertilité.",
    integrationKo: "눈이 주요 표적. CRY 이중 시스템. 멜라토닌-생식력 연결.",
  },
  {
    id: "individual",
    number: 11,
    nameEn: "Individual Variation",
    nameFi: "Yksilöllinen vaihtelu",
    nameJa: "個体",
    nameFr: "Individuel",
    nameKo: "개체",
    chiModulatorEn: "Measured exposure-by-genotype interactions, nutrition (B2, ω-3), sex, age",
    chiModulatorFi: "Mitatut altistuksen ja genotyypin yhteisvaikutukset, ravitsemus (B2, ω-3), sukupuoli, ikä",
    chiModulatorJa: "測定された曝露×遺伝型の交互作用、栄養（B2, ω-3）、性別、年齢",
    chiModulatorFr: "Interactions mesurées exposition × génotype, nutrition (B2, ω-3), sexe, âge",
    chiModulatorKo: "측정된 노출 × 유전형 상호작용, 영양 (B2, ω-3), 성별, 연령",
    keyComponentsEn: "CACNA1C genotype with a named sleep-spindle endpoint, CACNA1G T-type SNPs, OCA2, LCT, B2 status, declared cell history (passage, differentiation, prior exposures)",
    keyComponentsFi: "CACNA1C-genotyyppi nimetyn unisukkulapäätepisteen kanssa, CACNA1G:n T-tyypin SNP:t, OCA2, LCT, B2-status, ilmoitettu soluhistoria (passage, erilaistuminen, aiemmat altistukset)",
    keyComponentsJa: "名指しの睡眠紡錘エンドポイントを伴うCACNA1C遺伝型, CACNA1GのT型SNP, OCA2, LCT, B2状態, 明示された細胞履歴（継代・分化・既往曝露）",
    keyComponentsFr: "Génotype CACNA1C avec un endpoint de fuseaux de sommeil nommé, SNPs de type T CACNA1G, OCA2, LCT, statut B2, historique cellulaire déclaré (passage, différenciation, expositions antérieures)",
    keyComponentsKo: "명시된 수면방추 종점을 가진 CACNA1C 유전형, CACNA1G T형 SNP, OCA2, LCT, B2 상태, 선언된 세포 이력 (계대, 분화, 이전 노출)",
    newInSession: false,
    integrationEn: "Imported L3 candidate χ_channel represents genetic channel-gating variation; it does not alter χ_geo. Priority goes to interactions measured in the same people as the exposure and the endpoint: a randomised human study genotyped for CACNA1C read a named sleep-spindle endpoint under controlled radiofrequency exposure. For cells, the corresponding record is the declared history — passage number, differentiation, culture conditions and prior exposures — which is what a replication has to match, in place of the publication year.",
    integrationFi: "Tuotu L3-ehdokas χ_channel kuvaa kanavaportituksen geneettistä vaihtelua; se ei muuta χ_geoa. Etusijalla ovat yhteisvaikutukset, jotka on mitattu samoilta henkilöiltä kuin altistus ja päätepiste: satunnaistettu ihmistutkimus CACNA1C-genotyypityksellä luki nimetyn unisukkulapäätepisteen hallitussa radiotaajuisessa altistuksessa. Soluilla vastaava tietue on ilmoitettu historia — passage, erilaistuminen, kasvatusolot ja aiemmat altistukset — ja juuri se on replikaation kohdattava suure julkaisuvuoden sijaan.",
    integrationJa: "導入L3候補χ_channelはチャネルゲーティングの遺伝的変異を表し、χ_geoを変更しない。優先されるのは、曝露とエンドポイントと同一人物で測定された交互作用である：CACNA1Cを遺伝型判定した無作為化ヒト研究が、制御された高周波曝露下で名指しの睡眠紡錘エンドポイントを読んだ。細胞では対応する記録は明示された履歴——継代数、分化、培養条件、既往曝露——であり、複製が一致させるべきは発表年ではなくこれである。",
    integrationFr: "Le candidat L3 importé χ_channel représente la variation génétique du gating ; il ne modifie pas χ_geo. La priorité va aux interactions mesurées chez les mêmes personnes que l'exposition et l'endpoint : une étude humaine randomisée génotypée pour CACNA1C a lu un endpoint de fuseaux de sommeil nommé sous exposition radiofréquence contrôlée. Pour les cellules, l'enregistrement correspondant est l'historique déclaré — passage, différenciation, conditions de culture, expositions antérieures — c'est cela qu'une réplication doit apparier, et non l'année de publication.",
    integrationKo: "도입 L3 후보 χ_channel은 채널 게이팅의 유전 변이를 나타내며 χ_geo를 바꾸지 않는다. 우선순위는 노출·종점과 같은 사람에게서 측정된 상호작용이다: CACNA1C 유전형을 판정한 무작위 인체 연구가 통제된 고주파 노출에서 명시된 수면방추 종점을 읽었다. 세포의 경우 대응하는 기록은 선언된 이력 — 계대 수, 분화, 배양 조건, 이전 노출 — 이며, 복제가 맞추어야 할 것은 발표 연도가 아니라 이것이다.",
  },
  {
    id: "population",
    number: 12,
    nameEn: "Population & Environment",
    nameFi: "Populaatio ja ympäristö",
    nameJa: "集団",
    nameFr: "Population",
    nameKo: "집단",
    chiModulatorEn: "Electrification, urbanization, dairy consumption patterns",
    chiModulatorFi: "Sähköistyminen, kaupungistuminen, maitotuotteiden kulutusmallit",
    chiModulatorJa: "電化、都市化、乳製品消費パターン",
    chiModulatorFr: "Électrification, urbanisation, modes de consommation laitière",
    chiModulatorKo: "전기화, 도시화, 유제품 소비 패턴",
    keyComponentsEn: "χ_env, COVID-WFH test, population χ profiles",
    keyComponentsFi: "χ_env, COVID-WFH-testi, populaation χ-profiilit",
    keyComponentsJa: "χ_env, COVID在宅勤務テスト, 集団χプロファイル",
    keyComponentsFr: "χ_env, test COVID-télétravail, profils χ de population",
    keyComponentsKo: "χ_env, COVID 재택근무 테스트, 집단 χ 프로파일",
    newInSession: false,
    integrationEn: "Imported L3 candidate χ_env is a population/technology-timing profile in the 54-country dataset, not the onset of χ_geo or a measured dose.",
    integrationFi: "Tuotu L3-ehdokas χ_env on 54 maan aineiston populaatio-/teknologia-ajoitusprofiili, ei χ_geon alkaminen tai mitattu annos.",
    integrationJa: "導入L3候補χ_envは54か国データの集団・技術時期プロファイルであり、χ_geoの開始でも測定線量でもない。",
    integrationFr: "Le candidat L3 importé χ_env est un profil de population/calendrier technologique dans le jeu de 54 pays, non le début de χ_geo ni une dose mesurée.",
    integrationKo: "도입 L3 후보 χ_env는 54개국 데이터의 인구·기술 시점 프로필이며 χ_geo의 시작이나 측정 선량이 아니다.",
  },
];
