export interface ModulomeLayer {
  id: string;
  number: number;
  nameEn: string;
  nameFi: string;
  chiModulatorEn: string;
  chiModulatorFi: string;
  keyComponentsEn: string;
  keyComponentsFi: string;
  newInSession: boolean;
  integrationEn: string;
  integrationFi: string;
}

export const MODULOME_LAYERS: ModulomeLayer[] = [
  {
    id: "molecular",
    number: 1,
    nameEn: "Molecular (Spin & Chromophore)",
    nameFi: "Molekulaarinen (spin ja kromofori)",
    chiModulatorEn: "FAD availability and photocycle state",
    chiModulatorFi: "FAD:n saatavuus ja fotosyklin tila",
    keyComponentsEn: "CRY1, CRY2, FAD, FADH•, tryptophan chain",
    keyComponentsFi: "CRY1, CRY2, FAD, FADH•, tryptofaaniketju",
    newInSession: false,
    integrationEn: "RPM mechanism. B2 → FAD → χ_molecular.",
    integrationFi: "RPM-mekanismi. B2 → FAD → χ_molekulaarinen.",
  },
  {
    id: "ion_channel",
    number: 2,
    nameEn: "Ion Channel (Gating Dynamics)",
    nameFi: "Ionikanava (porttidynamiikka)",
    chiModulatorEn: "Vm vs channel threshold; T-type at bifurcation",
    chiModulatorFi: "Vm vs kanavakynnys; T-tyyppi bifurkaatiossa",
    keyComponentsEn: "Cav1 (L-type), Cav3 (T-type), TRPC1, CatSper, K_ATP",
    keyComponentsFi: "Cav1 (L-tyyppi), Cav3 (T-tyyppi), TRPC1, CatSper, K_ATP",
    newInSession: false,
    integrationEn: "T-type window current = primary EMF transducer at low intensities. L-type at high intensities.",
    integrationFi: "T-tyypin ikkunavirta = primaarinen EMF-anturi matalilla intensiteeteillä. L-tyyppi korkeilla intensiteeteillä.",
  },
  {
    id: "mitochondrial",
    number: 3,
    nameEn: "Mitochondrial (ΔΨm Ca²⁺→ROS Converter)",
    nameFi: "Mitokondriaalinen (ΔΨm Ca²⁺→ROS-muunnin)",
    chiModulatorEn: "ΔΨm ≈ −180 mV (>2× plasma membrane); mitochondrial age/health",
    chiModulatorFi: "ΔΨm ≈ −180 mV (>2× solukalvo); mitokondrion ikä/terveys",
    keyComponentsEn: "VDAC (outer), MCU (inner, Ca²⁺ uniporter), ETC complexes I–IV",
    keyComponentsFi: "VDAC (ulompi), MCU (sisä, Ca²⁺-uniportteri), ETC-kompleksit I–IV",
    newInSession: true,
    integrationEn: "The MISSING LINK in ‘Ca²⁺ → ROS’. Cytoplasmic Ca²⁺ from VGCC enters mitochondria via MCU → disrupts electron transport chain → ROS production. Aged/damaged mitochondria produce MORE ROS per Ca²⁺ unit → age amplifies EMF damage. ΔΨm is the highest sustained voltage in the cell.",
    integrationFi: "PUUTTUVA LINKKI ‘Ca²⁺ → ROS’ -ketjussa. Sytoplasman Ca²⁺ VGCC:ltä pääsee mitokondrioihin MCU:n kautta → häiritsee elektroninsiirtoketjua → ROS-tuotanto. Vanhat/vaurioituneet mitokondriot tuottavat ENEMMÄN ROS:ia per Ca²⁺-yksikkö → ikä vahvistaa EMF-vaurioita.",
  },
  {
    id: "membrane_barrier",
    number: 4,
    nameEn: "Membrane & Biological Barriers",
    nameFi: "Kalvo ja biologiset esteet",
    chiModulatorEn: "Lipid composition (CRY orientation) + TJ integrity",
    chiModulatorFi: "Lipidikoostumus (CRY-orientaatio) + TJ-eheys",
    keyComponentsEn: "Occludin, claudin, ZO-1; ω-3/7 lipids; BBB, BTB, BRB, placenta",
    keyComponentsFi: "Okkludiini, klaudiini, ZO-1; ω-3/7-lipidit; BBB, BTB, BRB, istukka",
    newInSession: false,
    integrationEn: "Barriers are continuous χ modulators. Positive feedback: EMF opens barrier → χ rises → more damage.",
    integrationFi: "Esteet ovat jatkuvia χ-modulaattoreita. Positiivinen takaisinkytkentä: EMF avaa esteen → χ nousee → lisää vaurioita.",
  },
  {
    id: "redox_defense",
    number: 5,
    nameEn: "Redox Defense (Buffer Capacity)",
    nameFi: "Redox-puolustus (puskurikapasiteetti)",
    chiModulatorEn: "Glutathione reserve, SOD, catalase; FAD-dependent GR",
    chiModulatorFi: "Glutationivarasto, SOD, katalaasi; FAD-riippuvainen GR",
    keyComponentsEn: "GSH/GSSG ratio, glutathione reductase (GR, requires FAD), SOD1/2, catalase, Nrf2 pathway",
    keyComponentsFi: "GSH/GSSG-suhde, glutationireduktaasi (GR, vaatii FAD:n), SOD1/2, katalaasi, Nrf2-reitti",
    newInSession: true,
    integrationEn: "The THRESHOLD LAYER. Below redox capacity, Ca²⁺→ROS is buffered. Above it, damage is exponential. B2/FAD links this to layer 1: FAD is required for BOTH CRY stability AND glutathione reductase. B2 deficiency weakens BOTH. This explains China: low CRY sensitivity but WORST TFR because glutathione collapse amplifies VGCC-mediated damage.",
    integrationFi: "KYNNYSKERROS. Redox-kapasiteetin alla Ca²⁺→ROS puskuroidaan. Sen yläpuolella vahinko on eksponentiaalista. B2/FAD linkittää tämän kerrokseen 1: FAD tarvitaan SEKÄ CRY:n vakauteen ETTÄ glutationireduktaasiin. B2-puutos heikentää molempia. Tämä selittää Kiinan: matala CRY-herkkyys mutta PAHIN TFR, koska glutationin romahdus vahvistaa VGCC-välitteistä vauriota.",
  },
  {
    id: "cell_type",
    number: 6,
    nameEn: "Cell Type (Expression Profile)",
    nameFi: "Solutyyppi (ekspressioprofiili)",
    chiModulatorEn: "Cell-specific channel expression density and combination",
    chiModulatorFi: "Soluspesifinen kanavien ilmentymistiheys ja yhdistelmä",
    keyComponentsEn: "Leydig (Cav3), gonadotroph (Cav3), β-cell (Cav1+3), cardiomyocyte (Cav1.2)",
    keyComponentsFi: "Leydig (Cav3), gonadotrooppi (Cav3), β-solu (Cav1+3), kardiomyosyytti (Cav1.2)",
    newInSession: false,
    integrationEn: "Each cell type has unique χ-profile based on which channels it expresses.",
    integrationFi: "Jokaisella solutyypillä on ainutlaatuinen χ-profiili perustuen sen kanavien ilmentymiseen.",
  },
  {
    id: "organ",
    number: 7,
    nameEn: "Organ (Composite χ-Profile)",
    nameFi: "Elin (kokonais-χ-profiili)",
    chiModulatorEn: "Combined cell types + vascularization + barrier status + dielectric properties",
    chiModulatorFi: "Yhdistetyt solutyypit + vaskularisaatio + estetilanteen + dielektriset ominaisuudet",
    keyComponentsEn: "Eye, testes, pituitary, adrenal, pancreas, hippocampus, heart, thyroid",
    keyComponentsFi: "Silmä, kivekset, aivolisäke, lisämunuainen, haima, hippokampus, sydän, kilpirauhanen",
    newInSession: false,
    integrationEn: "8 target organs verified from existing research. Pituitary is the EMF hub: outside BBB, T-type in all hormone cell types.",
    integrationFi: "8 kohde-elintä verifioitu olemassa olevasta tutkimuksesta. Aivolisäke on EMF-solmukohta: BBB:n ulkopuolella, T-tyyppi kaikissa hormonisolutyypeissä.",
  },
  {
    id: "autonomic",
    number: 8,
    nameEn: "Autonomic Nervous System (System-Wide Modulator)",
    nameFi: "Autonominen hermosto (koko kehon modulaattori)",
    chiModulatorEn: "HRV, vagal tone, sympathetic/parasympathetic balance",
    chiModulatorFi: "HRV, vagaalinen tonus, sympaattinen/parasympaattinen tasapaino",
    keyComponentsEn: "SA node (Cav3 pacemaking), vagus nerve, cholinergic anti-inflammatory pathway, baroreflexes",
    keyComponentsFi: "SA-solmu (Cav3-tahdistus), vagushermo, kolinerginen anti-inflammatorinen reitti, barorefleksit",
    newInSession: true,
    integrationEn: "The INTEGRATION LAYER. Autonomic balance modulates ALL lower layers simultaneously: sympathetic activation → cortisol → HPA→HPG suppression. HRV reduction → chronic inflammation → barrier weakening. SA node T-type channels are direct EMF targets → HRV reduction is a measurable early biomarker. FOURTH independent EMF→TFR route.",
    integrationFi: "INTEGRAATIOKERROS. Autonominen tasapaino moduloi KAIKKIA alempia kerroksia samanaikaisesti: sympaattinen aktivaatio → kortisoli → HPA→HPG-suppressio. HRV:n lasku → krooninen tulehdus → esteiden heikkeneminen. SA-solmun T-tyypin kanavat ovat suoria EMF-kohteita → HRV:n lasku on mitattava varhainen biomarkeri. NELJÄS itsenäinen EMF→TFR-reitti.",
  },
  {
    id: "endocrine",
    number: 9,
    nameEn: "Endocrine Axes (HPG, HPA, HPT)",
    nameFi: "Endokriiniset akselit (HPG, HPA, HPT)",
    chiModulatorEn: "Pituitary T-type channels → all hormone secretion",
    chiModulatorFi: "Aivolisäkkeen T-tyypin kanavat → kaikki hormonisekretio",
    keyComponentsEn: "HPG (FSH/LH), HPA (ACTH/cortisol), HPT (TSH/T3/T4), prolactin",
    keyComponentsFi: "HPG (FSH/LH), HPA (ACTH/kortisoli), HPT (TSH/T3/T4), prolaktiini",
    newInSession: false,
    integrationEn: "Pituitary as EMF hub: Cav3 in gonadotroph, corticotroph, thyrotroph, lactotroph. Outside BBB.",
    integrationFi: "Aivolisäke EMF-solmukohtana: Cav3 gonadotroopissa, kortikotroopissa, tyreotroopissa, laktotroopissa. BBB:n ulkopuolella.",
  },
  {
    id: "circadian",
    number: 10,
    nameEn: "Circadian Timing",
    nameFi: "Sirkadiaaninen ajoitus",
    chiModulatorEn: "Light spectrum, CRY photocycle, melatonin",
    chiModulatorFi: "Valospektri, CRY-fotosykli, melatoniini",
    keyComponentsEn: "SCN, pineal, CRY1/2, peripheral clocks",
    keyComponentsFi: "SCN, käpyli, CRY1/2, periferiset kellot",
    newInSession: false,
    integrationEn: "Eye as primary target. CRY dual system. Melatonin-fertility bridge.",
    integrationFi: "Silmä primaarisena kohteena. CRY-kaksoissysteemi. Melatoniini-fertiliteetti-silta.",
  },
  {
    id: "individual",
    number: 11,
    nameEn: "Individual Variation",
    nameFi: "Yksilöllinen vaihtelu",
    chiModulatorEn: "Genetics (OCA2, LCT, CACNA1C, CACNA1G), nutrition (B2, ω-3), sex, age",
    chiModulatorFi: "Genetiikka (OCA2, LCT, CACNA1C, CACNA1G), ravitsemus (B2, ω-3), sukupuoli, ikä",
    keyComponentsEn: "Eye color, lactose tolerance, B2 status, mitochondrial age, CACNA1C psychiatric risk variants, CACNA1G T-type ASD SNPs",
    keyComponentsFi: "Silmän väri, laktoosi-intoleranssi, B2-status, mitokondrion ikä, CACNA1C:n psykiatriset riskivariantit, CACNA1G:n T-tyypin ASD-SNP:t",
    newInSession: false,
    integrationEn: "Northern package: OCA2 + LCT + cattle = CRY co-selection. CACNA1C variants confer risk for ALL FIVE major psychiatric disorders (ASD, ADHD, bipolar, MDD, schizophrenia). Timothy syndrome: CACNA1C GoF → 80% autism penetrance. CACNA1G (T-type) SNPs → ASD. These are genetic χ-modulators: altered channel gating → different χ_channel → different EMF sensitivity.",
    integrationFi: "Pohjoinen paketti: OCA2 + LCT + karja = CRY:n yhteisvalinta. CACNA1C-variantit aiheuttavat riskin KAIKILLE VIIDELLE suurelle psykiatriselle häiriölle (ASD, ADHD, kaksisuuntainen, MDD, skitsofrenia). Timothyn oireyhtymä: CACNA1C GoF → 80 % autismipenetranssi. CACNA1G (T-tyyppi) SNP:t → ASD. Nämä ovat geneettisiä χ-modulaattoreita: muuttunut kanavan porttitoiminta → erilainen χ_channel → erilainen EMF-herkkyys.",
  },
  {
    id: "population",
    number: 12,
    nameEn: "Population & Environment",
    nameFi: "Populaatio ja ympäristö",
    chiModulatorEn: "Electrification, urbanization, dairy consumption patterns",
    chiModulatorFi: "Sähköistyminen, kaupungistuminen, maitotuotteiden kulutusmallit",
    keyComponentsEn: "χ_env, COVID-WFH test, population χ profiles",
    keyComponentsFi: "χ_env, COVID-WFH-testi, populaation χ-profiilit",
    newInSession: false,
    integrationEn: "54-country dataset. Electrification boundary = χ onset.",
    integrationFi: "54 maan aineisto. Sähköistymisraja = χ:n alkaminen.",
  },
];
