export interface ModulomeLayer {
  id: string;
  number: number;
  nameEn: string;
  nameFi: string;
  nameJa: string;
  nameFr: string;
  nameKo: string;
  chiModulatorEn: string;
  chiModulatorFi: string;
  chiModulatorJa: string;
  chiModulatorFr: string;
  chiModulatorKo: string;
  keyComponentsEn: string;
  keyComponentsFi: string;
  keyComponentsJa: string;
  keyComponentsFr: string;
  keyComponentsKo: string;
  newInSession: boolean;
  integrationEn: string;
  integrationFi: string;
  integrationJa: string;
  integrationFr: string;
  integrationKo: string;
}

export const MODULOME_LAYERS: ModulomeLayer[] = [
  {
    id: "molecular",
    number: 1,
    nameEn: "Molecular (Spin & Chromophore)",
    nameFi: "Molekulaarinen (spin ja kromofori)",
    nameJa: "分子 (スピンと発色団)",
    nameFr: "Moléculaire (spin et chromophore)",
    nameKo: "분자 (스핀과 발색단)",
    chiModulatorEn: "FAD availability and photocycle state",
    chiModulatorFi: "FAD:n saatavuus ja fotosyklin tila",
    chiModulatorJa: "FADの利用可能性と光サイクル状態",
    chiModulatorFr: "Disponibilité du FAD et état du photocycle",
    chiModulatorKo: "FAD 가용성 및 광주기 상태",
    keyComponentsEn: "CRY1, CRY2, FAD, FADH•, tryptophan chain",
    keyComponentsFi: "CRY1, CRY2, FAD, FADH•, tryptofaaniketju",
    keyComponentsJa: "CRY1, CRY2, FAD, FADH•, トリプトファン鎖",
    keyComponentsFr: "CRY1, CRY2, FAD, FADH•, chaîne tryptophane",
    keyComponentsKo: "CRY1, CRY2, FAD, FADH•, 트립토판 사슬",
    newInSession: false,
    integrationEn: "RPM mechanism. B2 → FAD → χ_molecular.",
    integrationFi: "RPM-mekanismi. B2 → FAD → χ_molekulaarinen.",
    integrationJa: "RPMメカニズム。B2 → FAD → χ_molecular。",
    integrationFr: "Mécanisme RPM. B2 → FAD → χ_moléculaire.",
    integrationKo: "RPM 메커니즘. B2 → FAD → χ_molecular.",
  },
  {
    id: "ion_channel",
    number: 2,
    nameEn: "Ion Channel (Gating Dynamics)",
    nameFi: "Ionikanava (porttidynamiikka)",
    nameJa: "イオンチャネル (ゲーティング動態)",
    nameFr: "Canal ionique (dynamique de gating)",
    nameKo: "이온 채널 (게이팅 역학)",
    chiModulatorEn: "Vm vs channel threshold; T-type at bifurcation",
    chiModulatorFi: "Vm vs kanavakynnys; T-tyyppi bifurkaatiossa",
    chiModulatorJa: "Vm対チャネル閾値; 分岐点でのT型",
    chiModulatorFr: "Vm vs seuil du canal ; type T à la bifurcation",
    chiModulatorKo: "Vm 대 채널 역치; 분기점에서의 T형",
    keyComponentsEn: "Cav1 (L-type), Cav3 (T-type), TRPC1, CatSper, K_ATP",
    keyComponentsFi: "Cav1 (L-tyyppi), Cav3 (T-tyyppi), TRPC1, CatSper, K_ATP",
    keyComponentsJa: "Cav1 (L型), Cav3 (T型), TRPC1, CatSper, K_ATP",
    keyComponentsFr: "Cav1 (type L), Cav3 (type T), TRPC1, CatSper, K_ATP",
    keyComponentsKo: "Cav1 (L형), Cav3 (T형), TRPC1, CatSper, K_ATP",
    newInSession: false,
    integrationEn: "T-type window current = pathway-A transduction step at low intensities. L-type at high intensities. B (CRY/RPM) is the primary pathway.",
    integrationFi: "T-tyypin ikkunavirta = reitti-A:n transduktioaskel matalilla intensiteeteillä. L-tyyppi korkeilla. B (CRY/RPM) on ensisijainen reitti.",
    integrationJa: "T型ウィンドウ電流＝低強度での経路Aの伝達ステップ。高強度ではL型。B（CRY/RPM）が主要経路。",
    integrationFr: "Courant de fenêtre de type T = étape de transduction de la voie A à faibles intensités. Type L à hautes intensités. B (CRY/RPM) est la voie primaire.",
    integrationKo: "T형 창 전류 = 저강도에서 경로 A의 변환 단계. 고강도에서는 L형. B (CRY/RPM)가 주요 경로.",
  },
  {
    id: "mitochondrial",
    number: 3,
    nameEn: "Mitochondrial (ΔΨm Ca²⁺→ROS Converter)",
    nameFi: "Mitokondriaalinen (ΔΨm Ca²⁺→ROS-muunnin)",
    nameJa: "ミトコンドリア (ΔΨm Ca²⁺→ROS変換器)",
    nameFr: "Mitochondrial (convertisseur ΔΨm Ca²⁺→ROS)",
    nameKo: "미토콘드리아 (ΔΨm Ca²⁺→ROS 변환기)",
    chiModulatorEn: "ΔΨm ≈ −180 mV (>2× plasma membrane); mitochondrial age/health",
    chiModulatorFi: "ΔΨm ≈ −180 mV (>2× solukalvo); mitokondrion ikä/terveys",
    chiModulatorJa: "ΔΨm ≈ −180 mV（細胞膜の2倍以上）; ミトコンドリアの年齢/健康状態",
    chiModulatorFr: "ΔΨm ≈ −180 mV (>2× membrane plasmique) ; âge/santé mitochondriale",
    chiModulatorKo: "ΔΨm ≈ −180 mV (세포막의 2배 이상); 미토콘드리아 연령/건강 상태",
    keyComponentsEn: "VDAC (outer), MCU (inner, Ca²⁺ uniporter), ETC complexes I–IV",
    keyComponentsFi: "VDAC (ulompi), MCU (sisä, Ca²⁺-uniportteri), ETC-kompleksit I–IV",
    keyComponentsJa: "VDAC（外膜）, MCU（内膜, Ca²⁺ユニポーター）, ETC複合体I–IV",
    keyComponentsFr: "VDAC (externe), MCU (interne, uniporteur Ca²⁺), complexes ETC I–IV",
    keyComponentsKo: "VDAC (외막), MCU (내막, Ca²⁺ 유니포터), ETC 복합체 I–IV",
    newInSession: true,
    integrationEn: "The MISSING LINK in ‘Ca²⁺ → ROS’. Cytoplasmic Ca²⁺ from VGCC enters mitochondria via MCU → disrupts electron transport chain → ROS production. Aged/damaged mitochondria produce MORE ROS per Ca²⁺ unit → age amplifies EMF damage. ΔΨm is the highest sustained voltage in the cell.",
    integrationFi: "PUUTTUVA LINKKI ‘Ca²⁺ → ROS’ -ketjussa. Sytoplasman Ca²⁺ VGCC:ltä pääsee mitokondrioihin MCU:n kautta → häiritsee elektroninsiirtoketjua → ROS-tuotanto. Vanhat/vaurioituneet mitokondriot tuottavat ENEMMÄN ROS:ia per Ca²⁺-yksikkö → ikä vahvistaa EMF-vaurioita.",
    integrationJa: "「Ca²⁺ → ROS」の欠けていたリンク。VGCCからの細胞質Ca²⁺がMCU経由でミトコンドリアに流入 → 電子伝達鎖を撹乱 → ROS産生。老化/損傷したミトコンドリアはCa²⁺単位あたりより多くのROSを産生 → 加齢がEMF損傷を増幅。ΔΨmは細胞内で最も高い持続電圧。",
    integrationFr: "Le CHAÎNON MANQUANT dans « Ca²⁺ → ROS ». Le Ca²⁺ cytoplasmique provenant des VGCC entre dans les mitochondries via MCU → perturbe la chaîne de transport d’électrons → production de ROS. Les mitochondries âgées/endommagées produisent PLUS de ROS par unité de Ca²⁺ → l’âge amplifie les dommages EMF. ΔΨm est la tension soutenue la plus élevée de la cellule.",
    integrationKo: "’Ca²⁺ → ROS’의 빠진 고리. VGCC로부터의 세포질 Ca²⁺가 MCU를 통해 미토콘드리아로 유입 → 전자전달계 교란 → ROS 생성. 노화/손상된 미토콘드리아는 Ca²⁺ 단위당 더 많은 ROS 생성 → 노화가 EMF 손상을 증폭. ΔΨm은 세포 내 가장 높은 지속 전압.",
  },
  {
    id: "membrane_barrier",
    number: 4,
    nameEn: "Membrane & Biological Barriers",
    nameFi: "Kalvo ja biologiset esteet",
    nameJa: "膜と生物学的障壁",
    nameFr: "Membrane et barrières biologiques",
    nameKo: "막과 생물학적 장벽",
    chiModulatorEn: "Lipid composition (CRY orientation) + TJ integrity",
    chiModulatorFi: "Lipidikoostumus (CRY-orientaatio) + TJ-eheys",
    chiModulatorJa: "脂質組成（CRYの配向）+ TJの完全性",
    chiModulatorFr: "Composition lipidique (orientation CRY) + intégrité des TJ",
    chiModulatorKo: "지질 조성 (CRY 배향) + TJ 완전성",
    keyComponentsEn: "Occludin, claudin, ZO-1; ω-3/7 lipids; BBB, BTB, BRB, placenta",
    keyComponentsFi: "Okkludiini, klaudiini, ZO-1; ω-3/7-lipidit; BBB, BTB, BRB, istukka",
    keyComponentsJa: "オクルディン, クローディン, ZO-1; ω-3/7脂質; BBB, BTB, BRB, 胎盤",
    keyComponentsFr: "Occludine, claudine, ZO-1 ; lipides ω-3/7 ; BHE, BTB, BRB, placenta",
    keyComponentsKo: "오클루딘, 클라우딘, ZO-1; ω-3/7 지질; BBB, BTB, BRB, 태반",
    newInSession: false,
    integrationEn: "Barrier integrity is a candidate tissue-kernel moderator. A proposed feedback is EMF → barrier opening → greater target exposure → further damage; its direction and gain require endpoint calibration.",
    integrationFi: "Esteen eheys on kudosytimen ehdokasmoderaattori. Ehdotettu takaisinkytkentä on EMF → esteen avautuminen → suurempi kohdekudosaltistus → lisävaurio; suunta ja vahvistus vaativat päätepistekalibroinnin.",
    integrationJa: "障壁完全性は組織カーネルの候補修飾因子です。EMF→障壁開口→標的曝露増加→追加損傷というフィードバックが提案されますが、方向と利得にはエンドポイント校正が必要です。",
    integrationFr: "L'intégrité de la barrière est un modérateur candidat du noyau tissulaire. La rétroaction proposée est CEM → ouverture de la barrière → exposition accrue de la cible → dommages supplémentaires ; direction et gain exigent une calibration d'endpoint.",
    integrationKo: "장벽 완전성은 조직 커널의 후보 조절인자입니다. 제안된 피드백은 EMF → 장벽 개방 → 표적 노출 증가 → 추가 손상이며 방향과 이득은 종점 보정이 필요합니다.",
  },
  {
    id: "redox_defense",
    number: 5,
    nameEn: "Redox Defense (Buffer Capacity)",
    nameFi: "Redox-puolustus (puskurikapasiteetti)",
    nameJa: "レドックス防御 (緩衝能力)",
    nameFr: "Défense redox (capacité tampon)",
    nameKo: "산화환원 방어 (완충 용량)",
    chiModulatorEn: "Glutathione reserve, SOD, catalase; FAD-dependent GR",
    chiModulatorFi: "Glutationivarasto, SOD, katalaasi; FAD-riippuvainen GR",
    chiModulatorJa: "グルタチオン予備量, SOD, カタラーゼ; FAD依存性GR",
    chiModulatorFr: "Réserve de glutathion, SOD, catalase ; GR dépendante du FAD",
    chiModulatorKo: "글루타치온 예비량, SOD, 카탈라아제; FAD 의존성 GR",
    keyComponentsEn: "GSH/GSSG ratio, glutathione reductase (GR, requires FAD), SOD1/2, catalase, Nrf2 pathway",
    keyComponentsFi: "GSH/GSSG-suhde, glutationireduktaasi (GR, vaatii FAD:n), SOD1/2, katalaasi, Nrf2-reitti",
    keyComponentsJa: "GSH/GSSG比, グルタチオン還元酵素（GR、FAD必須）, SOD1/2, カタラーゼ, Nrf2経路",
    keyComponentsFr: "Ratio GSH/GSSG, glutathion réductase (GR, nécessite FAD), SOD1/2, catalase, voie Nrf2",
    keyComponentsKo: "GSH/GSSG 비율, 글루타치온 환원효소 (GR, FAD 필요), SOD1/2, 카탈라아제, Nrf2 경로",
    newInSession: true,
    integrationEn: "The THRESHOLD LAYER. Below redox capacity, Ca²⁺→ROS is buffered. Above it, damage is exponential. B2/FAD links this to layer 1: FAD is required for BOTH CRY stability AND glutathione reductase. B2 deficiency weakens BOTH. This explains East Asia: South Korea (TFR 0.70) and urban China (TFR 1.00) have low CRY sensitivity but severely depressed fertility because glutathione collapse amplifies VGCC-mediated damage.",
    integrationFi: "KYNNYSKERROS. Redox-kapasiteetin alla Ca²⁺→ROS puskuroidaan. Sen yläpuolella vahinko on eksponentiaalista. B2/FAD linkittää tämän kerrokseen 1: FAD tarvitaan SEKÄ CRY:n vakauteen ETTÄ glutationireduktaasiin. B2-puutos heikentää molempia. Tämä selittää Itä-Aasian: Etelä-Korea (TFR 0,70) ja kaupunki-Kiina (TFR 1,00) — matala CRY-herkkyys mutta vakavasti alentunut hedelmällisyys, koska glutationin romahdus vahvistaa VGCC-välitteistä vauriota.",
    integrationJa: "閾値層。レドックス容量以下ではCa²⁺→ROSは緩衝される。それを超えると損傷は指数関数的。B2/FADはこれを第1層に結びつける：FADはCRYの安定性とグルタチオン還元酵素の両方に必要。B2欠乏は両方を弱める。これが東アジアを説明する：韓国（TFR 0.70）と都市部中国（TFR 1.00）はCRY感受性は低いが深刻な出生率低下を示す。グルタチオンの崩壊がVGCC媒介損傷を増幅するため。",
    integrationFr: "La COUCHE SEUIL. En dessous de la capacité redox, Ca²⁺→ROS est tamponné. Au-dessus, les dommages sont exponentiels. B2/FAD relie ceci à la couche 1 : le FAD est requis à la fois pour la stabilité de CRY ET pour la glutathion réductase. La carence en B2 affaiblit les DEUX. Cela explique l'Asie de l'Est : la Corée du Sud (TFR 0,70) et la Chine urbaine (TFR 1,00) ont une faible sensibilité CRY mais une fécondité sévèrement déprimée car l'effondrement du glutathion amplifie les dommages médiés par VGCC.",
    integrationKo: "역치 층. 산화환원 용량 이하에서는 Ca²⁺→ROS가 완충된다. 그 이상에서는 손상이 기하급수적. B2/FAD가 이것을 제1층과 연결: FAD는 CRY 안정성과 글루타치온 환원효소 모두에 필요. B2 결핍은 둘 다 약화. 이것이 동아시아를 설명: 한국(TFR 0.70)과 도시 중국(TFR 1.00)은 낮은 CRY 감수성이지만 심각하게 저하된 출산율, 글루타치온 붕괴가 VGCC 매개 손상을 증폭하기 때문.",
  },
  {
    id: "cell_type",
    number: 6,
    nameEn: "Cell Type (Expression Profile)",
    nameFi: "Solutyyppi (ekspressioprofiili)",
    nameJa: "細胞型 (χ_tissue)",
    nameFr: "Type cellulaire (χ_tissue)",
    nameKo: "세포 유형 (χ_tissue)",
    chiModulatorEn: "Cell-specific channel expression density and combination",
    chiModulatorFi: "Solutarkka kanavien ilmentymistiheys ja yhdistelmä",
    chiModulatorJa: "細胞特異的チャネル発現密度と組み合わせ",
    chiModulatorFr: "Densité et combinaison d'expression des canaux spécifiques à la cellule",
    chiModulatorKo: "세포 특이적 채널 발현 밀도 및 조합",
    keyComponentsEn: "Leydig (Cav3), gonadotroph (Cav3), β-cell (Cav1+3), cardiomyocyte (Cav1.2)",
    keyComponentsFi: "Leydig (Cav3), gonadotrooppi (Cav3), β-solu (Cav1+3), kardiomyosyytti (Cav1.2)",
    keyComponentsJa: "ライディッヒ細胞 (Cav3), 性腺刺激ホルモン分泌細胞 (Cav3), β細胞 (Cav1+3), 心筋細胞 (Cav1.2)",
    keyComponentsFr: "Cellule de Leydig (Cav3), gonadotrope (Cav3), cellule β (Cav1+3), cardiomyocyte (Cav1.2)",
    keyComponentsKo: "라이디히 세포 (Cav3), 생식선자극호르몬 분비세포 (Cav3), β세포 (Cav1+3), 심근세포 (Cav1.2)",
    newInSession: false,
    integrationEn: "Each cell type has unique χ-profile based on which channels it expresses.",
    integrationFi: "Jokaisella solutyypillä on ainutlaatuinen χ-profiili perustuen sen kanavien ilmentymiseen.",
    integrationJa: "各細胞型は発現するチャネルに基づく固有のχプロファイルを持つ。",
    integrationFr: "Chaque type cellulaire possède un profil χ unique basé sur les canaux qu'il exprime.",
    integrationKo: "각 세포 유형은 발현하는 채널에 기반한 고유한 χ 프로파일을 갖는다.",
  },
  {
    id: "organ",
    number: 7,
    nameEn: "Organ (Composite χ-Profile)",
    nameFi: "Elin (kokonais-χ-profiili)",
    nameJa: "臓器系",
    nameFr: "Système organique",
    nameKo: "장기 계통",
    chiModulatorEn: "Combined cell types + vascularization + barrier status + dielectric properties",
    chiModulatorFi: "Yhdistetyt solutyypit + vaskularisaatio + estetilanteen + dielektriset ominaisuudet",
    chiModulatorJa: "複合細胞型 + 血管化 + 障壁状態 + 誘電特性",
    chiModulatorFr: "Types cellulaires combinés + vascularisation + état des barrières + propriétés diélectriques",
    chiModulatorKo: "복합 세포 유형 + 혈관화 + 장벽 상태 + 유전 특성",
    keyComponentsEn: "Eye, testes, pituitary, adrenal, pancreas, hippocampus, heart, thyroid",
    keyComponentsFi: "Silmä, kivekset, aivolisäke, lisämunuainen, haima, hippokampus, sydän, kilpirauhanen",
    keyComponentsJa: "眼, 精巣, 下垂体, 副腎, 膵臓, 海馬, 心臓, 甲状腺",
    keyComponentsFr: "Œil, testicules, hypophyse, surrénale, pancréas, hippocampe, cœur, thyroïde",
    keyComponentsKo: "눈, 고환, 뇌하수체, 부신, 췌장, 해마, 심장, 갑상선",
    newInSession: false,
    integrationEn: "12 target organs verified from existing research. Pituitary is the EMF hub: outside BBB, T-type in all hormone cell types.",
    integrationFi: "8 kohde-elintä todennettu olemassa olevasta tutkimuksesta. Aivolisäke on EMF-solmukohta: BBB:n ulkopuolella, T-tyyppi kaikissa hormonisolutyypeissä.",
    integrationJa: "既存の研究から8つの標的臓器を検証。下垂体がEMFのハブ：BBBの外側、すべてのホルモン細胞型にT型。",
    integrationFr: "8 organes cibles vérifiés à partir de la recherche existante. L'hypophyse est le hub EMF : en dehors de la BHE, type T dans tous les types de cellules hormonales.",
    integrationKo: "기존 연구에서 8개 표적 장기 검증. 뇌하수체가 EMF 허브: BBB 외부, 모든 호르몬 세포 유형에 T형.",
  },
  {
    id: "autonomic",
    number: 8,
    nameEn: "Autonomic Nervous System (System-Wide Modulator)",
    nameFi: "Autonominen hermosto (koko kehon modulaattori)",
    nameJa: "自律神経 (迷走神経ブレーキ)",
    nameFr: "Autonome (frein vagal)",
    nameKo: "자율신경 (미주신경 브레이크)",
    chiModulatorEn: "HRV, vagal tone, sympathetic/parasympathetic balance",
    chiModulatorFi: "HRV, vagaalinen tonus, sympaattinen/parasympaattinen tasapaino",
    chiModulatorJa: "HRV, 迷走神経緊張, 交感神経/副交感神経バランス",
    chiModulatorFr: "VFC, tonus vagal, équilibre sympathique/parasympathique",
    chiModulatorKo: "HRV, 미주신경 긴장도, 교감/부교감 신경 균형",
    keyComponentsEn: "SA node (Cav3 pacemaking), vagus nerve, cholinergic anti-inflammatory pathway, baroreflexes",
    keyComponentsFi: "SA-solmu (Cav3-tahdistus), vagushermo, kolinerginen anti-inflammatorinen reitti, barorefleksit",
    keyComponentsJa: "洞房結節（Cav3ペースメーキング）, 迷走神経, コリン作動性抗炎症経路, 圧受容器反射",
    keyComponentsFr: "Nœud SA (pacemaking Cav3), nerf vague, voie anti-inflammatoire cholinergique, baroréflexes",
    keyComponentsKo: "동방결절 (Cav3 박동 조율), 미주신경, 콜린성 항염증 경로, 압력반사",
    newInSession: true,
    integrationEn: "The INTEGRATION LAYER. Autonomic balance modulates ALL lower layers simultaneously: sympathetic activation → cortisol → HPA→HPG suppression. HRV reduction → chronic inflammation → barrier weakening. SA node T-type channels are direct EMF targets → HRV reduction is a measurable early biomarker. FOURTH independent EMF→TFR route.",
    integrationFi: "INTEGRAATIOKERROS. Autonominen tasapaino säätelee KAIKKIA alempia kerroksia samanaikaisesti: sympaattinen aktivaatio → kortisoli → HPA→HPG-suppressio. HRV:n lasku → krooninen tulehdus → esteiden heikkeneminen. SA-solmun T-tyypin kanavat ovat suoria EMF-kohteita → HRV:n lasku on mitattava varhainen biomarkeri. NELJÄS itsenäinen EMF→TFR-reitti.",
    integrationJa: "統合層。自律神経バランスがすべての下位層を同時に調節：交感神経活性化 → コルチゾール → HPA→HPG抑制。HRV低下 → 慢性炎症 → 障壁弱体化。洞房結節のT型チャネルは直接的なEMF標的 → HRV低下は測定可能な早期バイオマーカー。第4の独立したEMF→TFR経路。",
    integrationFr: "La COUCHE D'INTÉGRATION. L'équilibre autonome module TOUTES les couches inférieures simultanément : activation sympathique → cortisol → suppression HPA→HPG. Réduction de la VFC → inflammation chronique → affaiblissement des barrières. Les canaux de type T du nœud SA sont des cibles EMF directes → la réduction de la VFC est un biomarqueur précoce mesurable. QUATRIÈME voie indépendante EMF→TFR.",
    integrationKo: "통합 층. 자율신경 균형이 모든 하위 층을 동시에 조절: 교감신경 활성화 → 코르티솔 → HPA→HPG 억제. HRV 감소 → 만성 염증 → 장벽 약화. 동방결절 T형 채널은 직접적인 EMF 표적 → HRV 감소는 측정 가능한 조기 바이오마커. 제4의 독립적 EMF→TFR 경로.",
  },
  {
    id: "endocrine",
    number: 9,
    nameEn: "Endocrine Axes (HPG, HPA, HPT)",
    nameFi: "Endokriiniset akselit (HPG, HPA, HPT)",
    nameJa: "内分泌 (HPG軸)",
    nameFr: "Endocrinien (axe HPG)",
    nameKo: "내분비 (HPG 축)",
    chiModulatorEn: "Pituitary T-type channels → all hormone secretion",
    chiModulatorFi: "Aivolisäkkeen T-tyypin kanavat → kaikki hormonisekretio",
    chiModulatorJa: "下垂体T型チャネル → すべてのホルモン分泌",
    chiModulatorFr: "Canaux de type T hypophysaires → toute sécrétion hormonale",
    chiModulatorKo: "뇌하수체 T형 채널 → 모든 호르몬 분비",
    keyComponentsEn: "HPG (FSH/LH), HPA (ACTH/cortisol), HPT (TSH/T3/T4), prolactin",
    keyComponentsFi: "HPG (FSH/LH), HPA (ACTH/kortisoli), HPT (TSH/T3/T4), prolaktiini",
    keyComponentsJa: "HPG (FSH/LH), HPA (ACTH/コルチゾール), HPT (TSH/T3/T4), プロラクチン",
    keyComponentsFr: "HPG (FSH/LH), HPA (ACTH/cortisol), HPT (TSH/T3/T4), prolactine",
    keyComponentsKo: "HPG (FSH/LH), HPA (ACTH/코르티솔), HPT (TSH/T3/T4), 프로락틴",
    newInSession: false,
    integrationEn: "Pituitary as EMF hub: Cav3 in gonadotroph, corticotroph, thyrotroph, lactotroph. Outside BBB.",
    integrationFi: "Aivolisäke EMF-solmukohtana: Cav3 gonadotroopissa, kortikotroopissa, tyreotroopissa, laktotroopissa. BBB:n ulkopuolella.",
    integrationJa: "下垂体がEMFハブ：性腺刺激ホルモン分泌細胞、副腎皮質刺激ホルモン分泌細胞、甲状腺刺激ホルモン分泌細胞、乳腺刺激ホルモン分泌細胞にCav3。BBBの外側。",
    integrationFr: "L'hypophyse comme hub EMF : Cav3 dans les gonadotropes, corticotropes, thyréotropes, lactotropes. En dehors de la BHE.",
    integrationKo: "뇌하수체가 EMF 허브: 생식선자극호르몬 분비세포, 부신피질자극호르몬 분비세포, 갑상선자극호르몬 분비세포, 유즙분비호르몬 분비세포에 Cav3. BBB 외부.",
  },
  {
    id: "circadian",
    number: 10,
    nameEn: "Circadian Timing",
    nameFi: "Sirkadiaaninen ajoitus",
    nameJa: "概日リズム (CRY時計)",
    nameFr: "Circadien (horloge CRY)",
    nameKo: "일주기 (CRY 시계)",
    chiModulatorEn: "Light spectrum, CRY photocycle, melatonin",
    chiModulatorFi: "Valospektri, CRY-fotosykli, melatoniini",
    chiModulatorJa: "光スペクトル, CRY光サイクル, メラトニン",
    chiModulatorFr: "Spectre lumineux, photocycle CRY, mélatonine",
    chiModulatorKo: "광 스펙트럼, CRY 광주기, 멜라토닌",
    keyComponentsEn: "SCN, pineal, CRY1/2, peripheral clocks",
    keyComponentsFi: "SCN, käpyli, CRY1/2, periferiset kellot",
    keyComponentsJa: "SCN, 松果体, CRY1/2, 末梢時計",
    keyComponentsFr: "NSC, pinéale, CRY1/2, horloges périphériques",
    keyComponentsKo: "SCN, 송과체, CRY1/2, 말초 시계",
    newInSession: false,
    integrationEn: "Eye as primary target. CRY dual system. Melatonin-fertility bridge.",
    integrationFi: "Silmä primaarisena kohteena. CRY-kaksoissysteemi. Melatoniini-fertiliteetti-silta.",
    integrationJa: "眼が主要標的。CRY二重システム。メラトニン-生殖能力の橋渡し。",
    integrationFr: "L'œil comme cible primaire. Système dual CRY. Pont mélatonine-fertilité.",
    integrationKo: "눈이 주요 표적. CRY 이중 시스템. 멜라토닌-생식력 연결.",
  },
  {
    id: "individual",
    number: 11,
    nameEn: "Individual Variation",
    nameFi: "Yksilöllinen vaihtelu",
    nameJa: "個体",
    nameFr: "Individuel",
    nameKo: "개체",
    chiModulatorEn: "Genetics (OCA2, LCT, CACNA1C, CACNA1G), nutrition (B2, ω-3), sex, age",
    chiModulatorFi: "Genetiikka (OCA2, LCT, CACNA1C, CACNA1G), ravitsemus (B2, ω-3), sukupuoli, ikä",
    chiModulatorJa: "遺伝学（OCA2, LCT, CACNA1C, CACNA1G）、栄養（B2, ω-3）、性別、年齢",
    chiModulatorFr: "Génétique (OCA2, LCT, CACNA1C, CACNA1G), nutrition (B2, ω-3), sexe, âge",
    chiModulatorKo: "유전학 (OCA2, LCT, CACNA1C, CACNA1G), 영양 (B2, ω-3), 성별, 연령",
    keyComponentsEn: "Eye color, lactose tolerance, B2 status, mitochondrial age, CACNA1C psychiatric risk variants, CACNA1G T-type ASD SNPs",
    keyComponentsFi: "Silmän väri, laktoosi-intoleranssi, B2-status, mitokondrion ikä, CACNA1C:n psykiatriset riskivariantit, CACNA1G:n T-tyypin ASD-SNP:t",
    keyComponentsJa: "眼の色, 乳糖耐性, B2状態, ミトコンドリア年齢, CACNA1Cの精神科リスクバリアント, CACNA1GのT型ASD SNPs",
    keyComponentsFr: "Couleur des yeux, tolérance au lactose, statut B2, âge mitochondrial, variants de risque psychiatrique CACNA1C, SNPs ASD de type T CACNA1G",
    keyComponentsKo: "눈 색깔, 유당 내성, B2 상태, 미토콘드리아 연령, CACNA1C 정신과적 위험 변이, CACNA1G T형 ASD SNPs",
    newInSession: false,
    integrationEn: "Northern package: OCA2 + LCT + cattle = CRY co-selection. CACNA1C variants confer risk for ALL FIVE major psychiatric disorders (ASD, ADHD, bipolar, MDD, schizophrenia). Timothy syndrome: CACNA1C GoF → 80% autism penetrance. CACNA1G (T-type) SNPs → ASD. These are genetic χ-modulators: altered channel gating → different χ_channel → different EMF sensitivity.",
    integrationFi: "Pohjoinen paketti: OCA2 + LCT + karja = CRY:n yhteisvalinta. CACNA1C-variantit aiheuttavat riskin KAIKILLE VIIDELLE suurelle psykiatriselle häiriölle (ASD, ADHD, kaksisuuntainen, MDD, skitsofrenia). Timothyn oireyhtymä: CACNA1C GoF → 80 % autismipenetranssi. CACNA1G (T-tyyppi) SNP:t → ASD. Nämä ovat geneettisiä χ-modulaattoreita: muuttunut kanavan porttitoiminta → erilainen χ_channel → erilainen EMF-herkkyys.",
    integrationJa: "北方パッケージ：OCA2 + LCT + 牧畜 = CRYの共選択。CACNA1Cバリアントは5大精神疾患すべて（ASD、ADHD、双極性障害、MDD、統合失調症）のリスクを付与。ティモシー症候群：CACNA1C GoF → 80%の自閉症浸透率。CACNA1G（T型）SNPs → ASD。これらは遺伝的χモジュレーター：チャネルゲーティングの変化 → 異なるχ_channel → 異なるEMF感受性。",
    integrationFr: "Package nordique : OCA2 + LCT + bétail = co-sélection CRY. Les variants CACNA1C confèrent un risque pour les CINQ troubles psychiatriques majeurs (TSA, TDAH, bipolaire, TDM, schizophrénie). Syndrome de Timothy : CACNA1C GoF → 80 % de pénétrance autistique. SNPs CACNA1G (type T) → TSA. Ce sont des χ-modulateurs génétiques : gating altéré → χ_channel différent → sensibilité EMF différente.",
    integrationKo: "북방 패키지: OCA2 + LCT + 목축 = CRY 공동선택. CACNA1C 변이는 5대 주요 정신질환 모두(ASD, ADHD, 양극성 장애, MDD, 조현병)의 위험을 부여. 티모시 증후군: CACNA1C GoF → 80% 자폐증 침투율. CACNA1G (T형) SNPs → ASD. 이들은 유전적 χ 조절자: 변경된 채널 게이팅 → 다른 χ_channel → 다른 EMF 감수성.",
  },
  {
    id: "population",
    number: 12,
    nameEn: "Population & Environment",
    nameFi: "Populaatio ja ympäristö",
    nameJa: "集団",
    nameFr: "Population",
    nameKo: "집단",
    chiModulatorEn: "Electrification, urbanization, dairy consumption patterns",
    chiModulatorFi: "Sähköistyminen, kaupungistuminen, maitotuotteiden kulutusmallit",
    chiModulatorJa: "電化、都市化、乳製品消費パターン",
    chiModulatorFr: "Électrification, urbanisation, modes de consommation laitière",
    chiModulatorKo: "전기화, 도시화, 유제품 소비 패턴",
    keyComponentsEn: "χ_env, COVID-WFH test, population χ profiles",
    keyComponentsFi: "χ_env, COVID-WFH-testi, populaation χ-profiilit",
    keyComponentsJa: "χ_env, COVID在宅勤務テスト, 集団χプロファイル",
    keyComponentsFr: "χ_env, test COVID-télétravail, profils χ de population",
    keyComponentsKo: "χ_env, COVID 재택근무 테스트, 집단 χ 프로파일",
    newInSession: false,
    integrationEn: "54-country dataset. Electrification boundary = χ onset.",
    integrationFi: "54 maan aineisto. Sähköistymisraja = χ:n alkaminen.",
    integrationJa: "54か国データセット。電化の境界 = χの開始。",
    integrationFr: "Jeu de données de 54 pays. Frontière d'électrification = début de χ.",
    integrationKo: "54개국 데이터셋. 전기화 경계 = χ 시작.",
  },
];
