export interface OrganProfile {
  id: string;
  nameEn: string;
  nameFi: string;
  nameJa: string;
  nameFr: string;
  nameKo: string;
  color: string;
  level: string;
  subpage: string;
  summaryEn: string;
  summaryFi: string;
  summaryJa: string;
  summaryFr: string;
  summaryKo: string;
  cav3Subtype: string;
  cellTypeEn: string;
  functionEn: string;
  functionFi: string;
  ready: boolean;
}

export const ORGAN_PROFILES: OrganProfile[] = [
  {
    id: "eye",
    nameEn: "Eye",
    nameFi: "Silmä",
    nameJa: "眼",
    nameFr: "Œil",
    nameKo: "눈",
    color: "#3B82F6",
    level: "M|C",
    subpage: "/modulome/eye",
    summaryEn: "CRY1 + CRY2 + dual-band candidate convergence. Six BERM tissue-response criteria proposed; L2 operator conditional and calibration open.",
    summaryFi: "CRY1 + CRY2 + kaksikaistan yhdentyminen. 6/6 Lindgren-kriteeriä.",
    summaryJa: "CRY1 + CRY2 + 二重帯域収束。6/6リンドグレン基準。",
    summaryFr: "CRY1 + CRY2 + convergence double bande. 6/6 critères de Lindgren.",
    summaryKo: "CRY1 + CRY2 + 이중 대역 수렴. 6/6 린드그렌 기준.",
    cav3Subtype: "CRY1/CRY2 (not Cav3)",
    cellTypeEn: "Retinal ganglion cells, blue cone photoreceptors",
    functionEn: "Magnetoreception, circadian entrainment, light-dependent EMF transduction",
    functionFi: "Magnetoreseptio, sirkadiaaninen synkronointi, valosta riippuva EMF-transduktio",
    ready: true,
  },
  {
    id: "pituitary",
    nameEn: "Pituitary",
    nameFi: "Aivolisäke",
    nameJa: "下垂体",
    nameFr: "Hypophyse",
    nameKo: "뇌하수체",
    color: "#8B5CF6",
    level: "M|C",
    subpage: "/modulome/pituitary",
    summaryEn: "Outside BBB. Cav3 in ALL hormone cells. EMF hub.",
    summaryFi: "BBB:n ulkopuolella. Cav3 KAIKISSA hormonisoluissa. EMF-solmukohta.",
    summaryJa: "BBBの外側。すべてのホルモン細胞にCav3。EMFハブ。",
    summaryFr: "En dehors de la BHE. Cav3 dans TOUTES les cellules hormonales. Hub EMF.",
    summaryKo: "BBB 외부. 모든 호르몬 세포에 Cav3. EMF 허브.",
    cav3Subtype: "Cav3 (T-type)",
    cellTypeEn: "Gonadotroph, lactotroph, corticotroph, thyrotroph",
    functionEn: "Master endocrine regulation: FSH/LH, prolactin, ACTH, TSH",
    functionFi: "Endokriinisen järjestelmän keskushallinta: FSH/LH, prolaktiini, ACTH, TSH",
    ready: true,
  },
  {
    id: "testes",
    nameEn: "Testes",
    nameFi: "Kivekset",
    nameJa: "精巣",
    nameFr: "Testicules",
    nameKo: "정소",
    color: "#EF4444",
    level: "M|C",
    subpage: "/modulome/testes",
    summaryEn: "Cav3 Leydig → testosterone. BTB = barrier multiplier.",
    summaryFi: "Cav3 Leydig → testosteroni. BTB = estemultiplikattori.",
    summaryJa: "Cav3ライディッヒ → テストステロン。BTB = バリア乗数。",
    summaryFr: "Cav3 Leydig → testostérone. BTB = multiplicateur de barrière.",
    summaryKo: "Cav3 라이디히 → 테스토스테론. BTB = 장벽 배수.",
    cav3Subtype: "Cav3 (Leydig) + CatSper (sperm)",
    cellTypeEn: "Leydig cells, spermatogonia, Sertoli cells",
    functionEn: "Testosterone synthesis, spermatogenesis, BTB maintenance",
    functionFi: "Testosteronisynteesi, spermatogeneesi, BTB:n ylläpito",
    ready: true,
  },
  {
    id: "pancreas",
    nameEn: "Pancreas",
    nameFi: "Haima",
    nameJa: "膵臓",
    nameFr: "Pancréas",
    nameKo: "췌장",
    color: "#EC4899",
    level: "M|C",
    subpage: "/modulome/pancreas",
    summaryEn: "Glucose-dependent χ. β-cell Cav1+Cav3 → insulin.",
    summaryFi: "Glukoosiriippuvainen χ. β-solun Cav1+Cav3 → insuliini.",
    summaryJa: "グルコース依存性χ。β細胞Cav1+Cav3 → インスリン。",
    summaryFr: "χ dépendant du glucose. Cav1+Cav3 des cellules β → insuline.",
    summaryKo: "포도당 의존성 χ. β세포 Cav1+Cav3 → 인슐린.",
    cav3Subtype: "Cav1 (L-type) + Cav3 (T-type)",
    cellTypeEn: "β-cell → Insulin",
    functionEn: "Glucose-stimulated insulin secretion via VGCC → Ca²⁺",
    functionFi: "Glukoosistimuloitu insuliinisekretio VGCC → Ca²⁺ kautta",
    ready: true,
  },
  {
    id: "brain",
    nameEn: "Brain",
    nameFi: "Aivot",
    nameJa: "脳",
    nameFr: "Cerveau",
    nameKo: "뇌",
    color: "#6366F1",
    level: "M|C",
    subpage: "/modulome/brain",
    summaryEn: "Cav3.2 hippocampus, CACNA1C 5 disorders, 7 developmental channels.",
    summaryFi: "Cav3.2 hippokampus, CACNA1C 5 häiriötä, 7 kehityskanavaa.",
    summaryJa: "Cav3.2海馬、CACNA1C 5疾患、7発達チャネル。",
    summaryFr: "Cav3.2 hippocampe, CACNA1C 5 troubles, 7 canaux de développement.",
    summaryKo: "Cav3.2 해마, CACNA1C 5개 질환, 7개 발달 채널.",
    cav3Subtype: "Cav3.2 (highest T-type density in brain)",
    cellTypeEn: "Granule cells, neuronal progenitors",
    functionEn: "Neurogenesis, memory consolidation, learning",
    functionFi: "Neurogeneesi, muistin konsolidaatio, oppiminen",
    ready: true,
  },
  {
    id: "heart",
    nameEn: "Heart",
    nameFi: "Sydän",
    nameJa: "心臓",
    nameFr: "Cœur",
    nameKo: "심장",
    color: "#10B981",
    level: "M",
    subpage: "/modulome/heart",
    summaryEn: "SA node Cav3 pacemaking. HRV = early EMF biomarker.",
    summaryFi: "SA-solmun Cav3-tahdistus. HRV = varhainen EMF-biomarkeri.",
    summaryJa: "洞房結節Cav3ペースメーキング。HRV = 早期EMFバイオマーカー。",
    summaryFr: "Stimulation Cav3 du nœud SA. VFC = biomarqueur précoce d'EMF.",
    summaryKo: "동방결절 Cav3 조율. HRV = 조기 EMF 바이오마커.",
    cav3Subtype: "Cav3 (SA pacemaking) + Cav1.2 (contraction)",
    cellTypeEn: "Pacemaker cells, cardiomyocytes",
    functionEn: "Heart rate, rhythm, contractile force",
    functionFi: "Syketaajuus, rytmi, supistusvoima",
    ready: true,
  },
  {
    id: "thyroid",
    nameEn: "Thyroid",
    nameFi: "Kilpirauhanen",
    nameJa: "甲状腺",
    nameFr: "Thyroïde",
    nameKo: "갑상선",
    color: "#F59E0B",
    level: "M|C",
    subpage: "/modulome/thyroid",
    summaryEn: "Anterior neck = direct phone exposure. HPT axis disruption.",
    summaryFi: "Kaulan etuosa = suora puhelinaltistus. HPT-akselin häiriö.",
    summaryJa: "前頸部 = 直接的な電話曝露。HPT軸の障害。",
    summaryFr: "Partie antérieure du cou = exposition directe au téléphone. Perturbation de l'axe HPT.",
    summaryKo: "전경부 = 직접적 전화 노출. HPT 축 장애.",
    cav3Subtype: "Cav3 (thyrotroph) → TSH",
    cellTypeEn: "Thyrotroph → TSH → Thyrocyte",
    functionEn: "Thyroid hormone synthesis (T3, T4)",
    functionFi: "Kilpirauhashormonien synteesi (T3, T4)",
    ready: true,
  },
  {
    id: "adrenal",
    nameEn: "Adrenal",
    nameFi: "Lisämunuainen",
    nameJa: "副腎",
    nameFr: "Surrénale",
    nameKo: "부신",
    color: "#F97316",
    level: "M|C",
    subpage: "/modulome/adrenal",
    summaryEn: "Cav3.2 glomerulosa → aldosterone → hypertension.",
    summaryFi: "Cav3.2 glomerulosa → aldosteroni → verenpainetauti.",
    summaryJa: "Cav3.2糸球体帯 → アルドステロン → 高血圧。",
    summaryFr: "Cav3.2 glomérulée → aldostérone → hypertension.",
    summaryKo: "Cav3.2 사구체대 → 알도스테론 → 고혈압.",
    cav3Subtype: "Cav3.2",
    cellTypeEn: "Glomerulosa cell → Aldosterone",
    functionEn: "Aldosterone synthesis → sodium retention → blood pressure",
    functionFi: "Aldosteronisynteesi → natriumretentio → verenpaine",
    ready: true,
  },
  {
    id: "ear",
    nameEn: "Inner Ear",
    nameFi: "Sisäkorva",
    nameJa: "内耳",
    nameFr: "Oreille interne",
    nameKo: "내이",
    color: "#14B8A6",
    level: "M|C",
    subpage: "/modulome/ear",
    summaryEn: "Cav1.3 in IHC synapses. IL-6→Cav1.3↑. Bluetooth/earphone EMF.",
    summaryFi: "Cav1.3 IHC-synapseissa. IL-6→Cav1.3↑. Bluetooth/kuuloke-EMF.",
    summaryJa: "IHCシナプスのCav1.3。IL-6→Cav1.3↑。Bluetooth/イヤホンEMF。",
    summaryFr: "Cav1.3 dans les synapses CCI. IL-6→Cav1.3↑. EMF Bluetooth/écouteurs.",
    summaryKo: "IHC 시냅스의 Cav1.3. IL-6→Cav1.3↑. 블루투스/이어폰 EMF.",
    cav3Subtype: "Cav1.3 (L-type)",
    cellTypeEn: "Inner hair cells, spiral ganglion neurons",
    functionEn: "Sound transduction, auditory signal transmission",
    functionFi: "Äänentransduktio, kuulosignaalin välitys",
    ready: true,
  },
  {
    id: "drg",
    nameEn: "Spinal Cord (DRG)",
    nameFi: "Selkäydin (DRG)",
    nameJa: "脊髄（DRG）",
    nameFr: "Moelle épinière (DRG)",
    nameKo: "척수 (DRG)",
    color: "#E11D48",
    level: "M|C",
    subpage: "/modulome/pain",
    summaryEn: "Cav3.2 in nociceptors. Primary pain channel. Sex-differential expression.",
    summaryFi: "Cav3.2 nosiseptoreissa. Primaarinen kipukanava. Sukupuolitarkka ilmentyminen.",
    summaryJa: "侵害受容器のCav3.2。一次痛覚チャネル。性差のある発現。",
    summaryFr: "Cav3.2 dans les nocicepteurs. Canal de douleur primaire. Expression différentielle selon le sexe.",
    summaryKo: "통각수용기의 Cav3.2. 1차 통증 채널. 성별 차이 발현.",
    cav3Subtype: "Cav3.2 (T-type)",
    cellTypeEn: "DRG nociceptors, C-fiber neurons",
    functionEn: "Pain sensation, nociceptive signaling, peripheral sensitization",
    functionFi: "Kiputunto, nosiseptiivinen signalointi, perifeerinen sensitisaatio",
    ready: true,
  },
  {
    id: "hypothalamus",
    nameEn: "Hypothalamus (ARC)",
    nameFi: "Hypotalamus (ARC)",
    nameJa: "視床下部（ARC）",
    nameFr: "Hypothalamus (ARC)",
    nameKo: "시상하부 (ARC)",
    color: "#F97316",
    level: "E",
    subpage: "/modulome/hypothalamus",
    summaryEn: "ARC glia Ca²⁺ → AgRP/NPY ↑ → appetite. Direct Ca²⁺→feeding link (eLife 2016).",
    summaryFi: "ARC-glian Ca²⁺ → AgRP/NPY ↑ → ruokahalu. Suora Ca²⁺→ravinto-yhteys (eLife 2016).",
    summaryJa: "ARCグリアCa²⁺ → AgRP/NPY ↑ → 食欲。直接的Ca²⁺→摂食連結（eLife 2016）。",
    summaryFr: "Ca²⁺ de la glie ARC → AgRP/NPY ↑ → appétit. Lien direct Ca²⁺→alimentation (eLife 2016).",
    summaryKo: "ARC 교세포 Ca²⁺ → AgRP/NPY ↑ → 식욕. 직접적 Ca²⁺→섭식 연결 (eLife 2016).",
    cav3Subtype: "VGCC (glia + neurons)",
    cellTypeEn: "ARC astrocytes, AgRP/NPY neurons, POMC neurons",
    functionEn: "Energy homeostasis, appetite regulation, metabolic sensing",
    functionFi: "Energiatasapainon säätely, ruokahalun säätely, metabolinen tunnistus",
    ready: true,
  },
  {
    id: "bat",
    nameEn: "Brown Adipose Tissue",
    nameFi: "Ruskea rasvakudos",
    nameJa: "褐色脂肪組織",
    nameFr: "Tissu adipeux brun",
    nameKo: "갈색 지방 조직",
    color: "#DC2626",
    level: "E",
    subpage: "/modulome/bat",
    summaryEn: "CaMKII/CREB → UCP1 ↓ + SERCA2b/RyR2 Ca²⁺ cycling ↓. Two thermogenic pathways disrupted.",
    summaryFi: "CaMKII/CREB → UCP1 ↓ + SERCA2b/RyR2 Ca²⁺-sykli ↓. Kaksi termogeenistä reittiä häiriintynyt.",
    summaryJa: "CaMKII/CREB → UCP1 ↓ + SERCA2b/RyR2 Ca²⁺サイクリング ↓。2つの熱産生経路が障害。",
    summaryFr: "CaMKII/CREB → UCP1 ↓ + cyclage Ca²⁺ SERCA2b/RyR2 ↓. Deux voies thermogéniques perturbées.",
    summaryKo: "CaMKII/CREB → UCP1 ↓ + SERCA2b/RyR2 Ca²⁺ 순환 ↓. 두 가지 열 생성 경로 장애.",
    cav3Subtype: "VGCC → CaMKII",
    cellTypeEn: "Brown adipocytes, beige adipocytes",
    functionEn: "Non-shivering thermogenesis, energy expenditure, metabolic rate regulation",
    functionFi: "Ei-värisyttävä termogeneesi, energiankulutus, perusaineenvaihdunnan säätely",
    ready: true,
  },
];
