export interface OrganProfile {
  id: string;
  nameEn: string;
  nameFi: string;
  color: string;
  level: string;
  subpage: string;
  summaryEn: string;
  summaryFi: string;
  cav3Subtype: string;
  cellTypeEn: string;
  functionEn: string;
  functionFi: string;
  ready: boolean;
}

export const ORGAN_PROFILES: OrganProfile[] = [
  {
    id: "eye",
    nameEn: "Eye",
    nameFi: "Silmä",
    color: "#3B82F6",
    level: "M|C",
    subpage: "/modulome/eye",
    summaryEn: "CRY1 + CRY2 + dual-band convergence. 6/6 Lindgren criteria.",
    summaryFi: "CRY1 + CRY2 + kaksikaistan konvergenssi. 6/6 Lindgren-kriteeriä.",
    cav3Subtype: "CRY1/CRY2 (not Cav3)",
    cellTypeEn: "Retinal ganglion cells, blue cone photoreceptors",
    functionEn: "Magnetoreception, circadian entrainment, light-dependent EMF transduction",
    functionFi: "Magnetoreseptio, sirkadiaaninen synkronointi, valosta riippuva EMF-transduktio",
    ready: true,
  },
  {
    id: "pituitary",
    nameEn: "Pituitary",
    nameFi: "Aivolisäke",
    color: "#8B5CF6",
    level: "M|C",
    subpage: "/modulome/pituitary",
    summaryEn: "Outside BBB. Cav3 in ALL hormone cells. EMF hub.",
    summaryFi: "BBB:n ulkopuolella. Cav3 KAIKISSA hormonisoluissa. EMF-solmukohta.",
    cav3Subtype: "Cav3 (T-type)",
    cellTypeEn: "Gonadotroph, lactotroph, corticotroph, thyrotroph",
    functionEn: "Master endocrine regulation: FSH/LH, prolactin, ACTH, TSH",
    functionFi: "Endokriinisen järjestelmän keskushallinta: FSH/LH, prolaktiini, ACTH, TSH",
    ready: true,
  },
  {
    id: "testes",
    nameEn: "Testes",
    nameFi: "Kivekset",
    color: "#EF4444",
    level: "M|C",
    subpage: "/modulome/testes",
    summaryEn: "Cav3 Leydig → testosterone. BTB = barrier multiplier.",
    summaryFi: "Cav3 Leydig → testosteroni. BTB = estemultiplikattori.",
    cav3Subtype: "Cav3 (Leydig) + CatSper (sperm)",
    cellTypeEn: "Leydig cells, spermatogonia, Sertoli cells",
    functionEn: "Testosterone synthesis, spermatogenesis, BTB maintenance",
    functionFi: "Testosteronisynteesi, spermatogeneesi, BTB:n ylläpito",
    ready: true,
  },
  {
    id: "pancreas",
    nameEn: "Pancreas",
    nameFi: "Haima",
    color: "#EC4899",
    level: "M|C",
    subpage: "/modulome/pancreas",
    summaryEn: "Glucose-dependent χ. β-cell Cav1+Cav3 → insulin.",
    summaryFi: "Glukoosiriippuvainen χ. β-solun Cav1+Cav3 → insuliini.",
    cav3Subtype: "Cav1 (L-type) + Cav3 (T-type)",
    cellTypeEn: "β-cell → Insulin",
    functionEn: "Glucose-stimulated insulin secretion via VGCC → Ca²⁺",
    functionFi: "Glukoosistimuloitu insuliinisekretio VGCC → Ca²⁺ kautta",
    ready: true,
  },
  {
    id: "brain",
    nameEn: "Brain",
    nameFi: "Aivot",
    color: "#6366F1",
    level: "M|C",
    subpage: "/modulome/brain",
    summaryEn: "Cav3.2 hippocampus, CACNA1C 5 disorders, 7 developmental channels.",
    summaryFi: "Cav3.2 hippokampus, CACNA1C 5 häiriötä, 7 kehityskanavaa.",
    cav3Subtype: "Cav3.2 (highest T-type density in brain)",
    cellTypeEn: "Granule cells, neuronal progenitors",
    functionEn: "Neurogenesis, memory consolidation, learning",
    functionFi: "Neurogeneesi, muistin konsolidaatio, oppiminen",
    ready: true,
  },
  {
    id: "heart",
    nameEn: "Heart",
    nameFi: "Sydän",
    color: "#10B981",
    level: "M",
    subpage: "/modulome/heart",
    summaryEn: "SA node Cav3 pacemaking. HRV = early EMF biomarker.",
    summaryFi: "SA-solmun Cav3-tahdistus. HRV = varhainen EMF-biomarkeri.",
    cav3Subtype: "Cav3 (SA pacemaking) + Cav1.2 (contraction)",
    cellTypeEn: "Pacemaker cells, cardiomyocytes",
    functionEn: "Heart rate, rhythm, contractile force",
    functionFi: "Syketaajuus, rytmi, supistusvoima",
    ready: true,
  },
  {
    id: "thyroid",
    nameEn: "Thyroid",
    nameFi: "Kilpirauhanen",
    color: "#F59E0B",
    level: "M|C",
    subpage: "/modulome/thyroid",
    summaryEn: "Anterior neck = direct phone exposure. HPT axis disruption.",
    summaryFi: "Kaulan etuosa = suora puhelinaltistus. HPT-akselin häiriö.",
    cav3Subtype: "Cav3 (thyrotroph) → TSH",
    cellTypeEn: "Thyrotroph → TSH → Thyrocyte",
    functionEn: "Thyroid hormone synthesis (T3, T4)",
    functionFi: "Kilpirauhashormonien synteesi (T3, T4)",
    ready: true,
  },
  {
    id: "adrenal",
    nameEn: "Adrenal",
    nameFi: "Lisämunuainen",
    color: "#F97316",
    level: "M|C",
    subpage: "/modulome/adrenal",
    summaryEn: "Cav3.2 glomerulosa → aldosterone → hypertension.",
    summaryFi: "Cav3.2 glomerulosa → aldosteroni → verenpainetauti.",
    cav3Subtype: "Cav3.2",
    cellTypeEn: "Glomerulosa cell → Aldosterone",
    functionEn: "Aldosterone synthesis → sodium retention → blood pressure",
    functionFi: "Aldosteronisynteesi → natriumretentio → verenpaine",
    ready: true,
  },
  {
    id: "ear",
    nameEn: "Inner Ear",
    nameFi: "Sisäkorva",
    color: "#14B8A6",
    level: "M|C",
    subpage: "/modulome/ear",
    summaryEn: "Cav1.3 in IHC synapses. IL-6→Cav1.3↑. Bluetooth/earphone EMF.",
    summaryFi: "Cav1.3 IHC-synapseissa. IL-6→Cav1.3↑. Bluetooth/kuuloke-EMF.",
    cav3Subtype: "Cav1.3 (L-type)",
    cellTypeEn: "Inner hair cells, spiral ganglion neurons",
    functionEn: "Sound transduction, auditory signal transmission",
    functionFi: "Äänentransduktio, kuulosignaalin välitys",
    ready: true,
  },
  {
    id: "drg",
    nameEn: "Spinal Cord (DRG)",
    nameFi: "Selkäydin (DRG)",
    color: "#E11D48",
    level: "M|C",
    subpage: "/modulome/pain",
    summaryEn: "Cav3.2 in nociceptors. Primary pain channel. Sex-differential expression.",
    summaryFi: "Cav3.2 nosiseptoreissa. Primaarinen kipukanava. Sukupuolispesifinen ilmentyminen.",
    cav3Subtype: "Cav3.2 (T-type)",
    cellTypeEn: "DRG nociceptors, C-fiber neurons",
    functionEn: "Pain sensation, nociceptive signaling, peripheral sensitization",
    functionFi: "Kiputunto, nosiseptiivinen signalointi, perifeerinen sensitisaatio",
    ready: true,
  },
];
